var jlpten3 = [
  ["love, affection","愛情","あいじょう"  ],
  ["sign, signal","合図","あいず"  ],
  ["to love","愛する","あいする"  ],
  ["companion, partner, company","相手","あいて"  ],
  ["unfortunately, Sorry, but....","","あいにく"  ],
  ["lamplight, light (in general),brightness","明かり","あかり"  ],
  ["room, time to spare, emptiness","空き","あき"  ],
  ["obvious, evident, clear","明らか","あきらか"  ],
  ["to give up, to abandon","諦める","あきらめる"  ],
  ["to get tired of, to lose interest in, to have enough","飽きる","あきる"  ],
  ["handshake","握手","あくしゅ"  ],
  ["devil, demon, evil spirit","悪魔","あくま"  ],
  ["to dawn, to become daylight","明ける","あける"  ],
  ["to give into custody, to entrust, to deposit","預ける","あずける"  ],
  ["sweat, perspiration","汗","あせ"  ],
  ["to give, to present, to award","与える","あたえる"  ],
  ["warm, mild","暖かい","あたたか(い)"  ],
  ["vicinity, nearby","辺り","あたり"  ],
  ["to be hit, to be successful, to be equivalent to","当たる","あたる"  ],
  ["here and there","","あちこち"  ],
  ["Ah!, Oh!","","あっ"  ],
  ["to handle, to deal with, to treat","扱う","あつかう"  ],
  ["gathering, meeting, assembly, collection","集まり","あつまり"  ],
  ["to hit, to apply a patch","当てる","あてる"  ],
  ["(1) trace, tracks, mark, sign, (2) remains, ruins, (3) scar","跡","あと"  ],
  ["hole","穴","あな"  ],
  ["to bathe, to bask in the sun, to shower","浴びる","あびる"  ],
  ["oil","油","あぶら"  ],
  ["not very (used as adverb),not much","余り","あまり"  ],
  ["error","誤り","あやまり"  ],
  ["Coarse","粗い","あらい"  ],
  ["storm, tempest","嵐","あらし"  ],
  ["new, fresh, novel","新た","あらた"  ],
  ["all, every","","あらゆる"  ],
  ["to express, to show, to reveal","表す","あらわす"  ],
  ["to show, to indicate, to display","現す","あらわす"  ],
  ["embodiment, materialization","現れ","あらわれ"  ],
  ["(1) to appear, to come in sight, to become visible,(2) to express oneself","現れる","あらわれる"  ],
  ["(conj,exp,int) Thank you","","ありがとう"  ],
  ["to be, to have(used for inanimate objects)","有る","ある"  ],
  ["a certain...,some...","或","ある"  ],
  ["or, possibly","","あるいは"  ],
  ["bubble, foam, froth, head on beer","泡","あわ"  ],
  ["to join together, to be opposite, to face, to unite","合わせる","あわせる"  ],
  ["helpless, pity, sorrow, grief","哀れ","あわれ"  ],
  ["plan, suffix meaning draft","案","あん"  ],
  ["memorization, learning by heart","暗記","あんき"  ],
  ["stability, equilibrium","安定","あんてい"  ],
  ["information, guidance, leading, to guide","案内","あんない・する"  ],
  ["to that extent, to that degree","","あんなに"  ],
  ["not very, not much, remainder, rest","","あんまり"  ],
  ["stomach","胃","い"  ],
  ["committee member","委員","いいん"  ],
  ["same as いいえ in spoken","いえ","いえ"  ],
  ["unexpected, surprising","意外","いがい"  ],
  ["breath, tone","息","いき"  ],
  ["going,","行き","いき/ゆき"  ],
  ["force, vigour, energy, spirit","勢い","いきおい"  ],
  ["living thing, animal","生き物","いきもの"  ],
  ["how many?, how old?","幾つ","いくつ"  ],
  ["how much?,","幾ら","いくら"  ],
  ["must not do, bad, wrong, not good","","いけない"  ],
  ["doctor, physician","医師","いし"  ],
  ["mind, intention","意思","いし"  ],
  ["will, volition","意志","いし"  ],
  ["maintenance, preservation","維持","いじ"  ],
  ["consciousness, senses","意識","いしき"  ],
  ["strangeness, abnormality, disorder","異常","いじょう"  ],
  ["chair","椅子","いす"  ],
  ["spring, fountain","泉","いずみ"  ],
  ["which, either, one","","いずれ"  ],
  ["ago since, before, previous","以前","いぜん"  ],
  ["board, plank","板","いた"  ],
  ["greatness","偉大","いだい"  ],
  ["(sl) to embrace, to hug, to harbour, to entertain","抱く","いだく"  ],
  ["tease, prank, trick, practical joke","","いたずら"  ],
  ["expression of gratitude before meals","","いただきます"  ],
  ["to receive, to take food or drink (hum)","頂く","いただく"  ],
  ["pain, ache, sore, grief, distress","痛み","いたみ"  ],
  ["to come, to arrive","至る","いたる"  ],
  ["market, fair","市","いち"  ],
  ["place, situation, position, location","位置","いち"  ],
  ["moment, time","一時","いちじ"  ],
  ["all at once","一度に","いちどに"  ],
  ["(the) market (as a concept)","市場","いちば"  ],
  ["best, first, number one","一番","いちばん"  ],
  ["a house, a home, a family, a household","一家","いっか"  ],
  ["sometime, someday, one day","","いつか"  ],
  ["a species, a kind, a variety","一種","いっしゅ"  ],
  ["a moment, an instant","一瞬","いっしゅん"  ],
  ["whole life, a lifetime, all through life","一生","いっしょう"  ],
  ["much more, still more, all the more","一層","いっそう"  ],
  ["(1) one object, one body,(2) what on earth?, really?,(3) generally","一体","いったい"  ],
  ["(1) coincidence, agreement,(2) conformity","一致","いっち"  ],
  ["(at) any time, always, at all times, never (neg)","","いつでも"  ],
  ["general, liberal, universal, ordinary, average","一般","いっぱん"  ],
  ["(1) on the other hand,(2) meanwhile,(3) only, simple, in turn","一方","いっぽう"  ],
  ["forever, for good, eternally, as long as one likes, indefinitely","","いつまでも"  ],
  ["always, usually, every time, never (with neg. verb)","","いつも"  ],
  ["removal, migration, movement","移動","いどう"  ],
  ["cousin (male)","従兄弟","いとこ"  ],
  ["rice-plant","稲","いね"  ],
  ["dozing, nodding off","居眠り","いねむり"  ],
  [",life, destiny","命","いのち"  ],
  ["violation (of law),transgression, infringement, breach","違反","いはん"  ],
  ["clothes","衣服","いふく"  ],
  ["living room (western style)","居間","いま"  ],
  ["before long, even now","今に","いまに"  ],
  ["at any time, soon","今にも","いまにも"  ],
  ["no, the nose","否","いや"  ],
  ["since, henceforth","以来","いらい"  ],
  ["(1) request, commission, dispatch,(2) dependence, trust","依頼","いらい"  ],
  ["getting nervous, irritation","","いらいら"  ],
  ["welcome","","いらっしゃい"  ],
  ["medical care, medical treatment","医療","いりょう"  ],
  ["rock, crag","岩","いわ"  ],
  ["celebration, festival","祝い","いわい"  ],
  ["to congratulate, to celebrate","祝う","いわう"  ],
  ["so to speak","言わば","いわば"  ],
  ["the so-called, so to speak","","いわゆる"  ],
  ["printing","印刷","いんさつ"  ],
  ["impression","印象","いんしょう"  ],
  ["retire","引退","いんたい"  ],
  ["quotation, citation","引用","いんよう"  ],
  ["fish","魚","うお"  ],
  ["gargle, rinse mouth","","うがい"  ],
  ["(hon) to visit, to ask, to inquire","伺う","うかがう"  ],
  ["to receive, to get, to accept, to take","受け取る","うけとる"  ],
  ["to move, to shift","動かす","うごかす"  ],
  ["rabbit, hare","兎","うさぎ"  ],
  ["cattle, cow","牛","うし"  ],
  ["to lose, to part with","失う","うしなう"  ],
  ["afterwards, since then, in the future, behind","後ろ","うしろ"  ],
  ["lie, falsehood, incorrect fact, inappropriate","嘘","うそ"  ],
  ["to doubt, to distrust, to be suspicious of, to suspect","疑う","うたがう"  ],
  ["inside","内","うち"  ],
  ["universe, cosmos, space","宇宙","うちゅう"  ],
  ["to attack, to defeat, to destroy","撃つ","うつ"  ],
  ["to remove, to transfer, to infect","移す","うつす"  ],
  ["to sue (a person),to resort to, to appeal to","訴える","うったえる"  ],
  ["to groan, to moan","","うなる"  ],
  ["to snatch away","奪う","うばう"  ],
  ["(1) horse,(2) promoted bishop (shogi)","馬","うま"  ],
  ["be good at, delicious (spoken)","うまい","うまい"  ],
  ["birth, birth-place","生まれ","うまれ"  ],
  ["plum, plum-tree, lowest (of a three-tier ranking system)","梅","うめ"  ],
  ["to betray, to turn traitor to, to double-cross","裏切る","うらぎる"  ],
  ["to get, to gain, to win","得る","うる"  ],
  ["happy, glad, pleasant","嬉しい","うれしい"  ],
  ["to be sold","売れる","うれる"  ],
  ["rumour, report, gossip, common talk","噂","うわさ"  ],
  ["fortune, luck","運","うん"  ],
  ["operation, motion, driving, to drive","運転","うんてん・する"  ],
  ["motion, exercise, to exercise","運動","うんどう・する"  ],
  ["handle, grip","柄","え"  ],
  ["eternity, perpetuity, immortality, permanence","永遠","えいえん"  ],
  ["eternity ,perpetuity, immortality","永久","えいきゅう"  ],
  ["influence, effect","影響","えいきょう"  ],
  ["business, trade, management","営業","えいぎょう"  ],
  ["satellite","衛星","えいせい"  ],
  ["nutrition, nourishment","栄養","えいよう"  ],
  ["smiling face","笑顔","えがお"  ],
  ["to draw, to paint, to sketch, to depict, to describe","描く","えがく"  ],
  ["feed, bait","餌","えさ"  ],
  ["to get, to gain, to win","得る","える"  ],
  ["circle, money","円","えん"  ],
  ["relation, connection, ties, fate","縁","えん"  ],
  ["postponement, adjournment","延期","えんき"  ],
  ["acting, performance","演技","えんぎ"  ],
  ["assistance, aid, support","援助","えんじょ"  ],
  ["speech, address","演説","えんぜつ"  ],
  ["musical performance","演奏","えんそう"  ],
  ["diffidence, restraint, reserve","遠慮","えんりょ"  ],
  ["honourable","御","お"  ],
  ["old age, old person, the old, the aged","老い","おい"  ],
  ["to overtake, to catch up (with)","追い付く","おいつく"  ],
  ["king, ruler, sovereign, monarch","王","おう"  ],
  ["to chase, to run after","追う","おう"  ],
  ["king","王様","おうさま"  ],
  ["prince","王子","おうじ"  ],
  ["to respond, to satisfy, to accept, to comply with, to apply for","応じる","おうじる"  ],
  ["crossing","横断","おうだん"  ],
  ["to finish","終える","おえる"  ],
  ["very, much, greatly","大いに","おおいに"  ],
  ["to cover, to hide, to conceal, to wrap, to disguise","覆う","おおう"  ],
  ["rich family, distinguished family","大家","おおや"  ],
  ["hill, height, knoll, rising ground","丘","おか"  ],
  ["open sea","沖","おき"  ],
  ["interior, inner part","奥","おく"  ],
  ["to send, to give to, to award to, to confer on","贈る","おくる"  ],
  ["to occur, to happen","起こる","おこる"  ],
  ["very young, childish","幼い","おさない"  ],
  ["to obtain, to reap, to pay, to supply, to accept","収める","おさめる"  ],
  ["chattering, talk, idle talk","","おしゃべり"  ],
  ["pollution, contamination","汚染","おせん"  ],
  ["perhaps","","おそらく"  ],
  ["to fear, to be afraid of","恐れる","おそれる"  ],
  ["terrible, dreadful","恐ろしい","おそろしい"  ],
  ["mutual, reciprocal, each other","お互い","おたがい"  ],
  ["calm, gentle, quiet","穏やか","おだやか"  ],
  ["man","男の人","おとこのひと"  ],
  ["to fall behind, to be inferior to","劣る","おとる"  ],
  ["stomach, tummy","お腹","おなか"  ],
  ["ogre, demon, it (i.e., in a game of tag)","鬼","おに"  ],
  ["band (e.g. conduction, valence)","帯","おび"  ],
  ["lunch, noon","お昼","おひる"  ],
  ["to be drowned, to indulge in","溺れる","おぼれる"  ],
  ["(fam) you (sing)","","おまえ"  ],
  ["Congratulations!, an auspicious occasion!","","おめでとう"  ],
  ["memories, recollections, reminiscence","思い出","おもいで"  ],
  ["mainly, primarily","主に","おもに"  ],
  ["unintentional, spontaneous","思わず","おもわず"  ],
  ["swimming","泳ぎ","およぎ"  ],
  ["about, roughly, as a rule, approximately","","およそ"  ],
  ["to exert, to cause, to exercise","及ぼす","およぼす"  ],
  ["to be (animate),to be, to exist","居る","おる"  ],
  ["to lower, to let go down","下す","おろす"  ],
  ["to take down, to launch, to drop","降ろす","おろす"  ],
  ["sound, note","音","おん"  ],
  ["favour, obligation, debt of gratitude","恩","おん"  ],
  ["warmth","温暖","おんだん"  ],
  ["temperature","温度","おんど"  ],
  ["passable","可","か"  ],
  ["counter for chapters (of a book) section","課","か"  ],
  ["meeting, assembly, party, association, club","会","かい"  ],
  ["counter for occurrences","回","かい"  ],
  ["injury, harm, evil influence, damage","害","がい"  ],
  ["member, the membership","会員","かいいん"  ],
  ["picture, paintings","絵画","かいが"  ],
  ["foreign, abroad, overseas","海外","かいがい"  ],
  ["account, finance, accountant","会計","かいけい"  ],
  ["settlement, solution, resolution","解決","かいけつ"  ],
  ["meeting, assembly","会合","かいごう"  ],
  ["diplomacy","外交","がいこう"  ],
  ["start, commencement, beginning","開始","かいし"  ],
  ["explanation, interpretation","解釈","かいしゃく"  ],
  ["outing, going out","外出","がいしゅつ"  ],
  ["betterment, improvement","改善","かいぜん"  ],
  ["pleasant, agreeable, comfortable","快適","かいてき"  ],
  ["recovery (from illness),improvement, rehabilitation, restoration","回復","かいふく"  ],
  ["to keep, to raise, to feed","飼う","かう"  ],
  ["to exchange, to interchange, to substitute, to replace","替える/換える","かえる"  ],
  ["aroma, fragrance, scent, smell","香り","かおり"  ],
  ["painter, artist","画家","がか"  ],
  ["to hold or carry under or in the arms","抱える","かかえる"  ],
  ["price, value, cost","価格","かかく"  ],
  ["chemistry","化学","かがく"  ],
  ["to shine, to glitter, to sparkle","輝く","かがやく"  ],
  ["official, duty, person in charge","係","かかり"  ],
  ["to take (e.g. time, money, etc),to hang","掛かる","かかる"  ],
  ["to suffer from","罹る","かかる"  ],
  ["key","鍵","かぎ"  ],
  ["to restrict,to limit,to confine","限る","かぎる"  ],
  ["to draw,to paint,to sketch,to depict,to describe","描く","かく"  ],
  ["furniture","家具","かぐ"  ],
  ["learning,scholarship,erudition,knowledge","学","がく"  ],
  ["picture frame","額","がく"  ],
  ["resolution, resignation, readiness, preparedness","覚悟","かくご"  ],
  ["certainty, reliability, soundness","確実","かくじつ"  ],
  ["scholar","学者","がくしゃ"  ],
  ["study,learning","学習","がくしゅう"  ],
  ["to hide,to conceal","隠す","かくす"  ],
  ["magnification, enlargement","拡大","かくだい"  ],
  ["affirmation, confirmation","確認","かくにん"  ],
  ["scholarship, study, learning","学問","がくもん"  ],
  ["to hide, to be hidden, to conceal oneself, to disappear","隠れる","かくれる"  ],
  ["shade, shadow, other side","影","かげ"  ],
  ["shade,shadow,other side","陰","かげ"  ],
  ["to be lacking","欠ける","かける"  ],
  ["addition and subtraction,allowance for","加減","かげん"  ],
  ["the past,bygone days,the previous","過去","かこ"  ],
  ["basket,cage","籠","かご"  ],
  ["to surround,to encircle","囲む","かこむ"  ],
  ["conflagration,fire","火災","かさい"  ],
  ["pastry","菓子","かし"  ],
  ["housework,domestic chores","家事","かじ"  ],
  ["wise,clever,smart","賢い","かしこい"  ],
  ["singer","歌手","かしゅ"  ],
  ["number,figure","数","かず"  ],
  ["to earn income,to labor","稼ぐ","かせぐ"  ],
  ["to count","数える","かぞえる"  ],
  ["mold,model,style,shape,data-type","型","かた"  ],
  ["shoulder","肩","かた"  ],
  ["solid,hard (esp. metal, stone),unpolished writing","硬い","かたい"  ],
  ["persons,this and that,here and there,everywhere","方々","かたがた"  ],
  ["shape, form","計","かたち"  ],
  ["sword,saber,knife,engraving tool","刀","かたな"  ],
  ["to talk,to tell,to recite","語る","かたる"  ],
  ["win,victory","勝ち","かち"  ],
  ["value,worth,merit","価値","かち"  ],
  ["feel disappointed,be dejected,lose heart","","がっかり"  ],
  ["energy,liveliness","活気","かっき"  ],
  ["term (school)","学期","がっき"  ],
  ["shape,form,posture,suitability,appearance","格好","かっこう"  ],
  ["action,activity","活動","かつどう"  ],
  ["conjugation,practical use","活用","かつよう"  ],
  ["to be sad,to mourn for,to regret","悲しむ","かなしむ"  ],
  ["(not) always,(not) necessarily,(not) all,(not) entirely","必ずしも","かならずしも"  ],
  ["considerably,fairly,quite","","かなり"  ],
  ["(1) gold,(2) gold general (shogi) (abbr)","金","かね"  ],
  ["possible,practicable,feasible","可能","かのう"  ],
  ["share,stock,stump (of tree)","株","かぶ"  ],
  ["to put on , wear, cover (one's) head,","被る","かぶる"  ],
  ["to mind,to care about,to be concerned about","構う","かまう"  ],
  ["patience,endurance,perseverance","我慢","がまん"  ],
  ["(1) first volume,(2) superior quality,(3) governmental","上","かみ"  ],
  ["god","神","かみ"  ],
  ["thunder","雷","かみなり"  ],
  ["hair (head)","髪の毛","かみのけ"  ],
  ["(school) subject,curriculum,course","科目","かもく"  ],
  ["may,might,perhaps,may be,possibly","","かもしれない"  ],
  ["(abbr) Tuesday","火曜","かよう"  ],
  ["empty","空","から"  ],
  ["pattern","柄","がら"  ],
  ["to cut (hair),to mow (grass),to harvest","刈る","かる"  ],
  ["they (usually male)","彼等","かれら"  ],
  ["river","川","かわ"  ],
  ["river,stream","河","かわ"  ],
  ["skin,hide,leather,fur,pelt,bark,shell","皮","かわ"  ],
  ["leather","革","かわ"  ],
  ["poor,pitiable,pathetic","","かわいそう"  ],
  ["lovely,sweet","","かわいらしい"  ],
  ["can,tin","缶","かん"  ],
  ["perception,intuition,the sixth sense","勘","かん"  ],
  ["thinking,thought,ideas,intention","考え","かんがえ"  ],
  ["sense,sensation","感覚","かんかく"  ],
  ["audience,spectator(s)","観客","かんきゃく"  ],
  ["environment,circumstance","環境","かんきょう"  ],
  ["welcome,reception","歓迎","かんげい"  ],
  ["sightseeing","観光","かんこう"  ],
  ["observation,survey","観察","かんさつ"  ],
  ["feeling,sense,impression","感じ","かんじ"  ],
  ["thanks,gratitude","感謝","かんしゃ"  ],
  ["a patient","患者","かんじゃ"  ],
  ["calculation,counting,consideration","勘定","かんじょう"  ],
  ["emotion(s),feeling(s),sentiment","感情","かんじょう"  ],
  ["to feel,to sense,to experience","感じる","かんじる"  ],
  ["admiration,Well done!","感心","かんしん"  ],
  ["concern,interest","関心","かんしん"  ],
  ["to concern,to be related","関する","かんする"  ],
  ["(1) complete,completion,(2) perfection,accomplishment","完成","かんせい"  ],
  ["perfection,completeness","完全","かんぜん"  ],
  ["being deeply moved,excitement,impression,deep emotion","感動","かんどう"  ],
  ["supervision,control,superintendence","監督","かんとく"  ],
  ["control,management (e.g. of a business)","管理","かんり"  ],
  ["completion,conclusion","完了","かんりょう"  ],
  ["relation,connection,relevance","関連","かんれん"  ],
  ["member of the Diet, congress or parliament","議員","ぎいん"  ],
  ["memory,recollection,remembrance","記憶","きおく"  ],
  ["temperature","気温","きおん"  ],
  ["machine,mechanism","機械","きかい"  ],
  ["Diet,congress,parliament","議会","ぎかい"  ],
  ["period,term","期間","きかん"  ],
  ["organ,mechanism,facility,engine","機関","きかん"  ],
  ["enterprise,undertaking","企業","きぎょう"  ],
  ["to be effective","効く","きく"  ],
  ["humour,temper,mood","機嫌","きげん"  ],
  ["climate","気候","きこう"  ],
  ["bank,coast,shore","岸","きし"  ],
  ["birthplace","生地","きじ"  ],
  ["article,news story,report,account","記事","きじ"  ],
  ["engineer,technician","技師","ぎし"  ],
  ["reporter","記者","きしゃ"  ],
  ["wound,injury,hurt,cut","傷","きず"  ],
  ["expectation,anticipation,hope","期待","きたい"  ],
  ["returning home","帰宅","きたく"  ],
  ["precious,valuable","貴重","きちょう"  ],
  ["chairman","議長","ぎちょう"  ],
  ["precisely,accurately","","きちんと"  ],
  ["tight,close,intense","","きつい"  ],
  ["to notice,to recognize,to become aware of","気付く","きづく"  ],
  ["to be pleased with,to suit","気に入る","きにいる"  ],
  ["entry,filling in of forms","記入","きにゅう"  ],
  ["commemoration,memory","記念","きねん"  ],
  ["function,faculty","機能","きのう"  ],
  ["pitiful,a pity","気の毒","きのどく"  ],
  ["contribution,donation","寄付","きふ"  ],
  ["hope,wish,aspiration","希望","きぼう"  ],
  ["foundation,basis,standard","基本","きほん"  ],
  ["settlement,conclusion,regulation,rule","決まり","きまり"  ],
  ["-like,-looking,-looked","気味","きみ"  ],
  ["strange,queer,curious","奇妙","きみょう"  ],
  ["duty,obligation,responsibility","義務","ぎむ"  ],
  ["question,problem,doubt,guess","疑問","ぎもん"  ],
  ["reverse,opposite","逆","ぎゃく"  ],
  ["ex-","旧","きゅう"  ],
  ["class, grade, rank,school class, grade","級","きゅう"  ],
  ["globe,sphere,ball","球","きゅう"  ],
  ["nine","九","きゅう / く"  ],
  ["holiday,day off,furlough","休暇","きゅうか"  ],
  ["rest,break,recess,intermission","休憩","きゅうけい"  ],
  ["sudden,precipitous,radical","急激","きゅうげき"  ],
  ["absorption,suction,attraction","吸収","きゅうしゅう"  ],
  ["relief,aid,rescue","救助","きゅうじょ"  ],
  ["rapid (e.g. progress)","急速","きゅうそく"  ],
  ["suddenly","急に","きゅうに"  ],
  ["salary,wages","給料","きゅうりょう"  ],
  ["skillful,handy","器用","きよう"  ],
  ["text book","教科書","きょうかしょ"  ],
  ["game,match,contest","競技","きょうぎ"  ],
  ["manners","行儀","ぎょうぎ"  ],
  ["supply,provision","供給","きょうきゅう"  ],
  ["teacher (classroom)","教師","きょうし"  ],
  ["teaching,instruction,professor","教授","きょうじゅ"  ],
  ["emphasis,stress,stressed point","強調","きょうちょう"  ],
  ["commonness,community","共通","きょうつう"  ],
  ["cooperation,association,collaboration,joint","共同","きょうどう"  ],
  ["be afraid,dread,dismay,terror","恐怖","きょうふ"  ],
  ["cooperation,collaboration","協力","きょうりょく"  ],
  ["herculean strength,mountain carrier-guide","強力","きょうりょく"  ],
  ["permission,approval","さ","きょか"  ],
  ["a bureau, department","局","きょく"  ],
  ["a pole","極","きょく"  ],
  ["huge,gigantic,enormous","巨大","きょだい"  ],
  ["to hate,to dislike,to loathe","嫌う","きらう"  ],
  ["fog,mist","霧","きり"  ],
  ["cloth,piece,cut,chop","切れ","きれ"  ],
  ["(1) to cut well,to be sharp,(2) to break (off)","切れる","きれる"  ],
  ["(abbr) kilo-,kilogram,kilometre,10^3","","キロ"  ],
  ["record,minutes,document","記録","きろく"  ],
  ["argument,discussion,dispute","議論","ぎろん"  ],
  ["(1) gold,(2) gold general (shogi) (abbr)","金","きん"  ],
  ["(1) silver,silver coin,silver paint","銀","ぎん"  ],
  ["No Smoking!","禁煙","きんえん"  ],
  ["amount of money","金額","きんがく"  ],
  ["safe,vault,treasury,provider of funds","金庫","きんこ"  ],
  ["prohibition,ban","禁止","きんし"  ],
  ["money,cash","金銭","きんせん"  ],
  ["metal","金属","きんぞく"  ],
  ["modern ages","近代","きんだい"  ],
  ["tension,mental strain,nervousness","緊張","きんちょう"  ],
  ["muscle,sinew","筋肉","きんにく"  ],
  ["finance, monetary circulation,","金融","きんゆう"  ],
  ["(abbr) Friday","金曜","きんよう"  ],
  ["nine","九","く"  ],
  ["sentence","句","く"  ],
  ["(male) (vulg) to eat","食う","くう"  ],
  ["(by) chance,unexpectedly,suddenly","偶然","ぐうぜん"  ],
  ["stink, smelly (bad)","臭い","くさい"  ],
  ["chain","鎖","くさり"  ],
  ["to rot,to go bad","腐る","くさる"  ],
  ["a habit (often a bad habit),peculiarity","癖","くせ"  ],
  ["pipe,tube","管","くだ"  ],
  ["concrete,tangible,material","具体","ぐたい"  ],
  ["(hon) to give,to confer","下さる","くださる"  ],
  ["down-train (going away from Tokyo)","下り","くだり"  ],
  ["pain,agony","苦痛","くつう"  ],
  ["sound asleep,fast asleep","","ぐっすり"  ],
  ["distinction,differentiation,classification","区別","くべつ"  ],
  ["class,group,team,set","組","くみ"  ],
  ["association,union","組合","くみあい"  ],
  ["to put together","組む","くむ"  ],
  ["cloudiness,cloudy weather,shadow","曇","くもり"  ],
  ["grade,rank,about","位","くらい"  ],
  ["living,livelihood,subsistence,circumstances","暮らし","くらし"  ],
  ["to live,to get along","暮らす","くらす"  ],
  ["to repeat,to do something over again","繰り返す","くりかえす"  ],
  ["to go mad,to get out of order","狂う","くるう"  ],
  ["painful,difficult","苦しい","くるしい"  ],
  ["to suffer,to groan,to be worried","苦しむ","くるしむ"  ],
  ["year end,sunset,nightfall,end","暮れ","くれ"  ],
  ["troubles,hardships","苦労","くろう"  ],
  ["to append,to sum up,to add (up)","加える","くわえる"  ],
  ["knowing very well,detailed,full,accurate","詳しい","くわしい"  ],
  ["to join in,to accede to,to increase,to gain in (influence)","加わる","くわわる"  ],
  ["native Japanese reading of a Chinese character","訓","くん"  ],
  ["army,force,troops","軍","ぐん"  ],
  ["army,troops","軍隊","ぐんたい"  ],
  ["practice,training","訓練","くんれん"  ],
  ["under,below,beneath","下","げ"  ],
  ["respect,honour","敬意","けいい"  ],
  ["management,administration","経営","けいえい"  ],
  ["plan,project,schedule,scheme,program,to plan","計画","けいかく・する"  ],
  ["business climate, condition,state","景気","けいき"  ],
  ["experience, to experience","経験","けいけん・する"  ],
  ["tendency,trend,inclination","傾向","けいこう"  ],
  ["warning,advice","警告","けいこく"  ],
  ["calculation,reckoning","計算","けいさん"  ],
  ["notice,bulletin","掲示","けいじ"  ],
  ["a police detective","刑事","けいじ"  ],
  ["(fine) art,the arts","芸術","げいじゅつ"  ],
  ["contract,compact,agreement","契約","けいやく"  ],
  ["go by the way,via","経由","けいゆ"  ],
  ["injury (to animate object),hurt, to injure","怪我","けが・する"  ],
  ["drama,play","劇","げき"  ],
  ["theatre,playhouse","劇場","げきじょう"  ],
  ["make-up (cosmetic)","化粧","けしょう"  ],
  ["stinginess,miser,miserliness","","けち"  ],
  ["result,consequence","結果","けっか"  ],
  ["defect,fault,deficiency","欠陥","けっかん"  ],
  ["after all,eventually","結局","けっきょく"  ],
  ["determination,resolution","決心","けっしん"  ],
  ["absence,non-attendance","欠席","けっせき"  ],
  ["decision,determination","決定","けってい"  ],
  ["faults,defect,weakness","欠点","けってん"  ],
  ["Monday","月曜","げつよう・げつようび"  ],
  ["conclusion","結論","けつろん"  ],
  ["smoke,fumes","煙","けむり"  ],
  ["ticket,coupon,bond,certificate","券","けん"  ],
  ["prefecture","県","けん"  ],
  ["a couter for house","軒","けん"  ],
  ["quarrel,(drunken) brawl,failure","喧嘩","けんか"  ],
  ["opinion,point of view","見解","けんかい"  ],
  ["limit,bound","限界","げんかい"  ],
  ["cash,ready money,mercenary,","現金","げんきん"  ],
  ["language","言語","げんご"  ],
  ["health,sound,wholesome","健康","けんこう"  ],
  ["inspection (e.g. customs, factory),examination","検査","けんさ"  ],
  ["present,up to now,nowadays,modern times,current","現在","げんざい"  ],
  ["reality","現実","げんじつ"  ],
  ["phenomenon","現象","げんしょう"  ],
  ["present condition,existing state,status quo","現状","げんじょう"  ],
  ["construction,establishment","建設","けんせつ"  ],
  ["nowadays,modern times,present-day","現代","げんだい"  ],
  ["construction,architecture","建築","けんちく"  ],
  ["be found,aim,estimate,guess,approx","見当","けんとう"  ],
  ["consideration,examination,investigation,study,scrutiny","検討","けんとう"  ],
  ["actual spot,scene,scene of the crime","現場","げんば"  ],
  ["constitution","憲法","けんぽう"  ],
  ["right,privilege","権利","けんり"  ],
  ["afterwards,since then,in the future","後","ご"  ],
  ["suffix for language,word","語","ご"  ],
  ["love,tender passion","恋","こい"  ],
  ["thick (as of color, liquid),dense,strong","濃い","こい"  ],
  ["lover,sweetheart","恋人","こいびと"  ],
  ["good luck,fortune","幸運","こううん"  ],
  ["lecture,address","講演","こうえん"  ],
  ["effect,effectiveness,efficacy,result","効果","こうか"  ],
  ["coin","硬貨","こうか"  ],
  ["high price","高価","こうか"  ],
  ["wonderful,gorgeous,splendor,pomp,extravagance","豪華","ごうか"  ],
  ["success,passing (e.g. exam),eligibility","合格","ごうかく"  ],
  ["exchange,interchange,reciprocity","交換","こうかん"  ],
  ["aviation,flying","航空","こうくう"  ],
  ["scene,spectacle","光景","こうけい"  ],
  ["sum total,total amount","合計","ごうけい"  ],
  ["attack,strike,offensive,criticism,censure","攻撃","こうげき"  ],
  ["contribution,services","貢献","こうけん"  ],
  ["advertisement","広告","こうこく"  ],
  ["company,friendship,association,society,acquaintance","交際","こうさい"  ],
  ["the latter","後者","こうしゃ"  ],
  ["organization,composition","構成","こうせい"  ],
  ["high speed,high gear","高速","こうそく"  ],
  ["action,conduct,behaviour,mobilization","行動","こうどう"  ],
  ["robbery,burglary","強盗","ごうとう"  ],
  ["happiness,blessedness","幸福","こうふく"  ],
  ["fairness,impartial,justice","公平","こうへい"  ],
  ["candidacy","候補","こうほ"  ],
  ["consideration,taking into account","考慮","こうりょ"  ],
  ["to exceed,to cross over,to cross","越える","こえる"  ],
  ["ice,hail","氷","こおり"  ],
  ["to freeze,to be frozen over,to congeal","凍る","こおる"  ],
  ["misunderstanding","誤解","ごかい"  ],
  ["language study","語学","ごがく"  ],
  ["breath,respiration","呼吸","こきゅう"  ],
  ["home town,birthplace,old village,historic village","故郷","こきょう"  ],
  ["national language","国語","こくご"  ],
  ["blackboard","黒板","こくばん"  ],
  ["subjugation,conquest","克服","こくふく"  ],
  ["national,people,citizen","国民","こくみん"  ],
  ["grain,cereal,corn","穀物","こくもつ"  ],
  ["here","ここ","ここ"  ],
  ["hip","腰","こし"  ],
  ["break-down,failure,accident,out of order","故障","こしょう"  ],
  ["individual,private person,personal,private","個人","こじん"  ],
  ["to go over (e.g. with audience)","越す","こす"  ],
  ["state,country,nation","国家","こっか"  ],
  ["National Diet,parliament,congress","国会","こっかい"  ],
  ["national or state border","国境","こっきょう"  ],
  ["bone fracture","骨折","こっせつ"  ],
  ["parcel,package","小包","こづつみ"  ],
  ["thing,matter,fact,circumstances","事","こと"  ],
  ["to differ,to vary,to disagree","異なる","ことなる"  ],
  ["proverb,maxim","諺","ことわざ"  ],
  ["to refuse,to decline,to dismiss","断る","ことわる"  ],
  ["flour,meal,powder","粉","こな"  ],
  ["this","この","この"  ],
  ["liking,taste,choice","好み","このみ"  ],
  ["to like,to prefer","好む","このむ"  ],
  ["dust,dirt　rubbish","塵","ごみ"  ],
  ["wheat","小麦","こむぎ"  ],
  ["I beg your pardon,excuse me","","ごめんなさい"  ],
  ["hut,cabin,shed,(animal) pen","小屋","こや"  ],
  ["these","","これら"  ],
  ["time,about,toward,approximately (time)","頃","ころ"  ],
  ["to kill","殺す","ころす"  ],
  ["to fall down,to fall over","転ぶ","ころぶ"  ],
  ["now,this time,lately","今回","こんかい"  ],
  ["from now on,hereafter","今後","こんご"  ],
  ["congestion,","混雑","こんざつ"  ],
  ["so,like this,in this way","","こんなに"  ],
  ["difficulty,distress","困難","こんなん"  ],
  ["today,this day","今日","こんにち"  ],
  ["hello,good day (daytime greeting, id)","","こんにちは"  ],
  ["engagement,betrothal","婚約","こんやく"  ],
  ["disorder,chaos,confusion,mayhem","混乱","こんらん"  ],
  ["difference,variation","差","さ"  ],
  ["on the occasion of,circumstances","際","さい"  ],
  ["highest,supreme,the most","最高","さいこう"  ],
  ["property,fortune,assets","財産","ざいさん"  ],
  ["last,final,closing","最終","さいしゅう"  ],
  ["in the middle of","最中","さいちゅう"  ],
  ["least,lowest,worst","最低","さいてい"  ],
  ["talent,ability","才能","さいのう"  ],
  ["trial,judgement","裁判","さいばん"  ],
  ["ingredients,material","材料","ざいりょう"  ],
  ["happiness,blessedness","幸い","さいわい"  ],
  ["border,boundary,mental state","境","さかい"  ],
  ["to go against,to oppose,to disobey,to defy","逆らう","さからう"  ],
  ["the highest, the peak, prime","盛り","さかり"  ],
  ["work,operation,manufacturing,fatigue duty","作業","さぎょう"  ],
  ["work,opus,performance,production","作品","さくひん"  ],
  ["produce (e.g. agricultural),crops","作物","さくもつ"  ],
  ["cherry blossom,cherry tree","桜","さくら"  ],
  ["alcohol,sake","酒","さけ"  ],
  ["to shout,to cry","叫ぶ","さけぶ"  ],
  ["(1) to avoid (physical contact ),(2) to ward off,to avert","避ける","さける"  ],
  ["to support, to hold, maintain","支える","ささえる"  ],
  ["to point,to put up umbrella,to play","指す","さす"  ],
  ["seat","座席","ざせき"  ],
  ["(1) to invite,to ask,(2) to tempt,to lure,to induce","誘う","さそう"  ],
  ["(1) token,label,(2) ticket,(3) charm","札","さつ"  ],
  ["author,writer,novelist,artist","作家","さっか"  ],
  ["composition,setting (of music)","作曲","さっきょく"  ],
  ["roughly,in round numbers","","ざっと"  ],
  ["feeling refreshed,feeling relieved,neat,trimmed","","さっぱり"  ],
  ["well,now,then","","さて"  ],
  ["desert","砂漠","さばく"  ],
  ["discrimination,distinction,differentiation","差別","さべつ"  ],
  ["manners,etiquette,propriety","作法","さほう"  ],
  ["varied,various","様々","さまざま"  ],
  ["to awaken","覚ます","さます"  ],
  ["to wake,to wake up","覚める","さめる"  ],
  ["(1) left and right,(2) influence,control,domination","左右","さゆう"  ],
  ["plate,dish","皿","さら"  ],
  ["furthermore,again,after all,more and more,moreover","更に","さらに"  ],
  ["to leave,to go away","去る","さる"  ],
  ["monkey","猿","さる"  ],
  ["uproar,disturbance","騒ぎ","さわぎ"  ],
  ["participation","参加","さんか"  ],
  ["reference,consultation","参考","さんこう"  ],
  ["approval,agreement,support,favour","賛成","さんせい"  ],
  ["oxygen","酸素","さんそ"  ],
  ["walk,stroll","散歩","さんぽ"  ],
  ["family name,lineage,birth","氏","し"  ],
  ["poem,verse of poetry","詩","し"  ],
  ["four","四","し/よん"  ],
  ["happiness,good fortune,luck,blessing","幸せ","しあわせ"  ],
  ["jet aeroplane","ジェット機","ジェットき"  ],
  ["immediately,readily,directly","直に","じかに"  ],
  ["moreover,furthermore,nevertheless,and yet","","しかも"  ],
  ["to scold","叱る","しかる"  ],
  ["equation,formula,ceremony","式","しき"  ],
  ["earnestly,immediately,exactly","お","じき"  ],
  ["time,season,period","時期","じき"  ],
  ["payment,allowance","支給","しきゅう"  ],
  ["frequently,repeatedly,incessantly,eagerly","","しきりに"  ],
  ["stimulus,impetus,incentive","刺激","しげき"  ],
  ["resources","資源","しげん"  ],
  ["event,affair,incident","事件","じけん"  ],
  ["instant,time,moment","時刻","じこく"  ],
  ["suicide","自殺","じさつ"  ],
  ["fact,truth,reality","事実","じじつ"  ],
  ["expenditure,expenses","支出","ししゅつ"  ],
  ["circumstances,consideration,conditions,situation,reasons","事情","じじょう"  ],
  ["poet","詩人","しじん"  ],
  ["by oneself,personally","自身","じしん"  ],
  ["to sink,to feel depressed","沈む","しずむ"  ],
  ["nature,spontaneous","自然","しぜん"  ],
  ["thought,idea","思想","しそう"  ],
  ["tongue","舌","した"  ],
  ["(1) order,precedence,(2) circumstances,(3) immediate(ly)","次第","しだい"  ],
  ["situation,present state of affairs","事態","じたい"  ],
  ["to abide (by the rules),to obey,to follow,to accompany","従う","したがう"  ],
  ["therefore,consequently,in accordance with","したがって","したがって"  ],
  ["preparation, to prepare","支度","したく・する"  ],
  ["intimate,close (e.g. friend)","親しい","したしい"  ],
  ["seven","七","しち・なな"  ],
  ["quality,nature (of person)","質","しつ"  ],
  ["unemployment","失業","しつぎょう"  ],
  ["experiment","実験","じっけん"  ],
  ["implementation,materialization,realization","実現","じつげん"  ],
  ["practice,performance,execution (e.g. program),realization","実行","じっこう"  ],
  ["practical,actual condition,status quo","実際","じっさい"  ],
  ["enforcement,enact,put into practice,carry out,operation","実施","じっし"  ],
  ["fixedly,firmly,patiently,quietly","","じっと"  ],
  ["indeed,truly,surely","実に","じつに"  ],
  ["as a matter of fact,by the way","実は","じつは"  ],
  ["disappointment,despair","失望","しつぼう"  ],
  ["branch store (office)","支店","してん"  ],
  ["leadership,guidance,coaching","指導","しどう"  ],
  ["automatic,self-motion","自動","じどう"  ],
  ["thing,article,goods,dignity,article (goods),counter for meal courses","品","しな"  ],
  ["rule,control,direction","支配","しはい"  ],
  ["play,drama","芝居","しばい"  ],
  ["often,again and again,frequently","","しばしば"  ],
  ["lawn","芝生","しばふ"  ],
  ["payment","支払","しはらい"  ],
  ["to pay","支払う","しはらう"  ],
  ["death,mortality","死亡","しぼう"  ],
  ["funds,capital","資本","しほん"  ],
  ["sisters","姉妹","しまい"  ],
  ["to finish, to close, put an end","","しまう"  ],
  ["Damn it!","","しまった"  ],
  ["pride,boast","自慢","じまん"  ],
  ["business,office work","事務","じむ"  ],
  ["to denote,to show,to point out,to indicate","示す","しめす"  ],
  ["(1) to comprise,to account for,to make up (of),(2) to hold,to occupy","占める","しめる"  ],
  ["under,below,beneath","下","しも"  ],
  ["frost","霜","しも"  ],
  ["debt,loan,liabilities","借金","しゃっきん"  ],
  ["to talk,to chat,to chatter","","しゃべる"  ],
  ["hindrance,intrusion","邪魔","じゃま"  ],
  ["week","週","しゅう"  ],
  ["a state, province, county","州","しゅう"  ],
  ["10,ten","十","じゅう"  ],
  ["gun","銃","じゅう"  ],
  ["surroundings,circumference,environs","周囲","しゅうい"  ],
  ["harvest,crop,ingathering","収穫","しゅうかく"  ],
  ["week,weekly","週間","しゅうかん"  ],
  ["religion","宗教","しゅうきょう"  ],
  ["importance,stress,serious consideration","重視","じゅうし"  ],
  ["finding employment,inauguration","就職","しゅうしょく"  ],
  ["amendment,correction,revision,modification","修正","しゅうせい"  ],
  ["congestion (e.g. traffic),delay,stagnation","渋滞","じゅうたい"  ],
  ["serious,important,grave,weighty","重大","じゅうだい"  ],
  ["resident,housing","住宅","じゅうたく"  ],
  ["group,mass","集団","しゅうだん"  ],
  ["concentration,focusing the mind","集中","しゅうちゅう"  ],
  ["income,receipts,revenue","収入","しゅうにゅう"  ],
  ["citizens,inhabitants,residents,population","住民","じゅうみん"  ],
  ["important, momentous, essential, principal, major","重要","じゅうよう"  ],
  ["repairing,mending","修理","しゅうり"  ],
  ["doctrine,rule,principle","主義","しゅぎ"  ],
  ["lodging","宿泊","しゅくはく"  ],
  ["surgical operation","手術","しゅじゅつ"  ],
  ["Prime Minister","首相","しゅしょう"  ],
  ["means,way,measure","手段","しゅだん"  ],
  ["claim,request,insistence,assertion","主張","しゅちょう"  ],
  ["graduate from,come from","出身","しゅっしん"  ],
  ["attendance,presence, to attend","出席","しゅっせき・する"  ],
  ["departure, to depart","出発","しゅっぱつ・する"  ],
  ["publication","出版","しゅっぱん"  ],
  ["capital city","首都","しゅと"  ],
  ["housewife,","主婦","しゅふ"  ],
  ["chief,main,principal,major","主要","しゅよう"  ],
  ["demand,request","需要","じゅよう"  ],
  ["variety,kind,type","種類","しゅるい"  ],
  ["order,turn","順","じゅん"  ],
  ["moment,second,instant","瞬間","しゅんかん"  ],
  ["favourable,doing well,O.K.,all right","順調","じゅんちょう"  ],
  ["turn (in line),order of things","順番","じゅんばん"  ],
  ["preparation,arrangements,provision,reserve, to prepare","準備","じゅんび・する"  ],
  ["small","小","しょう"  ],
  ["(1) chapter,section,(2) medal","章","しょう"  ],
  ["prize,award","賞","しょう"  ],
  ["use,application,employment,utilization","使用","しよう"  ],
  ["(1) first volume,(2) superior quality,","上","じょう"  ],
  ["obstacle,impediment (fault),damage","障害","しょうがい"  ],
  ["scholarship","奨学金","しょうがくきん"  ],
  ["passenger","乗客","じょうきゃく"  ],
  ["proceeding to the capital (Tokyo)","上京","じょうきょう"  ],
  ["state of affairs,situation,circumstances","状況","じょうきょう"  ],
  ["conditions,terms","条件","じょうけん"  ],
  ["noon,mid-day","正午","しょうご"  ],
  ["honesty,integrity,frankness","正直","しょうじき"  ],
  ["common sense","常識","じょうしき"  ],
  ["daughter,young lady,virgin,maiden,little girl","少女","しょうじょ"  ],
  ["just a minute,small quantity","少々","しょうしょう"  ],
  ["symptoms,condition","症状","しょうじょう"  ],
  ["to produce,to yield,to result from,to arise,to be generated","生じる","しょうじる"  ],
  ["condition,situation,circumstances,state","状態","じょうたい"  ],
  ["invitation, to invite","招待","しょうたい・する"  ],
  ["improvement,advance,progress","上達","じょうたつ"  ],
  ["jest,joke","冗談","じょうだん"  ],
  ["consent,acceptance,assent,admitting, to consent","承知","しょうち・する"  ],
  ["superiority,first class,very good","上等","じょうとう"  ],
  ["collision,conflict","衝突","しょうとつ"  ],
  ["trader,shopkeeper,merchant","商人","しょうにん"  ],
  ["recognition,acknowledgement,approval,consent,agreement","承認","しょうにん"  ],
  ["boys,juveniles","少年","しょうねん"  ],
  ["trade,business,commerce,transaction,occupation","商売","しょうばい"  ],
  ["consumption,expenditure","消費","しょうひ"  ],
  ["commodity,article of commerce,goods,stock,merchandise","商品","しょうひん"  ],
  ["fire fighting,fire department","消防","しょうぼう"  ],
  ["information,(military) intelligence","情報","じょうほう"  ],
  ["proof,verification","証明","しょうめい"  ],
  ["queen","女王","じょおう"  ],
  ["employment","職","しょく"  ],
  ["occupation,business","職業","しょくぎょう"  ],
  ["meal, to have a meal","食事","しょくじ・する"  ],
  ["dining table","食卓","しょくたく"  ],
  ["commodity,foodstuff","食品","しょくひん"  ],
  ["plant,vegetation","植物","しょくぶつ"  ],
  ["food,foodstuff","食物","しょくもつ"  ],
  ["appetite (for food)","食欲","しょくよく"  ],
  ["food","食料","しょくりょう"  ],
  ["provisions,rations","食糧","しょくりょう"  ],
  ["study","書斎","しょさい"  ],
  ["woman,girl","女子","じょし"  ],
  ["helper,helpmeet,assistant,tutor","助手","じょしゅ"  ],
  ["slowly,little by little,gradually,steadily,quietly","徐々に","じょじょに"  ],
  ["signature","署名","しょめい"  ],
  ["books","書物","しょもつ"  ],
  ["actress","女優","じょゆう"  ],
  ["processing,dealing with,treatment,disposition,disposal","処理","しょり"  ],
  ["documents,official papers","書類","しょるい"  ],
  ["notice","知らせ","しらせ"  ],
  ["buttocks,bottom","尻","しり"  ],
  ["(1) mark,(2) symbol,(3) evidence","印","しるし"  ],
  ["castle","城","しろ"  ],
  ["going on to a higher level school,","進学","しんがく"  ],
  ["nerve,sensitivity","神経","しんけい"  ],
  ["seriousness,earnestness","真剣","しんけん"  ],
  ["(religious) faith,belief,creed","信仰","しんこう"  ],
  ["traffic lights,signal,semaphore","信号","しんごう"  ],
  ["artificial,manmade,human work,human skill,artificiality","人工","じんこう"  ],
  ["serious","深刻","しんこく"  ],
  ["medical examination","診察","しんさつ"  ],
  ["race (of people)","人種","じんしゅ"  ],
  ["to believe,to place trust in","信じる","しんじる"  ],
  ["(human) life (i.e. conception to death)","人生","じんせい"  ],
  ["relative","親戚","しんせき"  ],
  ["fresh","新鮮","しんせん"  ],
  ["heart (organ)","心臓","しんぞう"  ],
  ["the body","身体","しんたい"  ],
  ["height (of body),stature","身長","しんちょう"  ],
  ["discretion,prudence","慎重","しんちょう"  ],
  ["worry,concern,anxiety,care, to worry","心配","しんぱい・する"  ],
  ["refereeing,trial,judgement,umpire,referee","審判","しんぱん"  ],
  ["character,personality,person,man,personage,talented man","人物","じんぶつ"  ],
  ["progress,development","進歩","しんぽ"  ],
  ["close friend,buddy","親友","しんゆう"  ],
  ["confidence,dependence,credit,faith","信用","しんよう"  ],
  ["reliance,trust,confidence","信頼","しんらい"  ],
  ["pshcyology, mental state","心理","しんり"  ],
  ["mankind,humanity","人類","じんるい"  ],
  ["sandbank","州","す"  ],
  ["nest,rookery,breeding place,beehive,cobweb","巣","す"  ],
  ["figure (e.g. Fig 1),drawing,picture,illustration","図","ず"  ],
  ["(1) level, standard, (2) water level","水準","すいじゅん"  ],
  ["recommendation","推薦","すいせん"  ],
  ["extremely","随分","ずいぶん"  ],
  ["sleep","睡眠","すいみん"  ],
  ["number,figure","数","すう"  ],
  ["numeral,figure","数字","すうじ"  ],
  ["the end of,powder","末","すえ"  ],
  ["figure,shape,appearance","姿","すがた"  ],
  ["(1) to open,to become empty,(2) to be less crowded","空く","すく"  ],
  ["to rescue from,to help out of","救う","すくう"  ],
  ["to surpass,to outstrip,to excel","優れる","すぐれる"  ],
  ["terrible,dreadful,terrific,amazing,great","","すごい"  ],
  ["anything of,not one bit","少しも","すこしも"  ],
  ["to pass,to spend,to go through,to tide over","過ごす","すごす"  ],
  ["muscle,string,line","筋","すじ"  ],
  ["to advance,to promote,to hasten","進める","すすめる"  ],
  ["to recommend,to advise,to encourage,to offer (wine)","勧める","すすめる"  ],
  ["headache","頭痛","ずつう"  ],
  ["consecutively,throughout,a lot","","ずっと"  ],
  ["lovely,dreamy,beautiful,great","","すてき"  ],
  ["already,too late","既に","すでに"  ],
  ["that is,namely,i.e.","","すなわち"  ],
  ["wonderful,splendid,magnificent","素晴らしい","すばらしい"  ],
  ["all,the whole,entirely,in general,wholly","全て","すべて"  ],
  ["all,whole,entire,complete,overall,pan","全て","すべて"  ],
  ["to be finished","済ませる","すませる"  ],
  ["sorry,excuse me","","すみません"  ],
  ["to do","為る","する"  ],
  ["thereupon,hereupon","すると","すると"  ],
  ["pointed,sharp","鋭い","するどい"  ],
  ["height,stature","背","せい"  ],
  ["(logical) true,regular","正","せい"  ],
  ["sex,gender","性","せい"  ],
  ["cause,reason,fault","所為","せい"  ],
  ["a tax","税","ぜい"  ],
  ["character,personality","性格","せいかく"  ],
  ["accurate,punctuality,exactness,authenticity,veracity","正確","せいかく"  ],
  ["century,era","世紀","せいき"  ],
  ["claim,demand,application,request","請求","せいきゅう"  ],
  ["tax,duty","税金","ぜいきん"  ],
  ["clean","清潔","せいけつ"  ],
  ["restriction,restraint,limitation","制限","せいげん"  ],
  ["success,hit","成功","せいこう"  ],
  ["production,manufacture","生産","せいさん"  ],
  ["due form,official,formality","正式","せいしき"  ],
  ["mind,soul,heart,spirit,intention","精神","せいしん"  ],
  ["adult","成人","せいじん"  ],
  ["at the most,at best,to the utmost,as much (far) as possible","精々","せいぜい"  ],
  ["results,record","成績","せいせき"  ],
  ["manufacture,production","製造","せいぞう"  ],
  ["luxury,extravagance","贅沢","ぜいたく"  ],
  ["growth,grow to adulthood","成長","せいちょう"  ],
  ["system,institution,organization","制度","せいど"  ],
  ["youth,young man","青年","せいねん"  ],
  ["manufactured goods,finished goods","製品","せいひん"  ],
  ["government,administration","政府","せいふ"  ],
  ["raw food","生物","せいぶつ"  ],
  ["life,existence","生命","せいめい"  ],
  ["sorting,arrangement,adjustment,regulation","整理","せいり"  ],
  ["cough","咳","せき"  ],
  ["coal","石炭","せきたん"  ],
  ["duty,responsibility","責任","せきにん"  ],
  ["oil,petroleum,kerosene","石油","せきゆ"  ],
  ["world,society","世間","せけん"  ],
  ["theory","説","せつ"  ],
  ["positive,active,proactive","積極的","せっきょくてき"  ],
  ["plan,design","設計","せっけい"  ],
  ["absolute,unconditional,absoluteness","絶対","ぜったい"  ],
  ["equipment,device,facilities,installation","設備","せつび"  ],
  ["destruction,extinction","絶滅","ぜつめつ"  ],
  ["economising,saving","節約","せつやく"  ],
  ["certainly,without fail","是非","ぜひ"  ],
  ["to condemn,to blame,to criticize","責める","せめる"  ],
  ["looking after,help,aid,assistance, to look after","世話","せわ・する"  ],
  ["good,goodness,right,virtue","善","ぜん"  ],
  ["all members (unanimity),all hands,the whole crew","全員","ぜんいん"  ],
  ["major subject,special study","専攻","せんこう"  ],
  ["country-wide,nation-wide,whole country,national","全国","ぜんこく"  ],
  ["the other day,a few days ago","先日","せんじつ"  ],
  ["the former","前者","ぜんしゃ"  ],
  ["(1) player (in game),(2) team","選手","せんしゅ"  ],
  ["advance,drive,progress","前進","ぜんしん"  ],
  ["(1) wholly,entirely,completely,(2) not at all (with neg. verb)","全然","ぜんぜん"  ],
  ["whole,entirety,whatever (is the matter)","全体","ぜんたい"  ],
  ["selection,choice","選択","せんたく"  ],
  ["so","そう","そう"  ],
  ["elephant","象","ぞう"  ],
  ["noise","騒音","そうおん"  ],
  ["increase,addition","増加","ぞうか"  ],
  ["operation,management,processing","操作","そうさ"  ],
  ["cleaning,sweeping, to clean, to sweep","掃除","そうじ/そうじする"  ],
  ["imagination,guess","想像","そうぞう"  ],
  ["succession,inheritance","相続","そうぞく"  ],
  ["consultation,discussion，to consult, to discuss","相談","そうだん/そうだんする"  ],
  ["equipment,installation,apparatus","装置","そうち"  ],
  ["suitable,fair,tolerable,proper","相当","そうとう"  ],
  ["speed,velocity,rate","速度","そくど"  ],
  ["bottom,sole","底","そこ"  ],
  ["so (conj),accordingly,now,then,thereupon","","そこで"  ],
  ["(1) organization,(2) structure,construction,(3) tissue,(4) system","組織","そしき"  ],
  ["and","","そして"  ],
  ["to pour (into),to irrigate,to pay,to fill,to feed (e.g. a fire)","注ぐ","そそぐ"  ],
  ["to raise (child),to be brought up,to grow (up)","育つ","そだつ"  ],
  ["all,altogether,entirely,be just like,the splitting image of","","そっくり"  ],
  ["face of the earth","","そっと"  ],
  ["sleeve","袖","そで"  ],
  ["to furnish,to provide for,to equip,to install","備える","そなえる"  ],
  ["the,that","その","その"  ],
  ["eventually,sooner or later,of the previously mentioned","","そのうち"  ],
  ["without change,as it is (i.e. now)","","そのまま"  ],
  ["side,edge,third person","側","そば"  ],
  ["crude,rough,plain,humble","粗末","そまつ"  ],
  ["it,that","","それ"  ],
  ["each,every,either,respectively,severally","","それぞれ"  ],
  ["but (still),and yet,nevertheless,even so,notwithstanding","","それでも"  ],
  ["or,or else","","それとも"  ],
  ["loss,disadvantage","損","そん"  ],
  ["damage,injury,loss","損害","そんがい"  ],
  ["respect,esteem,reverence,honour","尊敬","そんけい"  ],
  ["existence,being","存在","そんざい"  ],
  ["respect,esteem,regard","尊重","そんちょう"  ],
  ["rice field","田","た"  ],
  ["other (esp. places and things)","他","た"  ],
  ["stand,rack,table,support, counter for machine","台","だい"  ],
  ["title,subject,theme,topic","題","だい"  ],
  ["physical education,gymnastics,athletics","体育","たいいく"  ],
  ["temperature (body)","体温","たいおん"  ],
  ["convention,tournament,mass meeting,rally","大会","たいかい"  ],
  ["the air, atmosphere","大気","たいき"  ],
  ["price,payment,cost,charge","代金","だいきん"  ],
  ["tedium,boredom","退屈","たいくつ"  ],
  ["stay,sojourn","滞在","たいざい"  ],
  ["ambassador","大使","たいし"  ],
  ["considerable,great,important,significant,a big deal","大した","たいした"  ],
  ["target,object (of worship, study, etc),subject (of taxation, etc)","対象","たいしょう"  ],
  ["cabinet minister","大臣","だいじん"  ],
  ["to face,to confront,to oppose","対する","たいする"  ],
  ["great war,great battle","大戦","たいせん"  ],
  ["usually,generally","大抵","たいてい"  ],
  ["attitude,manner","態度","たいど"  ],
  ["president,chief executive","大統領","だいとうりょう"  ],
  ["majority,mostly,generally","大半","たいはん"  ],
  ["representative,representation,delegation,type,example,model","代表","だいひょう"  ],
  ["most part,greater part,majority","大部分","だいぶぶん"  ],
  ["awful,dreadful,terrible,very","大変","たいへん"  ],
  ["arrest,apprehension,capture","逮捕","たいほ"  ],
  ["sun,solar","太陽","たいよう"  ],
  ["flatness,level,smooth,calm,plain","平ら","たいら"  ],
  ["representation,agency,proxy,deputy,agent","代理","だいり"  ],
  ["continent","大陸","たいりく"  ],
  ["to throw down,to beat,to bring down,to blow down","倒す","たおす"  ],
  ["however","だが","だが"  ],
  ["mutual,reciprocal","互い","たがい"  ],
  ["treasure","宝","たから"  ],
  ["so,therefore","だから","だから"  ],
  ["house,home,husband","宅","たく"  ],
  ["however","","だけど"  ],
  ["to ascertain, confirm","確かめる","たしかめる"  ],
  ["more or less,somewhat,a little,some","多少","たしょう"  ],
  ["to help,to save,to rescue","助ける","たすける"  ],
  ["free of charge,","","ただ"  ],
  ["mere,sole,only","唯","ただ"  ],
  ["battle,fight,struggle,conflict","戦い","たたかい"  ],
  ["to fight,to battle,to combat","戦う","たたかう"  ],
  ["to strike,to clap,to dust,to beat","叩く","たたく"  ],
  ["at once,immediately,directly,in person","直ちに","ただちに"  ],
  ["to stand up","立ち上がる","たちあがる"  ],
  ["standpoint,position,situation","立場","たちば"  ],
  ["to pass,to lapse","経つ","たつ"  ],
  ["to reach,to get to","達する","たっする"  ],
  ["only (use with a word which indicates numbers)","唯","たった"  ],
  ["but,because,even,also,too","","だって"  ],
  ["full,in plenty,ample","","たっぷり"  ],
  ["length,height","縦","たて"  ],
  ["simile,metaphor,allegory","","たとえ"  ],
  ["valley","谷","たに"  ],
  ["another person,unrelated person,outsider,stranger","他人","たにん"  ],
  ["(1) seed,(2) material,(3) cause,source","種","たね"  ],
  ["handbreadth,bundle","束","たば"  ],
  ["counter for occurrences","度","たび"  ],
  ["travel,trip,journey","旅","たび"  ],
  ["often,repeatedly,frequently","","たびたび"  ],
  ["perhaps,probably","多分","たぶん"  ],
  ["ball,sphere,coin","玉","たま"  ],
  ["globe,sphere,ball","球","たま"  ],
  ["bullet,shot,shell","弾","たま"  ],
  ["casually,unexpectedly,accidentally,by chance","偶々","たまたま"  ],
  ["intolerable, unbearable, unendurable","","たまらない"  ],
  ["to be silent","黙る","だまる"  ],
  ["useless,no good,hopeless","駄目","だめ"  ],
  ["trial,test","試し","ためし"  ],
  ["to attempt,to test","試す","ためす"  ],
  ["news, tidings, information, correspondence, letter","便り","たより"  ],
  ["to rely on,to have recourse to,to depend on","頼る","たよる"  ],
  ["someone,somebody","誰か","だれか"  ],
  ["step,stair,flight of steps,grade,rank,level","段","だん"  ],
  ["unit,denomination,credit (in school)","単位","たんい"  ],
  ["word,vocabulary,(usually) single-character word","単語","たんご"  ],
  ["a boy, a man, a male","男子","だんし"  ],
  ["simplicity","単純","たんじゅん"  ],
  ["birth","誕生","たんじょう"  ],
  ["organization,association, a group","団体","だんたい"  ],
  ["(in) charge","担当","たんとう"  ],
  ["mere,simple,sheer","単なる","たんなる"  ],
  ["simply,merely,only,solely","単に","たんに"  ],
  ["earth","地","ち"  ],
  ["(social) position,status","地位","ちい"  ],
  ["area,region","地域","ちいき"  ],
  ["wisdom, intelligence, advice","知恵","ちえ"  ],
  ["basement,underground","地下","ちか"  ],
  ["difference,discrepancy","違い","ちがい"  ],
  ["(phrase) sure,no mistaking it,for certain","違いない","ちがいない"  ],
  ["lately,recently,nowadays","近頃","ちかごろ"  ],
  ["the earth","地球","ちきゅう"  ],
  ["district,section,sector","地区","ちく"  ],
  ["lateness,late coming","遅刻","ちこく"  ],
  ["prefectural governor","知事","ちじ"  ],
  ["knowledge,information","知識","ちしき"  ],
  ["father","父親","ちちおや"  ],
  ["intelligence,brains","知能","ちのう"  ],
  ["horizon","地平線","ちへいせん"  ],
  ["area,locality,district,region,the coast","地方","ちほう"  ],
  ["tea","茶","ちゃ"  ],
  ["perfectly,properly,exactly","","ちゃんと"  ],
  ["inside,middle,among","中","ちゅう"  ],
  ["annotation,explanatory note","注","ちゅう"  ],
  ["centre,central,center,middle","中央","ちゅうおう"  ],
  ["middle school,junior high school","中学","ちゅうがく"  ],
  ["(1) used,second-hand,old","中古","ちゅうこ"  ],
  ["suspension, stoppage, discontinuance, interruption","中止","ちゅうし"  ],
  ["parking (e.g. car)","駐車","ちゅうしゃ"  ],
  ["lunch,midday meal","昼食","ちゅうしょく"  ],
  ["center,core,heart,pivot,emphasis,balance","中心","ちゅうしん"  ],
  ["notice,attention,observation","注目","ちゅうもく"  ],
  ["order,request","注文","ちゅうもん"  ],
  ["long time period","長期","ちょうき"  ],
  ["investigation,examination,inquiry,survey","調査","ちょうさ"  ],
  ["condition, form, shape, tune,tone,key","調子","ちょうし"  ],
  ["top,summit,peak","頂上","ちょうじょう"  ],
  ["(1) please do for me (preceded by -te),(2) reception,being given,get (spoken)","","ちょうだい"  ],
  ["(bank) savings","貯金","ちょきん"  ],
  ["direct,immediate,personal,firsthand","直接","ちょくせつ"  ],
  ["author,writer","著者","ちょしゃ"  ],
  ["pair,couple,set","対","つい"  ],
  ["finally,at last","遂に","ついに"  ],
  ["passage through,passing","通過","つうか"  ],
  ["commuting to school","通学","つうがく"  ],
  ["passage,passing","通行","つうこう"  ],
  ["to run to,to lead to,to communicate,to understand","通じる","つうじる"  ],
  ["correspondence,communication,news,signal","通信","つうしん"  ],
  ["to be caught,to be arrested","捕まる","つかまる"  ],
  ["to seize,to catch,to grasp","掴む","つかむ"  ],
  ["tiredness,fatigue","疲れ","つかれ"  ],
  ["moon,month","月","つき"  ],
  ["association,socializing,fellowship","付き合い","つきあい"  ],
  ["in succession,one by one","次々","つぎつぎ"  ],
  ["to take (seat, position),to get (a job)","就く","つく"  ],
  ["to pour (into),to irrigate,to pay","注ぐ","つぐ"  ],
  ["to attach,to join,to add,to append","付ける","つける"  ],
  ["earth,soil","土","つち"  ],
  ["sequel,continuation","続き","つづき"  ],
  ["bundle,package,parcel,bale","包み","つつみ"  ],
  ["(1) service, business, job(2) Buddhist religious services","勤め","つとめ"  ],
  ["(1) service,duty,","務め","つとめ"  ],
  ["to tie,to fasten,to connect,to transfer (phone call)","繋ぐ","つなぐ"  ],
  ["always,constantly","常に","つねに"  ],
  ["horn","角","つの"  ],
  ["wings","翼","つばさ"  ],
  ["in short,in brief,in other words","","つまり"  ],
  ["crime,fault,indiscretion","罪","つみ"  ],
  ["to pack,to shorten,to work out (details)","詰める","つめる"  ],
  ["to pile up","積もる","つもる"  ],
  ["rainy season,rain during the rainy season","梅雨","つゆ"  ],
  ["painful,heart-breaking","辛い","つらい"  ],
  ["fishing","釣","つり"  ],
  ["companion,company","連れ","つれ"  ],
  ["meeting,rendezvous,encounter","出会い","であい"  ],
  ["to meet by chance,to come across,to happen to encounter","出会う","であう"  ],
  ["proposal,proposition,suggestion","提案","ていあん"  ],
  ["fixed term","定期","ていき"  ],
  ["resistance,opposition, electrical resistance,","抵抗","ていこう"  ],
  ["presentation,submission,filing","提出","ていしゅつ"  ],
  ["degree,amount,grade,standard,of the order of (following a number)","程度","ていど"  ],
  ["bus or tram stop","停留所","ていりゅうじょ"  ],
  ["enemy,rival","敵","てき"  ],
  ["incident,affair,happening,event","出来事","できごと"  ],
  ["to fit,to suit","適する","てきする"  ],
  ["pertinent,appropriate,adequate,relevance","適切","てきせつ"  ],
  ["moderate","適度","てきど"  ],
  ["applying","適用","てきよう"  ],
  ["to be able to,to be ready,to occur","","できる"  ],
  ["as (much) (soon) as possible","出来るだけ","できるだけ"  ],
  ["if at all possible","","できれば"  ],
  ["sleight of hand,conjuring trick,magic,juggling","手品","てじな"  ],
  ["therefore","","ですから"  ],
  ["iron","鉄","てつ"  ],
  ["philosophy","哲学","てつがく"  ],
  ["help,helper,assistant","手伝い","てつだい"  ],
  ["thoroughness,completeness","徹底","てってい"  ],
  ["railroad","鉄道","てつどう"  ],
  ["all night,all night vigil,sleepless night","徹夜","てつや"  ],
  ["then, in that case,if so","では","では"  ],
  ["time,labour","手間","てま"  ],
  ["but,however","でも","でも"  ],
  ["type,pattern,archetypal","典型","てんけい"  ],
  ["weather","天候","てんこう"  ],
  ["electron","電子","でんし"  ],
  ["tradition,convention","伝統","でんとう"  ],
  ["nature,spontaneity","天然","てんねん"  ],
  ["counter for occurrences","度","ど"  ],
  ["question,query","問い","とい"  ],
  ["party (political)","党","とう"  ],
  ["tower,pagoda","塔","とう"  ],
  ["examination paper,examination script","答案","とうあん"  ],
  ["identity,sameness,similarity","同一","どういつ"  ],
  ["copper coin","銅貨","どうか"  ],
  ["at that time,in those days","当時","とうじ"  ],
  ["verb","動詞","どうし"  ],
  ["simultaneous(ly),concurrent,same time,synchronous","同時","どうじ"  ],
  ["by all means,at any cost,no matter what","","どうしても"  ],
  ["arrival","到着","とうちゃく"  ],
  ["morals","道徳","どうとく"  ],
  ["voting,poll","投票","とうひょう"  ],
  ["identical,equal to,same (kind),like","同様","どうよう"  ],
  ["coworker,colleague,associate","同僚","どうりょう"  ],
  ["road,highway","道路","どうろ"  ],
  ["10,ten","十","とお"  ],
  ["to let pass,to overlook,to continue","通す","とおす"  ],
  ["in accordance with ~,following ~,~ Street,~ Avenue","通り","とおり"  ],
  ["to pass,to pass through","通り過ぎる","とおりすぎる"  ],
  ["city","都会","とかい"  ],
  ["(1) time,hour,(2) occasion,moment","時","とき"  ],
  ["to unfasten, to solve","解く","とく"  ],
  ["poison,toxicant","毒","どく"  ],
  ["pride,triumph,prosperity","得意","とくい"  ],
  ["reading","読書","どくしょ"  ],
  ["bachelorhood,single,unmarried,celibate","独身","どくしん"  ],
  ["distinctive feature,characteristic","特徴","とくちょう"  ],
  ["peculiarity,uniqueness,characteristic","独特","どくとく"  ],
  ["independence (e.g. Ind. Day),self-support","独立","どくりつ"  ],
  ["to come untied,to come apart","解ける","とける"  ],
  ["somewhere,anywhere","","どこか"  ],
  ["however,while,even if","","ところが"  ],
  ["by the way,even if,no matter what","","ところで"  ],
  ["mountain-climbing","登山","とざん"  ],
  ["town,city,municipal,urban","都市","とし"  ],
  ["months and years","年月","としつき(ねんげつ）"  ],
  ["books","図書","としょ"  ],
  ["old people,the aged","年寄","としより"  ],
  ["to close (e.g. book, eyes),to shut","閉じる","とじる"  ],
  ["just (now, at the moment, etc.)","途端","とたん"  ],
  ["plot of land,lot,soil","土地","とち"  ],
  ["abruptly,suddenly,unexpectedly,all at once","突然","とつぜん"  ],
  ["to reach","届く","とどく"  ],
  ["anyhow,at any rate,anyway,somehow or other,generally speaking,in any case","","とにかく"  ],
  ["to skip over,to omit","飛ばす","とばす"  ],
  ["to jump out,to rush out,to fly out","飛び出す","とびだす"  ],
  ["to fasten,to turn off,to detain","留める","とめる"  ],
  ["friend,companion,pal","友","とも"  ],
  ["sharing with,participate in","共に","ともに"  ],
  ["Saturday","土曜/土曜日","どよう/どようび"  ],
  ["tiger","虎","とら"  ],
  ["to take up,to pick up,to disqualify,to confiscate,to deprive","取り上げる","とりあげる"  ],
  ["great effort,exertion,endeavour,effort","努力","どりょく"  ],
  ["which (of three or more)","どれ","どれ"  ],
  ["to come off,to be taken off,to be removed","取れる","とれる"  ],
  ["mud","泥","どろ"  ],
  ["unexpected,offensive,What a thing to say!,No way!","","とんでもない"  ],
  ["what,what kind of","","どんな"  ],
  ["how,how much","","どんなに"  ],
  ["name,reputation","名","な"  ],
  ["subject, contents, substance,","内容","ないよう"  ],
  ["straight,mischief,ordinary,common","","なお"  ],
  ["relation,relationship","仲","なか"  ],
  ["to drain,to float,to shed (blood, tears),to cruise (e.g. taxi)","流す","ながす"  ],
  ["very,considerably,easily","","なかなか"  ],
  ["middle,half,semi,halfway,partly","半ば","なかば"  ],
  ["company,fellow,colleague,associate","仲間","なかま"  ],
  ["scene,view,prospect,outlook","眺め","ながめ"  ],
  ["to view,to gaze at","眺める","ながめる"  ],
  ["stream,current","流れ","ながれ"  ],
  ["to stream,to flow,to run (ink),to be washed away","流れる","ながれる"  ],
  ["without","無し","なし"  ],
  ["because","","なぜなら"  ],
  ["riddle,puzzle,enigma","謎","なぞ"  ],
  ["consent,assent,understanding","納得","なっとく"  ],
  ["et cetera,etc.,and the like","等","など"  ],
  ["seven","七","なな"  ],
  ["what","何","なに"  ],
  ["something","何か","なにか"  ],
  ["nothing","","なにも"  ],
  ["saucepan,pot","鍋","なべ"  ],
  ["(1) draft (beer),(2) raw,unprocessed","生","なま"  ],
  ["(1) draft (beer),(2) raw,unprocessed","生","なま"  ],
  ["to be idle,to neglect","怠ける","なまける"  ],
  ["wave","波","なみ"  ],
  ["tear","涙","なみだ"  ],
  ["to be worried,to be troubled","悩む","なやむ"  ],
  ["to change,to be of use,to reach to","為る","なる"  ],
  ["to become","成る","なる"  ],
  ["rope,hemp","縄","なわ"  ],
  ["Why?,What for?","何で","なんで"  ],
  ["by all means,everything","何でも","なんでも"  ],
  ["somehow,anyhow,one way or another","何とか","なんとか"  ],
  ["to suit,to match,to become,to be like","似合う","にあう"  ],
  ["odour,scent,smell,stench","匂い","におい"  ],
  ["poor (at),weak (in),dislike (of)","苦手","にがて"  ],
  ["to grasp,to hold a (thing) in one's hand, grip","握る","にぎる"  ],
  ["sun,sunshine,day","日","にち"  ],
  ["ordinary,regular,everyday,usual","日常","にちじょう"  ],
  ["Sunday","日曜","にちよう"  ],
  ["sunlight","日光","にっこう"  ],
  ["smile sweetly,smile,grin","","にっこり"  ],
  ["daytime,broad daylight","日中","にっちゅう"  ],
  ["Japan","日本","にっぽん・にほん"  ],
  ["entry to school or university,matriculation","入学","にゅうがく"  ],
  ["entrance,admission,entering","入場","にゅうじょう"  ],
  ["popularity","人気","にんき"  ],
  ["human being,man,person","人間","にんげん"  ],
  ["to extract,to omit,to surpass,to draw out,to unplug","抜く","ぬく"  ],
  ["to come out,to fall out,to be omitted","抜ける","ぬける"  ],
  ["cloth","布","ぬの"  ],
  ["to get wet","濡れる","ぬれる"  ],
  ["root","根","ね"  ],
  ["value,price,cost,worth,merit","値","ね"  ],
  ["desire,wish,request","願い","ねがい"  ],
  ["to desire,to wish,to request","願う","ねがう"  ],
  ["(1) mouse,　rat,","鼠","ねずみ"  ],
  ["price,cost","値段","ねだん"  ],
  ["zeal,enthusiasm","熱心","ねっしん"  ],
  ["tropics","熱帯","ねったい"  ],
  ["to devote oneself, be devoted to, be crazy about","熱中する","ねっちゅうする"  ],
  ["year","年間","ねんかん"  ],
  ["months and years","年月","ねんげつ"  ],
  ["whole year,always,everyday","年中","ねんじゅう"  ],
  ["age,era,period,date","年代","ねんだい"  ],
  ["age,years","年齢","ねんれい"  ],
  ["field","野","の"  ],
  ["ability, talent, a Noh play","能","のう"  ],
  ["farmer,farm family","農家","のうか"  ],
  ["agriculture","農業","のうぎょう"  ],
  ["farmers,peasants","農民","のうみん"  ],
  ["ability,faculty","能力","のうりょく"  ],
  ["eaves","軒","のき"  ],
  ["to leave (behind, over),to bequeath,to save,to reserve","残す","のこす"  ],
  ["remnant,residue,remaining,left-over","残り","のこり"  ],
  ["to take on board,to give a ride","乗せる","のせる"  ],
  ["to remove,to exclude,to except","除く","のぞく"  ],
  ["wish,desire,(a) hope","望み","のぞみ"  ],
  ["to desire,to wish for,to see,to command (a view of)","望む","のぞむ"  ],
  ["afterwards,since then,in the future","後","のち"  ],
  ["throat","喉","のど"  ],
  ["to lengthen,to stretch,to reach out,to grow (beard)","伸ばす","のばす"  ],
  ["to stretch,to extend,to make progress,to grow (beard, body height)","伸びる","のびる"  ],
  ["to state,to express,to mention","述べる","のべる"  ],
  ["to arise,to ascend,to go up","昇る","のぼる"  ],
  ["carefree,at leisure","","のんびり"  ],
  ["place,field (physics)","場","ば"  ],
  ["Yes, Uh-huh, I see,","","はあ"  ],
  ["ash","灰","はい"  ],
  ["rainy season,rain during the rainy season","梅雨","ばいう"  ],
  ["delivery,distribution","配達","はいたつ"  ],
  ["actor,actress,player,performer","俳優","はいゆう"  ],
  ["grave,tomb","墓","はか"  ],
  ["fool,idiot,trivial matter,folly","馬鹿","ばか"  ],
  ["doctorate,PhD","博士","はかせ"  ],
  ["to measure,to weigh,to survey","計る","はかる"  ],
  ["to wear,to put on (lower body)","履く","はく"  ],
  ["to breathe out, to vomit","吐く","はく"  ],
  ["clapping hands,applause","拍手","はくしゅ"  ],
  ["enormous,vast","莫大","ばくだい"  ],
  ["explosion,detonation,eruption","爆発","ばくはつ"  ],
  ["museum","博物館","はくぶつかん"  ],
  ["violent,vehement,intense","激しい","はげしい"  ],
  ["scissors","","はさみ"  ],
  ["(personal) bankruptcy","破産","はさん"  ],
  ["end (e.g. of street),edge,tip,margin,point","端","はし"  ],
  ["origin,beginning","始まり","はじまり"  ],
  ["to unfasten,to remove","外す","はずす"  ],
  ["flag","旗","はた"  ],
  ["skin","肌","はだ"  ],
  ["naked,nude","裸","はだか"  ],
  ["field","畑","はたけ"  ],
  ["20 years old,","二十（歳）","はたち"  ],
  ["work,labor","働き","はたらき"  ],
  ["discovery,detection,finding","発見","はっけん"  ],
  ["issue (publications)","発行","はっこう"  ],
  ["departure of a vehicle","発車","はっしゃ"  ],
  ["to punish,to penalize","罰する","ばっする"  ],
  ["development,growth","発達","はったつ"  ],
  ["with a clash (thud),with a bang,plump,flop","","ばったり"  ],
  ["development,growth","発展","はってん"  ],
  ["announcement,publication","発表","はっぴょう"  ],
  ["invention","発明","はつめい"  ],
  ["to discuss,to talk together","話し合う","はなしあう"  ],
  ["to part,divide,separate","離す","はなす"  ],
  ["to separate,to set free","放す","はなす"  ],
  ["to be separated from,to leave,to go away,to be a long way off","離れる","はなれる"  ],
  ["counter for birds,counter for rabbits","羽","はね"  ],
  ["width,breadth","幅","はば"  ],
  ["mother","母親","ははおや"  ],
  ["to omit,to eliminate,to curtail,to economize","省く","はぶく"  ],
  ["scene,setting (e.g. of novel)","場面","ばめん"  ],
  ["abdomen,belly,stomach","腹","はら"  ],
  ["field,plain,prairie,tundra,moor,wilderness","原","はら"  ],
  ["needle,hand (e.g. clock)","針","はり"  ],
  ["to stick,to paste","張る","はる"  ],
  ["counter for a number","番","ばん"  ],
  ["extent,scope,sphere,range","範囲","はんい"  ],
  ["opposition,resistance","反抗","はんこう"  ],
  ["crime","犯罪","はんざい"  ],
  ["judgement,decision","判断","はんだん"  ],
  ["offender,criminal","犯人","はんにん"  ],
  ["sale,selling,marketing","販売","はんばい"  ],
  ["light","灯","ひ"  ],
  ["damage","被害","ひがい"  ],
  ["comparison","比較","ひかく"  ],
  ["to run somebody over (with vehicle),to knock someone down","轢く","ひく"  ],
  ["tragedy","悲劇","ひげき"  ],
  ["aviation","飛行","ひこう"  ],
  ["knee,lap","膝","ひざ"  ],
  ["emergency,extraordinary,unusual","非常","ひじょう"  ],
  ["beautiful person (woman)","美人","びじん"  ],
  ["forehead,brow","額","ひたい"  ],
  ["be surprised,be amazed,be frightened,astonishment","","びっくり"  ],
  ["date,dating","日付","ひづけ"  ],
  ["inevitable death,desperation,frantic,inevitable result","必死","ひっし"  ],
  ["exactly,neatly,sharp","","ぴったり"  ],
  ["(1) to pull,to draw,to stretch,to drag,(2) to pull the ball (baseball)","引っ張る","ひっぱる"  ],
  ["negation,denial,repudiation","否定","ひてい"  ],
  ["single word","一言","ひとこと"  ],
  ["crowd of people","人込み","ひとごみ"  ],
  ["equal","等しい","ひとしい"  ],
  ["alone,","独り","ひとり"  ],
  ["one by one,each,one at a time","一人一人","ひとりひとり"  ],
  ["criticism,judgement,comment","批判","ひはん"  ],
  ["criticism,review,commentary","批評","ひひょう"  ],
  ["secret,secrecy","秘密","ひみつ"  ],
  ["delicate,subtle","微妙","びみょう"  ],
  ["(1) string,cord,(2) pimp","紐","ひも"  ],
  ["table (e.g. Tab 1),chart,list","表","ひょう"  ],
  ["cost,expense","費用","ひよう"  ],
  ["second (60th min)","秒","びょう"  ],
  ["valuation,estimation,assessment,evaluation","評価","ひょうか"  ],
  ["expression,presentation,representation (math)","表現","ひょうげん"  ],
  ["facial expression","表情","ひょうじょう"  ],
  ["equality (a),impartiality,evenness","平等","びょうどう"  ],
  ["fame,reputation,popularity,arrant","評判","ひょうばん"  ],
  ["surface,outside,face,appearance","表面","ひょうめん"  ],
  ["to spread (out),to extend,to stretch,to reach to,to get around","広がる","ひろがる"  ],
  ["elegance, grace, dignity,","品","ひん"  ],
  ["bottle","瓶","びん"  ],
  ["way,means","便","びん"  ],
  ["un,non,negative prefix","不","ふ"  ],
  ["nothing,naught,nil,zero","無","ぶ"  ],
  ["dividing,part","分","ぶ"  ],
  ["anxiety,uneasiness,insecurity,suspense","不安","ふあん"  ],
  ["scenery","風景","ふうけい"  ],
  ["married couple,husband and wife","夫婦","ふうふ"  ],
  ["flute,pipe","笛","ふえ"  ],
  ["wrong,bad,improper,unjustifiable,inadvisable","不可","ふか"  ],
  ["weapon,arms,ordinance","武器","ぶき"  ],
  ["dress, clothes","服装","ふくそう"  ],
  ["to hold in the mouth,to bear in mind","含む","ふくむ"  ],
  ["bag,sack","袋","ふくろ"  ],
  ["unhappiness,sorrow,misfortune,disaster,accident,death","不幸","ふこう"  ],
  ["tune,tone,knot,knob,point","節","ふし"  ],
  ["safety,peace,quietness","無事","ぶじ"  ],
  ["mystery,curiosity","不思議","ふしぎ"  ],
  ["discomfort,disability,inconvenience,destitution","不自由","ふじゆう"  ],
  ["wife,Mrs,madam","夫人","ふじん"  ],
  ["woman,female","婦人","ふじん"  ],
  ["injustice,unfairness","不正","ふせい"  ],
  ["to defend (against),to protect,to prevent","防ぐ","ふせぐ"  ],
  ["insufficiency,shortage,deficiency,lack,dearth","不足","ふそく"  ],
  ["stage (theatre)","舞台","ぶたい"  ],
  ["twins,a twin","双子","ふたご"  ],
  ["again,once more,a second time","再び","ふたたび"  ],
  ["usually,habitually,ordinarily,always","普段","ふだん"  ],
  ["an edge, a brim, a rim,","縁","ふち"  ],
  ["to hit,to strike","打つ","ぶつ"  ],
  ["prices of commodities,prices (in general)","物価","ぶっか"  ],
  ["material,substance","物質","ぶっしつ"  ],
  ["physics","物理","ぶつり"  ],
  ["writing brush","筆","ふで"  ],
  ["suddenly,casually,accidentally,incidentally,unexpectedly,unintentionally","","ふと"  ],
  ["ship,boat,watercraft,shipping,vessel,steamship","船","ふね"  ],
  ["portion,section,part","部分","ぶぶん"  ],
  ["complaint,discontent,dissatisfaction","不平","ふへい"  ],
  ["dissatisfaction,displeasure,discontent,complaints,unhappiness","不満","ふまん"  ],
  ["disadvantage,handicap,unfavorable,drawback","不利","ふり"  ],
  ["(1) to wave,to shake,to swing,(2) to sprinkle,(3) to cast (actor),to allocate (work)","振る","ふる"  ],
  ["to shiver,to shake,to quake","震える","ふるえる"  ],
  ["to touch,to be touched,to touch on a subject,to feel,to violate (law, copyright, etc.),to perceive,t","触れる","ふれる"  ],
  ["bath","風呂","ふろ"  ],
  ["dividing,part,segment","分","ぶん"  ],
  ["sentence","文","ぶん"  ],
  ["atmosphere (e.g. musical),mood,ambience","雰囲気","ふんいき"  ],
  ["analysis","分析","ぶんせき"  ],
  ["civilization,culture","文明","ぶんめい"  ],
  ["field,sphere,realm,division,branch","分野","ぶんや"  ],
  ["wall,fence","塀","へい"  ],
  ["equilibrium,balance,average,mean","平均","へいきん"  ],
  ["peace,harmony","平和","へいわ"  ],
  ["(not) particularly,nothing","別に","べつに"  ],
  ["to abate,to decrease,to diminish,to shorten","減らす","へらす"  ],
  ["to decrease (in size or number),to diminish,to abate","減る","へる"  ],
  ["goblin,ghost,apparition,bugbear","変化","へんか"  ],
  ["study, work, to study, to sell (a thing) cheap","勉強/勉強する","べんきょう・する"  ],
  ["change,modification,alteration","変更","へんこう"  ],
  ["box lunch","弁当","べんとう"  ],
  ["side","方","ほう"  ],
  ["Act (law: the X Act)","法","ほう"  ],
  ["pole,rod,stick","棒","ぼう"  ],
  ["risk,venture,adventure","冒険","ぼうけん"  ],
  ["direction,course,way","方向","ほうこう"  ],
  ["report,information","報告","ほうこく"  ],
  ["gem,jewel","宝石","ほうせき"  ],
  ["broadcast,　broadcasting, to broadcast","放送/放送する","ほうそう・する"  ],
  ["abundance,wealth,plenty,bounty","豊富","ほうふ"  ],
  ["method,manner,way,means,technique","方法","ほうほう"  ],
  ["persons,this and that,here and there,everywhere","方々","ほうぼう"  ],
  ["call,visit","訪問","ほうもん"  ],
  ["to bark,to bay,to howl,to bellow,to roar,to cry","吠える","ほえる"  ],
  ["cheek (of face)","頬","ほお"  ],
  ["some, other place, the rest","他（外）","ほか"  ],
  ["pride","誇り","ほこり"  ],
  ["dust","埃","ほこり"  ],
  ["guarantee, security, assurance, pledge, warranty","保証","ほしょう"  ],
  ["preservation, conservation, storage, maintenance","保存","ほぞん"  ],
  ["degree,extent,bounds,limit","程","ほど"  ],
  ["footpath,walkway,sidewalk","歩道","ほどう"  ],
  ["Buddha,merciful person,Buddhist image,the dead","仏","ほとけ"  ],
  ["bone","骨","ほね"  ],
  ["flame","炎","ほのお"  ],
  ["cheek (of face)","頬","ほほ"  ],
  ["almost,roughly,approximately","","ほぼ"  ],
  ["to smile","微笑む","ほほえむ"  ],
  ["to praise,to admire,to speak well","褒める","ほめる"  ],
  ["moat","濠","ほり"  ],
  ["truth,reality","本当","ほんとう・ほんと"  ],
  ["the person himself","本人","ほんにん"  ],
  ["genuine article","本物","ほんもの"  ],
  ["absent-minded,block-head,dim,faint,vague","","ぼんやり"  ],
  ["space,room,time,pause","間","ま"  ],
  ["(female) you might say","","まあ"  ],
  ["mike","","マイク"  ],
  ["lost (stray) child","迷子","まいご"  ],
  ["to entrust to another,to leave to","任せる","まかせる"  ],
  ["curtain,bunting,act (in play)","幕","まく"  ],
  ["defeat,loss,losing (a game)","負け","まけ"  ],
  ["grandchild","孫","まご"  ],
  ["nonsense, that's impossible,","","まさか"  ],
  ["correctly, surely","","まさに"  ],
  ["diligent,serious,honest","真面目","まじめ"  ],
  ["to increase,to grow","増す","ます"  ],
  ["first (of all),to start with,about,almost,hardly (with neg. verb)","先ず","まず"  ],
  ["poor, needy","貧しい","まずしい"  ],
  ["increasingly,more and more","","ますます"  ],
  ["again,and","又","また"  ],
  ["yet,still,more,besides","未だ","まだ"  ],
  ["(1) town, city","街","まち"  ],
  ["mistake","間違い","まちがい"  ],
  ["(1) pine tree,(2) highest (of a three-tier ranking system)","松","まつ"  ],
  ["deep red,flushed (of face)","真っ赤","まっか"  ],
  ["straight (ahead),direct,upright","真っ直ぐ","まっすぐ"  ],
  ["really,truly,entirely,completely","全く","まったく"  ],
  ["festival,feast","祭","まつり"  ],
  ["to study (in depth),to learn,to take lessons in","学ぶ","まなぶ"  ],
  ["mimicry,imitation,behavior,pretense","真似","まね"  ],
  ["to invite","招く","まねく"  ],
  ["beans,peas","豆","まめ"  ],
  ["to protect,to obey,to guard,to abide (by the rules)","守る","まもる"  ],
  ["circle,full (month),perfection,purity,suffix for ship names","丸","まる"  ],
  ["round,circular,spherical","丸い","まるい"  ],
  ["quite,entirely,completely","","まるで"  ],
  ["to turn,to revolve","回す","まわす"  ],
  ["circumference,surroundings,circulation","回り","まわり"  ],
  ["by any chance","万一","まんいち"  ],
  ["satisfaction","満足","まんぞく"  ],
  ["body,main part,oneself,sword","身","み"  ],
  ["fruit,nut,seed,content,good result","実","み"  ],
  ["seeing one off,farewell,escort","見送り","みおくり"  ],
  ["friend,ally,supporter","味方","みかた"  ],
  ["splendid,magnificent,beautiful,admirable","見事","みごと"  ],
  ["to be full,to rise (tide),to mature,to expire","満ちる","みちる"  ],
  ["dense, thick","密な","みつな"  ],
  ["to recognize,to appreciate,to approve,to admit,to notice","認める","みとめる"  ],
  ["enquiry,expression of sympathy,expression of concern","見舞い","みまい"  ],
  ["present,souvenir","土産","みやげ"  ],
  ["capital","都","みやこ"  ],
  ["strange,unusual","妙","みょう"  ],
  ["day after tomorrow","明後日","みょうごにち"  ],
  ["future (life, tense)","未来","みらい"  ],
  ["charm,fascination,glamour","魅力","みりょく"  ],
  ["all,everyone,everybody","皆","みんな"  ],
  ["nothing,naught,nil,zero","無","む"  ],
  ["facing,opposite,across the street,other side","向かい","むかい"  ],
  ["meeting,person sent to pick up an arrival","迎え","むかえ"  ],
  ["to face","向く","むく"  ],
  ["to turn towards,to point","向ける","むける"  ],
  ["disregard,ignore","無視","むし"  ],
  ["cavity,tooth decay,decayed tooth,caries","虫歯","むしば"  ],
  ["rather,better,instead","寧ろ","むしろ"  ],
  ["to tie,to bind,to link","結ぶ","むすぶ"  ],
  ["futility,uselessness","無駄","むだ"  ],
  ["daze,(in a) trance,ecstasy,delirium,engrossment","夢中","むちゅう"  ],
  ["breast,chest","胸","むね"  ],
  ["free,no charge","無料","むりょう"  ],
  ["sprout","芽","め"  ],
  ["clear up,clarify,define","明確","めいかく"  ],
  ["to order,to command,to appoint","命じる","めいじる"  ],
  ["master,expert","名人","めいじん"  ],
  ["order,command,decree,directive,(software) instruction","命令","めいれい"  ],
  ["trouble,bother,annoyance","迷惑","めいわく"  ],
  ["(sl) meals,food","飯","めし"  ],
  ["rarely (with neg. verb),seldom","滅多に","めったに"  ],
  ["a mask, the face, the surface, an aspect, a side,","面","めん"  ],
  ["cotton,padding","綿","めん"  ],
  ["license,permit,licence,certificate","免許","めんきょ"  ],
  ["trouble,difficulty,care,attention","面倒","めんどう"  ],
  ["to apply for,to make an application","申し込む","もうしこむ"  ],
  ["apology,excuse","申し訳","もうしわけ"  ],
  ["blanket","毛布","もうふ"  ],
  ["to burn","燃える","もえる"  ],
  ["purpose,goal,aim,objective,intention","目的","もくてき"  ],
  ["mark,objective,target","目標","もくひょう"  ],
  ["Thursday","木曜/木曜日","もくよう/もくようび"  ],
  ["letter (of alphabet),character","文字","もじ"  ],
  ["if","","もしも"  ],
  ["to raise,to lift up,to flatter","持ち上げる","もちあげる"  ],
  ["to use,to make use of","用いる","もちいる"  ],
  ["of course,certainly,naturally","勿論","もちろん"  ],
  ["most,extremely","最も","もっとも"  ],
  ["quite right,plausible,natural,but then,although","尤も","もっとも"  ],
  ["(1) origin,original,(2) former","元","もと"  ],
  ["basis","基","もと"  ],
  ["to restore,to put back,to return","戻す","もどす"  ],
  ["to be grounded on,to be based on,to be due to,to originate from","基づく","もとづく"  ],
  ["to seek,to request,to demand,to want,to wish for,to search for,to pursue (pleasure),to hunt (a job),","求める","もとめる"  ],
  ["person","者","もの"  ],
  ["sounds","物音","ものおと"  ],
  ["tale,story,legend","物語","ものがたり"  ],
  ["things,everything","物事","ものごと"  ],
  ["pattern,figure,design","模様","もよう"  ],
  ["to receive","貰う","もらう"  ],
  ["phrase,complaint","文句","もんく"  ],
  ["letter (of alphabet),character","文字","もんじ"  ],
  ["before long,soon,at length","","やがて"  ],
  ["use,service,role,position","役","やく"  ],
  ["approximately,about,some","約","やく"  ],
  ["translation, a version","訳","やく"  ],
  ["part,assigning (allotment of) parts,role,duties","役割","やくわり"  ],
  ["rent","家賃","やちん"  ],
  ["trouble,burden,care,bother","厄介","やっかい"  ],
  ["inn,lodging","宿","やど"  ],
  ["to employ,to hire","雇う","やとう"  ],
  ["roof","屋根","やね"  ],
  ["also,as I thought,still,in spite of,absolutely,of course","","やはり"  ],
  ["to tear,to violate,to defeat,to smash,to destroy","破る","やぶる"  ],
  ["to retire","辞める","やめる"  ],
  ["a little,partially,somewhat,a short time,a while","","やや"  ],
  ["only,sole,unique","唯一","ゆいいつ"  ],
  ["to say","言う","ゆう"  ],
  ["courage,bravery,valour,nerve,boldness","勇気","ゆうき"  ],
  ["validity,availability,effectiveness","有効","ゆうこう"  ],
  ["superiority,excellence","優秀","ゆうしゅう"  ],
  ["overall victory,championship","優勝","ゆうしょう"  ],
  ["friendship,fellowship","友情","ゆうじょう"  ],
  ["friend","友人","ゆうじん"  ],
  ["able,capable,efficient,skill","有能","ゆうのう"  ],
  ["mail,postal service","郵便","ゆうびん"  ],
  ["evening","夕べ","ゆうべ"  ],
  ["advantageous,better,profitable,lucrative","有利","ゆうり"  ],
  ["floor","床","ゆか"  ],
  ["pleasant,happy","愉快","ゆかい"  ],
  ["export, to export","輸出","ゆしゅつ・する"  ],
  ["to turn over,to assign,to hand over","譲る","ゆずる"  ],
  ["abundant,wealthy,plentiful,rich","豊か","ゆたか"  ],
  ["slowly,at ease","","ゆっくり/と"  ],
  ["importation,import,introduction, to import","輸入","ゆにゅう・する"  ],
  ["to permit, to allow, to approve, to forgive","許す","ゆるす"  ],
  ["evening,night","夜","よ"  ],
  ["dawn,daybreak","夜明け","よあけ"  ],
  ["good,nice,pleasant,ok","","よい"  ],
  ["way,manner,kind","様","よう"  ],
  ["to get drunk,to become intoxicated","酔う","よう"  ],
  ["easy,simple,plain","容易","ようい"  ],
  ["cheerful, lively, merry","陽気な","ようき"  ],
  ["request,demand,requisition","要求","ようきゅう"  ],
  ["care,precaution,guarding,caution","用心","ようじん"  ],
  ["aspect,state,appearance","様子","ようす"  ],
  ["in a word,after all,the point is ..,in short ..","要するに","ようするに"  ],
  ["element","要素","ようそ"  ],
  ["gist,main point","要点","ようてん"  ],
  ["day of the week","曜日","ようび"  ],
  ["expectation,assume will happen,forecast","予期","よき"  ],
  ["to cross (e.g. arms),to traverse","横切る","よこぎる"  ],
  ["estimate,budget","予算","よさん"  ],
  ["to cease,to abolish,to resign,to give up","止す","よす"  ],
  ["prediction,estimation","予測","よそく"  ],
  ["midnight,dead of night","夜中","よなか"  ],
  ["society,the world,the times","世の中","よのなか"  ],
  ["extra,excess,surplus","余分","よぶん"  ],
  ["forecast,prediction","予報","よほう"  ],
  ["prevention,precaution,protection against","予防","よぼう"  ],
  ["reading","読み","よみ"  ],
  ["bride,daughter-in-law","嫁","よめ"  ],
  ["surplus,composure,margin,room,time,allowance,scope,rope","余裕","よゆう"  ],
  ["according to","","よると"  ],
  ["(a) joy,(a) delight,rapture,pleasure,gratification,rejoicing,congratulations,felicitations","喜び","よろこび"  ],
  ["(hon) good,OK,all right,fine,very well,will do,may,can","宜しい","よろしい"  ],
  ["well,properly,suitably,best regards,please remember me","","よろしく"  ],
  ["four","四","よん"  ],
  [",for (10 days),next (year)","来","らい"  ],
  ["comfort,ease","楽","らく"  ],
  ["profits,gains,(political, economic) interest","利益","りえき"  ],
  ["understanding,comprehension","理解","りかい"  ],
  ["(the) land","陸","りく"  ],
  ["clever,shrewd,bright,sharp,wise,intelligent","利口","りこう"  ],
  ["divorce","離婚","りこん"  ],
  ["ideal","理想","りそう"  ],
  ["rate,ratio,proportion,percentage","率","りつ"  ],
  ["splendid,fine,handsome,elegant,imposing,prominent,legal,legitimate","立派","りっぱ"  ],
  ["studying abroad","留学","りゅうがく"  ],
  ["fashionable,fad,in vogue,prevailing","流行","りゅうこう"  ],
  ["quantity,amount,volume,portion (of food)","量","りょう"  ],
  ["change,money exchange","両替","りょうがえ"  ],
  ["fee,charge,fare","料金","りょうきん"  ],
  ["instance,example,case","例","れい"  ],
  ["expression of gratitude","礼","れい"  ],
  ["manners,courtesy,etiquette","礼儀","れいぎ"  ],
  ["calm,composure,coolness,serenity","冷静","れいせい"  ],
  ["queue,line,row","列","れつ"  ],
  ["train (ordinary)","列車","れっしゃ"  ],
  ["practice, to practice","練習","れんしゅう・する"  ],
  ["association (of ideas),suggestion","連想","れんそう"  ],
  ["serial,consecutive,continuity,continuing","連続","れんぞく"  ],
  ["the aged,old person","老人","ろうじん"  ],
  ["manual labor,toil,work","労働","ろうどう"  ],
  ["to argue,to discuss,to debate","論じる","ろんじる"  ],
  ["controversy,dispute","論争","ろんそう"  ],
  ["thesis,essay,treatise,paper","論文","ろんぶん"  ],
  ["ring,hoop,circle","輪","わ"  ],
  ["selfishness, wilfulness, whim","","わがまま"  ],
  ["parting,separation,farewell","別れ","わかれ"  ],
  ["side","脇","わき"  ],
  ["to divide,to separate","分ける","わける"  ],
  ["on purpose","","わざと"  ],
  ["only,merely,a little,small quantity","僅か","わずか"  ],
  ["cotton,padding","綿","わた"  ],
  ["topic,subject","話題","わだい"  ],
  ["laugh,laughter,smile","笑い","わらい"  ],
  ["to divide,to cut,to break,to halve","割る","わる"  ],
  ["abuse,insult,slander,evil speaking","悪口","わるくち"  ],
  ["we","我々","われわれ"  ],
  ["bay,gulf,inlet","湾","わん"  ],
  ["ice cream","","アイスクリーム"  ],
  ["(electric) iron","","アイロン"  ],
  ["out","","アウト"  ],
  ["album","","アルバム"  ],
  ["ink","","インク"  ],
  ["whisky","","ウイスキー"  ],
  ["(n) energy (de: Energie)","","エネルギー"  ],
  ["engine","","エンジン"  ],
  ["(1) overcoat,(2) over","","オーバー"  ],
  ["office","","オフィス"  ],
  ["car","","カー"  ],
  ["card,curd","","カード"  ],
  ["captain","","キャプテン"  ],
  ["camp","","キャンプ"  ],
  ["(abbr) kilo-, kilogram, kilometre,","","キロ"  ],
  ["classic(s)","","クラシック"  ],
  ["(1) glass,(2) grass","","グラス"  ],
  ["gland,grand,(electrical) ground","","グランド"  ],
  ["cream","","クリーム"  ],
  ["Christmas","","クリスマス"  ],
  ["group","","グループ"  ],
  ["case","","ケース"  ],
  ["game","","ゲーム"  ],
  ["coach","","コーチ"  ],
  ["code,cord,chord","","コード"  ],
  ["goal","","ゴール"  ],
  ["(1) a (photo)copy,(2) blurb on a book jacket","","コピー"  ],
  ["computer","","コンピューター"  ],
  ["(1) service,support system,(2) goods or services without charge","","サービス"  ],
  ["(1) autograph,(2) sign,(3) sine","","サイン"  ],
  ["jeans","","ジーンズ"  ],
  ["jet aeroplane","ジェット機","ジェットき"  ],
  ["juice,soft drink,deuce","","ジュース"  ],
  ["switch","","スイッチ"  ],
  ["(Western) soup","","スープ"  ],
  ["skiing","","スキー"  ],
  ["skate(s),skating","","スケート"  ],
  ["star","","スター"  ],
  ["style","","スタイル"  ],
  ["stand","","スタンド"  ],
  ["speech","","スピーチ"  ],
  ["set","","セット"  ],
  ["a center","","センター"  ],
  ["sofa,couch","","ソファー"  ],
  ["typewriter","","タイプライター"  ],
  ["(1) diagram,(2) (railway) schedule,(3) diamond","","ダイヤ"  ],
  ["towel","","タオル"  ],
  ["dance","","ダンス"  ],
  ["cheese","","チーズ"  ],
  ["team","","チーム"  ],
  ["chance,opportunity","","チャンス"  ],
  ["date,go on a date","","デート"  ],
  ["(abbr) demo,demonstration","","デモ"  ],
  ["tent","","テント"  ],
  ["top","","トップ"  ],
  ["drive,trip by car,driving","","ドライブ"  ],
  ["(1) truck,(2) (running) track","","トラック"  ],
  ["drama","","ドラマ"  ],
  ["playing cards (lit: trump)","","トランプ"  ],
  ["dress","","ドレス"  ],
  ["ton","","トン"  ],
  ["tunnel","","トンネル"  ],
  ["no","","ノー"  ],
  ["(1) knock,(2) fungo (baseball)","","ノック"  ],
  ["percent","","パーセント"  ],
  ["violin","","バイオリン"  ],
  ["hiking","","ハイキング"  ],
  ["(1) pipe,tube,(2) channels, official or otherwise","","パイプ"  ],
  ["pilot","","パイロット"  ],
  ["path,pass (in games)","","パス"  ],
  ["passport","","パスポート"  ],
  ["bag,","","バッグ"  ],
  ["bun,van (caravan),VAN (value-added network)","","バン"  ],
  ["handsome","","ハンサム"  ],
  ["beer","","ビール"  ],
  ["picnic","","ピクニック"  ],
  ["video","","ビデオ"  ],
  ["pin","","ピン"  ],
  ["plus","","プラス"  ],
  ["plan","","プラン"  ],
  ["a brake","","ブレーキ"  ],
  ["professional","","プロ"  ],
  ["Belt for western clothes","","ベルト"  ],
  ["(n) paint (nl: pek)","","ペンキ"  ],
  ["bench","","ベンチ"  ],
  ["boy","","ボーイ"  ],
  ["rowing boat","","ボート"  ],
  ["(1) platform,(2) home","","ホーム"  ],
  ["ball,bowl","","ボール"  ],
  ["market","","マーケット"  ],
  ["mike","","マイク"  ],
  ["proprietor,manager,barowner,master (e.g. arts, science)","","マスター"  ],
  ["Mama","","ママ"  ],
  ["miss (mistake, error, failure),Miss","","ミス"  ],
  ["milk","","ミルク"  ],
  ["memorandum","","メモ"  ],
  ["member","","メンバー"  ],
  ["humor","","ユーモア"  ],
  ["Europe","","ヨーロッパ"  ],
  ["yacht","","ヨット"  ],
  ["lighter,rider,writer","","ライター"  ],
  ["racket, paddle,","","ラケット"  ],
  ["report,paper","","レポート"  ],
  ["locket,rocket","","ロケット"  ],
  ["wine","","ワイン"  ]
];

module.exports = jlpten3;