var jlpten4 = [
  ["like that","","ああ"  ],
  ["a space","間","あいだ"  ],
  ["to match","合う","あう"  ],
  ["baby","","あかちゃん"  ],
  ["to rise","上る","あがる"  ],
  ["baby","赤ん坊","あかんぼう"  ],
  ["to open, to become empty","空く","あく"  ],
  ["to give","","あげる"  ],
  ["shallow, superficial","浅い","あさい"  ],
  ["flavour","味","あじ"  ],
  ["tomorrow","明日","あす・あした"  ],
  ["play","遊び","あそび"  ],
  ["to gather","集る","あつまる"  ],
  ["to collect something","集める","あつめる"  ],
  ["to apologize","謝る","あやまる"  ],
  ["relief","安心","あんしん"  ],
  ["safety","安全","あんぜん"  ],
  ["such","","あんな"  ],
  ["less than","以下","いか"  ],
  ["with the exception of","以外","いがい"  ],
  ["medical science","医学","いがく"  ],
  ["to live","生きる","いきる"  ],
  ["opinion","意見","いけん"  ],
  ["stone","石","いし"  ],
  ["to tease","","いじめる"  ],
  ["more than, this is all","以上","いじょう"  ],
  ["to hurry","急ぐ","いそぐ"  ],
  ["(humble) to do","致す","いたす"  ],
  ["once","一度","いちど"  ],
  ["with utmost effort","一生懸命","いっしょうけんめい"  ],
  ["full","","いっぱい"  ],
  ["thread","糸","いと"  ],
  ["within","以内","いない"  ],
  ["countryside","田舎","いなか"  ],
  ["to pray","祈る","いのる"  ],
  ["(respectful) to be, to come or to go","","いらっしゃる"  ],
  ["to plant, to grow","植える","うえる"  ],
  ["receipt","受付","うけつけ"  ],
  ["to take a lesson or test","受ける","うける"  ],
  ["to move","動く","うごく"  ],
  ["within","","うち"  ],
  ["to hit","打つ","うつ"  ],
  ["beautiful","美しい","うつくしい"  ],
  ["to copy or photograph","写す","うつす"  ],
  ["to move house or transfer","移る","うつる"  ],
  ["arm","腕","うで"  ],
  ["reverse side","裏","うら"  ],
  ["place where things are sold","売り場","うりば"  ],
  ["(informal) yes","","うん"  ],
  ["driver","運転手","うんてんしゅ"  ],
  ["branch, twig","枝","えだ"  ],
  ["to choose","選ぶ","えらぶ"  ],
  ["to be reserved, to be restrained","遠慮","えんりょ・する"  ],
  ["(respectful) to be","","おいでになる"  ],
  ["congratulation","お祝い","おいわい"  ],
  ["owing to, thanks to","","おかげ"  ],
  ["strange or funny","","おかしい"  ],
  ["one hundred million","億","おく"  ],
  ["rooftop","屋上","おくじょう"  ],
  ["gift","贈り物","おくりもの"  ],
  ["to send","送る","おくる"  ],
  ["to be late","遅れる","おくれる"  ],
  ["to wake","起す","おこす"  ],
  ["to do","行う","おこなう"  ],
  ["to get angry, to be angry","怒る","おこる"  ],
  ["closet","押し入れ","おしいれ"  ],
  ["young lady","お嬢さん","おじょうさん"  ],
  ["(polite) your house","お宅","おたく"  ],
  ["to fall or drop","落る","おちる"  ],
  ["(respectful) to say","","おっしゃる"  ],
  ["husband","夫","おっと"  ],
  ["change from purchase, balance","","おつり"  ],
  ["sound, note","音","おと"  ],
  ["to drop","落す","おとす"  ],
  ["a dance","踊り","おどり"  ],
  ["to dance","踊る","おどる"  ],
  ["to be surprised","驚く","おどろく"  ],
  ["festival","お祭り","おまつり"  ],
  ["calling on someone who is ill, enquiry","お見舞い","おみまい"  ],
  ["souvenir","お土産","おみやげ"  ],
  ["to remember","思い出す","おもいだす"  ],
  ["to think, to feel","思う","おもう"  ],
  ["toy","","おもちゃ"  ],
  ["the front","表","おもて"  ],
  ["parents","親","おや"  ],
  ["way of swimming","泳ぎ方","およぎかた"  ],
  ["to get off, to descend","下りる","おりる"  ],
  ["to break or to fold","折る","おる"  ],
  ["expression of gratitude","お礼","おれい"  ],
  ["to break or be folded","折れる","おれる"  ],
  ["the end","終わり","おわり"  ],
  ["coast","海岸","かいがん"  ],
  ["meeting","会議","かいぎ"  ],
  ["meeting room","会議室","かいぎしつ"  ],
  ["assembly hall or meeting place","会場","かいじょう"  ],
  ["conversation","会話","かいわ"  ],
  ["return","帰り","かえり"  ],
  ["to change","変える","かえる"  ],
  ["science","科学","かがく"  ],
  ["mirror","鏡","かがみ"  ],
  ["to hang something","掛ける","かける"  ],
  ["to decorate","飾る","かざる"  ],
  ["fire","火事","かじ"  ],
  ["gas","","ガス"  ],
  ["hard","堅/硬/固い","かたい"  ],
  ["shape","形","かたち"  ],
  ["to tidy up","片付ける","かたづける"  ],
  ["section manager","課長","かちょう"  ],
  ["to win","勝つ","かつ"  ],
  ["housewife","家内","かない"  ],
  ["sad","悲しい","かなしい"  ],
  ["certainly,necessarily","必ず","かならず"  ],
  ["rich man","お・金持ち","かねもち/おかねもち"  ],
  ["she,girlfriend","彼女","かのじょ"  ],
  ["wall","壁","かべ"  ],
  ["hair","髪","かみ"  ],
  ["to bite,to chew","噛む","かむ"  ],
  ["to commute","通う","かよう"  ],
  ["he,boyfriend","彼","かれ"  ],
  ["to get dry","乾く","かわく"  ],
  ["substitute,alternate","代わり","かわり"  ],
  ["to change","変わる","かわる"  ],
  ["to consider","考える","かんがえる"  ],
  ["relationship","関係","かんけい"  ],
  ["nurse","看護師","かんごし"  ],
  ["simple","簡単","かんたん"  ],
  ["spirit,mood","気","き"  ],
  ["opportunity","機会","きかい"  ],
  ["danger","危険","きけん"  ],
  ["to be heard","聞こえる","きこえる"  ],
  ["steam train","汽車","きしゃ"  ],
  ["art,technology,skill","技術","ぎじゅつ"  ],
  ["season","季節","きせつ"  ],
  ["regulations","規則","きそく"  ],
  ["surely","","きっと"  ],
  ["silk","絹","きぬ"  ],
  ["strict","厳しい","きびしい"  ],
  ["mood","気分","きぶん"  ],
  ["to be decided","決る","きまる"  ],
  ["(informal) You","君","きみ"  ],
  ["to decide","決める","きめる"  ],
  ["feeling,mood","気持ち","きもち"  ],
  ["kimono","着物","きもの"  ],
  ["guest,customer","客","きゃく"  ],
  ["urgent, steep","急","きゅう"  ],
  ["speedy, express","急行","きゅうこう"  ],
  ["education","教育","きょういく"  ],
  ["church","教会","きょうかい"  ],
  ["competition","競争","きょうそう"  ],
  ["an interest","興味","きょうみ"  ],
  ["neighbourhood","近所","きんじょ"  ],
  ["condition,health","具合","ぐあい"  ],
  ["air,atmosphere","空気","くうき"  ],
  ["airport","空港","くうこう"  ],
  ["grass","草","くさ"  ],
  ["neck","首","くび"  ],
  ["cloud","雲","くも"  ],
  ["to compare","比べる","くらべる"  ],
  ["to give","","くれる"  ],
  ["to get dark,to come to an end","暮れる","くれる"  ],
  ["suffix for familiar young male","君","くん"  ],
  ["hair or fur","毛","け"  ],
  ["finance,economy","経済","けいざい"  ],
  ["police","警察","けいさつ"  ],
  ["scene,landscape","景色","けしき"  ],
  ["eraser","消しゴム","けしゴム"  ],
  ["lodging","下宿","げしゅく"  ],
  ["never","決して","けっして"  ],
  ["however","","けれど/けれども"  ],
  ["cause,source","原因","げんいん"  ],
  ["to quarrel","","けんか・する"  ],
  ["research","研究","けんきゅう"  ],
  ["study room,laboratory","研究室","けんきゅうしつ"  ],
  ["sightseeing","見物","けんぶつ"  ],
  ["child","子","こ"  ],
  ["this way","","こう"  ],
  ["outskirts","郊外","こうがい"  ],
  ["lecture","講義","こうぎ"  ],
  ["the manufacturing industry","工業","こうぎょう"  ],
  ["high school","高校","こうこう"  ],
  ["high school student","高校生","こうこうせい"  ],
  ["factory,plant,mill,workshop","工場","こうじょう/こうば"  ],
  ["headmaster","校長","こうちょう"  ],
  ["traffic,transportation","交通","こうつう"  ],
  ["auditorium","講堂","こうどう"  ],
  ["high school","高等学校","こうとうがっこう"  ],
  ["civil servant, government worker","公務員","こうむいん"  ],
  ["international","国際","こくさい"  ],
  ["heart, mind, core","心","こころ"  ],
  ["(honorable) your husband","御主人","ごしゅじん"  ],
  ["to break-down","故障","こしょう・する"  ],
  ["(respect form ) to know","ご存じ","ごぞんじ"  ],
  ["response","答","こたえ"  ],
  ["a feast","","ごちそう"  ],
  ["small bird","小鳥","ことり"  ],
  ["the other day,recently","","このあいだ"  ],
  ["these days,nowadays","","このごろ"  ],
  ["small, fine","細かい","こまかい"  ],
  ["to include","込む","こむ"  ],
  ["uncooked rice","米","こめ"  ],
  ["(respectful) to see","","ごらんになる"  ],
  ["after this","","これから"  ],
  ["frightening","怖い","こわい"  ],
  ["to break","壊す","こわす"  ],
  ["to be broken","壊れる","こわれる"  ],
  ["now,next time","今度","こんど"  ],
  ["tonight","今夜","こんや"  ],
  ["latest,nowadays","最近","さいきん"  ],
  ["last,end","最後","さいご"  ],
  ["beginning,first","最初","さいしょ"  ],
  ["slope,hill","坂","さか"  ],
  ["to look for","探す","さがす"  ],
  ["to get down,to descend","下る","さがる"  ],
  ["popularity,prosperous","盛ん","さかん"  ],
  ["to hang,to lower,to move back","下げる","さげる"  ],
  ["(polite) to give","差し上げる","さしあげる"  ],
  ["some time ago","","さっき"  ],
  ["lonely","寂しい","さびしい"  ],
  ["the month after next","さ来月","さらいげつ"  ],
  ["the week after next","さ来週","さらいしゅう"  ],
  ["to make noise,to be excited","騒ぐ","さわぐ"  ],
  ["to touch","触る","さわる"  ],
  ["industry","産業","さんぎょう"  ],
  ["disappointment","残念","ざんねん"  ],
  ["city","市","し"  ],
  ["character","字","じ"  ],
  ["match,game","試合","しあい"  ],
  ["method","仕方","しかた"  ],
  ["examination","試験","しけん"  ],
  ["accident","事故","じこ"  ],
  ["earthquake","地震","じしん"  ],
  ["era","時代","じだい"  ],
  ["underwear","下着","したぎ"  ],
  ["firmly,steadily","","しっかり"  ],
  ["failure,mistake","失敗","しっぱい"  ],
  ["dictionary","辞典","じてん"  ],
  ["goods","品物","しなもの"  ],
  ["little while","","しばらく"  ],
  ["island","島","しま"  ],
  ["citizen","市民","しみん"  ],
  ["office","事務所","じむしょ"  ],
  ["society,public","社会","しゃかい"  ],
  ["company president","社長","しゃちょう"  ],
  ["freedom","自由","じゆう"  ],
  ["custom,manners","習慣","しゅうかん"  ],
  ["an address,a residence","住所","じゅうしょ"  ],
  ["judo","柔道","じゅうどう"  ],
  ["enough","十分","じゅうぶん"  ],
  ["hobby","趣味","しゅみ"  ],
  ["introduction","紹介","しょうかい"  ],
  ["elementary school","小学校","しょうがっこう"  ],
  ["novel","小説","しょうせつ"  ],
  ["future,prospects","将来","しょうらい"  ],
  ["groceries","食料品","しょくりょうひん"  ],
  ["woman","女性","じょせい"  ],
  ["to notify","知らせる","しらせる"  ],
  ["to investigate","調べる","しらべる"  ],
  ["population","人口","じんこう"  ],
  ["Shinto shrine","神社","じんじゃ"  ],
  ["kindness","親切","しんせつ"  ],
  ["newspaper company","新聞社","しんぶんしゃ"  ],
  ["swimming","水泳","すいえい"  ],
  ["water supply","水道","すいどう"  ],
  ["mathematics,arithmetic","数学","すうがく"  ],
  ["to exceed","過ぎる","すぎる"  ],
  ["terrific","凄い","すごい"  ],
  ["to make progress","進む","すすむ"  ],
  ["completely","","すっかり"  ],
  ["straight,all of a sudden","","すっと"  ],
  ["to throw away","捨てる","すてる"  ],
  ["sand","砂","すな"  ],
  ["to slide,to slip","滑る","すべる"  ],
  ["corner,nook","隅","すみ"  ],
  ["to finish","済む","すむ"  ],
  ["pickpocket","","すり"  ],
  ["then","","すると"  ],
  ["to live","生活","せいかつ・する"  ],
  ["to produce","生産","せいさん・する"  ],
  ["politics,government","政治","せいじ"  ],
  ["western countries","西洋","せいよう"  ],
  ["the world","世界","せかい"  ],
  ["seat","席","せき"  ],
  ["explanation","説明","せつめい"  ],
  ["back of the body","背中","せなか"  ],
  ["line","線","せん"  ],
  ["war","戦争","せんそう"  ],
  ["senior","先輩","せんぱい"  ],
  ["really","","そう"  ],
  ["to rear,to bring up","育てる","そだてる"  ],
  ["graduation","卒業","そつぎょう"  ],
  ["grandfather","祖父","そふ"  ],
  ["grandmother","祖母","そぼ"  ],
  ["because of that","","それで"  ],
  ["moreover","","それに"  ],
  ["to that extent","","それほど"  ],
  ["gradually,soon","","そろそろ"  ],
  ["that sort of","","そんな"  ],
  ["so much,like that","","そんなに"  ],
  ["to leave hospital","退院","たいいん・する"  ],
  ["university student","大学生","だいがくせい"  ],
  ["important,valuable,serious matter","大事","だいじ"  ],
  ["generally","大体","だいたい"  ],
  ["usually","","たいてい"  ],
  ["greatly","大分","だいぶ"  ],
  ["typhoon","台風","たいふう"  ],
  ["to break down","倒れる","たおれる"  ],
  ["so,therefore","","だから"  ],
  ["definite","確か","たしか"  ],
  ["to add a number","足す","たす"  ],
  ["to visit","訪ねる","たずねる"  ],
  ["to ask","尋ねる","たずねる"  ],
  ["correct","正しい","ただしい"  ],
  ["Japanese straw mat","畳","たたみ"  ],
  ["to stand something up","立てる","たてる"  ],
  ["to build","建てる","たてる"  ],
  ["for example","例えば","たとえば"  ],
  ["shelves","棚","たな"  ],
  ["joy","楽しみ","たのしみ"  ],
  ["to enjoy oneself","楽む","たのしむ"  ],
  ["occasionally","","たまに"  ],
  ["in order to","為","ため"  ],
  ["to be enough","足りる","たりる"  ],
  ["male","男性","だんせい"  ],
  ["heating","暖房","だんぼう"  ],
  ["blood","血","ち"  ],
  ["to check","","チェック・する"  ],
  ["strength,power","力","ちから"  ],
  ["not at all (used with a negative verb)","","ちっとも"  ],
  ["suffix for familiar person","","ちゃん"  ],
  ["caution","注意","ちゅうい"  ],
  ["junior high school,middle school","中学校","ちゅうがっこう"  ],
  ["injection","注射","ちゅうしゃ"  ],
  ["parking lot","駐車場","ちゅうしゃじょう"  ],
  ["geography","地理","ちり"  ],
  ["to seize","捕まえる","つかまえる"  ],
  ["to be attached","付く","つく"  ],
  ["to soak,to pickle","漬ける","つける"  ],
  ["circumstances,convenience","都合","つごう"  ],
  ["to report","伝える","つたえる"  ],
  ["to be continued","続く","つづく"  ],
  ["to continue","続ける","つづける"  ],
  ["to wrap","包む","つつむ"  ],
  ["my wife","妻","つま"  ],
  ["intention","","つもり"  ],
  ["to fish","釣る","つる"  ],
  ["polite","丁寧","ていねい"  ],
  ["suitability","適当","てきとう"  ],
  ["to assist","手伝う","てつだう"  ],
  ["glove","手袋","てぶくろ"  ],
  ["temple","寺","てら"  ],
  ["point,dot","点","てん"  ],
  ["shop assistant","店員","てんいん"  ],
  ["weather forecast","天気予報","てんきよほう"  ],
  ["electric light","電灯","でんとう"  ],
  ["telegram","電報","でんぽう"  ],
  ["exhibition","展覧会","てんらんかい"  ],
  ["metropolitan","都","と"  ],
  ["tool,means","道具","どうぐ"  ],
  ["finally, after all","","とうとう"  ],
  ["zoo","動物園","どうぶつえん"  ],
  ["distant","遠く","とおく"  ],
  ["to go through","通る","とおる"  ],
  ["particularly,especially","特に","とくに"  ],
  ["special","特別","とくべつ"  ],
  ["barber","","とこや"  ],
  ["on the way","途中","とちゅう"  ],
  ["limited express train (faster than an express train)","特急","とっきゅう"  ],
  ["to send, to deliver, to report","届ける","とどける"  ],
  ["to lodge at","泊まる","とまる"  ],
  ["to stop something","止める","とめる"  ],
  ["to exchange","取り替える","とりかえる"  ],
  ["thief","泥棒","どろぼう"  ],
  ["more and more","","どんどん"  ],
  ["to fix,to repair","直す","なおす"  ],
  ["to be fixed,to be repaired","直る","なおる"  ],
  ["to be cured,to heal","治る","なおる"  ],
  ["to weep","泣く","なく"  ],
  ["to disappear,to get lost","無くなる","なくなる"  ],
  ["to die","亡くなる","なくなる"  ],
  ["to throw or cast away","投げる","なげる"  ],
  ["(respectful) to do","","なさる"  ],
  ["to sound","鳴る","なる"  ],
  ["as much as possible","","なるべく"  ],
  ["now I understand","","なるほど"  ],
  ["to grow accustomed to","慣れる","なれる"  ],
  ["bitter","苦い","にがい"  ],
  ["two storied","二階建て","にかいだて"  ],
  ["to escape","逃げる","にげる"  ],
  ["journal","日記","にっき"  ],
  ["to hospitalise, hospitalisation","入院","にゅういん・する"  ],
  ["to enter school or university","入学","にゅうがく・する"  ],
  ["to be similar","似る","にる"  ],
  ["doll, figure","人形","にんぎょう"  ],
  ["to steal","盗む","ぬすむ"  ],
  ["to paint, to colour, to plaster","塗る","ぬる"  ],
  ["to get wet","","ぬれる"  ],
  ["price","","ねだん"  ],
  ["fever","熱","ねつ"  ],
  ["sleeping in late","寝坊","ねぼう"  ],
  ["sleepy","眠い","ねむい"  ],
  ["to sleep","眠る","ねむる"  ],
  ["to remain","残る","のこる"  ],
  ["to change between buses or trains","乗り換える","のりかえる"  ],
  ["vehicle","乗り物","のりもの"  ],
  ["leaf","葉","は"  ],
  ["situation","場合","ばあい"  ],
  ["double","倍","ばい"  ],
  ["(humble) to look at","拝見","はいけん・する"  ],
  ["dentist","歯医者","はいしゃ"  ],
  ["to transport","運ぶ","はこぶ"  ],
  ["to begin","始める","はじめる"  ],
  ["location","場所","ばしょ"  ],
  ["it should be so","","はず"  ],
  ["embarrassed","恥ずかしい","はずかしい"  ],
  ["pronunciation","発音","はつおん"  ],
  ["clearly","","はっきり"  ],
  ["cherry-blossom viewing","花見","はなみ"  ],
  ["woods,forester","林","はやし"  ],
  ["to pay","払う","はらう"  ],
  ["television or radio program","番組","ばんぐみ"  ],
  ["opposition","反対","はんたい"  ],
  ["day, sun","日","ひ"  ],
  ["fire","火","ひ"  ],
  ["to grow cold","冷える","ひえる"  ],
  ["light","光","ひかり"  ],
  ["to shine,to glitter","光る","ひかる"  ],
  ["drawer,drawing out","引き出し","ひきだし"  ],
  ["to withdraw","","ひきだす"  ],
  ["beard","","ひげ"  ],
  ["airport","飛行場","ひこうじょう"  ],
  ["after a long time","久しぶり","ひさしぶり"  ],
  ["art gallery","美術館","びじゅつかん"  ],
  ["extremely","非常に","ひじょうに"  ],
  ["to move house","引っ越す","ひっこす"  ],
  ["necessary","必要","ひつよう"  ],
  ["awful","","ひどい"  ],
  ["to open an event","開く","ひらく"  ],
  ["daytime,during the day","昼間","ひるま"  ],
  ["noon break","昼休み","ひるやすみ"  ],
  ["to pick up,to gather","拾う","ひろう"  ],
  ["to increase","増える","ふえる"  ],
  ["deep","深い","ふかい"  ],
  ["complexity,complication","複雑","ふくざつ"  ],
  ["revision","復習","ふくしゅう"  ],
  ["head of a section","部長","ぶちょう"  ],
  ["usually, or a train that stops at every station","普通","ふつう"  ],
  ["grapes","","ぶどう"  ],
  ["to become fat","太る","ふとる"  ],
  ["Japanese bedding, futon","布団","ふとん"  ],
  ["ship","舟","ふね"  ],
  ["inconvenience","不便","ふべん"  ],
  ["to step on","踏む","ふむ"  ],
  ["to start to rain","降り出す","ふりだす"  ],
  ["culture","文化","ぶんか"  ],
  ["literature","文学","ぶんがく"  ],
  ["grammar","文法","ぶんぽう"  ],
  ["different","別","べつ"  ],
  ["strange","変","へん"  ],
  ["reply","返事","へんじ"  ],
  ["trade","貿易","ぼうえき"  ],
  ["law","法律","ほうりつ"  ],
  ["I (used by males)","僕","ぼく"  ],
  ["star","星","ほし"  ],
  ["mostly","","ほとんど"  ],
  ["to praise","","ほめる"  ],
  ["translation","翻訳","ほんやく"  ],
  ["(humble) to go,to come","参る","まいる"  ],
  ["to lose","負ける","まける"  ],
  ["or,otherwise","","または"  ],
  ["to make a mistake","間違える","まちがえる"  ],
  ["to be in time for","間に合う","まにあう"  ],
  ["surroundings","周り","まわり"  ],
  ["to go around","回る","まわる"  ],
  ["comic","漫画","まんが"  ],
  ["middle","真中","まんなか"  ],
  ["to be in sight","見える","みえる"  ],
  ["lake","湖","みずうみ"  ],
  ["miso, soybean paste","味噌","みそ"  ],
  ["to be discovered","見つかる","みつかる"  ],
  ["to discover","見つける","みつける"  ],
  ["everybody","皆","みな"  ],
  ["harbour","港","みなと"  ],
  ["to face","向かう","むかう"  ],
  ["to go out to meet","迎える","むかえる"  ],
  ["old times, old days, long ago, formerly","昔","むかし"  ],
  ["insect","虫","むし"  ],
  ["(humble) son","息子","むすこ"  ],
  ["(humble) daughter","娘","むすめ"  ],
  ["impossible","無理","むり"  ],
  ["(polite) to eat","召し上がる","めしあがる"  ],
  ["rare","珍しい","めずらしい"  ],
  ["(humble) to say,to tell","申し上げる","もうしあげる"  ],
  ["(humble) to be called,to say","申す","もうす"  ],
  ["soon","","もうすぐ"  ],
  ["if","","もし"  ],
  ["to turn back","戻る","もどる"  ],
  ["cotton","木綿","もめん"  ],
  ["forest","森","もり"  ],
  ["to bake,to grill","焼く","やく"  ],
  ["promise","約束","やくそく"  ],
  ["to be helpful","役に立つ","やくにたつ"  ],
  ["to burn,to be roasted","焼ける","やける"  ],
  ["kind","優しい","やさしい"  ],
  ["to become thin","痩せる","やせる"  ],
  ["at last","","やっと"  ],
  ["to stop","止む","やむ"  ],
  ["to stop","止める","やめる"  ],
  ["soft","柔らかい","やわらかい"  ],
  ["hot water","湯","ゆ"  ],
  ["finger","指","ゆび"  ],
  ["a ring","指輪","ゆびわ"  ],
  ["dream","夢","ゆめ"  ],
  ["to shake,to sway","揺れる","ゆれる"  ],
  ["use","用","よう"  ],
  ["preparation","用意","ようい"  ],
  ["things to do","用事","ようじ"  ],
  ["to get dirty","汚れる","よごれる"  ],
  ["preparation for a lesson","予習","よしゅう"  ],
  ["arrangement","予定","よてい"  ],
  ["reservation","予約","よやく"  ],
  ["to visit","寄る","よる"  ],
  ["to be delighted","喜ぶ","よろこぶ"  ],
  ["reason","理由","りゆう"  ],
  ["utilization","利用","りよう"  ],
  ["both sides","両方","りょうほう"  ],
  ["Japanese hotel","旅館","りょかん"  ],
  ["absence","留守","るす"  ],
  ["air conditioning","冷房","れいぼう"  ],
  ["history","歴史","れきし"  ],
  ["contact","連絡","れんらく"  ],
  ["to boil,to heat","沸かす","わかす"  ],
  ["to separate","別れる","わかれる"  ],
  ["to boil, to grow hot,to get excited","沸く","わく"  ],
  ["meaning,reason","訳","わけ"  ],
  ["lost article","忘れ物","わすれもの"  ],
  ["to laugh,to smile","笑う","わらう"  ],
  ["rate,ratio,percentage","割合","わりあい"  ],
  ["to break","割れる","われる"  ],
  ["accessory","","アクセサリー"  ],
  ["Asia","","アジア"  ],
  ["announcer","","アナウンサー"  ],
  ["Africa","","アフリカ"  ],
  ["America","","アメリカ"  ],
  ["alcohol","","アルコール"  ],
  ["part-time job","","アルバイト"  ],
  ["escalator","","エスカレーター"  ],
  ["motorcycle","","オートバイ"  ],
  ["curtain","","カーテン"  ],
  ["gas","","ガス"  ],
  ["petrol","","ガソリン"  ],
  ["petrol station","","ガソリンスタンド"  ],
  ["a glass pane","","ガラス"  ],
  ["cake","","ケーキ"  ],
  ["eraser, rubber","消しゴム","けしゴム"  ],
  ["concert","","コンサート"  ],
  ["computer","","コンピューター"  ],
  ["salad","","サラダ"  ],
  ["sandal","","サンダル"  ],
  ["sandwich","","サンドイッチ"  ],
  ["jam","","ジャム"  ],
  ["suit","","スーツ"  ],
  ["suitcase","","スーツケース"  ],
  ["screen","","スクリーン"  ],
  ["steak","","ステーキ"  ],
  ["stereo","","ステレオ"  ],
  ["soft","","ソフト"  ],
  ["type,style","","タイプ"  ],
  ["to check","","チェック・する"  ],
  ["text,text book","","テキスト"  ],
  ["tennis","","テニス"  ],
  ["part time","","パート"  ],
  ["personal computer","","パソコン"  ],
  ["handbag　","","ハンドバッグ"  ],
  ["piano","","ピアノ"  ],
  ["building or bill","","ビル"  ],
  ["fax","","ファックス"  ],
  ["present","","プレゼント"  ],
  ["bell","","ベル"  ],
  ["register","","レジ"  ],
  ["report","","レポート/リポート"  ],
  ["word processor","","ワープロ"  ]
];

module.exports = jlpten4;