var jlpten5 = [
  ["blue","青","あお"  ],
  ["blue","青い","あおい"  ],
  ["red","赤","あか"  ],
  ["red","赤い","あかい"  ],
  ["bright","明い","あかるい"  ],
  ["autumn","秋","あき"  ],
  ["to open,to become open","開く","あく"  ],
  ["to open","開ける","あける"  ],
  ["to give","上げる","あげる"  ],
  ["morning","朝","あさ"  ],
  ["breakfast","朝御飯","あさごはん"  ],
  ["day after tomorrow","","あさって"  ],
  ["foot,leg","足","あし"  ],
  ["tomorrow","明日","あした"  ],
  ["over there","","あそこ"  ],
  ["to play,to make a visit","遊ぶ","あそぶ"  ],
  ["warm","暖かい","あたたかい"  ],
  ["head","頭","あたま"  ],
  ["new","新しい","あたらしい"  ],
  ["there","","あちら"  ],
  ["hot","暑い","あつい"  ],
  ["hot to the touch","熱い","あつい"  ],
  ["kind, deep, thick","厚い","あつい"  ],
  ["over there","","あっち"  ],
  ["afterwards","後","あと"  ],
  ["you","","あなた"  ],
  ["(humble) older brother","兄","あに"  ],
  ["(humble) older sister","姉","あね"  ],
  ["that over there","","あの"  ],
  ["um...","","あの"  ],
  ["apartment","","アパート"  ],
  ["to bathe,to shower","","あびる"  ],
  ["dangerous","危ない","あぶない"  ],
  ["sweet","甘い","あまい"  ],
  ["not very","","あまり"  ],
  ["rain","雨","あめ"  ],
  ["candy","飴","あめ"  ],
  ["to wash","洗う","あらう"  ],
  ["to be,to have (used for inanimate objects)","","ある"  ],
  ["to walk","歩く","あるく"  ],
  ["that","","あれ"  ],
  ["good","","いい/よい"  ],
  ["no","","いいえ"  ],
  ["to say","言う","いう"  ],
  ["house","家","いえ"  ],
  ["how","","いかが"  ],
  ["to go","行く","いく"  ],
  ["how many?,how old?","","いくつ"  ],
  ["how much?","","いくら"  ],
  ["pond","池","いけ"  ],
  ["medical doctor","医者","いしゃ"  ],
  ["chair","","いす"  ],
  ["busy,irritated","忙しい","いそがしい"  ],
  ["painful","痛い","いたい"  ],
  ["one","一","いち"  ],
  ["(1) one day, (2) first of month","一日","いちにち"  ],
  ["best,first","","いちばん"  ],
  ["when","","いつ"  ],
  ["five days, fifth day","五日","いつか"  ],
  ["together","一緒","いっしょ"  ],
  ["five","五つ","いつつ"  ],
  ["always","","いつも"  ],
  ["dog","犬","いぬ"  ],
  ["now","今","いま"  ],
  ["meaning","意味","いみ"  ],
  ["(humble) younger sister","妹","いもうと"  ],
  ["unpleasant","嫌","いや"  ],
  ["entrance","入口","いりぐち"  ],
  ["to be, to have (used for people and animals)","居る","いる"  ],
  ["to need","要る","いる"  ],
  ["to put in","入れる","いれる"  ],
  ["colour","色","いろ"  ],
  ["various","","いろいろ"  ],
  ["on top of","上","うえ"  ],
  ["behind","後ろ","うしろ"  ],
  ["thin,weak","薄い","うすい"  ],
  ["song","歌","うた"  ],
  ["to sing","歌う","うたう"  ],
  ["to be born","生まれる","うまれる"  ],
  ["sea","海","うみ"  ],
  ["to sell","売る","うる"  ],
  ["noisy,annoying","煩い","うるさい"  ],
  ["jacket","上着","うわぎ"  ],
  ["picture","絵","え"  ],
  ["movie","映画","えいが"  ],
  ["cinema","映画館","えいがかん"  ],
  ["English language","英語","えいご"  ],
  ["yes","","ええ"  ],
  ["station","駅","えき"  ],
  ["elevator","","エレベーター"  ],
  ["pencil","鉛筆","えんぴつ"  ],
  ["delicious","","おいしい"  ],
  ["many","多い","おおい"  ],
  ["big","大きい","おおきい"  ],
  ["big","大きな","おおきな"  ],
  ["great number of people","大勢","おおぜい"  ],
  ["(honorable) mother","お母さん","おかあさん"  ],
  ["sweets, candy","お菓子","おかし"  ],
  ["money","お金","おかね"  ],
  ["to get up","起きる","おきる"  ],
  ["to put","置く","おく"  ],
  ["(honorable) wife","奥さん","おくさん"  ],
  ["alcohol, rice wine","お酒","おさけ"  ],
  ["plate, dish","お皿","おさら"  ],
  ["grandfather,male senior citizen","伯父/叔父","おじいさん"  ],
  ["to teach,to tell","教える","おしえる"  ],
  ["uncle,middle aged gentleman","伯父/叔父","おじさん"  ],
  ["to push, to stamp something","押す","おす"  ],
  ["late,slow","遅い","おそい"  ],
  ["green tea","お茶","おちゃ"  ],
  ["bathroom","お手洗い","おてあらい"  ],
  ["(honorable) father","お父さん","おとうさん"  ],
  ["younger brother","弟","おとうと"  ],
  ["man","男","おとこ"  ],
  ["boy","男の子","おとこのこ"  ],
  ["day before yesterday","一昨日","おととい"  ],
  ["year before last","一昨年","おととし"  ],
  ["adult","大人","おとな"  ],
  ["stomach","","おなか"  ],
  ["same","同じ","おなじ"  ],
  ["(honorable) older brother","お兄さん","おにいさん"  ],
  ["(honorable) older sister","お姉さん","おねえさん"  ],
  ["grandmother,female senior-citizen","","おばあさん"  ],
  ["aunt","伯母さん/叔母さん","おばさん"  ],
  ["bath","お風呂","おふろ"  ],
  ["boxed lunch","お弁当","おべんとう"  ],
  ["to remember","覚える","おぼえる"  ],
  ["friendly term for policeman","","おまわりさん"  ],
  ["heavy","重い","おもい"  ],
  ["interesting","","おもしろい"  ],
  ["to swim","泳ぐ","およぐ"  ],
  ["to get off, to descend","降りる","おりる"  ],
  ["to finish","終る","おわる"  ],
  ["music","音楽","おんがく"  ],
  ["woman","女","おんな"  ],
  ["girl","女の子","おんなのこ"  ],
  ["foreign country","外国","がいこく"  ],
  ["foreigner","外国人","がいこくじん"  ],
  ["company","会社","かいしゃ"  ],
  ["stairs","階段","かいだん"  ],
  ["shopping","買い物","かいもの"  ],
  ["to buy","買う","かう"  ],
  ["to return something","返す","かえす"  ],
  ["to go back","帰る","かえる"  ],
  ["to take time or money","","かかる"  ],
  ["key","","かぎ"  ],
  ["to write","書く","かく"  ],
  ["student","学生","がくせい"  ],
  ["to call by phone","","かける"  ],
  ["umbrella","傘","かさ"  ],
  ["to lend","貸す","かす"  ],
  ["wind","風","かぜ"  ],
  ["a cold","風邪","かぜ"  ],
  ["family","家族","かぞく"  ],
  ["person, way of doing","方","かた"  ],
  ["school","学校","がっこう"  ],
  ["cup","","カップ"  ],
  ["household","家庭","かてい"  ],
  ["a corner","角","かど"  ],
  ["bag,basket","","かばん"  ],
  ["a vase","花瓶","かびん"  ],
  ["paper","紙","かみ"  ],
  ["camera","","カメラ"  ],
  ["Tuesday","火曜日","かようび"  ],
  ["spicy","辛い","からい"  ],
  ["body","体","からだ"  ],
  ["to borrow","借りる","かりる"  ],
  ["light","軽い","かるい"  ],
  ["curry","","カレー"  ],
  ["calendar","","カレンダー"  ],
  ["river","川/河","かわ"  ],
  ["cute","","かわいい"  ],
  ["Chinese character","漢字","かんじ"  ],
  ["tree,wood","木","き"  ],
  ["yellow","黄色","きいろ"  ],
  ["yellow","黄色い","きいろい"  ],
  ["to disappear","消える","きえる"  ],
  ["to hear,to listen to,to ask","聞く","きく"  ],
  ["north","北","きた"  ],
  ["guitar","","ギター"  ],
  ["dirty","汚い","きたない"  ],
  ["coffee lounge","喫茶店","きっさてん"  ],
  ["postage stamp","切手","きって"  ],
  ["ticket","切符","きっぷ"  ],
  ["yesterday","昨日","きのう"  ],
  ["nine","九","きゅう / く"  ],
  ["beef","牛肉","ぎゅうにく"  ],
  ["milk","牛乳","ぎゅうにゅう"  ],
  ["today","今日","きょう"  ],
  ["classroom","教室","きょうしつ"  ],
  ["(humble) siblings","兄弟","きょうだい"  ],
  ["last year","去年","きょねん"  ],
  ["hate","嫌い","きらい"  ],
  ["to cut","切る","きる"  ],
  ["to put on from the shoulders down","着る","きる"  ],
  ["pretty,clean","","きれい"  ],
  ["kilogram","","キロ/キログラム"  ],
  ["kilometre","","キロ/キロメートル"  ],
  ["bank","銀行","ぎんこう"  ],
  ["Friday","金曜日","きんようび"  ],
  ["medicine","薬","くすり"  ],
  ["please","","ください"  ],
  ["fruit","果物","くだもの"  ],
  ["mouth,opening","口","くち"  ],
  ["shoes","靴","くつ"  ],
  ["socks","靴下","くつした"  ],
  ["country","国","くに"  ],
  ["cloudy weather","曇り","くもり"  ],
  ["to become cloudy,to become dim","曇る","くもる"  ],
  ["gloomy","暗い","くらい"  ],
  ["class","","クラス"  ],
  ["gram","","グラム"  ],
  ["to come","来る","くる"  ],
  ["car,vehicle","車","くるま"  ],
  ["black","黒","くろ"  ],
  ["black","黒い","くろい"  ],
  ["policeman","警官","けいかん"  ],
  ["this morning","今朝","けさ"  ],
  ["to erase,to turn off power","消す","けす"  ],
  ["splendid,enough","結構","けっこう"  ],
  ["marriage","結婚","けっこん"  ],
  ["Monday","月曜日","げつようび"  ],
  ["entry hall","玄関","げんかん"  ],
  ["health, vitality","元気","げんき"  ],
  ["five","五","ご"  ],
  ["park","公園","こうえん"  ],
  ["intersection","交差点","こうさてん"  ],
  ["black tea","紅茶","こうちゃ"  ],
  ["police box","交番","こうばん"  ],
  ["voice","声","こえ"  ],
  ["coat,tennis court","","コート"  ],
  ["coffee","","コーヒー"  ],
  ["here","","ここ"  ],
  ["afternoon","午後","ごご"  ],
  ["nine days, ninth day","九日","ここのか"  ],
  ["nine","九つ","ここのつ"  ],
  ["morning","午前","ごぜん"  ],
  ["to answer","答える","こたえる"  ],
  ["this person or way","","こちら"  ],
  ["this person or way","","こっち"  ],
  ["a glass","","コップ"  ],
  ["this year","今年","ことし"  ],
  ["word,language","言葉","ことば"  ],
  ["child","子供","こども"  ],
  ["this","","この"  ],
  ["cooked rice,meal","御飯","ごはん"  ],
  ["to copy","","コピーする"  ],
  ["to be worried","困る","こまる"  ],
  ["this","","これ"  ],
  ["this month","今月","こんげつ"  ],
  ["this week","今週","こんしゅう"  ],
  ["such","","こんな"  ],
  ["this evening","今晩","こんばん"  ],
  ["well…","","さあ"  ],
  ["wallet","財布","さいふ"  ],
  ["fish","魚","さかな"  ],
  ["the future,previous","先","さき"  ],
  ["to bloom","咲く","さく"  ],
  ["composition,writing","作文","さくぶん"  ],
  ["to stretch out hands,to raise an umbrella","差す","さす"  ],
  ["magazine","雑誌","ざっし"  ],
  ["sugar","砂糖","さとう"  ],
  ["cold","寒い","さむい"  ],
  ["year after next","さ来年","さらいねん"  ],
  ["three","三","さん"  ],
  ["to stroll","散歩","さんぽする"  ],
  ["four","四","し / よん"  ],
  ["salt","塩","しお"  ],
  ["however","","しかし"  ],
  ["time","時間","じかん"  ],
  ["job","仕事","しごと"  ],
  ["dictionary","辞書","じしょ"  ],
  ["quiet","静か","しずか"  ],
  ["below","下","した"  ],
  ["seven","七","しち / なな"  ],
  ["question","質問","しつもん"  ],
  ["bicycle","自転車","じてんしゃ"  ],
  ["automobile","自動車","じどうしゃ"  ],
  ["to die","死ぬ","しぬ"  ],
  ["dictionary","字引","じびき"  ],
  ["oneself","自分","じぶん"  ],
  ["to close,to be closed","閉まる","しまる"  ],
  ["to close something","閉める","しめる"  ],
  ["to tie","締める","しめる"  ],
  ["well then…","","じゃ/じゃあ"  ],
  ["photograph","写真","しゃしん"  ],
  ["shirt","","シャツ"  ],
  ["shower","","シャワー"  ],
  ["ten","十","じゅう とお"  ],
  ["lesson,class work","授業","じゅぎょう"  ],
  ["homework","宿題","しゅくだい"  ],
  ["skillful","上手","じょうず"  ],
  ["strong,durable","丈夫","じょうぶ"  ],
  ["soy sauce","","しょうゆ"  ],
  ["dining hall","食堂","しょくどう"  ],
  ["to know","知る","しる"  ],
  ["white","白","しろ"  ],
  ["white","白い","しろい"  ],
  ["newspaper","新聞","しんぶん"  ],
  ["Wednesday","水曜日","すいようび"  ],
  ["to smoke,to suck","吸う","すう"  ],
  ["skirt","","スカート"  ],
  ["likeable","好き","すき"  ],
  ["a few","少ない","すくない"  ],
  ["instantly","","すぐに"  ],
  ["few","少し","すこし"  ],
  ["refreshing","涼しい","すずしい"  ],
  ["heater","","ストーブ"  ],
  ["spoon","","スプーン"  ],
  ["sport","","スポーツ"  ],
  ["trousers","","ズボン"  ],
  ["to live in","住む","すむ"  ],
  ["slippers","","スリッパ"  ],
  ["to do","","する"  ],
  ["to sit","座る","すわる"  ],
  ["height,stature","背","せ"  ],
  ["pupil","生徒","せいと"  ],
  ["sweater,jumper","","セーター"  ],
  ["soap","","せっけん"  ],
  ["business suit","背広","せびろ"  ],
  ["narrow","狭い","せまい"  ],
  ["zero","","ゼロ"  ],
  ["thousand","千","せん"  ],
  ["last month","先月","せんげつ"  ],
  ["last week","先週","せんしゅう"  ],
  ["teacher,doctor","先生","せんせい"  ],
  ["washing","洗濯","せんたく"  ],
  ["all","全部","ぜんぶ"  ],
  ["to clean, to sweep","掃除","そうじする"  ],
  ["and","","そうして/そして"  ],
  ["that place","","そこ"  ],
  ["over there","","そちら"  ],
  ["over there","","そっち"  ],
  ["outside","外","そと"  ],
  ["that","","その"  ],
  ["near,beside","","そば"  ],
  ["sky","空","そら"  ],
  ["that","","それ"  ],
  ["after that","","それから"  ],
  ["in that situation","","それでは"  ],
  ["university","大学","だいがく"  ],
  ["embassy","大使館","たいしかん"  ],
  ["all right","大丈夫","だいじょうぶ"  ],
  ["to be very likeable","大好き","だいすき"  ],
  ["important","大切","たいせつ"  ],
  ["kitchen","台所","だいどころ"  ],
  ["very","","たいへん"  ],
  ["difficult situation","","たいへん"  ],
  ["tall, expensive","高い","たかい"  ],
  ["many","","たくさん"  ],
  ["taxi","","タクシー"  ],
  ["to put out","出す","だす"  ],
  ["to stand","立つ","たつ"  ],
  ["length,height","","たて"  ],
  ["building","建物","たてもの"  ],
  ["enjoyable","楽しい","たのしい"  ],
  ["to ask","頼む","たのむ"  ],
  ["tobacco,cigarettes","","たばこ"  ],
  ["probably","","たぶん"  ],
  ["food","食べ物","たべもの"  ],
  ["to eat","食べる","たべる"  ],
  ["egg","卵","たまご"  ],
  ["who","誰","だれ"  ],
  ["somebody","誰","だれか"  ],
  ["birthday","誕生日","たんじょうび"  ],
  ["gradually","","だんだん"  ],
  ["little","小さい","ちいさい"  ],
  ["little","小さな","ちいさな"  ],
  ["near","近い","ちかい"  ],
  ["to differ","違う","ちがう"  ],
  ["near","近く","ちかく"  ],
  ["underground train","地下鉄","ちかてつ"  ],
  ["map","地図","ちず"  ],
  ["brown","茶色","ちゃいろ"  ],
  ["rice bowl","","ちゃわん"  ],
  ["exactly","","ちょうど"  ],
  ["somewhat","","ちょっと"  ],
  ["first of month","一日","ついたち"  ],
  ["to use","使う","つかう"  ],
  ["to get tired","疲れる","つかれる"  ],
  ["next","次","つぎ"  ],
  ["to arrive at","着く","つく"  ],
  ["desk","机","つくえ"  ],
  ["to make","作る","つくる"  ],
  ["to turn on","","つける"  ],
  ["to work for someone","勤める","つとめる"  ],
  ["boring","","つまらない"  ],
  ["cold to the touch","冷たい","つめたい"  ],
  ["powerful","強い","つよい"  ],
  ["hand","手","て"  ],
  ["tape","","テープ"  ],
  ["table","","テーブル"  ],
  ["tape recorder","","テープレコーダー"  ],
  ["to go out","出かける","でかける"  ],
  ["letter","手紙","てがみ"  ],
  ["to be able to","","できる"  ],
  ["exit","出口","でぐち"  ],
  ["test","","テスト"  ],
  ["with that...","","では"  ],
  ["department store","","デパート"  ],
  ["but","","でも"  ],
  ["to appear,to leave","出る","でる"  ],
  ["television","","テレビ"  ],
  ["weather","天気","てんき"  ],
  ["electricity,electric light","電気","でんき"  ],
  ["electric train","電車","でんしゃ"  ],
  ["telephone","電話","でんわ"  ],
  ["Japanese style door","戸","と"  ],
  ["Western style door","","ドア"  ],
  ["toilet","","トイレ"  ],
  ["how,in what way","","どう"  ],
  ["for what reason","","どうして"  ],
  ["please","","どうぞ"  ],
  ["animal","動物","どうぶつ"  ],
  ["thanks","","どうも"  ],
  ["far","遠い","とおい"  ],
  ["ten days,the tenth day","十日","とおか"  ],
  ["sometimes","時々","ときどき"  ],
  ["watch,clock","時計","とけい"  ],
  ["where","","どこ"  ],
  ["place","所","ところ"  ],
  ["year","年","とし"  ],
  ["library","図書館","としょかん"  ],
  ["which of two","","どちら"  ],
  ["which","","どっち"  ],
  ["very","","とても"  ],
  ["who","","どなた"  ],
  ["next door to","隣","となり"  ],
  ["which","","どの"  ],
  ["to fly,to hop","飛ぶ","とぶ"  ],
  ["to come to a halt","止まる","とまる"  ],
  ["friend","友達","ともだち"  ],
  ["Saturday","土曜日","どようび"  ],
  ["bird","鳥","とり"  ],
  ["chicken meat","とり肉","とりにく"  ],
  ["to take something","取る","とる"  ],
  ["to take a photo or record a film","撮る","とる"  ],
  ["which (of three or more)","","どれ"  ],
  ["knife","","ナイフ"  ],
  ["middle","中","なか"  ],
  ["long","長い","ながい"  ],
  ["animal noise. to chirp, roar or croak etc.","鳴く","なく"  ],
  ["to lose something","無くす","なくす"  ],
  ["why","","なぜ"  ],
  ["summer","夏","なつ"  ],
  ["summer holiday","夏休み","なつやすみ"  ],
  ["et cetera","","など"  ],
  ["seven","七つ","ななつ"  ],
  ["seven days,the seventh day","七日","なのか"  ],
  ["name","名前","なまえ"  ],
  ["to learn","習う","ならう"  ],
  ["to line up,to stand in a line","並ぶ","ならぶ"  ],
  ["to line up,to set up","並べる","ならべる"  ],
  ["to become","","なる"  ],
  ["what","何","なん/なに"  ],
  ["two","二","に"  ],
  ["bustling,busy","賑やか","にぎやか"  ],
  ["meat","肉","にく"  ],
  ["west","西","にし"  ],
  ["Sunday","日曜日","にちようび"  ],
  ["luggage","荷物","にもつ"  ],
  ["news","","ニュース"  ],
  ["garden","庭","にわ"  ],
  ["to take off clothes","脱ぐ","ぬぐ"  ],
  ["luke warm","温い","ぬるい"  ],
  ["tie,necktie","","ネクタイ"  ],
  ["cat","猫","ねこ"  ],
  ["to go to bed,to sleep","寝る","ねる"  ],
  ["notebook,exercise book","","ノート"  ],
  ["to climb","登る","のぼる"  ],
  ["a drink","飲み物","のみもの"  ],
  ["to drink","飲む","のむ"  ],
  ["to get on,to ride","乗る","のる"  ],
  ["tooth","歯","は"  ],
  ["party","","パーティー"  ],
  ["yes","","はい"  ],
  ["ashtray","灰皿","はいざら"  ],
  ["to enter,to contain","入る","はいる"  ],
  ["postcard","葉書","はがき"  ],
  ["to wear,to put on trousers","","はく"  ],
  ["box","箱","はこ"  ],
  ["bridge","橋","はし"  ],
  ["chopsticks","","はし"  ],
  ["to begin","始まる","はじまる"  ],
  ["beginning","初め/始め","はじめ"  ],
  ["for the first time","初めて","はじめて"  ],
  ["to run","走る","はしる"  ],
  ["bus","","バス"  ],
  ["butter","","バター"  ],
  ["20 years old,20th year","二十歳","はたち"  ],
  ["to work","働く","はたらく"  ],
  ["eight","八","はち"  ],
  ["twenty days,twentieth","二十日","はつか"  ],
  ["flower","花","はな"  ],
  ["nose","鼻","はな"  ],
  ["talk,story","話","はなし"  ],
  ["to speak","話す","はなす"  ],
  ["early","早い","はやい"  ],
  ["quick","速い","はやい"  ],
  ["spring","春","はる"  ],
  ["to stick","貼る","はる"  ],
  ["clear weather","晴れ","はれ"  ],
  ["to be sunny","晴れる","はれる"  ],
  ["half","半","はん"  ],
  ["evening","晩","ばん"  ],
  ["bread","","パン"  ],
  ["handkerchief","","ハンカチ"  ],
  ["number","番号","ばんごう"  ],
  ["evening meal","晩御飯","ばんごはん"  ],
  ["half minute","半分","はんぶん"  ],
  ["east","東","ひがし"  ],
  ["to pull","引く","ひく"  ],
  ["to play an instrument with strings, including piano","弾く","ひく"  ],
  ["short,low","低い","ひくい"  ],
  ["aeroplane","飛行機","ひこうき"  ],
  ["left hand side","左","ひだり"  ],
  ["person","人","ひと"  ],
  ["one","一つ","ひとつ"  ],
  ["one month","一月","ひとつき"  ],
  ["one person","一人","ひとり"  ],
  ["free time","暇","ひま"  ],
  ["hundred","百","ひゃく"  ],
  ["hospital","病院","びょういん"  ],
  ["illness","病気","びょうき"  ],
  ["noon, daytime","昼","ひる"  ],
  ["midday meal","昼御飯","ひるごはん"  ],
  ["spacious,wide","広い","ひろい"  ],
  ["roll of film","","フィルム"  ],
  ["envelope","封筒","ふうとう"  ],
  ["swimming pool","","プール"  ],
  ["fork","","フォーク"  ],
  ["to blow","吹く","ふく"  ],
  ["clothes","服","ふく"  ],
  ["two","二つ","ふたつ"  ],
  ["pork","豚肉","ぶたにく"  ],
  ["two people","二人","ふたり"  ],
  ["two days, second day of the month","二日","ふつか"  ],
  ["fat","太い","ふとい"  ],
  ["winter","冬","ふゆ"  ],
  ["to fall, e.g. rain or snow","降る","ふる"  ],
  ["old (not used for people)","古い","ふるい"  ],
  ["bath","","ふろ"  ],
  ["sentence,text","文章","ぶんしょう"  ],
  ["page","","ページ"  ],
  ["unskillful","下手","へた"  ],
  ["bed","","ベッド"  ],
  ["pet","","ペット"  ],
  ["room","部屋","へや"  ],
  ["area","辺","へん"  ],
  ["pen","","ペン"  ],
  ["to study","勉強","べんきょうする"  ],
  ["useful, convenient","便利","べんり"  ],
  ["hat","帽子","ぼうし"  ],
  ["ball-point pen","","ボールペン"  ],
  ["other, the rest","","ほか"  ],
  ["pocket","","ポケット"  ],
  ["want","欲しい","ほしい"  ],
  ["post","","ポスト"  ],
  ["thin","細い","ほそい"  ],
  ["button","","ボタン"  ],
  ["hotel","","ホテル"  ],
  ["book","本","ほん"  ],
  ["bookshelves","本棚","ほんだな"  ],
  ["truth","","ほんとう"  ],
  ["every morning","毎朝","まいあさ"  ],
  ["every month","毎月","まいげつ/まいつき"  ],
  ["every week","毎週","まいしゅう"  ],
  ["every day","毎日","まいにち"  ],
  ["every year","毎年","まいねん/まいとし"  ],
  ["every night","毎晩","まいばん"  ],
  ["before","前","まえ"  ],
  ["to turn,to bend","曲る","まがる"  ],
  ["unpleasant","","まずい"  ],
  ["again,and","","また"  ],
  ["yet,still","","まだ"  ],
  ["town,city","町","まち"  ],
  ["to wait","待つ","まつ"  ],
  ["straight ahead,direct","","まっすぐ"  ],
  ["match","","マッチ"  ],
  ["window","窓","まど"  ],
  ["round,circular","丸い/円い","まるい"  ],
  ["ten thousand","万","まん"  ],
  ["fountain pen","万年筆","まんねんひつ"  ],
  ["to brush teeth, to polish","磨く","みがく"  ],
  ["right side","右","みぎ"  ],
  ["short","短い","みじかい"  ],
  ["water","水","みず"  ],
  ["shop","店","みせ"  ],
  ["to show","見せる","みせる"  ],
  ["street","道","みち"  ],
  ["three days, third day of the month","三日","みっか"  ],
  ["three","三つ","みっつ"  ],
  ["green","緑","みどり"  ],
  ["everyone","皆さん","みなさん"  ],
  ["south","南","みなみ"  ],
  ["ear","耳","みみ"  ],
  ["to see, to watch","見る 観る","みる"  ],
  ["everyone","","みんな"  ],
  ["six days, sixth day of the month","六日","むいか"  ],
  ["over there","向こう","むこう"  ],
  ["difficult","難しい","むずかしい"  ],
  ["six","六つ","むっつ"  ],
  ["village","村","むら"  ],
  ["eye","目","め"  ],
  ["metre","","メートル"  ],
  ["glasses","眼鏡","めがね"  ],
  ["already","","もう"  ],
  ["again","もう一度","もういちど"  ],
  ["Thursday","木曜日","もくようび"  ],
  ["to hold","持つ","もつ"  ],
  ["more","","もっと"  ],
  ["thing","物","もの"  ],
  ["gate","門","もん"  ],
  ["problem","問題","もんだい"  ],
  ["greengrocer","八百屋","やおや"  ],
  ["vegetable","野菜","やさい"  ],
  ["easy, simple","易しい","やさしい"  ],
  ["cheap","安い","やすい"  ],
  ["rest,holiday","休み","やすみ"  ],
  ["to rest","休む","やすむ"  ],
  ["eight","八つ","やっつ"  ],
  ["mountain","山","やま"  ],
  ["to do","","やる"  ],
  ["evening","夕方","ゆうがた"  ],
  ["dinner","夕飯","ゆうはん"  ],
  ["post office","郵便局","ゆうびんきょく"  ],
  ["last night","昨夜","ゆうべ"  ],
  ["famous","有名","ゆうめい"  ],
  ["snow","雪","ゆき"  ],
  ["to go","行く","ゆく"  ],
  ["slowly","","ゆっくりと"  ],
  ["eight days, eighth day of the month","八日","ようか"  ],
  ["western-style clothes","洋服","ようふく"  ],
  ["often, well","","よく"  ],
  ["beside,side,width","横","よこ"  ],
  ["four days, fouth day of the month","四日","よっか"  ],
  ["four","四つ","よっつ"  ],
  ["to call out,to invite","呼ぶ","よぶ"  ],
  ["to read","読む","よむ"  ],
  ["evening,night","夜","よる"  ],
  ["weak","弱い","よわい"  ],
  ["next month","来月","らいげつ"  ],
  ["next week","来週","らいしゅう"  ],
  ["next year","来年","らいねん"  ],
  ["radio","","ラジオ"  ],
  ["radio cassette player","","ラジカセ / ラジオカセット"  ],
  ["splendid","","りっぱ"  ],
  ["overseas student","留学生","りゅうがくせい"  ],
  ["both parents","両親","りょうしん"  ],
  ["cuisine","料理","りょうり"  ],
  ["travel","旅行","りょこう"  ],
  ["zero","零","れい"  ],
  ["refrigerator","冷蔵庫","れいぞうこ"  ],
  ["record","","レコード"  ],
  ["restaurant","","レストラン"  ],
  ["to practice","練習","れんしゅうする"  ],
  ["corridor","廊下","ろうか"  ],
  ["six","六","ろく"  ],
  ["business shirt","","ワイシャツ"  ],
  ["young","若い","わかい"  ],
  ["to be understood","分かる","わかる"  ],
  ["to forget","忘れる","わすれる"  ],
  ["(humble) I,myself","私","わたくし"  ],
  ["I,myself","私","わたし"  ],
  ["to hand over","渡す","わたす"  ],
  ["to go across","渡る","わたる"  ],
  ["bad","悪い","わるい"  ],
  ["Used for comparison.","","より、ほう"  ]
];

module.exports = jlpten5;