var jlpten2 = [
  ["idea","","アイデア/アイディア"  ],
  ["vague,ambiguous","","あいまい"  ],
  ["to meet,to encounter (undesirable nuance)","遭う","あう"  ],
  ["to fan,to flap","扇ぐ","あおぐ"  ],
  ["pale,pallid","青白い","あおじろい"  ],
  ["baby","","あかんぼう"  ],
  ["room,time to spare,emptiness","明き","あき"  ],
  ["to be amazed,to be shocked","","あきれる"  ],
  ["accent","","アクセント"  ],
  ["yawn","","あくび"  ],
  ["to the end,to the last,stubbornly","飽くまで","あくまで"  ],
  ["dawn","明け方","あけがた"  ],
  ["to lift,to fry","揚げる","あげる"  ],
  ["to raise,to fly","挙げる","あげる"  ],
  ["to do for","","あげる (=やる)"  ],
  ["to long for,to yearn after,to admire","憧れる","あこがれる"  ],
  ["footprints","足跡","あしあと"  ],
  ["to taste,to savor,to relish","味わう","あじわう"  ],
  ["to keep in custody,to receive on deposit,to take charge of","預かる","あずかる"  ],
  ["to warm up,to get warm","暖まる","あたたまる"  ],
  ["to warm,to heat","暖める","あたためる"  ],
  ["usual,common,ordinary","","あたりまえ"  ],
  ["","あひら","あひら"  ],
  ["here and there","","あちらこちら"  ],
  ["impudent,shameless,brazen","厚かましい","あつかましい"  ],
  ["compression,condensation,pressure","圧縮","あっしゅく"  ],
  ["address,direction","宛名","あてな"  ],
  ["to be applicable,to come under (a category),to fulfill","","あてはまる"  ],
  ["to apply,to adapt","","あてはめる"  ],
  ["to act violently,to rage,to struggle,to be riotous","暴れる","あばれる"  ],
  ["fat,tallow,lard","脂","あぶら"  ],
  ["to scorch","","あぶる"  ],
  ["to flood,to overflow,to brim over","","あふれる"  ],
  ["sliding storm door","雨戸","あまど"  ],
  ["to pamper,to spoil","甘やかす","あまやかす"  ],
  ["to remain,to be left over,to be in excess,to be too many","余る","あまる"  ],
  ["knitting,web","編物","あみもの"  ],
  ["to knit","編む","あむ"  ],
  ["dangerous,critical,grave","危うい","あやうい"  ],
  ["suspicious,dubious,doubtful","怪しい","あやしい"  ],
  ["rough,rude,wild","荒い","あらい"  ],
  ["coarse,rough","粗い","あらい"  ],
  ["outline,summary","","あらすじ"  ],
  ["to dispute,to argue,to be at variance,to compete","争う","あらそう"  ],
  ["another time,again,over again,anew,formally","改めて","あらためて"  ],
  ["to change,to alter,to reform,to revise","改める","あらためる"  ],
  ["to write,to publish","著す","あらわす"  ],
  ["grateful,thankful,welcome,appreciated,evoking gratitude","有難い","ありがたい"  ],
  ["to live,to be","在る","ある"  ],
  ["one thing or another,this and that,this or that","","あれこれ"  ],
  ["busy,hurried,confused,flurried","","あわただしい"  ],
  ["to become confused","","あわてる"  ],
  ["easy-going","安易","あんい"  ],
  ["unexpectedly","案外","あんがい"  ],
  ["antenna","","アンテナ"  ],
  ["to start talking,to speak,to tell,to propose,to suggest,to break the ice","言い出す","いいだす"  ],
  ["to tell,to tell on (someone),to order","言い付ける","いいつける"  ],
  ["meaning,significance","意義","いぎ"  ],
  ["vividly,lively","生き生き","いきいき"  ],
  ["(uk) abruptly,suddenly,all of a sudden,without warning","","いきなり"  ],
  ["childcare,nursing,upbringing","育児","いくじ"  ],
  ["somewhat","幾分","いくぶん"  ],
  ["(1) flower arrangement","生け花","いけばな"  ],
  ["after this,from now on,hereafter,thereafter","以後","いご"  ],
  ["on and after,hereafter,thereafter","以降","いこう"  ],
  ["equal","","イコール"  ],
  ["brave,valiant,gallant,courageous","勇ましい","いさましい"  ],
  ["necessities of life (food, clothing, etc.)","衣食住","いしょくじゅう"  ],
  ["malicious,ill-tempered,unkind","意地悪","いじわる"  ],
  ["one by one,separately","","いちいち"  ],
  ["once,tentatively,in outline,for the time being","一応","いちおう"  ],
  ["greater,more,further,still more","一段と","いちだんと"  ],
  ["first class,top grade,foremost,top-notch","一流","いちりゅう"  ],
  ["be lost,peace,hide,mistake,beautiful,in turn","佚","いつ"  ],
  ["day before yesterday","一昨日","いっさくじつ"  ],
  ["year before last","一昨年","いっさくねん"  ],
  ["simultaneous,all at once","一斉","いっせい"  ],
  ["once,for a moment,one morning,temporarily","一旦","いったん"  ],
  ["fixed,settled,definite","一定","いってい"  ],
  ["","","いっていらっしゃい"  ],
  ["","","いってらっしゃい"  ],
  ["","","いってまいります"  ],
  ["before one knows,unnoticed,unawares","","いつのまにか"  ],
  ["moving,transfer,demise","移転","いてん"  ],
  ["water well","井戸","いど"  ],
  ["latitude (nav.)","緯度","いど"  ],
  ["cousin (female)","従姉妹","いとこ"  ],
  ["to be proud,to swagger","威張る","いばる"  ],
  ["to hate,to dislike","嫌がる","いやがる"  ],
  ["more and more,all the more,increasingly,at last,beyond doubt","","いよいよ"  ],
  ["to parch,to fry","煎る","いる"  ],
  ["","炒る","いる"  ],
  ["container,case,receptacle","入れ物","いれもの"  ],
  ["ink","","インキ"  ],
  ["interview","","インタビュー"  ],
  ["gravity","引力","いんりょく"  ],
  ["woman","","ウーマン"  ],
  ["wool","","ウール"  ],
  ["waitress","","ウエートレス"  ],
  ["garden shrubs,trees,potted plant","植木","うえき"  ],
  ["to starve","飢える","うえる"  ],
  ["to float,to rise to surface,to come to mind","浮ぶ","うかぶ"  ],
  ["to float,to express,to look (sad, glad)","浮かべる","うかべる"  ],
  ["to float,to become merry,to become loose","浮く","うく"  ],
  ["(hum) to hear,to be told,to know","承る","うけたまわる"  ],
  ["receipt","受取","うけとり"  ],
  ["to take (be in) charge of","受け持つ","うけもつ"  ],
  ["dim,gloomy","薄暗い","うすぐらい"  ],
  ["to dilute,to water down","薄める","うすめる"  ],
  ["business meeting,previous arrangement,appointment","打合せ","うちあわせ"  ],
  ["to deny,to negate,to contradict","打ち消す","うちけす"  ],
  ["to attack,to avenge","討つ","うつ"  ],
  ["carelessly,thoughtlessly,inadvertently","","うっかり"  ],
  ["to project,to reflect,to cast (shadow)","映す","うつす"  ],
  ["to be photographed,to be projected","写る","うつる"  ],
  ["to be reflected,to harmonize with,to come out (photo)","映る","うつる"  ],
  ["noodles (Japanese)","","うどん"  ],
  ["yes or no,existence,flag indicator (comp),presence or absence marker","有無","うむ"  ],
  ["to bury,to fill up,to fill (a seat, a vacant position)","埋める","うめる"  ],
  ["to show respect,to honour","敬う","うやまう"  ],
  ["to turn inside out,to turn (something) over","裏返す","うらがえす"  ],
  ["backdoor,rear entrance","裏口","うらぐち"  ],
  ["to forecast,to predict","占う","うらなう"  ],
  ["resentment","恨み","うらみ"  ],
  ["to curse,to feel bitter","恨む","うらむ"  ],
  ["envious,enviable","羨ましい","うらやましい"  ],
  ["to envy","羨む","うらやむ"  ],
  ["amount sold,proceeds","売上","うりあげ"  ],
  ["sold-out","売り切れ","うりきれ"  ],
  ["to be sold out","売り切れる","うりきれる"  ],
  ["sales","売行き","うれゆき"  ],
  ["loiteringly,aimless wandering","","うろうろ"  ],
  ["canal,waterway","運河","うんが"  ],
  ["a great deal,very much","","うんと"  ],
  ["sentence in English","英文","えいぶん"  ],
  ["English-Japanese (e.g. dictionary)","英和","えいわ"  ],
  ["let me see,well,er....","","ええと"  ],
  ["liquid,fluid","液体","えきたい"  ],
  ["etiquette","","エチケット"  ],
  ["colors,paints","絵の具","えのぐ"  ],
  ["apron","","エプロン"  ],
  ["great,celebrated,eminent,terrible,awful,famous,remarkable,excellent","偉い","えらい"  ],
  ["party,banquet","宴会","えんかい"  ],
  ["horticulture,gardening","園芸","えんげい"  ],
  ["play (theatrical)","演劇","えんげき"  ],
  ["circumference","円周","えんしゅう"  ],
  ["trip,hike,picnic","遠足","えんそく"  ],
  ["extension,elongation,prolongation,lengthening","延長","えんちょう"  ],
  ["chimney","煙突","えんとつ"  ],
  ["to chase or run after someone,to run down,to pursue","追い掛ける","おいかける"  ],
  ["to pass (e.g. car),to outdistance,to outstrip","追い越す","おいこす"  ],
  ["oil,engine oil,kerosene","","オイル"  ],
  ["aid,assistance,help,reinforcement","応援","おうえん"  ],
  ["princess","王女","おうじょ"  ],
  ["to answer,to respond,to meet,to satisfy,to accept","応ずる","おうずる"  ],
  ["reception","応接","おうせつ"  ],
  ["receiving,dealing with","応対","おうたい"  ],
  ["(col) round trip,coming and going,return ticket","往復","おうふく"  ],
  ["Europe and America,the West","欧米","おうべい"  ],
  ["application,put to practical use","応用","おうよう"  ],
  ["orchestra","","オーケストラ"  ],
  ["rough (not precise),broad,sketchy","","おおざっぱ"  ],
  ["main street","大通り","おおどおり"  ],
  ["automation","","オートメーション"  ],
  ["","","オーバーコート"  ],
  ["about,roughly,as a rule,approximately","大凡","おおよそ"  ],
  ["return,welcome","お帰り","おかえり"  ],
  ["","","おかけください"  ],
  ["Thanks to god,thanks to you","","おかげさまで"  ],
  ["side dish,accompaniment for rice dishes","","おかず"  ],
  ["to worship,to beg,to make a supplication","拝む","おがむ"  ],
  ["second helping,another cup","お代わり","おかわり"  ],
  ["to compensate for","補う","おぎなう"  ],
  ["","","おきのどくに"  ],
  ["outdoors","屋外","おくがい"  ],
  ["(hon) wife,your wife,madam","","おくさん"  ],
  ["part of word written in kana","送り仮名","おくりがな"  ],
  ["","","おげんきで"  ],
  ["to neglect,to be off guard,to be feeling better","怠る","おこたる"  ],
  ["to stop,to restrain,to seize,to repress,to suppress,to press down","押える","おさえる"  ],
  ["before,ahead,previously","","おさきに"  ],
  ["to obtain,to reap,to pay,to supply,to accept","納める","おさめる"  ],
  ["(1) to govern,to manage,(2) to subdue","治める","おさめる"  ],
  ["regrettable,disappointing,precious","惜しい","おしい"  ],
  ["bow","御辞儀","おじぎ"  ],
  ["middle-aged gentleman,uncle","伯父さん","おじさん"  ],
  ["middle-aged gentleman,uncle","小父さん","おじさん"  ],
  ["middle-aged gentleman,uncle","叔父さん","おじさん"  ],
  ["smartly dressed,someone smartly dressed,fashion-conscious","","おしゃれ"  ],
  ["Excuse me for disturbing you","","おじゃまします"  ],
  ["to be taught","教わる","おそわる"  ],
  ["Take care of yourself","","おだいじに"  ],
  ["to calm down,to settle down","落着く","おちつく"  ],
  ["font of purifying water placed at entrance of shrine","御手洗","おてあらい"  ],
  ["","お出掛け","おでかけ"  ],
  ["maid","お手伝いさん","おてつだいさん"  ],
  ["to threaten,to coerce","","おどかす"  ],
  ["lost property","落し物","おとしもの"  ],
  ["day before yesterday","","おととい"  ],
  ["year before last","","おととし"  ],
  ["obedient,docile,quiet","","おとなしい"  ],
  ["to surprise,to frighten,to create a stir","驚かす","おどろかす"  ],
  ["please","","おねがいします"  ],
  ["each,every,either,respectively,severally","各々","おのおの"  ],
  ["(hon) aunt","伯母さん","おばさん"  ],
  ["(1) aunt,(2) middle-aged lady","叔母さん","おばさん"  ],
  ["(abbr) Good morning","","おはよう"  ],
  ["worship,shrine visit","お参り","おまいり"  ],
  ["Sorry to have kept you waiting","","おまたせしました"  ],
  ["Please wait a moment","","おまちください"  ],
  ["Sorry to have kept you waiting","","おまちどおさま"  ],
  ["happy event,matter for congratulation,auspicious event,pregnancy","","おめでたい"  ],
  ["unexpected,casual","思い掛けない","おもいがけない"  ],
  ["to be under impression that,to be convinced that","思い込む","おもいこむ"  ],
  ["","思いっ切り","おもいっきり"  ],
  ["to think of,to hit upon","思い付く","おもいつく"  ],
  ["heavy,massive,serious","重たい","おもたい"  ],
  ["(1) holiday,absence,rest,(2) (exp) Good night","","おやすみ"  ],
  ["(1) between meal snack,afternoon refreshment","","おやつ"  ],
  ["thumb","親指","おやゆび"  ],
  ["organ","","オルガン"  ],
  ["to sell wholesale,grated (vegetables)","卸す","おろす"  ],
  ["grace,favor,blessing,benefit","恩恵","おんけい"  ],
  ["greenhouse","温室","おんしつ"  ],
  ["spa,hot spring,onsen","温泉","おんせん"  ],
  ["temperate zone","温帯","おんたい"  ],
  ["and Company,Messrs.","御中","おんちゅう"  ],
  ["woman","女の人","おんなのひと"  ],
  ["mosquito","蚊","か"  ],
  ["(1) curve,(2) curve ball (baseball)","","カーブ"  ],
  ["shell,shellfish","貝","かい"  ],
  ["opening of a meeting","開会","かいかい"  ],
  ["meeting hall,assembly hall","会館","かいかん"  ],
  ["examination of tickets","改札","かいさつ"  ],
  ["breakup,dissolution","解散","かいさん"  ],
  ["sea bathing,seawater bath","海水浴","かいすいよく"  ],
  ["number of times,frequency","回数","かいすう"  ],
  ["book of tickets","回数券","かいすうけん"  ],
  ["revision,amendment,alteration","改正","かいせい"  ],
  ["good weather","快晴","かいせい"  ],
  ["explanation,commentary","解説","かいせつ"  ],
  ["(1) remodeling,(2) modding (comp)","改造","かいぞう"  ],
  ["opening,open","開通","かいつう"  ],
  ["rotation,revolution,turning","回転","かいてん"  ],
  ["answer,solution","解答","かいとう"  ],
  ["reply,answer","回答","かいとう"  ],
  ["the outside,external","外部","がいぶ"  ],
  ["release,liberation,emancipation","解放","かいほう"  ],
  ["open,throw open,liberalization","開放","かいほう"  ],
  ["ocean","海洋","かいよう"  ],
  ["intro,outline,general remarks","概論","がいろん"  ],
  ["to send back","帰す","かえす"  ],
  ["on the contrary,rather,all the more,instead","却って","かえって"  ],
  ["to exchange,to interchange,to substitute,to replace","代える","かえる"  ],
  ["to warp,to be warped,to curve","反る","かえる"  ],
  ["house,building","家屋","かおく"  ],
  ["to concern oneself in,to have to do with,to affect,to influence,to stick to (opinions)","係わる","かかわる"  ],
  ["writing down,putting on record,recording,making a note of,registration (of mail)","書留","かきとめ"  ],
  ["dictation","書取","かきとり"  ],
  ["hedge","垣根","かきね"  ],
  ["to scratch,to perspire","掻く","かく"  ],
  ["to sniff,to smell","嗅ぐ","かぐ"  ],
  ["aerial,overhead,fiction,fanciful","架空","かくう"  ],
  ["individual,each","各自","かくじ"  ],
  ["expansion","拡充","かくじゅう"  ],
  ["science,learning,scholarship","学術","がくじゅつ"  ],
  ["every place,various places","各地","かくち"  ],
  ["expansion,extension,enlargement,escape (ESC)","拡張","かくちょう"  ],
  ["angle","角度","かくど"  ],
  ["year in school,grade in school","学年","がくねん"  ],
  ["department of a university,undergraduate","学部","がくぶ"  ],
  ["exceptional","格別","かくべつ"  ],
  ["probability","確率","かくりつ"  ],
  ["scholarship,knowledge,literary ability","学力","がくりょく"  ],
  ["multiplication","掛け算","かけざん"  ],
  ["approval,adoption (e.g. motion, bill),passage","可決","かけつ"  ],
  ["a burner,origin of a fire","火口","かこう"  ],
  ["downward,descent,fall,drop,subsidence","下降","かこう"  ],
  ["to be piled up,lie on top of one another,overlap each other","重なる","かさなる"  ],
  ["to pile up,to put something on another,to heap up,to add,to repeat","重ねる","かさねる"  ],
  ["decoration","飾り","かざり"  ],
  ["volcano","火山","かざん"  ],
  ["certainly!","","かしこまりました"  ],
  ["lending,loaning","貸し出し","かしだし"  ],
  ["error,blunder,accident","過失","かしつ"  ],
  ["fruit,nut,berry.","果実","かじつ"  ],
  ["room to let","貸間","かしま"  ],
  ["house for rent","貸家","かしや"  ],
  ["passage,place,point,part","個所","かしょ"  ],
  ["excess,over-","過剰","かじょう"  ],
  ["to chew,to bite (at),to gnaw,to nibble","","かじる"  ],
  ["taxation","課税","かぜい"  ],
  ["underline,underscore","下線","かせん"  ],
  ["cassette (tape)","","カセット"  ],
  ["acceleration","加速","かそく"  ],
  ["acceleration","加速度","かそくど"  ],
  ["stubborn,firm (not viscous or easily moved)","固い","かたい"  ],
  ["hard (esp. wood),steadfast,honorable,stuffy writing","堅い","かたい"  ],
  ["katakana","片仮名","かたかな"  ],
  ["to put in order,to dispose of,to solve","片付く","かたづく"  ],
  ["lump,mass,clod,cluster","塊","かたまり"  ],
  ["to harden,to solidify,to become firm,to become certain","固まる","かたまる"  ],
  ["one-way (trip)","片道","かたみち"  ],
  ["to incline toward,to slant,to lurch","傾く","かたむく"  ],
  ["to be one-sided,to incline,to be partial","片寄る","かたよる"  ],
  ["study subject,course of study","学科","がっか"  ],
  ["scientific society,academic meeting","学会","がっかい"  ],
  ["musical instrument","楽器","がっき"  ],
  ["grade in school","学級","がっきゅう"  ],
  ["to shoulder,to carry on shoulder","担ぐ","かつぐ"  ],
  ["parenthesis,brackets","括弧","かっこ"  ],
  ["printing type","活字","かつじ"  ],
  ["activity","活躍","かつやく"  ],
  ["vitality,energy","活力","かつりょく"  ],
  ["assumption,supposition,hypothesis","仮定","かてい"  ],
  ["process","過程","かてい"  ],
  ["course,curriculum","課程","かてい"  ],
  ["(n) alias,pseudonym,pen name","仮名","かな"  ],
  ["kana orthography,syllabary spelling","仮名遣い","かなづかい"  ],
  ["bell,chime","鐘","かね"  ],
  ["heating","加熱","かねつ"  ],
  ["to hold (position),to serve,to be unable","兼ねる","かねる"  ],
  ["cover (ex. book)","","カバー"  ],
  ["majority","過半数","かはんすう"  ],
  ["to cover (with something)","被せる","かぶせる"  ],
  ["iron pot,kettle","釜","かま"  ],
  ["wastepaper","紙屑","かみくず"  ],
  ["god","神様","かみさま"  ],
  ["razor","剃刀","かみそり"  ],
  ["chewing gum","","ガム"  ],
  ["cargo,freight","貨物","かもつ"  ],
  ["itchy,itching","","かゆい"  ],
  ["song,ballad","歌謡","かよう"  ],
  ["shell,husk,hull,chaff","殻","から"  ],
  ["collar,color,colour","","カラー"  ],
  ["to ridicule,to tease,to banter with,to make fun of","","からかう"  ],
  ["empty,vacant,hollow","空っぽ","からっぽ"  ],
  ["(n) playing cards (pt: carta)","","かるた"  ],
  ["to wither,to die (plant),to be blasted (plant)","枯れる","かれる"  ],
  ["calorie","","カロリー"  ],
  ["to love,to be affectionate","","かわいがる"  ],
  ["to dry (clothes, etc.),to desiccate","乾かす","かわかす"  ],
  ["to be thirsty","渇く","かわく"  ],
  ["money order,exchange","為替","かわせ"  ],
  ["roof tile","瓦","かわら"  ],
  ["(v5r,vi) to take the place of,to relieve,to be substituted for","代る","かわる"  ],
  ["space,interval,SPC","間隔","かんかく"  ],
  ["ventilation","換気","かんき"  ],
  ["deep emotion,impression,inspiration","感激","かんげき"  ],
  ["","関西","かんさい"  ],
  ["appreciation","鑑賞","かんしょう"  ],
  ["to feel,to sense","感ずる","かんずる"  ],
  ["indirection,indirectness","間接","かんせつ"  ],
  ["dry,arid,insipid,dehydrated","乾燥","かんそう"  ],
  ["impressions,thoughts","感想","かんそう"  ],
  ["observation","観測","かんそく"  ],
  ["frigid zone","寒帯","かんたい"  ],
  ["government office,authorities","官庁","かんちょう"  ],
  ["misunderstanding,wrong guess","勘違い","かんちがい"  ],
  ["packing (in cans),canning,canned goods,tin can","缶詰","かんづめ"  ],
  ["dry cell,battery","乾電池","かんでんち"  ],
  ["eastern half of Japan, including Tokyo","関東","かんとう"  ],
  ["(1) idea,notion,conception,(2) sense (e.g. of duty)","観念","かんねん"  ],
  ["toast (drink)","乾杯","かんぱい"  ],
  ["sign,signboard,doorplate,poster","看板","かんばん"  ],
  ["nursing (a patient)","看病","かんびょう"  ],
  ["crown,diadem,first,best","冠","かんむり"  ],
  ["Chinese Character-Japanese (e.g. dictionary)","漢和","かんわ"  ],
  ["atmospheric pressure","気圧","きあつ"  ],
  ["instrument","器械","きかい"  ],
  ["changing clothes,change of clothes","着替え","きがえ"  ],
  ["locomotive,engine","機関車","きかんしゃ"  ],
  ["famine","飢饉","ききん"  ],
  ["utensil","器具","きぐ"  ],
  ["term,period","期限","きげん"  ],
  ["symbol,code","記号","きごう"  ],
  ["to mince,to carve,to engrave","刻む","きざむ"  ],
  ["ceremony,rite,ritual,service","儀式","ぎしき"  ],
  ["standard,basis,criteria,norm","基準","きじゅん"  ],
  ["standard,basis,criteria,norm","規準","きじゅん"  ],
  ["rising,getting out of bed","起床","きしょう"  ],
  ["to put on clothes","着せる","きせる"  ],
  ["foundation,basis","基礎","きそ"  ],
  ["vapour,gas","気体","きたい"  ],
  ["base","基地","きち"  ],
  ["chance,start,cue,excuse","","きっかけ"  ],
  ["tightly,fully","","ぎっしり"  ],
  ["foundation,basis","基盤","きばん"  ],
  ["guest seating","客席","きゃくせき"  ],
  ["parlor,guest room","客間","きゃくま"  ],
  ["gang","","ギャング"  ],
  ["campus","","キャンパス"  ],
  ["closed (e.g. store),business suspended,shutdown,holiday","休業","きゅうぎょう"  ],
  ["lecture cancelled","休講","きゅうこう"  ],
  ["rest,relief,relaxation","休息","きゅうそく"  ],
  ["allowance,grant,supply","給与","きゅうよ"  ],
  ["rest,break,recreation","休養","きゅうよう"  ],
  ["clear,pure,noble","清い","きよい"  ],
  ["strengthen,intensify,reinforce,solidify","強化","きょうか"  ],
  ["boundary","境界","きょうかい"  ],
  ["event,function","行事","ぎょうじ"  ],
  ["shame,very kind of you,sorry to trouble","恐縮","きょうしゅく"  ],
  ["culture,education,refinement,cultivation","教養","きょうよう"  ],
  ["(1) line,procession,(2) matrix (math)","行列","ぎょうれつ"  ],
  ["fishing (industry)","漁業","ぎょぎょう"  ],
  ["curve","曲線","きょくせん"  ],
  ["order,rules,law","規律","きりつ"  ],
  ["(v5r) to behead,to murder","斬る","きる"  ],
  ["to be careful,to pay attention,to take care","気を付ける","きをつける"  ],
  ["goldfish","金魚","きんぎょ"  ],
  ["limits,boundary,domain,zone,sphere,territory","区域","くいき"  ],
  ["even number","偶数","ぐうすう"  ],
  ["daydream,fantasy,fancy,vision","空想","くうそう"  ],
  ["sky,air","空中","くうちゅう"  ],
  ["cooler,air conditioner","","クーラー"  ],
  ["nail","釘","くぎ"  ],
  ["to punctuate,to cut off,to mark off,to stop,to put an end to","区切る","くぎる"  ],
  ["comb","櫛","くし"  ],
  ["sneeze","","くしゃみ"  ],
  ["complaint,troubles,objection","苦情","くじょう"  ],
  ["pain,trouble","苦心","くしん"  ],
  ["waste,scrap","屑","くず"  ],
  ["to destroy,to pull down,to make change (money)","崩す","くずす"  ],
  ["ring finger","薬指","くすりゆび"  ],
  ["to collapse,to crumble","崩れる","くずれる"  ],
  ["to break,to smash","砕く","くだく"  ],
  ["to break,to be broken","砕ける","くだける"  ],
  ["to get tired,to wear out","","くたびれる"  ],
  ["good-for-nothing,stupid,trivial,worthless","","くだらない"  ],
  ["to get down,to descend","下る","くだる"  ],
  ["lips","唇","くちびる"  ],
  ["lipstick","口紅","くちべに"  ],
  ["to adhere to,to keep close to","","くっつく"  ],
  ["to attach","","くっつける"  ],
  ["verbose,importunate,heavy (taste)","","くどい"  ],
  ["punctuation marks","句読点","くとうてん"  ],
  ["to distribute,to deliver","配る","くばる"  ],
  ["labourer,worker","工夫","くふう"  ],
  ["division,section,classification","区分","くぶん"  ],
  ["combination","組合せ","くみあわせ"  ],
  ["to assemble,to set up,to construct","組み立てる","くみたてる"  ],
  ["(1) to draw (water),to dip,to scoop,to pump","汲む","くむ"  ],
  ["to serve sake","酌む","くむ"  ],
  ["regrettable,mortifying,vexing","悔しい","くやしい"  ],
  ["to mourn","悔やむ","くやむ"  ],
  ["cleaning,dry cleaning,laundry service","","クリーニング"  ],
  ["to be engulfed in,to be enveloped by,to wrap up","","くるむ"  ],
  ["repeatedly,sincerely,earnestly","","くれぐれも"  ],
  ["","咥える","くわえる"  ],
  ["country,district","郡","ぐん"  ],
  ["practice,training,study","稽古","けいこ"  ],
  ["honorific,term of respect","敬語","けいご"  ],
  ["fluorescent lamp,person who is slow to react","蛍光灯","けいこうとう"  ],
  ["form,formality,format,math expression","形式","けいしき"  ],
  ["continuation","継続","けいぞく"  ],
  ["knitting wool","毛糸","けいと"  ],
  ["longitude","経度","けいど"  ],
  ["system,family line,geological formation","系統","けいとう"  ],
  ["public entertainment,accomplishments,attainments","芸能","げいのう"  ],
  ["horse racing","競馬","けいば"  ],
  ["defense,guard,policing,security","警備","けいび"  ],
  ["true adjective","形容詞","けいようし"  ],
  ["adjectival noun,quasi-adjective","形容動詞","けいようどうし"  ],
  ["surgical department","外科","げか"  ],
  ["fur,skin,pelt","毛皮","けがわ"  ],
  ["sudden increase","激増","げきぞう"  ],
  ["alighting,getting off","下車","げしゃ"  ],
  ["month (last third of)","下旬","げじゅん"  ],
  ["drainage,sewage,ditch,gutter,sewerage","下水","げすい"  ],
  ["to cut down little by little,to take a percentage","削る","けずる"  ],
  ["column,beam,digit","桁","けた"  ],
  ["geta (Japanese footwear),wooden clogs","下駄","げた"  ],
  ["blood pressure","血圧","けつあつ"  ],
  ["blood","血液","けつえき"  ],
  ["monthly salary","月給","げっきゅう"  ],
  ["masterpiece,best work,boner,blunder","傑作","けっさく"  ],
  ["end of the month","月末","げつまつ"  ],
  ["indication,market trend,worry","気配","けはい"  ],
  ["vulgarity,meanness,indecency,coarseness","下品","げひん"  ],
  ["smoky","煙い","けむい"  ],
  ["to kick","蹴る","ける"  ],
  ["but,however","けれど/けれども",""  ],
  ["inaccessible place,sharp eyes","険しい","けわしい"  ],
  ["inspection,study by observation,field trip","見学","けんがく"  ],
  ["modesty,humility","謙虚","けんきょ"  ],
  ["manuscript,copy","原稿","げんこう"  ],
  ["place of origin,habitat","原産","げんさん"  ],
  ["origin,primeval","原始","げんし"  ],
  ["training","研修","けんしゅう"  ],
  ["strict,rigour,severe,firm","厳重","げんじゅう"  ],
  ["humble,humility,modesty","謙遜","けんそん"  ],
  ["prefectural office","県庁","けんちょう"  ],
  ["limit,bounds","限度","げんど"  ],
  ["actually,really","現に","げんに"  ],
  ["microscope","顕微鏡","けんびきょう"  ],
  ["principle,theory,fundamental truth","原理","げんり"  ],
  ["raw materials","原料","げんりょう"  ],
  ["Go (board game of capturing territory)","碁","ご"  ],
  ["(1) dear,beloved,darling,(2) yearned for","恋しい","こいしい"  ],
  ["to ask,to request","請う","こう"  ],
  ["factory worker","工員","こういん"  ],
  ["overbearing,coercive,pushy,forcible,high-handed","強引","ごういん"  ],
  ["public nuisance,pollution","公害","こうがい"  ],
  ["high class,high grade","高級","こうきゅう"  ],
  ["public,community,public service,society,communal","公共","こうきょう"  ],
  ["industrial arts","工芸","こうげい"  ],
  ["filial piety","孝行","こうこう"  ],
  ["cross","交差","こうさ"  ],
  ["lecturer","講師","こうし"  ],
  ["construction work","工事","こうじ"  ],
  ["formula,formality,official","公式","こうしき"  ],
  ["excuse","口実","こうじつ"  ],
  ["thus","こうして","こうして"  ],
  ["school building","校舎","こうしゃ"  ],
  ["the public","公衆","こうしゅう"  ],
  ["perfume","香水","こうすい"  ],
  ["justice,fairness,impartiality","公正","こうせい"  ],
  ["achievements,merit,meritorious service,meritorious deed","功績","こうせき"  ],
  ["beam,light ray","光線","こうせん"  ],
  ["upper","高層","こうそう"  ],
  ["structure,construction","構造","こうぞう"  ],
  ["alternation,change,relief,relay,shift","交替","こうたい"  ],
  ["arable land","耕地","こうち"  ],
  ["transportation facilities","交通機関","こうつうきかん"  ],
  ["campus","校庭","こうてい"  ],
  ["positive,affirmation","肯定","こうてい"  ],
  ["altitude,height,advanced","高度","こうど"  ],
  ["high class,high grade","高等","こうとう"  ],
  ["combination,incorporation,union,amalgamation","合同","ごうどう"  ],
  ["junior (at work or school)","後輩","こうはい"  ],
  ["official announcement,proclamation","公表","こうひょう"  ],
  ["mineral","鉱物","こうぶつ"  ],
  ["official business,public business","公務","こうむ"  ],
  ["item","項目","こうもく"  ],
  ["(1) (Japanese) maple","紅葉","こうよう"  ],
  ["rational","合理","ごうり"  ],
  ["alternating current,intercourse,(cultural) exchange,intermingling","交流","こうりゅう"  ],
  ["confluence,union,linking up,merge","合流","ごうりゅう"  ],
  ["effect,efficacy,validity,potency","効力","こうりょく"  ],
  ["to exceed,to cross over,to cross","超える","こえる"  ],
  ["course","","コース"  ],
  ["chorus","","コーラス"  ],
  ["to burn,to scorch,to singe,to char","焦がす","こがす"  ],
  ["king","国王","こくおう"  ],
  ["nationality","国籍","こくせき"  ],
  ["national","国立","こくりつ"  ],
  ["Thank you very much for your....","","ごくろうさま"  ],
  ["to burn,to be burned","焦げる","こげる"  ],
  ["to freeze,to be chilled,to be frozen","凍える","こごえる"  ],
  ["having some knowledge of,happening to know","心当たり","こころあたり"  ],
  ["to be informed,to have thorough knowledge","心得る","こころえる"  ],
  ["seat,bench","腰掛け","こしかけ"  ],
  ["to sit (down)","腰掛ける","こしかける"  ],
  ["the Japanese syllabary","五十音","ごじゅうおん"  ],
  ["pepper","胡椒","こしょう"  ],
  ["to make,to manufacture","","こしらえる"  ],
  ["to cross,to pass,to tide over","超す","こす"  ],
  ["to rub,to chafe,to file,to frost (glass),to strike (match)","擦る","こする"  ],
  ["","","ごぞんじですか"  ],
  ["an individual","個体","こたい"  ],
  ["feast,treating (someone)","御馳走","ごちそう"  ],
  ["feast","","ごちそうさま"  ],
  ["it is I who should say so","","こちらこそ"  ],
  ["personal expenses,pocket money,spending money,incidental expenses,allowance","小遣い","こづかい"  ],
  ["(1) cook (nl:),(2) tap,spigot,faucet,cock","","コック"  ],
  ["stealthily,secretly","","こっそり"  ],
  ["old book,classics,classic","古典","こてん"  ],
  ["Koto (Japanese harp)","琴","こと"  ],
  ["to send word,to send a message","言付ける","ことづける"  ],
  ["speech,expression,wording","言葉遣い","ことばづかい"  ],
  ["the other day,lately,recently","","こないだ"  ],
  ["not writing or contacting for a while","御無沙汰","ごぶさた"  ],
  ["to spill","","こぼす"  ],
  ["to overflow,to spill","","こぼれる"  ],
  ["trash,rubbish","塵芥","ごみ"  ],
  ["gum,rubber,eraser","","ゴム"  ],
  ["your pardon,declining (something),dismissal,permission","御免","ごめん"  ],
  ["May I come in?","","ごめんください"  ],
  ["little finger","小指","こゆび"  ],
  ["to bear,to stand,to endure,to put up with","","こらえる"  ],
  ["pleasure,amusement","娯楽","ごらく"  ],
  ["(hon) look,inspection,try","御覧","ごらん"  ],
  ["(1) collection,(2) correction","","コレクション"  ],
  ["to roll","転がす","ころがす"  ],
  ["to roll,to tumble","転がる","ころがる"  ],
  ["navy blue,deep blue","紺","こん"  ],
  ["contest (fr: concours)","","コンクール"  ],
  ["concrete","","コンクリート"  ],
  ["mixing,mixture","混合","こんごう"  ],
  ["(1) consent,(2) concentric","","コンセント"  ],
  ["menu,program,schedule","献立","こんだて"  ],
  ["good evening","","こんばんは"  ],
  ["circle,sports club (i.e. at a company)","","サークル"  ],
  ["(enrolled) in school","在学","ざいがく"  ],
  ["again and again,repeatedly","再三","さいさん"  ],
  ["national holiday,festival day","祭日","さいじつ"  ],
  ["request,demand,claim,urge (action),press for","催促","さいそく"  ],
  ["marking,grading,looking over","採点","さいてん"  ],
  ["calamity,misfortune","災難","さいなん"  ],
  ["sewing","裁縫","さいほう"  ],
  ["lumber,timber","材木","ざいもく"  ],
  ["siren","","サイレン"  ],
  ["reverse,inversion,upside down","逆さ","さかさ"  ],
  ["inversion,upside down","逆様","さかさま"  ],
  ["to search,to seek,to look for","捜す","さがす"  ],
  ["to go back,to go upstream,to make retroactive","遡る","さかのぼる"  ],
  ["bar,bar-room","酒場","さかば"  ],
  ["two days before yesterday","","さきおととい"  ],
  ["some time ago","先程","さきほど"  ],
  ["to tear,to split","裂く","さく"  ],
  ["index,indices","索引","さくいん"  ],
  ["author,authoress","作者","さくしゃ"  ],
  ["elimination,cancellation,deletion,erasure","削除","さくじょ"  ],
  ["frame,draw up,make,producing","作成","さくせい"  ],
  ["manufacture","作製","さくせい"  ],
  ["to search,to look for,to sound out","探る","さぐる"  ],
  ["to whisper,to murmur","囁く","ささやく"  ],
  ["to stick,to be stuck","刺さる","ささる"  ],
  ["spoon","匙","さじ"  ],
  ["tatami room","座敷","ざしき"  ],
  ["hindrance,impediment","差し支え","さしつかえ"  ],
  ["deduction,subtraction,balance,ebb and flow,rise and fall","差し引き","さしひき"  ],
  ["sliced raw fish","刺身","さしみ"  ],
  ["to pierce,to stab,to prick,to thrust","刺す","さす"  ],
  ["to insert,to put in,to graft,to wear in belt","挿す","さす"  ],
  ["to pour (drink),to serve (drinks)","注す","さす"  ],
  ["to shine,to strike","射す","さす"  ],
  ["clever,adept,good,expectations,as one would expect","流石","さすが"  ],
  ["photographing","撮影","さつえい"  ],
  ["noise (jarring, grating)","雑音","ざつおん"  ],
  ["quickly","","さっさと"  ],
  ["at once,immediately,without delay,promptly","早速","さっそく"  ],
  ["rust (colour)","錆","さび"  ],
  ["to rust,to become rusty","錆びる","さびる"  ],
  ["cushion (Japanese)","座布団","ざぶとん"  ],
  ["to cool,to dampen,to let cool","冷ます","さます"  ],
  ["to disturb,to prevent","妨げる","さまたげる"  ],
  ["to become cool,to wear off,to abate,to subside","冷める","さめる"  ],
  ["good-bye","","さようなら"  ],
  ["month after next","再来月","さらいげつ"  ],
  ["week after next","再来週","さらいしゅう"  ],
  ["year after next","再来年","さらいねん"  ],
  ["salary man,company employee","","サラリーマン"  ],
  ["noisy","騒がしい","さわがしい"  ],
  ["fresh,refreshing,invigorating","","さわやか"  ],
  ["triangle,triangular","三角","さんかく"  ],
  ["arithmetic","算数","さんすう"  ],
  ["acidity","酸性","さんせい"  ],
  ["producing area","産地","さんち"  ],
  ["sample","","サンプル"  ],
  ["mountain forest,mountains and forest","山林","さんりん"  ],
  ["to be finished","仕上がる","しあがる"  ],
  ["two days after tomorrow","","しあさって"  ],
  ["season (sporting)","","シーズン"  ],
  ["sheet","","シーツ"  ],
  ["temple","寺院","じいん"  ],
  ["silent (as the grave),(deathly) quiet","しいんと","（する）"  ],
  ["self-defense","自衛","じえい"  ],
  ["salty (taste)","塩辛い","しおからい"  ],
  ["chairmanship","司会","しかい"  ],
  ["square","四角","しかく"  ],
  ["square","四角い","しかくい"  ],
  ["timetable,schedule","時間割","じかんわり"  ],
  ["four seasons","四季","しき"  ],
  ["site","敷地","しきち"  ],
  ["urgent,pressing","至急","しきゅう"  ],
  ["to spread out,to lay out","敷く","しく"  ],
  ["to grow thick,to luxuriate,to be luxurious","茂る","しげる"  ],
  ["bringing,taking,carrying","持参","じさん"  ],
  ["magnet","磁石","じしゃく"  ],
  ["rounding up (fractions)","四捨五入","ししゃごにゅう"  ],
  ["continuously,from beginning to end","始終","しじゅう"  ],
  ["self-study","自習","じしゅう"  ],
  ["to quieten down,to calm down,to subside","静まる","しずまる"  ],
  ["attitude,posture","姿勢","しせい"  ],
  ["natural science","自然科学","しぜんかがく"  ],
  ["speed (per hour)","時速","じそく"  ],
  ["descendants,posterity,offspring","子孫","しそん"  ],
  ["corpse","死体","したい"  ],
  ["rough copy,draft","下書き","したがき"  ],
  ["Shitamachi,lower parts of town","下町","したまち"  ],
  ["self-government,autonomy","自治","じち"  ],
  ["feelings (actual, true)","実感","じっかん"  ],
  ["moisture,humidity,dampness","湿気","しっけ"  ],
  ["moisture,humidity,dampness","湿気","しっき"  ],
  ["insistent,obstinate","","しつこい"  ],
  ["practice,training","実習","じっしゅう"  ],
  ["achievements,actual results","実績","じっせき"  ],
  ["level of humidity","湿度","しつど"  ],
  ["writing","執筆","しっぴつ"  ],
  ["real thing,original","実物","じつぶつ"  ],
  ["tail (animal)","","しっぽ"  ],
  ["practical use,utility","実用","じつよう"  ],
  ["merit,efficiency,arms,force","実力","じつりょく"  ],
  ["example,illustration","実例","じつれい"  ],
  ["disappointed love,broken heart,unrequited love,be lovelorn","失恋","しつれん"  ],
  ["designation,specification,assignment,pointing at","指定","してい"  ],
  ["private railway","私鉄","してつ"  ],
  ["children,juvenile","児童","じどう"  ],
  ["to tie,to bind","縛る","しばる"  ],
  ["(the) ground","地盤","じばん"  ],
  ["to become numb,to go to sleep (i.e., a limb)","","しびれる"  ],
  ["paper money,notes,bills","紙幣","しへい"  ],
  ["to wither,to fade (away),to shrivel,to wilt","","しぼむ"  ],
  ["to press,to wring,to squeeze","絞る","しぼる"  ],
  ["stripe","縞","しま"  ],
  ["plain,simple","地味","じみ"  ],
  ["keenly,deeply,heartily","","しみじみ"  ],
  ["full name,identity","氏名","しめい"  ],
  ["closing,cut-off,end,deadline,Closed,No Entrance","締切","しめきり"  ],
  ["to shut up","締め切る","しめきる"  ],
  ["to be wet,to become wet,to be damp","湿る","しめる"  ],
  ["journalist","","ジャーナリスト"  ],
  ["social science","社会科学","しゃかいかがく"  ],
  ["to squat","","しゃがむ"  ],
  ["faucet,tap","蛇口","じゃぐち"  ],
  ["weak point,weakness","弱点","じゃくてん"  ],
  ["garage,car shed","車庫","しゃこ"  ],
  ["(train) conductor","車掌","しゃしょう"  ],
  ["sketching,drawing from nature","写生","しゃせい"  ],
  ["editorial,leading article","社説","しゃせつ"  ],
  ["hiccough,hiccup","","しゃっくり"  ],
  ["shutter","","シャッター"  ],
  ["to suck,to chew","","しゃぶる"  ],
  ["(car) wheel","車輪","しゃりん"  ],
  ["joke,pun,witticism","洒落","しゃれ"  ],
  ["(n) rock-scissors-paper game","","じゃんけん"  ],
  ["meeting,assembly","集会","しゅうかい"  ],
  ["dwelling,house,residence,address","住居","じゅうきょ"  ],
  ["money collection","集金","しゅうきん"  ],
  ["gathering,assembly,meeting,set (math)","集合","しゅうごう"  ],
  ["penmanship","習字","しゅうじ"  ],
  ["repair,mending","修繕","しゅうぜん"  ],
  ["seriously ill,serious condition,critical state","重体","じゅうたい"  ],
  ["carpet","じゅうたん","（カーペット）"  ],
  ["terminus,last stop (e.g train)","終点","しゅうてん"  ],
  ["important point,lay stress on,colon,emphasis","重点","じゅうてん"  ],
  ["inauguration,assumption of office","就任","しゅうにん"  ],
  ["circumference,outskirts,environs,(computer) peripheral","周辺","しゅうへん"  ],
  ["director,high executive","重役","じゅうやく"  ],
  ["end,close,termination","終了","しゅうりょう"  ],
  ["(1) weight,(2) heavyweight boxer","重量","じゅうりょう"  ],
  ["gravity","重力","じゅうりょく"  ],
  ["idiom,idiomatic phrase,kanji compound","熟語","じゅくご"  ],
  ["national holiday","祝日","しゅくじつ"  ],
  ["reduction,curtailment","縮小","しゅくしょう"  ],
  ["taking an examination","受験","じゅけん"  ],
  ["(gram) subject","主語","しゅご"  ],
  ["going to work,at work","出勤","しゅっきん"  ],
  ["predicate","述語","じゅつご"  ],
  ["official tour,business trip","出張","しゅっちょう"  ],
  ["life span","寿命","じゅみょう"  ],
  ["leading part,leading actor (actress)","主役","しゅやく"  ],
  ["(telephone) receiver","受話器","じゅわき"  ],
  ["circulation,rotation,cycle","循環","じゅんかん"  ],
  ["police,policeman","巡査","じゅんさ"  ],
  ["in order,in turn","順々","じゅんじゅん"  ],
  ["order,sequence,procedure","順序","じゅんじょ"  ],
  ["pure heart,naivete,self-sacrificing devotion","純情","じゅんじょう"  ],
  ["pure,true,genuine,unmixed","純粋","じゅんすい"  ],
  ["digestion","消化","しょうか"  ],
  ["grade school student","小学生","しょうがくせい"  ],
  ["","","しょうがない"  ],
  ["Japanese chess","将棋","しょうぎ"  ],
  ["steam,vapour","蒸気","じょうき"  ],
  ["(measuring) ruler","定規","じょうぎ"  ],
  ["advanced level,high grade,senior","上級","じょうきゅう"  ],
  ["commerce,trade,business","商業","しょうぎょう"  ],
  ["passive","消極的","しょうきょくてき"  ],
  ["prize,monetary award","賞金","しょうきん"  ],
  ["high and low,up and down,unloading and loading,praising and blaming","上下","じょうげ"  ],
  ["paper sliding door","障子","しょうじ"  ],
  ["trading company,firm","商社","しょうしゃ"  ],
  ["taking a train,entraining","乗車","じょうしゃ"  ],
  ["first 10 days of month","上旬","じょうじゅん"  ],
  ["to cause,to arise,to be generated","生ずる","しょうずる"  ],
  ["fraction (part of),decimal","小数","しょうすう"  ],
  ["shop,business firm","商店","しょうてん"  ],
  ["focus,point","焦点","しょうてん"  ],
  ["disinfection,sterilization","消毒","しょうどく"  ],
  ["victory or defeat,issue (of battle)","勝敗","しょうはい"  ],
  ["evaporation,unexplained disappearance","蒸発","じょうはつ"  ],
  ["prize,trophy","賞品","しょうひん"  ],
  ["victory or defeat,match,contest,game,bout","勝負","しょうぶ"  ],
  ["(col) urine,piss","小便","しょうべん"  ],
  ["fire station","消防署","しょうぼうしょ"  ],
  ["net (weight)","正味","しょうみ"  ],
  ["the front,honesty","正面","しょうめん"  ],
  ["exhaustion,consumption","消耗","しょうもう"  ],
  ["soy sauce","醤油","しょうゆ"  ],
  ["omission,abbreviation,abridgment","省略","しょうりゃく"  ],
  ["elementary level","初級","しょきゅう"  ],
  ["assistant professor","助教授","じょきょうじゅ"  ],
  ["table salt","食塩","しょくえん"  ],
  ["worker,mechanic,artisan,craftsman","職人","しょくにん"  ],
  ["first 10 days of the month","初旬","しょじゅん"  ],
  ["book,publication","書籍","しょせき"  ],
  ["tableware","食器","しょっき"  ],
  ["a shop","","ショップ"  ],
  ["bookshop","書店","しょてん"  ],
  ["calligraphy","書道","しょどう"  ],
  ["white or grey hair,trendy hair bleaching","白髪","しらが"  ],
  ["acquaintance","知合い","しりあい"  ],
  ["series","","シリーズ"  ],
  ["private (establishment)","私立","しりつ"  ],
  ["materials,data","資料","しりょう"  ],
  ["juice,sap,soup,broth","汁","しる"  ],
  ["amateur,novice","素人","しろうと"  ],
  ["core,heart,wick,marrow","芯","しん"  ],
  ["bullet train (very high speed),shinkansen","新幹線","しんかんせん"  ],
  ["vacuum,hollow,empty","真空","しんくう"  ],
  ["to believe,to believe in,to place trust in","信ずる","しんずる"  ],
  ["mind and body","心身","しんしん"  ],
  ["application,request,petition","申請","しんせい"  ],
  ["man-made,synthetic,artificial","人造","じんぞう"  ],
  ["bed,couch","寝台","しんだい"  ],
  ["diagnosis","診断","しんだん"  ],
  ["penetration,invasion,raid,aggression,trespass","侵入","しんにゅう"  ],
  ["social sciences,humanities","人文科学","じんぶんかがく"  ],
  ["(human) life","人命","じんめい"  ],
  ["late at night","深夜","しんや"  ],
  ["forest,woods","森林","しんりん"  ],
  ["relation,kin","親類","しんるい"  ],
  ["course,direction,compass bearing","針路","しんろ"  ],
  ["myth,legend","神話","しんわ"  ],
  ["vinegar","酢","す"  ],
  ["marine products,fisheries","水産","すいさん"  ],
  ["cooking,culinary arts","炊事","すいじ"  ],
  ["water vapour,steam","水蒸気","すいじょうき"  ],
  ["hydrogen","水素","すいそ"  ],
  ["vertical,perpendicular","垂直","すいちょく"  ],
  ["presumption,assumption,estimation","推定","すいてい"  ],
  ["drop of water","水滴","すいてき"  ],
  ["canteen,flask,water bottle","水筒","すいとう"  ],
  ["essays,miscellaneous writings","随筆","ずいひつ"  ],
  ["moisture","水分","すいぶん"  ],
  ["water level,horizon","水平","すいへい"  ],
  ["horizon","水平線","すいへいせん"  ],
  ["Wednesday","水曜","すいよう"  ],
  ["impudent,shameless","","ずうずうしい"  ],
  ["","","ずうっと"  ],
  ["youngest child","末っ子","すえっこ"  ],
  ["scarf","","スカーフ"  ],
  ["picture book","図鑑","ずかん"  ],
  ["Japanese cedar","杉","すぎ"  ],
  ["likes and dislikes,taste","好き嫌い","すききらい"  ],
  ["matter of taste","好き好き","すきずき"  ],
  ["to be(come) transparent","透き通る","すきとおる"  ],
  ["crevice,crack,gap,opening","隙間","すきま"  ],
  ["school","","スクール"  ],
  ["at least","","すくなくとも"  ],
  ["figure","図形","ずけい"  ],
  ["schedule","","スケジュール"  ],
  ["bell","鈴","すず"  ],
  ["to cool oneself,to cool off,to enjoy evening cool","涼む","すずむ"  ],
  ["start","","スタート"  ],
  ["stewardess","","スチュワーデス"  ],
  ["shapely,clear,neat","","すっきり"  ],
  ["sour,acid","","すっぱい"  ],
  ["(1) stage,(2) performance","","ステージ"  ],
  ["","棄てる","すてる"  ],
  ["stockings","","ストッキング"  ],
  ["stop","","ストップ"  ],
  ["obedient,meek,docile,unaffected","素直","すなお"  ],
  ["head,brains,intellect","頭脳","ずのう"  ],
  ["speaker","","スピーカー"  ],
  ["chart,diagram,graph","図表","ずひょう"  ],
  ["smart,stylish,slim","","スマート"  ],
  ["dwelling,house,residence,address","住まい","すまい"  ],
  ["sorry (phrase)","","すまない"  ],
  ["ink","墨","すみ"  ],
  ["to clear (e.g. weather),to become transparent","澄む","すむ"  ],
  ["","清む","すむ"  ],
  ["sumo wrestling","相撲","すもう"  ],
  ["slide","","スライド"  ],
  ["to put off,to delay","","ずらす"  ],
  ["","","ずらり"  ],
  ["pickpocket","掏摸","すり"  ],
  ["to print","刷る","する"  ],
  ["sly,cunning","狡い","ずるい"  ],
  ["to pass by one another,to disagree","","すれちがう"  ],
  ["","滑れる","ずれる"  ],
  ["measurement,size,dimension","寸法","すんぽう"  ],
  ["surname,family name","姓","せい"  ],
  ["customs house","税関","ぜいかん"  ],
  ["manufacture,production","製作","せいさく"  ],
  ["work (film, book)","制作","せいさく"  ],
  ["nature,property,disposition","性質","せいしつ"  ],
  ["clean copy","清書","せいしょ"  ],
  ["youth,young person","青少年","せいしょうねん"  ],
  ["integer","整数","せいすう"  ],
  ["cleaning","清掃","せいそう"  ],
  ["existence,being,survival","生存","せいぞん"  ],
  ["growth,increment","生長","せいちょう"  ],
  ["(member of) political party","政党","せいとう"  ],
  ["birth date","生年月日","せいねんがっぴ"  ],
  ["ability,efficiency","性能","せいのう"  ],
  ["adjustment,completion,consolidation","整備","せいび"  ],
  ["ingredient,component,composition","成分","せいぶん"  ],
  ["distinction by sex,sex,gender","性別","せいべつ"  ],
  ["square","正方形","せいほうけい"  ],
  ["main gate,main entrance","正門","せいもん"  ],
  ["coming into existence,arrangements,establishment,completion","成立","せいりつ"  ],
  ["Christian Era,anno domini (A.D.)","西暦","せいれき"  ],
  ["to be burdened with,to carry on back or shoulder","背負う","せおう"  ],
  ["equator","赤道","せきどう"  ],
  ["with trouble,at great pains,long-awaited","折角","せっかく"  ],
  ["getting closer,drawing nearer,approaching","接近","せっきん"  ],
  ["soap","石鹸","せっけん"  ],
  ["to come in contact with,to connect,to attend,to receive","接する","せっする"  ],
  ["","","せっせと"  ],
  ["(1) connection,union,join,link,(2) changing trains","接続","せつぞく"  ],
  ["earthenware,crockery,china","瀬戸物","せともの"  ],
  ["by all means (with sense of not taking no for an answer)","","ぜひとも"  ],
  ["to draw near,to press","迫る","せまる"  ],
  ["(n) seminar","","ゼミ"  ],
  ["offense,method of attack","","せめて"  ],
  ["to attack,to assault","攻める","せめる"  ],
  ["cement","","セメント"  ],
  ["stopper,cork,stopcock","栓","せん"  ],
  ["around,throughout,front and back,before and behind,before and after","前後","ぜんご"  ],
  ["detergent,washing material","洗剤","せんざい"  ],
  ["complete works","全集","ぜんしゅう"  ],
  ["the whole body,full-length (portrait)","全身","ぜんしん"  ],
  ["folding fan","扇子","せんす"  ],
  ["despotism,autocracy","専制","せんせい"  ],
  ["month before last","先々月","せんせんげつ"  ],
  ["","先々週","せんせんしゅう"  ],
  ["ancestor","先祖","せんぞ"  ],
  ["pointed end,tip,fine point","先端","せんたん"  ],
  ["centimeter,centi-,10^-2","","センチ"  ],
  ["propaganda,publicity","宣伝","せんでん"  ],
  ["head,lead,vanguard,first","先頭","せんとう"  ],
  ["(the) whole,universal,wholly,general","全般","ぜんぱん"  ],
  ["electric fan","扇風機","せんぷうき"  ],
  ["line,track,roadbed","線路","せんろ"  ],
  ["difference,discrepancy,variation","相違","そうい"  ],
  ["which reminds me ..","","そういえば"  ],
  ["house-cloth,dust cloth","雑巾","ぞうきん"  ],
  ["increase and decrease,fluctuation","増減","ぞうげん"  ],
  ["storehouse,warehouse,godown","倉庫","そうこ"  ],
  ["mutual,reciprocal","相互","そうご"  ],
  ["production,literary creation,work","創作","そうさく"  ],
  ["funeral","葬式","そうしき"  ],
  ["and,like that","","そうして"  ],
  ["shipbuilding","造船","ぞうせん"  ],
  ["noisy,boisterous","騒々しい","そうぞうしい"  ],
  ["enlargement","増大","ぞうだい"  ],
  ["","","そうっと"  ],
  ["farewell,send-off","送別","そうべつ"  ],
  ["zoori (Japanese footwear),sandals","草履","ぞうり"  ],
  ["Prime Minister","総理大臣","そうりだいじん"  ],
  ["postage,carriage","送料","そうりょう"  ],
  ["to belong to,to come under,to be affiliated with,to be subject to","属する","ぞくする"  ],
  ["successively,one after another","続々","ぞくぞく"  ],
  ["express,special delivery","速達","そくたつ"  ],
  ["measurement","測定","そくてい"  ],
  ["measurement,surveying","測量","そくりょう"  ],
  ["speed","速力","そくりょく"  ],
  ["character,qualities,genius","素質","そしつ"  ],
  ["ancestor","祖先","そせん"  ],
  ["careless,thoughtless","","そそっかしい"  ],
  ["frankness,candour,openheartedness","卒直","そっちょく"  ],
  ["to be furnished with","具える","そなえる"  ],
  ["in addition,furthermore","","そのうえ"  ],
  ["","","そのころ"  ],
  ["hence,for that reason","","そのため"  ],
  ["otherwise","","そのほか"  ],
  ["soba (buckwheat noodles)","蕎麦","そば"  ],
  ["to shave","剃る","そる"  ],
  ["","","それなのに"  ],
  ["to stray (turn) from subject,to get lost,to go astray","逸れる","それる"  ],
  ["to become complete,to be equal,to be all present,to gather","揃う","そろう"  ],
  ["to put things in order,to arrange,to make uniform,to get something ready","揃える","そろえる"  ],
  ["abacus","算盤","そろばん"  ],
  ["(hum) to know","存じる","ぞんじる"  ],
  ["","存ずる","ぞんずる"  ],
  ["loss and gain,advantage and disadvantage","損得","そんとく"  ],
  ["paddy field,farm","田ぼ","たんぼ"  ],
  ["first,foremost,# 1","だいいち","（副）"  ],
  ["leaving hospital","退院","たいいん"  ],
  ["graduate school","大学院","だいがくいん"  ],
  ["carpenter","大工","だいく"  ],
  ["system,organization","体系","たいけい"  ],
  ["drum,tambourine","太鼓","たいこ"  ],
  ["counter-plan,counter-measure","対策","たいさく"  ],
  ["(not so) much,(not) very","大して","たいして"  ],
  ["contrast,antithesis,comparison","対照","たいしょう"  ],
  ["size","大小","だいしょう"  ],
  ["order,system,structure,set-up,organization","体制","たいせい"  ],
  ["capacity,volume","体積","たいせき"  ],
  ["very much,exaggerated,very fine","大層","たいそう"  ],
  ["gymnastics,physical exercises,calisthenics","体操","たいそう"  ],
  ["considerably,greatly,a lot","大分","だいぶん"  ],
  ["large tree","大木","たいぼく"  ],
  ["title","題名","だいめい"  ],
  ["pronoun","代名詞","だいめいし"  ],
  ["tire,tyre","","タイア"  ],
  ["diagram","","ダイヤグラム"  ],
  ["diamond","","ダイヤモンド"  ],
  ["dial","","ダイヤル"  ],
  ["confrontation,opposition,antagonism","Ͼ立","たいりつ"  ],
  ["rice planting","田植え","たうえ"  ],
  ["constantly","絶えず","たえず"  ],
  ["ellipse","楕円","だえん"  ],
  ["to raise,to lift,to boost","高める","たかめる"  ],
  ["to till,to plow,to cultivate","耕す","たがやす"  ],
  ["waterfall","滝","たき"  ],
  ["to boil,to cook","炊く","たく"  ],
  ["to burn,to kindle,to build a fire","焚く","たく"  ],
  ["to store,to lay in stock","蓄える","たくわえる"  ],
  ["bamboo,middle (of a three-tier ranking system)","竹","たけ"  ],
  ["to be saved,to be rescued,to survive,to be helpful","助かる","たすかる"  ],
  ["free of charge,mere,sole,only,usual,common","只","ただ"  ],
  ["but,however,provided that","但し","ただし"  ],
  ["to fold (clothes)","畳む","たたむ"  ],
  ["to stop,to halt,to stand still","立ち止まる","たちどまる"  ],
  ["at once,in a moment,suddenly,all at once","","たちまち"  ],
  ["to erect,to be erected,to be built","建つ","たつ"  ],
  ["to depart (on a plane, train, etc.)","発つ","たつ"  ],
  ["derailment,digression","脱線","だっせん"  ],
  ["valid,proper,right,appropriate","妥当","だとう"  ],
  ["to compare,to liken,to speak figuratively,to illustrate,to use a simile","例える","たとえる"  ],
  ["reliable,trustworthy,hopeful,promising","頼もしい","たのもしい"  ],
  ["tabi,Japanese socks (with split toe)","足袋","たび"  ],
  ["double","","ダブル"  ],
  ["to trick,to cheat,to deceive","","だます"  ],
  ["to collect,to gather,to save","溜まる","たまる"  ],
  ["dumb","","ダム"  ],
  ["a sigh","溜息","ためいき"  ],
  ["to hesitate","","ためらう"  ],
  ["to amass,to accumulate","溜める","ためる"  ],
  ["slovenly,loose,a slut","","だらしない"  ],
  ["to be sufficient,to be enough","足る","たる"  ],
  ["gradation,grade,stage","段階","だんかい"  ],
  ["short term","短期","たんき"  ],
  ["coal mine,coal pit","炭鉱","たんこう"  ],
  ["(1) defect,demerit,weak point,(2) disadvantage","短所","たんしょ"  ],
  ["chest of drawers","","たんす"  ],
  ["fresh water","淡水","たんすい"  ],
  ["water outage","断水","だんすい"  ],
  ["singular (number)","単数","たんすう"  ],
  ["multi-unit apartments","団地","だんち"  ],
  ["conclusion,decision","断定","だんてい"  ],
  ["short (e.g. story, film)","短編","たんぺん"  ],
  ["to swear,to vow,to take an oath,to pledge","誓う","ちかう"  ],
  ["underground water","地下水","ちかすい"  ],
  ["nearness,before long","近々","ちかぢか"  ],
  ["to bring near,to put close,to let come near,to associate with","近付ける","ちかづける"  ],
  ["to approach,to draw near","近寄る","ちかよる"  ],
  ["reassuring,emboldened","力強い","ちからづよい"  ],
  ["to cut up fine,to pick (fruit)","","ちぎる"  ],
  ["geological features","地質","ちしつ"  ],
  ["friend,acquaintance","知人","ちじん"  ],
  ["area,zone","地帯","ちたい"  ],
  ["to shrink,to be contracted","縮む","ちぢむ"  ],
  ["to shorten,to reduce,to boil down,to shrink","縮める","ちぢめる"  ],
  ["to be wavy,to be curled","縮れる","ちぢれる"  ],
  ["(1) gratuity,tip,(2) chip","","チップ"  ],
  ["site,point on a map","地点","ちてん"  ],
  ["place name","地名","ちめい"  ],
  ["","茶色い","ちゃいろい"  ],
  ["steadily","着々","ちゃくちゃく"  ],
  ["rice bowl,tea cup,teacup","茶碗","ちゃわん"  ],
  ["middle,midway,interim","中間","ちゅうかん"  ],
  ["second third of a month","中旬","ちゅうじゅん"  ],
  ["abstract","抽象","ちゅうしょう"  ],
  ["Middle Ages,mediaeval times","中世","ちゅうせい"  ],
  ["neuter gender,neutral (chem.),indifference,sterility","中性","ちゅうせい"  ],
  ["in the middle,half-way","中途","ちゅうと"  ],
  ["middle-aged","中年","ちゅうねん"  ],
  ["excess,being more than","超過","ちょうか"  ],
  ["carving,engraving,sculpture","彫刻","ちょうこく"  ],
  ["(1) strong point,merit,(2) advantage","長所","ちょうしょ"  ],
  ["eldest daughter","長女","ちょうじょ"  ],
  ["regulation,adjustment,tuning","調整","ちょうせい"  ],
  ["regulation,adjustment,control","調節","ちょうせつ"  ],
  ["length,long and short,+-","長短","ちょうたん"  ],
  ["top,summit","頂点","ちょうてん"  ],
  ["eldest son","長男","ちょうなん"  ],
  ["rectangle,oblong","長方形","ちょうほうけい"  ],
  ["condiment,seasoning","調味料","ちょうみりょう"  ],
  ["chock,chalk","","チョーク"  ],
  ["immediately following","直後","ちょくご"  ],
  ["straight line","直線","ちょくせん"  ],
  ["just before","直前","ちょくぜん"  ],
  ["direct communication","直通","ちょくつう"  ],
  ["direct current","直流","ちょくりゅう"  ],
  ["storage,preservation","貯蔵","ちょぞう"  ],
  ["right angle","直角","ちょっかく"  ],
  ["diameter","直径","ちょっけい"  ],
  ["to scatter around,to leave untidy","散らかす","ちらかす"  ],
  ["to be in disorder,to lie scattered around","散らかる","ちらかる"  ],
  ["to scatter,to disperse,to distribute","散らす","ちらす"  ],
  ["tissue paper,toilet paper","塵紙","ちりがみ"  ],
  ["to fall,to scatter (e.g. blossoms)","散る","ちる"  ],
  ["addition,supplement,appendix","追加","ついか"  ],
  ["opportunity,occasion","","ついで"  ],
  ["currency","通貨","つうか"  ],
  ["commuting to work","通勤","つうきん"  ],
  ["","通ずる","つうずる"  ],
  ["notice,notification","通知","つうち"  ],
  ["passbook","通帳","つうちょう"  ],
  ["interpretation","通訳","つうやく"  ],
  ["popular use,circulation","通用","つうよう"  ],
  ["passage,pathway","通路","つうろ"  ],
  ["to associate with,to keep company with,to get on with","付合う","つきあう"  ],
  ["end (e.g. of street)","突き当たり","つきあたり"  ],
  ["to run into,to collide with","突き当たる","つきあたる"  ],
  ["time,years,days","月日","つきひ"  ],
  ["to catch fire,(electricity) comes on","点く","つく"  ],
  ["(1) to thrust,to strike,(2) to poke","突く","つく"  ],
  ["to rank next to,to come after","次ぐ","つぐ"  ],
  ["to make,to create","作る/造る","つくる"  ],
  ["(1) to attach,to join,to add,to append","着ける","つける"  ],
  ["to turn on,to switch on,to light up","点ける","つける"  ],
  ["to dip in,to soak","浸ける","つける"  ],
  ["to be handed down,to be introduced,to be transmitted","伝わる","つたわる"  ],
  ["to plunge into,to go into deeply","突っ込む","つっこむ"  ],
  ["(1) to serve,to fill a post,to serve under,to work (for)","務める","つとめる"  ],
  ["(1) to serve,to fill a post,to serve under,to work (for)","努める","つとめる"  ],
  ["rope","綱","つな"  ],
  ["connection,link,relationship","繋がり","つながり"  ],
  ["to be tied together,to be connected to,to be related to","繋がる","つながる"  ],
  ["to connect","繋げる","つなげる"  ],
  ["grain","粒","つぶ"  ],
  ["to smash,to waste","潰す","つぶす"  ],
  ["to be smashed,to go bankrupt","潰れる","つぶれる"  ],
  ["to stumble,to trip","","つまずく"  ],
  ["to be blocked,to be packed","詰まる","つまる"  ],
  ["to pile up,to stack","積む","つむ"  ],
  ["fingernail or toenail,claw,talon,hoof","爪","つめ"  ],
  ["gloss,glaze","艶","つや"  ],
  ["firm,strong","強気","つよき"  ],
  ["to balance,to be in harmony,to suit","釣り合う","つりあう"  ],
  ["to hang","吊る","つる"  ],
  ["to hang","吊す","つるす"  ],
  ["an encounter","出合い","であい"  ],
  ["restroom,lavatory,hand-washing","手洗い","てあらい"  ],
  ["fixed number of regular personnel,capacity (of boat, etc.)","定員","ていいん"  ],
  ["established price","定価","ていか"  ],
  ["fall,decline,lowering,deterioration","低下","ていか"  ],
  ["commuter pass,season ticket","定期券","ていきけん"  ],
  ["regular holiday","定休日","ていきゅうび"  ],
  ["suspension,interruption,stoppage,ban","停止","ていし"  ],
  ["stopping (e.g. train)","停車","ていしゃ"  ],
  ["failure of electricity","停電","ていでん"  ],
  ["in and out,coming and going,free association,income and expenditure,debits and credit","出入り","でいり"  ],
  ["exit and entrance","出入口","でいりぐち"  ],
  ["repairs,maintenance","手入れ","ていれ"  ],
  ["(n) theme,project,topic (de: Thema)","","テーマ"  ],
  ["to depart,to set out,to start,to be going out","出掛ける","でかける"  ],
  ["be finished,ready,made for,cut out","出来上がり","できあがり"  ],
  ["(1) to be finished,to be ready,by definition,(2) to be very drunk","出来上がる","できあがる"  ],
  ["precise,accurate","的確","てきかく"  ],
  ["precise,accurate","適確","てきかく"  ],
  ["wrist","手首","てくび"  ],
  ["unevenness,roughness,ruggedness","凸凹","でこぼこ"  ],
  ["moderate,handy","手頃","てごろ"  ],
  ["(1) irresponsible utterance,nonsense,nonsensical,(2) random","","でたらめ"  ],
  ["notebook","手帳","てちょう"  ],
  ["railway bridge,iron bridge","鉄橋","てっきょう"  ],
  ["procedure,(legal) process,formalities","手続き","てつづき"  ],
  ["gun","鉄砲","てっぽう"  ],
  ["tennis court","","テニスコート"  ],
  ["(hand) towel","手拭い","てぬぐい"  ],
  ["before,this side,we,you","手前","てまえ"  ],
  ["meeting,reception","出迎え","でむかえ"  ],
  ["to meet,to greet","出迎える","でむかえる"  ],
  ["to shine on,to illuminate","照らす","てらす"  ],
  ["to shine","照る","てる"  ],
  ["develop,expansion (opposite of compression)","展開","てんかい"  ],
  ["biography,life story","伝記","でんき"  ],
  ["light bulb","電球","でんきゅう"  ],
  ["marks,points,score,runs","点数","てんすう"  ],
  ["contagion","伝染","でんせん"  ],
  ["battery","電池","でんち"  ],
  ["here and there,little by little","点々","てんてん"  ],
  ["","転々","てんてん"  ],
  ["telephone pole,telegraph pole,lightpole","電柱","でんちゅう"  ],
  ["Emperor of Japan","天皇","てんのう"  ],
  ["electro-magnetic wave","電波","でんぱ"  ],
  ["tempo","","テンポ"  ],
  ["electric current","電流","でんりゅう"  ],
  ["electric power","電力","でんりょく"  ],
  ["enquiry,ENQ","問い合わせ","といあわせ"  ],
  ["copper","銅","どう"  ],
  ["unity,consolidation,uniformity","統一","とういつ"  ],
  ["the same rank,equality,apposition","同格","どうかく"  ],
  ["ridge,(mountain) pass,difficult part","峠","とうげ"  ],
  ["scattering,a scatter,dispersion","統計","とうけい"  ],
  ["action,movements,motions,bearing,behaviour,manners","動作","どうさ"  ],
  ["East and West,whole country","東西","とうざい"  ],
  ["appointed day,very day","当日","とうじつ"  ],
  ["letter to the editor,letter from a reader,contribution","投書","とうしょ"  ],
  ["entry (on stage)","登場","とうじょう"  ],
  ["anyhow,in any case,at any rate","","どうせ"  ],
  ["pleased to meet you","","どうぞよろしく"  ],
  ["lighthouse","灯台","とうだい"  ],
  ["theft,robbery","盗難","とうなん"  ],
  ["being on duty","当番","とうばん"  ],
  ["division into equal parts","等分","とうぶん"  ],
  ["transparency,cleanness","透明","とうめい"  ],
  ["lamp oil,kerosene","灯油","とうゆ"  ],
  ["Orient","東洋","とうよう"  ],
  ["fairy tale","童話","どうわ"  ],
  ["to happen to pass by","通り掛かる","とおりかかる"  ],
  ["to melt,to dissolve","溶かす","とかす"  ],
  ["to taper to a point,to become sharp,to be sour,to look displeased","尖る","とがる"  ],
  ["throb,beat (fast)","","どきどき"  ],
  ["to dissolve (paint)","溶く","とく"  ],
  ["(1) to retreat,to recede,to withdraw","退く","どく"  ],
  ["special,unique","特殊","とくしゅ"  ],
  ["characteristic,feature","特色","とくしょく"  ],
  ["forte,merit","特長","とくちょう"  ],
  ["specific,special,particular","特定","とくてい"  ],
  ["special sale","特売","とくばい"  ],
  ["to melt into","溶け込む","とけこむ"  ],
  ["to melt,to thaw,to fuse,to dissolve","溶ける","とける"  ],
  ["to remove,to take away,to dislodge,to put something out of the way","退ける","どける"  ],
  ["alcove","床の間","とこのま"  ],
  ["barber","床屋","とこや"  ],
  ["here and there,some parts (of something)","所々","ところどころ"  ],
  ["heart (of city)","都心","としん"  ],
  ["cupboard,locker,closet,wardrobe","戸棚","とだな"  ],
  ["long ago,already,a long time ago","","とっくに"  ],
  ["suddenly","","どっと"  ],
  ["to be prepared,to be in order,to be put in order,to be arranged","整う","ととのう"  ],
  ["(1) to be fixed,(2) to abide,to stay (in the one place)","留まる","とどまる"  ],
  ["to shout,to yell","","どなる"  ],
  ["to jump in,to leap in,to plunge into,to dive","飛び込む","とびこむ"  ],
  ["to jump,to fly,to leap","跳ぶ","とぶ"  ],
  ["(1) to be fixed,(2) to abide,to stay (in the one place)","留まる","とまる"  ],
  ["to give shelter to,to lodge","泊める","とめる"  ],
  ["anyhow,anyway,somehow or other,generally speaking,in any case","","ともかく"  ],
  ["to seize,to grasp,to capture,to arrest","捕える","とらえる"  ],
  ["to harvest,to take in,to adopt","取り入れる","とりいれる"  ],
  ["to cancel","取り消す","とりけす"  ],
  ["to take out,to produce,to pick out","取り出す","とりだす"  ],
  ["(1) to adopt (measure, proposal),(2) to pick (fruit)","採る","とる"  ],
  ["to take,to catch (fish),to capture","捕る","とる"  ],
  ["training","","トレーニング"  ],
  ["porcelain bowl,bowl of rice with food on top","丼","どんぶり"  ],
  ["internist clinic,internal medicine","内科","ないか"  ],
  ["phone extension,indoor wiring,inner line","内線","ないせん"  ],
  ["nylon","","ナイロン"  ],
  ["to cure,to heal,to fix,to correct,to repair","治す","なおす"  ],
  ["long,lengthy","永い","ながい"  ],
  ["reconciliation,make peace with","仲直り","なかなおり"  ],
  ["to be prolonged,to drag on","長引く","ながびく"  ],
  ["contents,interior,substance,filling,(sword) blade","中身","なかみ"  ],
  ["contents,interior,substance,filling,(sword) blade","中味","なかみ"  ],
  ["middle finger","中指","なかゆび"  ],
  ["intimate friend,bosom buddy,chum","仲良し","なかよし"  ],
  ["to comfort,to console","慰める","なぐさめる"  ],
  ["to lose someone, wife, child, etc","亡くす","なくす"  ],
  ["to strike,to hit","","なぐる"  ],
  ["to accomplish,to do","為す","なす"  ],
  ["riddle,puzzle,enigma","謎謎","なぞなぞ"  ],
  ["","傾らか","なだらか"  ],
  ["dear,desired,missed","懐かしい","なつかしい"  ],
  ["to brush gently,to stroke","撫でる","なでる"  ],
  ["obliqueness","斜め","ななめ"  ],
  ["at any rate,anyhow,anyway,in any case","","なにしろ"  ],
  ["such and such,What?","何々","なになに"  ],
  ["what minute?,how many minutes?","何分","なにぶん"  ],
  ["impertinent,saucy,cheeky,conceit,audacious,brazen","生意気","なまいき"  ],
  ["roadside tree,row of trees","並木","なみき"  ],
  ["to imitate,to follow,to emulate","倣う","ならう"  ],
  ["to ring,to sound,to chime,to beat,to snort (nose)","鳴らす","ならす"  ],
  ["to bear fruit","生る","なる"  ],
  ["to become domesticated,to become tame","馴れる","なれる"  ],
  ["south pole,Antarctic","南極","なんきょく"  ],
  ["somehow or other,for some reason or another","","なんとなく"  ],
  ["nothing (with neg. verb),quite,not a bit","","なんとも"  ],
  ["number","","ナンバー"  ],
  ["South America","南米","なんべい"  ],
  ["south and north","南北","なんぼく"  ],
  ["to boil,to cook,to be cooked","煮える","にえる"  ],
  ["to be fragrant,to smell,to stink","匂う","におう"  ],
  ["to let loose,to set free,to let escape","逃がす","にがす"  ],
  ["hateful,abominable,poor-looking,detestable","憎い","にくい"  ],
  ["to hate,to detest","憎む","にくむ"  ],
  ["odious,hateful","憎らしい","にくらしい"  ],
  ["","","にこにこ"  ],
  ["to become muddy,to get impure","濁る","にごる"  ],
  ["rainbow","虹","にじ"  ],
  ["date and time","日時","にちじ"  ],
  ["daily necessities","日用品","にちようひん"  ],
  ["daily lesson,daily work,daily routine","日課","にっか"  ],
  ["agenda","日程","にってい"  ],
  ["dull (e.g. a knife),thickheaded,slow (opposite of fast),stupid","鈍い","にぶい"  ],
  ["entry to a company","入社","にゅうしゃ"  ],
  ["wife","女房","にょうぼう"  ],
  ["to glare at,to scowl at,to keep an eye on","睨む","にらむ"  ],
  ["to boil,to cook","煮る","にる"  ],
  ["sudden,abrupt,unexpected,improvised,offhand","俄","にわか"  ],
  ["to sew","縫う","ぬう"  ],
  ["to wet,to soak,to dip","濡らす","ぬらす"  ],
  ["(a) screw","","ねじ"  ],
  ["to twist","捩る","ねじる"  ],
  ["necklace","","ネックレス"  ],
  ["to heat","熱する","ねっする"  ],
  ["sleep-wear,nightclothes,pyjamas,nightgown,nightdress","寝間着","ねまき"  ],
  ["sleep-wear,nightclothes,pyjamas,nightgown,nightdress","寝巻","ねまき"  ],
  ["aim","狙い","ねらい"  ],
  ["to aim at","狙う","ねらう"  ],
  ["year,fiscal year,school year,term","年度","ねんど"  ],
  ["agricultural produce","農産物","のうさんぶつ"  ],
  ["agricultural community,farm village,rural","農村","のうそん"  ],
  ["concentration,brightness","濃度","のうど"  ],
  ["agricultural chemicals","農薬","のうやく"  ],
  ["efficiency","能率","のうりつ"  ],
  ["saw","","のこぎり"  ],
  ["all,entirely,completely,without exception","残らず","のこらず"  ],
  ["to place on (something),to take on board,to give a ride","載せる","のせる"  ],
  ["to peep in,to look in,to peek in,to stick out","覗く","のぞく"  ],
  ["to lengthen,to stretch,to reach out,to grow (beard)","延ばす","のばす"  ],
  ["to be prolonged","延びる","のびる"  ],
  ["up-train (going to Tokyo),ascent","上り","のぼり"  ],
  ["to ascend,to go up,to climb","上る","のぼる"  ],
  ["paste,starch","糊","のり"  ],
  ["(n) transfer (trains, buses, etc.)","乗換","のりかえ"  ],
  ["to appear (in print),to be recorded","載る","のる"  ],
  ["dull (e.g. a knife),thickheaded,slow (opposite of fast),stupid","鈍い","のろい"  ],
  ["slowly,sluggishly","","のろのろ"  ],
  ["carefree,optimistic,careless,reckless,heedless","呑気","のんき"  ],
  ["grey,gray,ashen","灰色","はいいろ"  ],
  ["haiku poetry","俳句","はいく"  ],
  ["(hum) (pol) seeing,look at","拝見","はいけん"  ],
  ["shop,stand","売店","ばいてん"  ],
  ["","","バイバイ"  ],
  ["trade,buying and selling","売買","ばいばい"  ],
  ["to creep,to crawl","這う","はう"  ],
  ["(1) to grow,to spring up,(2) to cut (teeth)","生える","はえる"  ],
  ["(v5s) to tear off,to peel off,to rip off","剥す","はがす"  ],
  ["absurd","","ばからしい"  ],
  ["scales,weighing machine","秤","はかり"  ],
  ["to measure,to weigh,to survey","量る","はかる"  ],
  ["to measure,to weigh,to survey","測る","はかる"  ],
  ["nausea,sickness in the stomach","吐き気","はきけ"  ],
  ["lucidly","","はきはき"  ],
  ["to sweep,to brush,to gather up","掃く","はく"  ],
  ["gear,cog-wheel","歯車","はぐるま"  ],
  ["bucket,pail","","バケツ"  ],
  ["to get between,to be caught in","挟まる","はさまる"  ],
  ["to interpose,to hold between,to insert","挟む","はさむ"  ],
  ["chopsticks","箸","はし"  ],
  ["ladder,stairs","梯子","はしご"  ],
  ["to begin with,first of all","始めに","はじめに"  ],
  ["","初めに","はじめに"  ],
  ["How do you do?,I am glad to meet you","","はじめまして"  ],
  ["","斜","はす"  ],
  ["to be disconnected,to get out of place,to be off,to be out (e.g. of gear)","外れる","はずれる"  ],
  ["pattern","","パターン"  ],
  ["underwear","肌着","はだぎ"  ],
  ["as was expected,really","果して","はたして"  ],
  ["a bowl,a pot","鉢","はち"  ],
  ["","×","ばつ"  ],
  ["exhibition,demonstration,utilization,display","発揮","はっき"  ],
  ["back","","バック"  ],
  ["firing,shooting,discharge,catapult","発射","はっしゃ"  ],
  ["expression (music),conceptualization","発想","はっそう"  ],
  ["generation (e.g. power)","発電","はつでん"  ],
  ["sale","発売","はつばい"  ],
  ["showy,loud,gay,flashy,gaudy","派手","はで"  ],
  ["discussion,conference","話合い","はなしあい"  ],
  ["to accost a person,to talk (to someone)","話し掛ける","はなしかける"  ],
  ["while talking,the line is busy","話中","はなしちゅう"  ],
  ["extreme,excessive,terrible","甚だしい","はなはだしい"  ],
  ["fireworks","花火","はなび"  ],
  ["bride","花嫁","はなよめ"  ],
  ["to leave,to get free,to cut oneself off","放れる","はなれる"  ],
  ["shuttlecock","羽根","はね"  ],
  ["spring (e.g. coil, leaf)","","ばね"  ],
  ["to jump,to leap","跳ねる","はねる"  ],
  ["fragment,splinter,broken piece","破片","はへん"  ],
  ["dentifrice,toothpaste","歯磨き","はみがき"  ],
  ["(col) to get in,to insert,to put on,to make love","","はめる"  ],
  ["fast-talking","早口","はやくち"  ],
  ["to flourish,to thrive,to be popular,to come into fashion","流行る","はやる"  ],
  ["to deposit,to pay in","払い込む","はらいこむ"  ],
  ["to repay,to pay back","払い戻す","はらいもどす"  ],
  ["balance","","バランス"  ],
  ["wire","針金","はりがね"  ],
  ["to be in high spirits,to be full of vigor","張り切る","はりきる"  ],
  ["reflection,influence","反映","はんえい"  ],
  ["radius","半径","はんけい"  ],
  ["seal (used for signature)","判子","はんこ"  ],
  ["hurrah, cheers","万歳","ばんざい"  ],
  ["judge,judiciary","判事","はんじ"  ],
  ["reflection,reconsideration,introspection,meditation,contemplation","反省","はんせい"  ],
  ["house number,address","番地","ばんち"  ],
  ["underpants","","パンツ"  ],
  ["band","","バンド"  ],
  ["peninsula","半島","はんとう"  ],
  ["handle,steering wheel","","ハンドル"  ],
  ["exposure to the sun,sunny place","日当たり","ひあたり"  ],
  ["day trip","日帰り","ひがえり"  ],
  ["comparatively,relatively","比較的","ひかくてき"  ],
  ["shadow","日陰","ひかげ"  ],
  ["glitter,sparkle","","ぴかぴか"  ],
  ["to undertake,to take up,to take over","引受る","ひきうける"  ],
  ["to repeat,to send back,to bring back","引返す","ひきかえす"  ],
  ["subtraction","引算","ひきざん"  ],
  ["to pull out,to take out,to draw out,to withdraw","引出す","ひきだす"  ],
  ["to detain,to check,to restrain","引き止める","ひきとめる"  ],
  ["cowardice,meanness,unfairness","卑怯","ひきょう"  ],
  ["a draw (in competition),tie game","引分け","ひきわけ"  ],
  ["moustache,beard,whiskers","髭","ひげ"  ],
  ["sunlight,rays of the sun","陽射","ひざし"  ],
  ["elbow","肘","ひじ"  ],
  ["pistol","","ピストル"  ],
  ["vitamin","","ビタミン"  ],
  ["","","ぴたり"  ],
  ["to be caught in,to be stuck in,to be cheated","引っ掛かる","ひっかかる"  ],
  ["(taking) notes,copying","筆記","ひっき"  ],
  ["to turn over,to overturn,to knock over,to upset,to turn inside out","引っ繰り返す","ひっくりかえす"  ],
  ["to be overturned,to be upset,to topple over,to be reversed","引っ繰り返る","ひっくりかえる"  ],
  ["moving (dwelling etc.),changing residence","引越し","ひっこし"  ],
  ["to draw back,to sink,to cave in","引っ込む","ひっこむ"  ],
  ["writer,author","筆者","ひっしゃ"  ],
  ["necessities,necessary article,requisite,essential","必需品","ひつじゅひん"  ],
  ["index finger","人差指","ひとさしゆび"  ],
  ["ordinary,usual,in general,briefly","一通り","ひととおり"  ],
  ["pedestrian traffic","人通り","ひとどおり"  ],
  ["for the present,once,in outline","","ひとまず"  ],
  ["pupil (of eye)","瞳","ひとみ"  ],
  ["a rest","一休み","ひとやすみ"  ],
  ["a soliloquy,a monologue,speaking to oneself","独り言","ひとりごと"  ],
  ["by itself,automatically,naturally","","ひとりでに"  ],
  ["vinyl","","ビニール"  ],
  ["cynicism,sarcasm","皮肉","ひにく"  ],
  ["every day,daily,day after day","日日","ひにち"  ],
  ["to turn (a switch) on or off,to twist,to puzzle over","捻る","ひねる"  ],
  ["sunset","日の入り","ひのいり"  ],
  ["sunrise","日の出","ひので"  ],
  ["echo,sound,reverberation,noise","響き","ひびき"  ],
  ["to resound","響く","ひびく"  ],
  ["skin","皮膚","ひふ"  ],
  ["to cool,to refrigerate","冷やす","ひやす"  ],
  ["encyclopedia","","ひゃっかじてん"  ],
  ["beauty of figure or form","美容","びよう"  ],
  ["front cover,binding","表紙","ひょうし"  ],
  ["sign,mark","標識","ひょうしき"  ],
  ["standard,level","標準","ひょうじゅん"  ],
  ["example,specimen","標本","ひょうほん"  ],
  ["criticism,critique","評論","ひょうろん"  ],
  ["hiragana,47 syllables,the cursive syllabary","平仮名","ひらがな"  ],
  ["building","","ビルディング"  ],
  ["nap (at home),siesta","昼寝","ひるね"  ],
  ["to spread,to extend,to expand,to enlarge","広げる","ひろげる"  ],
  ["extent","広さ","ひろさ"  ],
  ["plaza","広場","ひろば"  ],
  ["extensive,spacious","広々","ひろびろ"  ],
  ["to broaden,to propagate","広める","ひろめる"  ],
  ["pink","","ピンク"  ],
  ["writing paper,stationery","便箋","びんせん"  ],
  ["bottling,bottled","瓶詰","びんづめ"  ],
  ["fastener,zipper","","ファスナー"  ],
  ["balloon","風船","ふうせん"  ],
  ["unlucky,misfortune,bad luck,fate","不運","ふうん"  ],
  ["to increase,to multiply","殖える","ふえる"  ],
  ["to deepen,to heighten,to intensify","深まる","ふかまる"  ],
  ["irregularity,unsteadiness,disorderly","不規則","ふきそく"  ],
  ["diffusion,spread","普及","ふきゅう"  ],
  ["neighbourhood,vicinity,environs","付近","ふきん"  ],
  ["to wipe,to dry","拭く","ふく"  ],
  ["adverb","副詞","ふくし"  ],
  ["copy,duplicate","複写","ふくしゃ"  ],
  ["plural,multiple","複数","ふくすう"  ],
  ["to include,to instruct,to make one understand","含める","ふくめる"  ],
  ["to swell,to expand,to inflate,to bulge","膨らます","ふくらます"  ],
  ["to expand,to swell (out),to get big,to become inflated","膨らむ","ふくらむ"  ],
  ["unclean,dirty,filthy,impure","不潔","ふけつ"  ],
  ["to get late,to advance,to wear on","更ける","ふける"  ],
  ["sign,mark,symbol","符号","ふごう"  ],
  ["man and wife,married couple","夫妻","ふさい"  ],
  ["to be plugged up,to be shut up","塞がる","ふさがる"  ],
  ["to stop up,to close up,to block (up)","塞ぐ","ふさぐ"  ],
  ["to romp,to gambol,to frolic,to joke","","ふざける"  ],
  ["neglecting to stay in contact","無沙汰","ぶさた"  ],
  ["warrior,samurai","武士","ぶし"  ],
  ["radical (of a kanji character)","部首","ぶしゅ"  ],
  ["sliding screen","襖","ふすま"  ],
  ["attached,belonging,affiliated","附属","ふぞく"  ],
  ["cover,lid,cap","蓋","ふた"  ],
  ["suspension,interruption,stoppage,tie-up,cessation","不通","ふつう"  ],
  ["to strike,to collide with","","ぶつかる"  ],
  ["to knock,to run into,to nail on,to strike hard,to hit and attack","","ぶつける"  ],
  ["dangerous,disturbed,insecure","物騒","ぶっそう"  ],
  ["grumbling,complaining in a small voice","","ぶつぶつ"  ],
  ["surface mail (ship)","船便","ふなびん"  ],
  ["parts,accessories","部品","ぶひん"  ],
  ["snow storm","吹雪","ふぶき"  ],
  ["father and mother,parents","父母","ふぼ"  ],
  ["railway crossing,level crossing,starting line,scratch,crossover","踏切","ふみきり"  ],
  ["the foot,the bottom,the base (of a mountain)","麓","ふもと"  ],
  ["to increase,to add to,to augment","増やす","ふやす"  ],
  ["to increase,to add to,to augment","殖やす","ふやす"  ],
  ["fry pan,frying pan","","フライパン"  ],
  ["blouse","","ブラウス"  ],
  ["to hang,to suspend,to dangle,to swing","","ぶらさげる"  ],
  ["brushy,brush","","ブラシ"  ],
  ["plastic","","プラスチック"  ],
  ["platform","","プラットホーム"  ],
  ["free","","フリー"  ],
  [",pronunciation key","振り仮名","ふりがな"  ],
  ["print,handout","","プリント"  ],
  ["to behave,to conduct oneself,to entertain (vt)","振舞う","ふるまう"  ],
  ["brooch","","ブローチ"  ],
  ["program","","プログラム"  ],
  ["wrapping cloth,cloth wrapper","風呂敷","ふろしき"  ],
  ["light,soft","","ふわふわ"  ],
  ["eruption","噴火","ふんか"  ],
  ["analysis,disassembly","分解","ぶんかい"  ],
  ["literature,art and literature,belles-lettres","文芸","ぶんげい"  ],
  ["literature,books (reference)","文献","ぶんけん"  ],
  ["water fountain","噴水","ふんすい"  ],
  ["fraction (in math)","分数","ぶんすう"  ],
  ["literary style","文体","ぶんたい"  ],
  ["distribution","分布","ぶんぷ"  ],
  ["stationery","文房具","ぶんぼうぐ"  ],
  ["context","文脈","ぶんみゃく"  ],
  ["amount,quantity","分量","ぶんりょう"  ],
  ["classification","分類","ぶんるい"  ],
  ["closure","閉会","へいかい"  ],
  ["coolness,calmness,composure,unconcern","平気","へいき"  ],
  ["(going) side by side,concurrent,abreast,at the same time","並行","へいこう"  ],
  ["weekday,ordinary days","平日","へいじつ"  ],
  ["soldier,sailor","兵隊","へいたい"  ],
  ["common,commonplace,ordinary,mediocre","平凡","へいぼん"  ],
  ["plain,open field","平野","へいや"  ],
  ["to be dented,to be indented,to yield to,to give,to sink,to collapse,to cave in,to be snubbed","凹む","へこむ"  ],
  ["navel,belly-button","","へそ"  ],
  ["to be shut out","隔てる","へだてる"  ],
  ["holiday house,villa","別荘","べっそう"  ],
  ["separately,individually","別々","べつべつ"  ],
  ["veteran","","ベテラン"  ],
  ["helicopter","","ヘリコプター"  ],
  ["to decrease (in size or number),to diminish,to abate","","へる"  ],
  ["pen","","ぺん"  ],
  ["editing,compilation,editorial (e.g. committee)","編集","へんしゅう"  ],
  ["toilet,lavatory,rest room,latrine,comfort station","便所","べんじょ"  ],
  ["(abbr) pliers (lit: pinchers)","","ペンチ"  ],
  ["telescope","望遠鏡","ぼうえんきょう"  ],
  ["direction,way,compass point","方角","ほうがく"  ],
  ["(n) broom","箒","ほうき"  ],
  ["dialect","方言","ほうげん"  ],
  ["Buddhist priest,monk","坊さん","ぼうさん"  ],
  ["prevention,check","防止","ぼうし"  ],
  ["objective,plan,policy","方針","ほうしん"  ],
  ["packing,wrapping","包装","ほうそう"  ],
  ["law,rule","法則","ほうそく"  ],
  ["bandage,dressing","包帯","ほうたい"  ],
  ["huge,bulky,enormous,extensive,swelling,expansion","膨大","ぼうだい"  ],
  ["kitchen knife,carving knife","庖丁","ほうちょう"  ],
  ["equation","方程式","ほうていしき"  ],
  ["prevention of crime","防犯","ぼうはん"  ],
  ["direction,district,field (e.g., of study)","方面","ほうめん"  ],
  ["boy","坊や","ぼうや"  ],
  ["to let go","放る","ほうる"  ],
  ["bonus","","ボーナス"  ],
  ["brightness,cheerfulness,melodious","朗らか","ほがらか"  ],
  ["(1) farm (livestock),(2) pasture land,meadow,grazing land","牧場","ぼくじょう"  ],
  ["stock-farming","牧畜","ぼくちく"  ],
  ["health preservation,hygiene,sanitation","保健","ほけん"  ],
  ["recruiting,taking applications","募集","ぼしゅう"  ],
  ["to air,to dry,to desiccate,to drain (off),to drink up","干す","ほす"  ],
  ["poster","","ポスター"  ],
  ["North Pole","北極","ほっきょく"  ],
  ["son (of others)","坊っちゃん","ぼっちゃん"  ],
  ["to unfasten","","ほどく"  ],
  ["moat,canal","堀","ほり"  ],
  ["to dig,to excavate","掘る","ほる"  ],
  ["to carve,to engrave,to sculpture,to chisel","彫る","ほる"  ],
  ["rag,scrap,tattered clothes,fault (esp. in a pretense)","","ぼろ"  ],
  ["Lantern Festival,Festival of the Dead,tray","盆","ぼん"  ],
  ["basin (e.g. between mountains)","盆地","ぼんち"  ],
  ["headquarters","本部","ほんぶ"  ],
  ["essentially,naturally,by nature","本来","ほんらい"  ],
  ["so-so","","まあまあ"  ],
  ["the number of flat things","枚数","まいすう"  ],
  ["each time,common service-sector greeting","毎度","まいど"  ],
  ["minus","","マイナス"  ],
  ["to wind,to coil,to roll","巻く","まく"  ],
  ["to sow (seeds)","蒔く","まく"  ],
  ["to scatter,to sprinkle,to sow","撒く","まく"  ],
  ["pillow,bolster","枕","まくら"  ],
  ["to bend,to crook,to lean","曲げる","まげる"  ],
  ["confused","","まごまご"  ],
  ["friction,rubbing,rubdown,chafe","摩擦","まさつ"  ],
  ["to be mixed,to be blended with,to associate with,to mingle with,to join","混ざる","まざる"  ],
  ["to be mixed,to be blended with,to associate with,to mingle with,to join","交ざる","まざる"  ],
  ["to be mixed,to be blended with,to associate with","混じる","まじる"  ],
  ["to be mixed,to be blended with,to associate with","交じる","まじる"  ],
  ["mask","","マスク"  ],
  ["to mix,to stir","混ぜる","まぜる"  ],
  ["to be mixed,to be blended with","交ぜる","まぜる"  ],
  ["to straddle","","またぐ"  ],
  ["or,otherwise","又は","または"  ],
  ["waiting room","待合室","まちあいしつ"  ],
  ["to rendezvous,to meet at a prearranged place and time","待ち合わせる","まちあわせる"  ],
  ["street corner","街角","まちかど"  ],
  ["total darkness,shortsightedness,pitch dark","真っ暗","まっくら"  ],
  ["pitch black","真っ黒","まっくろ"  ],
  ["deep blue,ghastly pale","真っ青","まっさお"  ],
  ["the head,the foremost,beginning","真っ先","まっさき"  ],
  ["pure white","真っ白","まっしろ"  ],
  ["to deify,to enshrine","祭る","まつる"  ],
  ["ticket window","窓口","まどぐち"  ],
  ["to be collected,to be settled,to be in order","纏まる","まとまる"  ],
  ["to put in order,to collect,to bring to a conclusion","纏める","まとめる"  ],
  ["to mimic,to imitate","真似る","まねる"  ],
  ["dazzling,radiant","","まぶしい"  ],
  ["eyelids","","まぶた"  ],
  ["muffler,scarf","","マフラー"  ],
  ["soon,before long,in a short time","間も無く","まもなく"  ],
  ["marathon","","マラソン"  ],
  ["round,circular,spherical","円い","まるい"  ],
  ["rare,seldom","稀","まれ"  ],
  ["detour","回り道","まわりみち"  ],
  ["full house,no vacancy,sold out","満員","まんいん"  ],
  ["large apartment,apartment house","","マンション"  ],
  ["perfect score","満点","まんてん"  ],
  ["(1) to see off,to farewell,(2) to escort,(3) to let pass","見送る","みおくる"  ],
  ["to overlook,to command a view of,to look down on something","見下ろす","みおろす"  ],
  ["outward appearance","見掛け","みかけ"  ],
  ["new moon,crescent moon","三日月","みかづき"  ],
  ["cape (on coast)","岬","みさき"  ],
  ["(arch) sad,pitiful,wretched","","みじめ"  ],
  ["sewing machine","","ミシン"  ],
  ["store,shop","店屋","みせや"  ],
  ["heading,caption,subtitle,index","見出し","みだし"  ],
  ["itinerary,route","道順","みちじゅん"  ],
  ["to be found,to be discovered","見付かる","みつかる"  ],
  ["to be familiar,to discover,to detect","見付ける","みつける"  ],
  ["shameful,indecent","","みっともない"  ],
  ["to look again,to get a better opinion of","見直す","みなおす"  ],
  ["to become used to seeing,to be familiar with","見慣れる","みなれる"  ],
  ["ugly","醜い","みにくい"  ],
  ["to bear fruit,to ripen","実る","みのる"  ],
  ["social position,social status","身分","みぶん"  ],
  ["sample","見本","みほん"  ],
  ["to ask after (health),to visit","見舞う","みまう"  ],
  ["less than,insufficient","未満","みまん"  ],
  ["surname,family name","名字","みょうじ"  ],
  ["milli-,10^-3","ミリ","（メートル）"  ],
  ["to examine (medical)","診る","みる"  ],
  ["private,civilian,civil,popular,folk,unofficial","民間","みんかん"  ],
  ["folk song,popular song","民謡","みんよう"  ],
  ["(v5u) to face,to go towards","向う","むかう"  ],
  ["to peel,to skin,to pare,to hull","剥く","むく"  ],
  ["infinite","無限","むげん"  ],
  ["plain,unfigured","無地","むじ"  ],
  ["humid,sultry","蒸し暑い","むしあつい"  ],
  ["contradiction,inconsistency","矛盾","むじゅん"  ],
  ["to steam,to poultice,to be sultry","蒸す","むす"  ],
  ["countless number,infinite number","無数","むすう"  ],
  ["purple colour,violet","紫","むらさき"  ],
  ["group,crowd,flock,herd","群れ","むれ"  ],
  ["niece","姪","めい"  ],
  ["masterpiece","名作","めいさく"  ],
  ["business card","名刺","めいし"  ],
  ["noun","名詞","めいし"  ],
  ["famous place","名所","めいしょ"  ],
  ["to command,to appoint","命ずる","めいずる"  ],
  ["superstition","迷信","めいしん"  ],
  ["famous product,special product,speciality","名物","めいぶつ"  ],
  ["each,individual","銘々","めいめい"  ],
  ["superior(s),senior","目上","めうえ"  ],
  ["meter (clock)","","メーター"  ],
  ["to be blessed with,to be rich in","恵まれる","めぐまれる"  ],
  ["to go around","巡る","めぐる"  ],
  ["to aim at,to have an eye on","目指す","めざす"  ],
  ["(abbr) alarm-clock","目覚し","めざまし"  ],
  ["at present,now","目下","めした"  ],
  ["mark,sign,landmark","目印","めじるし"  ],
  ["to be conspicuous,to stand out","目立つ","めだつ"  ],
  ["absurd,unreasonable,excessive,messed up,spoiled,wreaked","","めちゃくちゃ"  ],
  ["remarkably","","めっきり"  ],
  ["happy,simple soul,propitious,joyous","","めでたい"  ],
  ["menu","","メニュー"  ],
  ["dizziness,giddiness","","めまい"  ],
  ["criterion,aim","目安","めやす"  ],
  ["tax exemption,duty exemption","免税","めんぜい"  ],
  ["area","面積","めんせき"  ],
  ["interview","面接","めんせつ"  ],
  ["bother to do,tiresome","面倒臭い","めんどうくさい"  ],
  ["to be profitable,to yield a profit","儲かる","もうかる"  ],
  ["to get,to earn,to gain,to have (bear, beget) a child","儲ける","もうける"  ],
  ["inexcusable","申し訳ない","もうしわけない"  ],
  ["motor","","モーター"  ],
  ["lumber,timber,wood","木材","もくざい"  ],
  ["table of contents","目次","もくじ"  ],
  ["(1) to drive,to pass through,(2) to evade,to hide,(3) to dive (into or under water),to go undergroun","潜る","もぐる"  ],
  ["perhaps,maybe,by some chance","","もしかしたら"  ],
  ["perhaps,maybe,by some chance","","もしかすると"  ],
  ["to lean against,to lean on,to recline on,to lie heavy (on the stomach)","","もたれる"  ],
  ["modern","","モダン"  ],
  ["sticky rice cake","餅","もち"  ],
  ["too good,more than one deserves,wasteful,sacrilegious,unworthy of","","もったいない"  ],
  ["model","","モデル"  ],
  ["originally,by nature,from the start","元々","もともと"  ],
  ["storage room","物置","ものおき"  ],
  ["to tell,to indicate","物語る","ものがたる"  ],
  ["ruler,measure","物差し","ものさし"  ],
  ["earth-shattering,staggering,to a very great extent","物凄い","ものすごい"  ],
  ["monorail","","モノレール"  ],
  ["(1) (Japanese) maple","紅葉","もみじ"  ],
  ["to rub,to crumple (up),to wrinkle","揉む","もむ"  ],
  ["to burn","燃やす","もやす"  ],
  ["event,festivities,function","催し","もよおし"  ],
  ["(1) to serve (food, etc.),(2) to fill up,(3) to prescribe","盛る","もる"  ],
  ["questions and answers,dialogue","問答","もんどう"  ],
  ["(1) noisy,(2) strict,fussy","","やかましい"  ],
  ["at night,nighttime","夜間","やかん"  ],
  ["kettle","薬缶","やかん"  ],
  ["actor,actress","役者","やくしゃ"  ],
  ["government office,public office","役所","やくしょ"  ],
  ["to translate","訳す","やくす"  ],
  ["government official","役人","やくにん"  ],
  ["medicine(s),chemical(s)","薬品","やくひん"  ],
  ["duty,business","役目","やくめ"  ],
  ["burn,scald","火傷","やけど"  ],
  ["walking around at night,night train,night travel","夜行","やこう"  ],
  ["directing arrow","矢印","やじるし"  ],
  ["randomly,recklessly,blindly","","やたらに"  ],
  ["pharmacy,drugstore","薬局","やっきょく"  ],
  ["to attack (an enemy),to beat,to do away with,to finish off","","やっつける"  ],
  ["landlord","家主","やぬし"  ],
  ["also,as I thought,still,in spite of,absolutely,of course","","やっぱり"  ],
  ["","破く","やぶく"  ],
  ["to get torn,to wear out","破れる","やぶれる"  ],
  ["cannot be helped,unavoidable","","やむをえない"  ],
  ["soft,tender,limp","軟らかい","やわらかい"  ],
  ["amusement park","遊園地","ゆうえんち"  ],
  ["evening paper","夕刊","ゆうかん"  ],
  ["friendship","友好","ゆうこう"  ],
  ["mailing","郵送","ゆうそう"  ],
  ["(sudden) evening shower (rain)","夕立","ゆうだち"  ],
  ["(in) the evening sun,setting sun","夕日","ゆうひ"  ],
  ["quiet,calm,leisurely","悠々","ゆうゆう"  ],
  ["admission-paid,toll","有料","ゆうりょう"  ],
  ["bathrobe,informal summer kimono,yukata","浴衣","ゆかた"  ],
  ["steam,vapour","湯気","ゆげ"  ],
  ["blood transfusion","輸血","ゆけつ"  ],
  ["transport,transportation","輸送","ゆそう"  ],
  ["negligence,unpreparedness","油断","ゆだん"  ],
  ["to boil","","ゆでる"  ],
  ["teacup","湯飲み","ゆのみ"  ],
  ["loose,lenient,slow","緩い","ゆるい"  ],
  ["lava","溶岩","ようがん"  ],
  ["container,vessel","容器","ようき"  ],
  ["term,terminology","用語","ようご"  ],
  ["gist,essentials,summary,fundamentals","要旨","ようし"  ],
  ["infant,baby,child","幼児","ようじ"  ],
  ["capacity,volume","容積","ようせき"  ],
  ["infancy,childish,infantile","幼稚","ようち"  ],
  ["kindergarten","幼稚園","ようちえん"  ],
  ["use,usefulness","用途","ようと"  ],
  ["shop which handles Western-style apparel and accessories","洋品店","ようひんてん"  ],
  ["nourishment,nutrient","養分","ようぶん"  ],
  ["wool","羊毛","ようもう"  ],
  ["gradually,finally,hardly","漸く","ようやく"  ],
  ["point,gist,essentials,outline","要領","ようりょう"  ],
  ["avarice,covetousness,greed","欲張り","よくばり"  ],
  ["too much,unnecessary,abundance,surplus,excess,superfluity","余計","よけい"  ],
  ["(1) to send,to forward,(2) to hand over (e.g. money)","","よこす"  ],
  ["(1) to disgrace,to dishonour,(2) to pollute,to contaminate,to soil,to make dirty,to stain","汚す","よごす"  ],
  ["to collect,to gather,to add,to put aside","寄せる","よせる"  ],
  ["another place,somewhere else,strange parts","余所","よそ"  ],
  ["four corners,crossroads","四つ角","よつかど"  ],
  ["drunkard","酔っ払い","よっぱらい"  ],
  ["preparation,preliminaries,reserve,spare","予備","よび"  ],
  ["to call out to,to accost,to address (crowd),to appeal","呼び掛ける","よびかける"  ],
  ["to summon,to call (e.g. phone)","呼び出す","よびだす"  ],
  ["to be resurrected,to be revived,to be resuscitated,to be rehabilitated","蘇る","よみがえる"  ],
  ["to come from","因る","よる"  ],
  ["(n) (a) joy,(a) delight,rapture,pleasure,gratification,rejoicing,congratulations,felicitations","慶び","よろこび"  ],
  ["","慶ぶ","よろこぶ"  ],
  ["arrival in Japan,coming to Japan,visit to Japan","来日","らいにち"  ],
  ["failure,dropping out of a class","落第","らくだい"  ],
  ["rush hour","","ラッシュアワー"  ],
  ["column of text (e.g. as in a newspaper)","欄","らん"  ],
  ["launch,lunch","","ランチ"  ],
  ["(1) running,(2) tank top","","ランニング"  ],
  ["rude,violent,rough,lawless,unreasonable,reckless","乱暴","らんぼう"  ],
  ["science","理科","りか"  ],
  ["advantages and disadvantages,interest","利害","りがい"  ],
  ["rhythm","","リズム"  ],
  ["litre","","リットル"  ],
  ["ribbon","","リボン"  ],
  ["to abbreviate","略す","りゃくす"  ],
  ["(river) basin","流域","りゅういき"  ],
  ["hostel,dormitory","寮","りょう"  ],
  ["both sides","両側","りょうがわ"  ],
  ["fisherman","漁師","りょうし"  ],
  ["consul","領事","りょうじ"  ],
  ["receipt,voucher","領収","りょうしゅう"  ],
  ["temporary,special,extraordinary","臨時","りんじ"  ],
  ["care-taking,caretaker,house-watching","留守番","るすばん"  ],
  ["exception","例外","れいがい"  ],
  ["zero,no marks","零点","れいてん"  ],
  ["freezing,cold storage,refrigeration","冷凍","れいとう"  ],
  ["raincoat","","レインコート"  ],
  ["recreation","","レクリェーション"  ],
  ["leisure","","レジャー"  ],
  ["chain of islands","列島","れっとう"  ],
  ["level","","レベル"  ],
  ["report,paper","","リポート"  ],
  ["brick","煉瓦","れんが"  ],
  ["union,alliance","連合","れんごう"  ],
  ["lens","","レンズ"  ],
  ["candle","蝋燭","ろうそく"  ],
  ["romanization,Roman letters","","ローマじ"  ],
  ["(audio) recording","録音","ろくおん"  ],
  ["locker","","ロッカー"  ],
  ["lobby","","ロビー"  ],
  ["to argue,to discuss,to debate","論ずる","ろんずる"  ],
  ["Japanese-English","和英","わえい"  ],
  ["to be understood","分る","わかる"  ],
  ["to branch off,to diverge from,to fork,to split,to dispense,to scatter,to divide into","分かれる","わかれる"  ],
  ["youthful,young","若々しい","わかわかしい"  ],
  ["to boil,to grow hot,to get excited,to gush forth","湧く","わく"  ],
  ["to apologize","詫びる","わびる"  ],
  ["Japanese clothes","和服","わふく"  ],
  ["comparatively","","わりあいに"  ],
  ["division (math)","割算","わりざん"  ],
  ["relatively, comparitively","割と","わりと"  ],
  ["discount,reduction,rebate","割引","わりびき"  ],
  ["Japanese soup bowl,wooden bowl","椀","わん"  ],
  ["bowl","碗","わん"  ],
  ["one-piece dress","","ワンピース"  ]
];

module.exports = jlpten2;