var jlptfr2 = [
  ["à l'envers","さかさま","逆様"  ],
  ["à l'envers, inversé, sens dessus dessous","さかさ","逆さ"  ],
  ["à l'inverse, au contraire","かえって","却って"  ],
  ["à l'origine, au départ, par nature","ほんらい","本来"  ],
  ["à l'origine, depuis le départ, par nature","もともと","元々"  ],
  ["à mi-chemin, au milieu","ちゅうと","中途"  ],
  ["à nouveau, une nouvelle fois","あらためて","改めて"  ],
  ["à tour de rôle, l'un après l'autre","じゅんじゅん","順々"  ],
  ["à tout à l'heure (se dit en partant et en ayant l'intention de revenir)","いってきます","行って来ます"  ],
  ["à tout prix, coûte que coûte","ぜひとも","是非とも"  ],
  ["abandonner, laisser à l'abandon, ne pas s'occuper, lancer [五段] [vt]","ほうる","放る"  ],
  ["abréger, omettre","りゃくする","略する"  ],
  ["abréger, omettre [五段] [vt]","りゃくす","略す"  ],
  ["abstrait","ちゅうしょう","抽象"  ],
  ["absurde, insensé, peu méthodique, au hasard","でたらめ","出鱈目"  ],
  ["absurde, ridicule, illogique","めちゃくちゃ","目茶苦茶"  ],
  ["accélération","かそく","加速"  ],
  ["accélération","かそくど","加速度"  ],
  ["accent [accent (en)]","アクセント",""  ],
  ["accessoire, pièces détachées","ぶひん","部品"  ],
  ["accident, erreur, bourde","かしつ","過失"  ],
  ["accidenté, rude, escarpé, inaccessible, aiguisé (pour le regard ou la parole)","けわしい","険しい"  ],
  ["accomplir, faire [五段] [vt]","なす","為す"  ],
  ["accomplissement, résultats actuels","じっせき","実績"  ],
  ["accoster (quelqu'un), engager la conversation, adresser la parole à quelqu'un [一段] [vt]","はなしかける","話し掛ける"  ],
  ["accrocher quelque chose, suspendre, attraper, enfiler en vitesse (des vêtements) [一段] [vt]","ひっかける","引っ掛ける"  ],
  ["accrocher, suspendre [五段]","つる","吊る"  ],
  ["accrocher, suspendre [五段] [vt]","つるす","吊るす"  ],
  ["accueillir une personne, recevoir quelqu'un [一段] [vt]","でむかえる","出迎える"  ],
  ["accumuler, empiler, entasser, charger (un véhicule) [五段]","つむ","積む"  ],
  ["accumuler, empiler, répéter une action [一段] [vt]","かさねる","重ねる"  ],
  ["acide, aigre","すっぱい","酸っぱい"  ],
  ["acidité","さんせい","酸性"  ],
  ["acquiescer [五段] [vi]","うなずく","頷く・肯く"  ],
  ["acte, action","しょい","所為"  ],
  ["acteur, actrice","やくしゃ","役者"  ],
  ["action, comportement, manière","どうさ","動作"  ],
  ["activité, effort","かつやく","活躍"  ],
  ["actuel, présent [préfixe]","げん","現"  ],
  ["adapter, faire correspondre [一段] [vt]","あてはめる","当てはめる"  ],
  ["adhérer à, coller à, rester proche de [五段]","くっつく","くっ付く"  ],
  ["adieux","そうべつ","送別"  ],
  ["adjectif","けいようし","形容詞"  ],
  ["adjectif nominal, adjectif en -na","けいようどうし","形容動詞"  ],
  ["administration du personnel","じんじ","人事"  ],
  ["adopter (une mesure, une proposition), cueillir (un fruit), attraper (un insecte), prélever (un échantillon) [五段] [vt]","とる","採る"  ],
  ["adresse et nom du destinataire","あてな","宛名"  ],
  ["adresse, habitation, résidence, maison","じゅうきょ","住居"  ],
  ["adverbe","ふくし","副詞"  ],
  ["aérien, imaginaire","かくう","架空"  ],
  ["affaire de goût","すきずき","好き好き"  ],
  ["affaire publique, affaire officielle","こうむ","公務"  ],
  ["affiche, poster [poster (en)]","ポスター",""  ],
  ["affirmation, positif","こうてい","肯定"  ],
  ["âge mûr, âge moyen","ちゅうねん","中年"  ],
  ["agrandissement","ぞうだい","増大"  ],
  ["agréable, confortable, plaisant","きらく","気楽"  ],
  ["aide, assistance, appui, renfort","おうえん","応援"  ],
  ["aimant","じしゃく","磁石"  ],
  ["air conditionné, climatiseur [cooler (en)]","クーラー",""  ],
  ["air, ciel","くうちゅう","空中"  ],
  ["aire géograpique, zone","ちたい","地帯"  ],
  ["aire, étendue","めんせき","面積"  ],
  ["ajout","ついか","追加"  ],
  ["ajouter","ついかする","追加する"  ],
  ["ajustement, consolidation, aménagement","せいび","整備"  ],
  ["alcôve traditionnelle où sont disposées des fleurs","とこのま","床の間"  ],
  ["aller au travail, aller travailler","しゅっきんする","出勤する"  ],
  ["aller au travail, se rendre au travail","つうきんする","通勤する"  ],
  ["aller simple","かたみち","片道"  ],
  ["aller-retour","おうふく","往復"  ],
  ["allez, viens ! Par ici !","さあ",""  ],
  ["alliance, union","れんごう","連合"  ],
  ["allocation, répartition, quota","わりあて","割り当て・割当"  ],
  ["alternance, changement, remplacement","こうたい","交替"  ],
  ["altitude, hauteur","こうど","高度"  ],
  ["amateur, débutant, inexpérimenté, novice","しろうと","素人"  ],
  ["ambigu, peu précis, vague","あいまい","曖昧"  ],
  ["Amérique du Sud","なんべい","南米"  ],
  ["ami proche, ami intime","なかよし","仲良し"  ],
  ["amitié","ゆうこう","友好"  ],
  ["ampoule électrique","でんきゅう","電球"  ],
  ["amusement, divertissement, distraction","ごらく","娯楽"  ],
  ["analyse, démontage, désassemblage","ぶんかい","分解"  ],
  ["ancêtre","せんぞ","先祖"  ],
  ["ancêtre","そせん","祖先"  ],
  ["anglais-japonais (un dictionnaire par exemple)","えいわ","英和"  ],
  ["angle","かくど","角度"  ],
  ["angle droit","ちょっかく","直角"  ],
  ["année (fiscale, scolaire…)","ねんど","年度"  ],
  ["année scolaire","がくねん","学年"  ],
  ["annonce officielle, proclamation","こうひょう","公表"  ],
  ["annonce, notification","つうち","通知"  ],
  ["annoncer officiellement, proclamer","こうひょうする","公表する"  ],
  ["annulaire","くすりゆび","薬指"  ],
  ["annulation d'un cours","きゅうこう","休講"  ],
  ["annuler [五段] [vt]","とりけす","取り消す"  ],
  ["antenne [antenna (en)]","アンテナ",""  ],
  ["apparaître dans (un registre, un annuaire, un dictionnaire...), figurer dans la liste de [五段] [vi]","のる","載る"  ],
  ["apparence extérieure","みかけ","見掛け"  ],
  ["appartenir à, être affilié à, faire partie de","ぞくする","属する"  ],
  ["appartenir à, être rattaché à, être lié à, être associé à","ふぞくする","付属する"  ],
  ["appeler quelqu'un, faire appeler, convoquer [五段] [vt]","よびだす","呼び出す"  ],
  ["appeler, s'adresser (à la foule), faire appel [一段] [vt]","よびかける","呼び掛ける"  ],
  ["application, utilisation, mise en pratique","おうよう","応用"  ],
  ["appliquer (une règle) [五段]","あてはまる","当てはまる"  ],
  ["appréciation (d'un art par exemple), sens de l'esthétisme","かんしょう","鑑賞"  ],
  ["apprendre par soi-même","じしゅうする","自習する"  ],
  ["approbation, adoption (d'une loi, d'un texte….)","かけつ","可決"  ],
  ["approcher quelque chose, rapproche quelque chose [一段] [vt]","ちかづける","近づける"  ],
  ["approcher, se mettre sur le côté, rassembler, collecter [一段] [vt]","よせる","寄せる"  ],
  ["approprié, adéquat","だとう","妥当"  ],
  ["approximation, critère, but, niveau","めやす","目安"  ],
  ["après quoi, dorénavant","いご","以後"  ],
  ["après tout, de toute manière, en tout cas","どうせ",""  ],
  ["après, passé [suffixe]","すぎ","過ぎ"  ],
  ["arbre énorme","たいぼく","大木"  ],
  ["arbuste, arbre","うえき","植木"  ],
  ["arc-en-ciel","にじ","虹"  ],
  ["archipel","れっとう","列島"  ],
  ["ardemment, chaleureusement, de bon cœur","しみじみ","泌み泌み"  ],
  ["argent de poche","こづかい","小遣い"  ],
  ["arme à feu, pistolet, fusil","てっぽう","鉄砲"  ],
  ["arracher, enlever, détacher, peler [五段] [vt]","はがす","剥がす"  ],
  ["arrêt (d'un train, d'un véhicule…)","ていしゃ","停車"  ],
  ["arrêt, fin","しゅうりょう","終了"  ],
  ["arrêter de fumer","きんえんする","禁煙する"  ],
  ["arrêter, freiner, réprimer, retenir [一段] [vt]","おさえる","抑える・押さえる"  ],
  ["arridité, sécheresse, assèchement, déshydratation","かんそう","乾燥"  ],
  ["arrière, dos, soutien [back (en)]","バック",""  ],
  ["arrivée à [suffixe]","ちゃく","着"  ],
  ["arrivée au Japon, venue au Japon","らいにち","来日"  ],
  ["arriver (quelque part)","とうちゃくする","到着する"  ],
  ["arrondi au chiffre supérieur","ししゃごにゅう","四捨五入"  ],
  ["arrondissement, district","ぐん","郡"  ],
  ["arrondissement, district [suffixe]","く","区"  ],
  ["art culinaire, cuisine","すいじ","炊事"  ],
  ["art du spectacle, divertissement","げいのう","芸能"  ],
  ["articles indispensables, articles de première nécessité","ひつじゅひん","必需品"  ],
  ["artificiel, synthétique","じんぞう","人造"  ],
  ["artisan, travailleur","しょくにん","職人"  ],
  ["arts et lettres, belles-lettres, littérature","ぶんげい","文芸"  ],
  ["ascension, montée, train qui part en direction d'une métropole","のぼり","上り"  ],
  ["aspirer à, languir de quelque chose [一段] [vi]","あこがれる","憧れる"  ],
  ["assaisonnement","ちょうみりょう","調味料"  ],
  ["assembler, construire [一段] [vt]","くみたてる","組み立てる"  ],
  ["assembler, coudre [五段] [vt]","あむ","編む"  ],
  ["asseyez-vous s'il vous plait, veuillez vous asseoir s'il vous plait","おかけください","お掛け下さい"  ],
  ["attacher, adhérer, coller, accompagner, s'allumer (pour la lumière), avoir de la chance [五段] [vi]","つく","付く"  ],
  ["attacher, lier [五段] [vt]","しばる","縛る"  ],
  ["attacher, lier, connecter, transférer (un appel téléphonique) [一段] [vt]","つなげる","繋げる"  ],
  ["attaquer, assaillir [一段] [vt]","せめる","攻める"  ],
  ["attitude, posture","しせい","姿勢"  ],
  ["attraper, prendre, capturer [五段] [vt]","とる","捕る・獲る"  ],
  ["au moins","すくなくとも","少なくとも"  ],
  ["au moyen de, avec, étant donné que, vu que","もって","以って"  ],
  ["aube","あけがた","明け方"  ],
  ["augmenter, ajouter à, accroître [五段] [vt]","ふやす","増やす・殖やす"  ],
  ["augmenter, élever, accroître, améliorer [一段] [vt]","たかめる","高める"  ],
  ["augmenter, se multiplier [一段] [vi]","ふえる","殖える"  ],
  ["auriculaire","こゆび","小指"  ],
  ["autant que possible","かぎり","限り"  ],
  ["auteur","さくしゃ","作者"  ],
  ["auto-défense","じえい","自衛"  ],
  ["autogouverné, autonome","じち","自治"  ],
  ["automatiquement, de soi-même","ひとりでに","一人でに"  ],
  ["automatisation [automation (en)]","オートメーション",""  ],
  ["autorité de, le droit de faire [suffixe]","けん","権"  ],
  ["autorités, bureau gouvernemental","かんちょう","官庁"  ],
  ["avancé, de haute qualité","こうど","高度"  ],
  ["avant de s'en rendre compte, inaperçu","いつのまにか","何時の間にか"  ],
  ["avant et après, devant et derrière, environ, à peu près","ぜんご","前後"  ],
  ["avant-garde, pionner, premier","せんとう","先頭"  ],
  ["avant, ce côté","てまえ","手前"  ],
  ["avantages et inconvénients, points forts et points faibles, long et court","ちょうたん","長短"  ],
  ["avarice","よくばり","欲張り"  ],
  ["avec imprudence, aveuglément","やたらに","矢鱈に"  ],
  ["avec peine, tout juste","ようやく","漸く"  ],
  ["avoir besoin de, exiger, réclamer","ようする","要する"  ],
  ["avoir conscience","いしきする","意識する"  ],
  ["avoir des connaissances approfondies sur, être bien renseigné sur [一段] [vt]","こころえる","心得る"  ],
  ["avoir la sensation de [suffixe]","ぎみ","気味"  ],
  ["avoir le bienfait de, être béni par [一段] [vi]","めぐまれる","恵まれる"  ],
  ["avoir pour but, avoir un œil sur [五段] [vt]","めざす","目指す"  ],
  ["avoir un enfant, gagner de l'argent, obtenir [一段] [vt]","もうける","儲ける"  ],
  ["bague","ゆびわ","指輪"  ],
  ["baillement","あくび","欠伸"  ],
  ["bain de mer","かいすいよく","海水浴"  ],
  ["baisser, s'abaisser, se dégrader, se détériorer","ていかする","低下する"  ],
  ["balance, bascule (pour mesurer un poid)","はかり","秤"  ],
  ["balayage, nettoyage","そうじ","掃除"  ],
  ["balayer, brosser [五段] [vt]","はく","掃く"  ],
  ["ballon (de baudruche)","ふうせん","風船"  ],
  ["bambou","たけ","竹"  ],
  ["banquet, festin, fête","えんかい","宴会"  ],
  ["bar, café","さかば","酒場"  ],
  ["barrage, muet, idiot [dam, dumb (en)]","ダム",""  ],
  ["bas (fine et longue chaussette portée par les femmes) [stockings (en)]","ストッキング",""  ],
  ["bas, petit, peu élevé [préfixe]","てい","低"  ],
  ["base","きち","基地"  ],
  ["base, critère, référence, norme, standard","きじゅん","基準・規準"  ],
  ["bassin (géographique), vallée","ぼんち","盆地"  ],
  ["bassin fluvial","りゅういき","流域"  ],
  ["bâtiment scolaire","こうしゃ","校舎"  ],
  ["bâtiment universitaire","だいがくいん","大学院"  ],
  ["battement de cœur rapide, pulsation","どきどき",""  ],
  ["batterie, pile, batterie sèche","かんでんち","乾電池"  ],
  ["battre, attaquer, terminer, finir [一段] [vt]","やっつける","遣っ付ける"  ],
  ["beau temps","かいせい","快晴"  ],
  ["beaucoup, plusieurs [préfixe]","しょ","諸"  ],
  ["beaucoup, une grande quantité","うんと",""  ],
  ["béton [concrete (en)]","コンクリート",""  ],
  ["bidon, gourde","すいとう","水筒"  ],
  ["bien fait, clair, ordonné","すっきり",""  ],
  ["bienfait, faveur, bénédiction, grâce","おんけい","恩恵"  ],
  ["bientôt, sous peu","ちかぢか","近々"  ],
  ["bientôt, sous peu","まもなく","間もなく"  ],
  ["billet de banque, papier monnaie","しへい","紙幣"  ],
  ["biographie","でんき","伝記"  ],
  ["blanc","しろ","白"  ],
  ["blanc immaculé","まっしろ","真っ白"  ],
  ["blanc immaculé","まっしろい","真っ白い"  ],
  ["blême, livide, bleu foncé","まっさお","真っ青"  ],
  ["blême, pâle","あおじろい","青白い"  ],
  ["blessure","けが","怪我"  ],
  ["bleu marine","こん","紺"  ],
  ["bois de construction","もくざい","木材"  ],
  ["bois de construction","ざいもく","材木"  ],
  ["bois, petite forêt","はやし","林"  ],
  ["boîte aux lettres, courrier, poste de travail [post (en)]","ポスト",""  ],
  ["boîte de conserve, cannette","かんづめ","缶詰"  ],
  ["bol en porcelaine","わん","碗"  ],
  ["bol en porcelaine, bol de riz avec de la garniture au dessus","どんぶり","丼"  ],
  ["bol japonais pour la soupe","わん","椀"  ],
  ["bol, pot, bassine, pot de fleur","はち","鉢"  ],
  ["bondé, plein, complet","まんいん","満員"  ],
  ["bonne, femme de ménage, femme de chambre","おてつだいさん","お手伝いさん"  ],
  ["bonus [bonus (en)]","ボーナス",""  ],
  ["boucher, emplir, enfouir, enterrer [一段] [vt]","うめる","埋める"  ],
  ["boucher, encombrer, obstruer, occuper [五段] [vt]","ふさぐ","塞ぐ"  ],
  ["bouger d'un lieu à un autre, se déplacer","てんてんする","転々する"  ],
  ["bougie, cierge","ろうそく","蝋燭"  ],
  ["bouillir, cuisiner [一段] [vt]","にる","煮る"  ],
  ["bouilloire","やかん","薬缶"  ],
  ["boulier","そろばん","算盤"  ],
  ["bout (d'une rue, d'un chemin...)","つきあたり","突き当たり"  ],
  ["boutique de, magasin de [suffixe]","や","屋・家"  ],
  ["boutique, lieu de vente, échoppe, stand","ばいてん","売店"  ],
  ["boutique, magasin","しょうてん","商店"  ],
  ["briller [五段] [vi]","てる","照る"  ],
  ["briller, frapper [五段]","さす","射す"  ],
  ["brique","れんが","煉瓦"  ],
  ["briser, fracasser [五段] [vt]","くだく","砕く"  ],
  ["broche [brooch (en)]","ブローチ",""  ],
  ["brosse [brush (en)]","ブラシ",""  ],
  ["brouillon","したがき","下書き"  ],
  ["bruits parasites","ざつおん","雑音"  ],
  ["brûler [五段] [vt]","もやす","燃やす"  ],
  ["brûler, carboniser [一段] [vi]","こげる","焦げる"  ],
  ["brûler, carboniser [五段] [vt]","こがす","焦がす"  ],
  ["brûlure","やけど","火傷"  ],
  ["brusquement, soudainement","いきなり","行成"  ],
  ["brutal, violent","あらい","荒い"  ],
  ["bruyant, agité","さわがしい","騒がしい"  ],
  ["bruyant, turbulent","そうぞうしい","騒々しい"  ],
  ["bruyant, turbulent, stric, pointilleux","やかましい","喧しい"  ],
  ["bureau des, service des, département des [suffixe]","きょく","局"  ],
  ["bureau gouvernemental [suffixe]","ちょう","庁"  ],
  ["bureau préfectoral","けんちょう","県庁"  ],
  ["business, travail, occupation [suffixe]","ぎょう","業"  ],
  ["c'est inévitable, on n'y peut rien","しかたがない","仕方がない"  ],
  ["cadavre","したい","死体"  ],
  ["cadet (à l'école, au travail…), nouveau (en parlant d'une personne)","こうはい","後輩"  ],
  ["cadet, le plus jeune enfant","すえっこ","末っ子"  ],
  ["cadran, composer (un numéro) [dial (en)]","ダイヤル",""  ],
  ["calcul, arithmétique","さんすう","算数"  ],
  ["calligraphie","しょどう","書道"  ],
  ["calligraphie","しゅうじ","習字"  ],
  ["calme, cool, indifférent","へいき","平気"  ],
  ["calmement, tranquillement, de manière détendue","ゆうゆうと","悠々と"  ],
  ["calorie [calorie (en)]","カロリー",""  ],
  ["campus","こうてい","校庭"  ],
  ["campus universitaire [campus (en)]","キャンパス",""  ],
  ["capable de, avoir tendance à [suffixe]","がち","勝ち"  ],
  ["capacité (d'un moyen de transport, d'un lieu), nombre de places","ていいん","定員"  ],
  ["capacité, contenance, volume","ようせき","容積"  ],
  ["capacité, volume","たいせき","体積"  ],
  ["capturer, attraper, arrêter, saisir, percevoir [一段] [vt]","とらえる","捕える"  ],
  ["caractère, qualité, génie","そしつ","素質"  ],
  ["caractères d'imprimerie","かつじ","活字"  ],
  ["caractéristique, particularité, endroit coloré","とくしょく","特色"  ],
  ["caresser, brosser doucement [一段] [vt]","なでる","撫でる"  ],
  ["cargaison, marchandise","かもつ","貨物"  ],
  ["carnet de note, certificat","てちょう","手帳"  ],
  ["carnet de tickets","かいすうけん","回数券"  ],
  ["carré","しかく","四角"  ],
  ["carré","しかくい","四角い"  ],
  ["carré","せいほうけい","正方形"  ],
  ["carré de tissu noué par les coins","ふろしき","風呂敷"  ],
  ["carrefour, croisement, intersection","こうさてん","交差点"  ],
  ["carrefour, quatre coins","よつかど","四つ角"  ],
  ["carte d'abonnement","ていきけん","定期券"  ],
  ["carte de visite","めいし","名刺"  ],
  ["cartes à jouer, jeu de cartes","かるた","歌留多"  ],
  ["caserne de pompiers","しょうぼうしょ","消防署"  ],
  ["cassette [cassette (en)]","カセット",""  ],
  ["ce qui est souligné","かせん","下線"  ],
  ["cèdre japonais","すぎ","杉"  ],
  ["cela me dit quelque chose, cela me parle","こころあたりがある","心当たりがある"  ],
  ["célèbre, éminent, admirable","えらい","偉い"  ],
  ["célèbre, réputé, formidable [préfixe]","めい","名"  ],
  ["centimètre [centi (en)]","センチ",""  ],
  ["centre administratif, bureau administratif","やくしょ","役所"  ],
  ["centre-ville","としん","都心"  ],
  ["céramique, porcelaine","せともの","瀬戸物"  ],
  ["cercle","まる","円"  ],
  ["cercle [circle (en)]","サークル",""  ],
  ["cérémonie, rite, rituel","ぎしき","儀式"  ],
  ["certainement, sûrement, sans l'ombre d'un doute","てっきり",""  ],
  ["cerveau","ずのう","頭脳"  ],
  ["chacun, chacune","かくじ","各自"  ],
  ["chacun, individuellement","めいめい","銘々"  ],
  ["chambre à louer","かしま","貸間"  ],
  ["chance, occasion, prétexte","きっかけ","切っ掛け"  ],
  ["change (argent)","かわせ","為替"  ],
  ["changer de vêtement [一段]","きがえる","着替える"  ],
  ["chanson populaire","みんよう","民謡"  ],
  ["chanson pour enfants","どうよう","童謡"  ],
  ["chanson, ballade","かよう","歌謡"  ],
  ["chantier, travaux (lié à de la construction)","こうじ","工事"  ],
  ["chaque [préfixe]","かく","各"  ],
  ["chaque [suffixe]","ごと","毎"  ],
  ["chaque jour, quotidiennement","ひび","日々"  ],
  ["charpentier","だいく","大工"  ],
  ["chat","ねこ","猫"  ],
  ["chaud et humide","むしあつい","蒸し暑い"  ],
  ["chaudron, marmite","かま","釜"  ],
  ["chauffage","かねつ","加熱"  ],
  ["chauffer","ねっする","熱する"  ],
  ["chef d'œuvre","めいさく","名作"  ],
  ["chef-d'œuvre","けっさく","傑作"  ],
  ["chef, directeur [suffixe]","ちょう","長"  ],
  ["chemin de fer privé","してつ","私鉄"  ],
  ["chemin, passage","つうろ","通路"  ],
  ["chemin, route","しんろ","進路"  ],
  ["cheminée","えんとつ","煙突"  ],
  ["chemise de nuit, pyjama","ねまき","寝巻"  ],
  ["chemisier [blouse (en)]","ブラウス",""  ],
  ["chercher, enquêter, examiner [五段] [vt]","さぐる","探る"  ],
  ["cheveux","かみ","髪"  ],
  ["cheveux blancs, cheveux gris","しらが","白髪"  ],
  ["chewing-gum [gum (en)]","ガム",""  ],
  ["chiffon, tissu utilisé pour le ménage","ぞうきん","雑巾"  ],
  ["chiffons, haillons, vêtements usés, défaut","ぼろ","藍褸"  ],
  ["chinois-japonais (comme un dictionnaire par exemple)","かんわ","漢和"  ],
  ["chirurgie","げか","外科"  ],
  ["chœur de chanteurs, chorale [chorus (en)]","コーラス",""  ],
  ["choyer, gâter un enfant [五段] [vt]","あまやかす","甘やかす"  ],
  ["chuchoter [五段] [vi]","ささやく","囁く"  ],
  ["chute d'eau, cascade","たき","滝"  ],
  ["cible, but, visée","ねらい","狙い"  ],
  ["ciel, atmosphère","くう","空"  ],
  ["cieux, firmament","おおぞら","大空"  ],
  ["cime, sommet, point culminant","ちょうてん","頂点"  ],
  ["ciment [cement (en)]","セメント",""  ],
  ["circonférence","えんしゅう","円周"  ],
  ["circonférence, environs, périphérie, périphériques informatiques","しゅうへん","周辺"  ],
  ["circulation piétonne","ひとどおり","人通り"  ],
  ["circulation, rotation, cycle","じゅんかん","循環"  ],
  ["clair, pur, limpide","きよい","清い"  ],
  ["clairement, avec lucidité, de façon efficace","はきはき",""  ],
  ["classification","ぶんるい","分類"  ],
  ["classique (la littérature par exemple), vieux livres","こてん","古典"  ],
  ["climatisation, air conditionné","れいぼう","冷房"  ],
  ["cloche","すず","鈴"  ],
  ["cloche, carillon","かね","鐘"  ],
  ["clôturer, fermer, condamner (une porte, une ouverture) [五段] [vt]","しめきる","締め切る"  ],
  ["clou","くぎ","釘"  ],
  ["cœur, centre, mèche, mine (de crayon), agrafe","しん","芯"  ],
  ["coin de la rue","まちかど","街角"  ],
  ["collecte d'argent","しゅうきん","集金"  ],
  ["collection [collection (en)]","コレクション",""  ],
  ["coller, attacher, fixer, étendre, étirer [五段]","はる","貼る"  ],
  ["coller, fixer, adhérer [一段]","くっつける","くっ付ける"  ],
  ["collier [necklace (en)]","ネックレス",""  ],
  ["colonne de journal, champ (dans un formulaire, une page web…)","らん","欄"  ],
  ["colonne, ligne, verset","ぎょう","行"  ],
  ["combat de sumo","すもう","相撲"  ],
  ["combinaison","くみあわせ","組み合わせ"  ],
  ["combinaison, union, fusion, mélange","ごうどう","合同"  ],
  ["combiné téléphonique","じゅわき","受話器"  ],
  ["commander, donner un ordre","ちゅうもんする","注文する"  ],
  ["comme d'habitude, comme toujours","あいかわらず","相変わらず"  ],
  ["comme on pouvait s'y attendre","さすが","流石"  ],
  ["comme prévu, vraiment, comme on l'attendait","はたして","果たして"  ],
  ["comme-ci comme-ça, moyen, interjection utilisée pour calmer quelqu'un","まあまあ",""  ],
  ["comme, similaire à, ressemblant à [suffixe]","みたい",""  ],
  ["commerce, boutique, magasin [shop (en)]","ショップ",""  ],
  ["commerce, business","しょうぎょう","商業"  ],
  ["commode","たんす","箪笥"  ],
  ["commun, ordinaire, quelconque, médiocre","へいぼん","平凡"  ],
  ["commun, public","こうきょう","公共"  ],
  ["communication [communication (en)]","コミュニケーション",""  ],
  ["communisme, parti communiste","きょうさん","共産"  ],
  ["comparativement","わりあいに","割合に"  ],
  ["comparativement","ひかくてき","比較的"  ],
  ["comparer, illustrer avec un exemple, utiliser une comparaison [一段] [vt]","たとえる","例える"  ],
  ["compenser, compléter [五段]","おぎなう","補う"  ],
  ["compilation (de textes), édition, livre, volume","へん","編"  ],
  ["complet, entier, total [préfixe]","そう","総"  ],
  ["complètement, entièrement","すっかり",""  ],
  ["comprendre","りかいする","理解する"  ],
  ["compression","あっしゅく","圧縮"  ],
  ["compteur (d'eau, de gaz par exemple), mètre [meter (en)]","メーター",""  ],
  ["compteur pour les articles, individuel [suffixe]","こ","個"  ],
  ["compteur pour les coup de feux [suffixe]","はつ","発"  ],
  ["compteur pour les documents, les lettres [suffixe]","つう","通"  ],
  ["compteur pour les gorgées [suffixe]","くち","口"  ],
  ["compteur pour les grands animaux [suffixe]","とう","頭"  ],
  ["compteur pour les lapins et les oiseaux [suffixe]","わ","羽"  ],
  ["compteur pour les nuits d'un séjour [suffixe]","はく","泊"  ],
  ["compteur pour les pas [suffixe]","ほ","歩"  ],
  ["compteur pour les personnes (notamment pour les réservation, les nombres de place…) (hon) [suffixe]","めい","名"  ],
  ["compteur pour les questions (dans un test, un examen…) [suffixe]","だい","題"  ],
  ["compteur pour les tatamis (unité de mesure de longueur) [suffixe]","じょう","畳"  ],
  ["compteur pour les vêtements [suffixe]","ちゃく","着"  ],
  ["conception, inspiration, idée","はっそう","発想"  ],
  ["conclusion, décision","だんてい","断定"  ],
  ["concours [concours (fr)]","コンクール",""  ],
  ["conducteur de train","しゃしょう","車掌"  ],
  ["confiance en soi","じしん","自信"  ],
  ["confirmer","かくにんする","確認する"  ],
  ["confrontation, opposition","たいりつ","対立"  ],
  ["congélation","れいとう","冷凍"  ],
  ["connaissance (en parlant d'une personne)","ごぞんじ","ご存知"  ],
  ["connaissance (en parlant d'une personne), ami","ちじん","知人"  ],
  ["connaissance (personne)","しりあい","知り合い"  ],
  ["connexion, lien, relation","つながり","繋がり"  ],
  ["connexion, union, liaison, lien","せつぞく","接続"  ],
  ["conservation, stockage, réserve","ちょぞう","貯蔵"  ],
  ["consigne automatique, casier [locker (en)]","ロッカー",""  ],
  ["consolidation, unification, uniformité","とういつ","統一"  ],
  ["constamment, sans cesse","たえず","絶えず"  ],
  ["consul","りょうじ","領事"  ],
  ["contagion","でんせん","伝染"  ],
  ["conte de fées, conte pour enfants","どうわ","童話"  ],
  ["contenu, substance, intérieur","なかみ","中身・中味"  ],
  ["contexte","ぶんみゃく","文脈"  ],
  ["continuation","けいぞく","継続"  ],
  ["contraste, antithèse, comparaison","たいしょう","対照"  ],
  ["contre toute attente, inattendu","あんがい","案外"  ],
  ["contre-mesure","たいさく","対策"  ],
  ["contre, versus","たい","対"  ],
  ["contribution, lettre envoyée à un journal","とうしょ","投書"  ],
  ["contrôle des billets","かいさつ","改札"  ],
  ["convenance, orientation, pertinence, aspect","むき","向き"  ],
  ["copie, reproduction, duplicata","ふくしゃ","複写"  ],
  ["copier, imiter, prendre modèle sur [五段] [vi]","ならう","倣う"  ],
  ["coquillage","かい","貝"  ],
  ["coquille, cosse, coque","から","殻"  ],
  ["corde","つな","綱"  ],
  ["corps enseignant, équipe pédagogique","きょういん","教員"  ],
  ["corps et âme","しんしん","心身"  ],
  ["corps solide, état solide","こたい","固体"  ],
  ["correspondance (de train, d'avion…)","のりかえ","乗り換え"  ],
  ["costume, tailleur [suit (en)]","スーツ",""  ],
  ["côté de [suffixe]","がわ","側"  ],
  ["coucher du soleil","ひのいり","日の入り"  ],
  ["coude","ひじ","肘"  ],
  ["coudre [五段] [vt]","ぬう","縫う"  ],
  ["couleur [colour (en)]","カラー",""  ],
  ["couloir","ろうか","廊下"  ],
  ["couper, découper [五段]","ちぎる","千切る"  ],
  ["couper, tailler, aiguiser, réduire, rayer, supprimer [五段] [vt]","けずる","削る・梳る"  ],
  ["couple marié, homme et femme","ふさい","夫妻"  ],
  ["coupure de courant, panne d'électricité","ていでん","停電"  ],
  ["courageux","いさましい","勇ましい"  ],
  ["courant direct","ちょくりゅう","直流"  ],
  ["courant électrique","でんりゅう","電流"  ],
  ["courbe","きょくせん","曲線"  ],
  ["courbe [curve (en)]","カーブ",""  ],
  ["courber, plier [一段] [vt]","まげる","曲げる"  ],
  ["couronne","かんむり","冠"  ],
  ["courrier, lettre, opportunité, chance","びん","便"  ],
  ["cours, parcours [course (en)]","コース",""  ],
  ["course à pied, débardeur []","ランニング",""  ],
  ["course de chevaux","けいば","競馬"  ],
  ["court terme, courte période","たんき","短期"  ],
  ["cousine","いとこ","従姉妹"  ],
  ["coussin","ざぶとん","座布団"  ],
  ["coût, dépense","ひ","費"  ],
  ["coût, prix, valeur","あたい","値"  ],
  ["couteau de cuisine","ほうちょう","庖丁"  ],
  ["coutume, usage","じつよう","実用"  ],
  ["couture","さいほう","裁縫"  ],
  ["couverture (d'un livre), reliure","ひょうし","表紙"  ],
  ["couverture, pochette, couvercle [cover (en)]","カバー",""  ],
  ["couvrir avec quelque chose, verser un liquide, recouvrir [一段] [vt]","かぶせる","被せる"  ],
  ["couvrir les coûts, subvenir aux besoins [五段] [vt]","まかなう","賄う"  ],
  ["craie [chalk (en)]","チョーク",""  ],
  ["cratère volcanique","かこう","火口"  ],
  ["création littéraire, production, travail","そうさく","創作"  ],
  ["crédit (d'argent), prêt","かし","貸し"  ],
  ["creuser, excaver [五段]","ほる","掘る"  ],
  ["creux, vide","からっぽ","空っぽ"  ],
  ["crier, hurler (de colère) [五段] [vi]","どなる","怒鳴る"  ],
  ["critique (d'une œuvre)","ひょうろん","評論"  ],
  ["critiquer, émettre un jugement","ひはんする","批判する"  ],
  ["croire, avoir confiance en, se fier à [一段] [vt]","しんずる","信ずる"  ],
  ["croisement de chemin de fer, passage à niveau, ligne de départ","ふみきり","踏切"  ],
  ["croisement, intersection","こうさ","交差"  ],
  ["croissance, expansion","かくじゅう","拡充"  ],
  ["croquis, esquisse, description","しゃせい","写生"  ],
  ["cuisinier, robinet [kok (nl)]","コック",""  ],
  ["cuisse","もも","腿"  ],
  ["cuivre","どう","銅"  ],
  ["culte, visite d'un temple","おまいり","お参り"  ],
  ["culture du riz, repiquage du riz","たうえ","田植え"  ],
  ["culture, éducation","きょうよう","教養"  ],
  ["cursus scolaire, curriculum","かてい","課程"  ],
  ["d'abord, en premier","まっさき","真っ先"  ],
  ["d'urgence, urgent","しきゅう","至急"  ],
  ["dangereux, peu sûr","ぶっそう","物騒"  ],
  ["dangereux, risqué","あやうい","危うい"  ],
  ["dans ce cas, si c'est le cas","それなら","其れなら"  ],
  ["dans l'ensemble, dans sa totalité, en général","ぜんぱん","全般"  ],
  ["dans tous les cas, de toute façon","なにしろ","何しろ"  ],
  ["dans trois jours","しあさって","明々後日"  ],
  ["dans un instant, soudainement, d'un coup, tout de suite","たちまち","忽ち"  ],
  ["danser, voltiger, tournoyer [五段] [vi]","まう","舞う"  ],
  ["date de naissance","せいねんがっぴ","生年月日"  ],
  ["date et heure","にちじ","日時"  ],
  ["date limite, échéance","きげん","期限"  ],
  ["date, années, jours","つきひ","月日"  ],
  ["davantage","いちだんと","一段と"  ],
  ["davantage, plus","いちだんと","一段と"  ],
  ["de force, par la force","ごういんに","強引に"  ],
  ["de haut niveau, d'un rang élevé","こうきゅう","高級"  ],
  ["de haut rang, du premier ordre, excellent","いちりゅう","一流"  ],
  ["de rang élevé","こうとう","高等"  ],
  ["de style japonais [préfixe]","わ","和"  ],
  ["de taille variée, grand et petit","だいしょう","大小"  ],
  ["de toute façon, dans tous les cas","ともかく","兎も角"  ],
  ["de toute façon, s'il vous plaît (pour insister sur une demande)","なにぶん","何分"  ],
  ["de toutes ses forces, à tout prix, coûte que coûte","おもいきり・おもいっきり","思い切り"  ],
  ["de type, du genre [suffixe]","てき","的"  ],
  ["débarras, resserre, remise","ものおき","物置"  ],
  ["début d'une réunion","かいかい","開会"  ],
  ["début du mois, premier tiers du mois","じょうじゅん","上旬"  ],
  ["débuter une réunion","かいかいする","開会する"  ],
  ["déception amoureuse, cœur brisé, chagrin amoureux","しつれん","失恋"  ],
  ["déchet, détritus","くず","屑"  ],
  ["déchirer, détruire, briser [五段] [vt]","やぶく","破く"  ],
  ["déchirer, lacérer, découper [五段] [vt]","さく","裂く"  ],
  ["décision, jugement","けつだん","決断"  ],
  ["déconcerté, confus","あわただしい","慌しい"  ],
  ["décoration, ornement","かざり","飾り"  ],
  ["découvrir","はっけんする","発見する"  ],
  ["défaut, point faible, imperfection","たんしょ","短所"  ],
  ["défense, sécurité, surveillance","けいび","警備"  ],
  ["défilé, parade, procession, matrice","ぎょうれつ","行列"  ],
  ["déifier, adorer (un culte), vénérer, prier [五段] [vt]","まつる","祭る"  ],
  ["délibérément, à sa guise","かってに","勝手に"  ],
  ["délimiter, fractionner, démarquer, ponctuer [五段] [vt]","くぎる","区切る"  ],
  ["demande de renseignements","といあわせ","問い合わせ"  ],
  ["demande pressante, requête, réclamation, revendication","さいそく","催促"  ],
  ["demander, réquisitionner, faire une requête","ようきゅうする","要求する"  ],
  ["déménagement, emménagement","ひっこし","引っ越し"  ],
  ["déménagement, emménagement","ひっこし","引越し"  ],
  ["démocratie","みんしゅ","民主"  ],
  ["démocratique [préfixe]","みんしゅ","民主"  ],
  ["démonstration, exposition, présentation","はっき","発揮"  ],
  ["dénoué, ample, lent","ゆるい","緩い"  ],
  ["densité, concentration, cardinalité","のうど","濃度"  ],
  ["dentifrice","はみがき","歯磨き"  ],
  ["départ, commencement","はつ","発"  ],
  ["départ, démarrage [start (en)]","スタート",""  ],
  ["département, catégorie, partie, compteur pour les exemplaires (d'un magazine, d'un journal…) [suffixe]","ぶ","部"  ],
  ["département, section [suffixe]","か","科"  ],
  ["dépasser (une voiture, un coureur), distancer [五段] [vt]","おいこす","追い越す"  ],
  ["dépasser [五段] [vi]","あまる","余る"  ],
  ["dépendre de, être basé sur, être dû à, être causé par [五段] [vi]","よる","因る"  ],
  ["déployer, recouvrir, étaler [五段]","しく","敷く"  ],
  ["déposer (de l'argent), verser [五段] [vt]","はらいこむ","払い込む"  ],
  ["déranger, gêner, troubler, empêcher [一段] [vt]","さまたげる","妨げる"  ],
  ["dernier tiers d'un mois","げじゅん","下旬"  ],
  ["dernière (année), hier (soir) [préfixe]","さく","昨"  ],
  ["des choses comme, des trucs tels que [suffixe]","なんて",""  ],
  ["désaccord, contradiction","むじゅん","矛盾"  ],
  ["désastre, calamité","さいなん","災難"  ],
  ["descendant","しそん","子孫"  ],
  ["descendre d'un véhicule","げしゃする","下車する"  ],
  ["descendre, aller en descendant, se rendre, capituler [五段] [vi]","くだる","下る"  ],
  ["descendre, aller vers le bas","かこうする","下降する"  ],
  ["descente (d'un véhicule)","げしゃ","下車"  ],
  ["désigner, pointer du doigt","していする","指定する"  ],
  ["désinfection, stérilisation","しょうどく","消毒"  ],
  ["désolé de vous avoir fait attendre","おまちどうさま","お待ちどうさま"  ],
  ["désolé, pardon","ごめん","御免"  ],
  ["désolé, pardon","すまない","済まない"  ],
  ["désormais, dorénavant, à l'avenir","いこう","以降"  ],
  ["despotisme, autocratie","せんせい","専制"  ],
  ["dessein, moyen, projet","くふう","工夫"  ],
  ["dessin, peinture, esquisse","が","画"  ],
  ["destination, direction","ゆくえ","行方"  ],
  ["destiné à, à destination de, orienté pour [suffixe]","むけ","向け"  ],
  ["destiné à, orienté pour [suffixe]","むき","向き"  ],
  ["détente, pause, repos","きゅうよう","休養"  ],
  ["détergent, lessive","せんざい","洗剤"  ],
  ["détestable, odieux, haïssable","にくい","憎い"  ],
  ["détestable, odieux, haïssable","にくらしい","憎らしい"  ],
  ["détester [五段] [vt]","いやがる","嫌がる"  ],
  ["détour","まわりみち","回り道"  ],
  ["détruire, abattre, faire le change (de monnaie) [五段] [vt]","くずす","崩す"  ],
  ["deux côtés","りょうがわ","両側"  ],
  ["développement, expansion","てんかい","展開"  ],
  ["devenir confus, agité, paniquer [一段] [vi]","あわてる","慌てる"  ],
  ["devenir transparent [五段] [vi]","すきとおる","透き通る"  ],
  ["devise monétaire","つうか","通貨"  ],
  ["diagnostic","しんだん","診断"  ],
  ["diagramme [diagram (en)]","ダイヤグラム",""  ],
  ["diagramme, graphique","ずひょう","図表"  ],
  ["dialecte","ほうげん","方言"  ],
  ["diamant [diamond (en)]","ダイヤモンド",""  ],
  ["diamètre","ちょっけい","直径"  ],
  ["diapositive [slide (en)]","スライド",""  ],
  ["dictée","かきとり","書き取り"  ],
  ["Dieu","かみさま","神様"  ],
  ["différence, variation, divergence","そうい","相違"  ],
  ["différent, varié, divers, contradictoire","まちまち","区々"  ],
  ["difficile à, dur à [suffixe]","にくい","難い"  ],
  ["difficile de (faire quelque chose) [suffixe]","づらい","辛い"  ],
  ["diffuser, propager, étendre [一段] [vt]","ひろめる","広める"  ],
  ["digestion","しょうか","消化"  ],
  ["digne de confiance, fiable, plein d'espoir","たのもしい","頼もしい"  ],
  ["diluer (de la peinture), brouiller (des œufs), dissoudre [五段] [vt]","とく","溶く"  ],
  ["diluer [一段] [vt]","うすめる","薄める"  ],
  ["dimension, mesure","すんぽう","寸法"  ],
  ["diminution, réduction","しゅくしょう","縮小"  ],
  ["direct (en parlant d'un trajet pour un train, un avion…)","ちょくつう","直通"  ],
  ["direct, en personne, immédiatement, tout de suite","じき","直"  ],
  ["directement, tout d'un coup, doucement","すっと",""  ],
  ["direction, côté","ほうがく","方角"  ],
  ["direction, domaine (d'étude par exemple)","ほうめん","方面"  ],
  ["direction, objectif","ほうしん","方針"  ],
  ["disciple, apprenti, élève","でし","弟子"  ],
  ["discours, expression, formulation","ことばづかい","言葉遣い"  ],
  ["discours, parole, remarque","せりふ","台詞"  ],
  ["discussion, débat, théorie, doctrine, dissertation, essai littéraire","ろん","論"  ],
  ["discussion, entretien, conversation","はなしあい","話し合い"  ],
  ["dissolution, séparation","かいさん","解散"  ],
  ["dissoudre, fondre [五段] [vt]","とかす","溶かす"  ],
  ["distance, intervalle, portée","きょり","距離"  ],
  ["distinction de sexe","せいべつ","性別"  ],
  ["distribuer, livrer [五段] [vt]","くばる","配る"  ],
  ["distribution, affectation, répartition","ぶんぷ","分布"  ],
  ["divers endroits","かくち","各地"  ],
  ["divers, diverses choses","あれこれ","彼此"  ],
  ["division (mathématique)","わりざん","割り算・割算"  ],
  ["division en parts égales","とうぶん","等分"  ],
  ["divorcer","りこんする","離婚する"  ],
  ["docile, calme","おとなしい","大人しい"  ],
  ["docile, obéissant, soumis","すなお","素直"  ],
  ["domaine, secteur","くいき","区域"  ],
  ["donnée, matériaux","しりょう","資料"  ],
  ["donner rendez-vous à quelqu'un [一段]","まちあわせる","待ち合わせる"  ],
  ["donner un coup de pied, frapper, refuser, rejeter [五段] [vt]","ける","蹴る"  ],
  ["dortoir, logement en commun","りょう","寮"  ],
  ["douanes","ぜいかん","税関"  ],
  ["double [double (en)]","ダブル",""  ],
  ["doucement, lentement","のろのろ",""  ],
  ["douleur, trouble, anxiété, effort","くしん","苦心"  ],
  ["drap [sheet (en)]","シーツ",""  ],
  ["du début à la fin","しじゅう","始終"  ],
  ["du haut, à la surface [préfixe]","うわ","上"  ],
  ["durant la nuit","やかん","夜間"  ],
  ["durée de vie","じゅみょう","寿命"  ],
  ["eau fraîche","たんすい","淡水"  ],
  ["eau souterraine","ちかすい","地下水"  ],
  ["éblouissant, radieux, éclatant","まぶしい","眩しい"  ],
  ["écart, digression, déraillement","だっせん","脱線"  ],
  ["échange culturel, rapport, interaction","こうりゅう","交流"  ],
  ["échantillon","みほん","見本"  ],
  ["échantillon [sample (en)]","サンプル",""  ],
  ["échantillon, modèle","ひょうほん","標本"  ],
  ["écharpe [scarf (en)]","スカーフ",""  ],
  ["échec à un examen, le fait de laisser tomber un cours","らくだい","落第"  ],
  ["écho, réverbération, bruit","ひびき","響き"  ],
  ["éclat, teint","つや","艶"  ],
  ["école [school (en)]","スクール",""  ],
  ["école de [suffixe]","こう","校"  ],
  ["école maternelle","ようちえん","幼稚園"  ],
  ["économiser (mettre de côté)","ちょきんする","貯金する"  ],
  ["écoulement des eaux, drainage, égout, caniveau","げすい","下水"  ],
  ["écraser, broyer, [五段] [vt]","つぶす","潰す"  ],
  ["écrits divers, rédaction","ずいひつ","随筆"  ],
  ["écriture","しっぴつ","執筆"  ],
  ["écrivain, auteur","ひっしゃ","筆者"  ],
  ["édition du soir (pour un journal)","ゆうかん","夕刊"  ],
  ["édition, compilation","へんしゅう","編集"  ],
  ["éditorial (article de journal)","しゃせつ","社説"  ],
  ["efficacité","のうりつ","能率"  ],
  ["efficacité, effet","こうりょく","効力"  ],
  ["effronté","ずうずうしい","図々しい"  ],
  ["effronté, insolent","あつかましい","厚かましい"  ],
  ["égal à [equal (en)]","イコール",""  ],
  ["eh !, dis donc !","おい",""  ],
  ["élaborer, concevoir, créer, produire","さくせいする","作成する"  ],
  ["élargir, étendre, aggrandir, étaler [一段] [vt]","ひろげる","広げる"  ],
  ["élargissement, augmentation, expansion, extension","かくちょう","拡張"  ],
  ["élégant, bien habillé, coquet","おしゃれ","お洒落"  ],
  ["élégant, chic, stylé [smart (en)]","スマート",""  ],
  ["élégant, distingué, raffiné","じょうひん","上品"  ],
  ["éléments de base, rudiments","しょほ","初歩"  ],
  ["élevage de bétail","ぼくちく","牧畜"  ],
  ["élève d'école primaire","しょうがくせい","小学生"  ],
  ["élever des enfants, s'occuper d'enfants","いくじする","育児する"  ],
  ["ellipse","だえん","楕円"  ],
  ["élongation, extension, prolongation","えんちょう","延長"  ],
  ["éloquent, clair, revigorant, frais, rafraîchissant","さわやか","爽やか"  ],
  ["emballage, empaquetage","ほうそう","包装"  ],
  ["embauche, recrutement","ぼしゅう","募集"  ],
  ["embêtant, ennuyeux, désagréable","めんどうくさい","面倒臭い"  ],
  ["emmagasiner, stocker, garder en réserve [一段] [vt]","たくわえる","蓄える"  ],
  ["émoussé, idiot, stupide, tardif, lent","にぶい","鈍い"  ],
  ["émoussé, idiot, stupide, tardif, lent","のろい","鈍い"  ],
  ["Empereur du Japon","てんのう・すめらぎ","天皇"  ],
  ["emploi du temps, programme","じかんわり","時間割"  ],
  ["employé de banque","こういん","行員"  ],
  ["employé, cadre [salary man (en)]","サラリーマン",""  ],
  ["empreinte de pied","あしあと","足跡"  ],
  ["emprunt, prêt","かしだし","貸し出し"  ],
  ["en bouteille","びんづめ","瓶詰"  ],
  ["en dehors de [suffixe]","がい","外"  ],
  ["en dépit de, malgré","せっかく","折角"  ],
  ["en dessous de [suffixe]","か","下"  ],
  ["en fait, en réalité","げんに","現に"  ],
  ["en général, du début à la fin, ordinaire, courant","ひととおり","一通り"  ],
  ["en gros, approximatif","おおざっぱ","大雑把"  ],
  ["en même temps, simultanément","いっせいに","一斉に"  ],
  ["en outre, de plus","そのうえ","その上"  ],
  ["en plusieurs endroits, ici et là","ところどころ","所々"  ],
  ["en route, à mi-chemin, sur le chemin","とじょう","途上"  ],
  ["en-cas, goûté, quatre-heure","おやつ","お八つ"  ],
  ["encore et encore, à répétition","さいさん","再三"  ],
  ["encore, de nouveau, re- [préfixe]","さい","再"  ],
  ["encre de Chine, encre noire","すみ","墨"  ],
  ["encyclopédie","ひゃっかじてん","百科事典・百科辞典"  ],
  ["endroit, lieu","ちてん","地点"  ],
  ["énergie, vitalité","かつりょく","活力"  ],
  ["enfant","じどう","児童"  ],
  ["enfant, bébé, nourrisson","ようじ","幼児"  ],
  ["enfin","やっと",""  ],
  ["enfouir, plonger dans, s'immiscer dans, interférer [五段]","つっこむ","突っ込む"  ],
  ["enfumé","けむい","煙い"  ],
  ["énigme, devinette, mystère","なぞなぞ","謎々"  ],
  ["enjamber [五段]","またぐ","跨ぐ"  ],
  ["enlever, exclure, omettre [一段] [vt]","どける","退ける"  ],
  ["énorme, gigantesque, étendu, expansion, gonflement","ぼうだい","膨大"  ],
  ["enregistrement audio","ろくおん","録音"  ],
  ["enregistrer, documenter, atteindre un record, atteindre une valeur","きろくする","記録する"  ],
  ["enrouler, rouler [五段] [vt]","まく","巻く"  ],
  ["enseignement, doctrine [suffixe]","きょう","教"  ],
  ["ensemble des syllabes japonaises","ごじゅうおん","五十音"  ],
  ["ensemble, réciproquement, mutuellement","おたがいに","お互いに"  ],
  ["entendre, recevoir (un ordre), réserver (une table) [五段] [vt]","うけたまわる","承る"  ],
  ["entièrement, complètement","のこらず","残らず"  ],
  ["entraînement [training (en)]","トレーニング",""  ],
  ["entraînement, exercice, étude","けいこ","稽古"  ],
  ["entraînement, pratique","じっしゅう","実習"  ],
  ["entrée (dans un dictionnaire par exemple), rubrique","こうもく","項目"  ],
  ["entrée dans une entreprise","にゅうしゃ","入社"  ],
  ["entrée et sortie","でいりぐち","出入り口"  ],
  ["entrée et sortie, débit et crédit, revenus et dépenses","でいり","出入り"  ],
  ["entrepôt","そうこ","倉庫"  ],
  ["entreprendre, s'occuper de, avoir la responsabilité de, garantir, assumer [一段] [vt]","ひきうける","引き受ける"  ],
  ["entrer en collision, se cogner [五段]","ぶつかる","打つかる"  ],
  ["entrer en contact, toucher, connecter","せっする","接する"  ],
  ["entrer en fonction, prendre un poste","しゅうにんする","就任する"  ],
  ["entrer sur scène, apparaître à l'écran","とうじょうする","登場する"  ],
  ["entretien, interview","めんせつ","面接"  ],
  ["envier, jalouser [五段] [vt]","うらやむ","羨む"  ],
  ["envieux, jaloux","うらやましい","羨ましい"  ],
  ["envoyer un message, envoyer un mot [一段] [vt]","ことづける","言付ける"  ],
  ["envoyer, transmettre [五段] [vt]","よこす","寄越す"  ],
  ["éparpiller, disperser, mettre en désordre [五段] [vt]","ちらかす","散らかす"  ],
  ["éparpiller, disperser, répandre, semer (des graines) [五段] [vt]","まく","蒔く・撒く"  ],
  ["éplucher, peler, décortiquer [五段] [vt]","むく","剥く"  ],
  ["épouse (la mienne)","にょうぼう","女房"  ],
  ["épuisement du stock","うりきれ","売り切れ"  ],
  ["épuisement, consommation","しょうこう","消耗"  ],
  ["équateur","せきどう","赤道"  ],
  ["équation","ほうていしき","方程式"  ],
  ["équilibre, balance [balance (en)]","バランス",""  ],
  ["érable, couleurs d'automne","もみじ・こうよう","紅葉"  ],
  ["ère chrétienne","せいれき","西暦"  ],
  ["erreur, méprise","かんちがい","勘違い"  ],
  ["éruption","ふんか","噴火"  ],
  ["essentiel, grandes lignes, points importants","ようりょう","要領"  ],
  ["essuie-main","てぬぐい","手拭い"  ],
  ["essuyer [五段] [vt]","ふく","拭く"  ],
  ["établier, fonder, créer [一段] [vt]","もうける","設ける"  ],
  ["étape, phase","だんかい","段階"  ],
  ["état, situation, circonstances, aspect","ようす","様子"  ],
  ["etc","そのほか","その外"  ],
  ["étendue","ひろさ","広さ"  ],
  ["éternité","えいえん","永遠"  ],
  ["éternuement","くしゃみ","嚏"  ],
  ["étincelant, joyeux","ほがらか","朗らか"  ],
  ["étincelle, scintillement","ぴかぴか",""  ],
  ["étiquette, règles de bienséance, protocole [etiquette (en)]","エチケット",""  ],
  ["étourdi, distrait, imprudent","そそっかしい",""  ],
  ["être à la mode, être populaire, se développer [五段] [vi]","はやる","流行る"  ],
  ["être absorbé par, se passionner pour [五段] [vi]","こる","凝る"  ],
  ["être affectueux avec, aimer [五段]","かわいがる","可愛がる"  ],
  ["être assoupi","いねむりする","居眠りする"  ],
  ["être blessé, subir une douleur [五段]","いたむ","痛む"  ],
  ["être bloqué, être plein [五段] [vi]","つまる","詰まる"  ],
  ["être cabossé, être bosselé, s'effondrer, céder, s'enfoncer [五段]","へこむ","凹む"  ],
  ["être changé, être remplacé [五段] [vi]","かわる","代わる・替わる・換わる"  ],
  ["être coincé dans, être pris entre deux [五段] [vi]","はさまる","挟まる"  ],
  ["être collé, coller [五段] [vi]","ささる","刺さる"  ],
  ["être confus","まごまごする",""  ],
  ["être connecté, être lié, être relié [五段] [vi]","つながる","繋がる"  ],
  ["être convaincu que, avoir l'impression que, imaginer que [五段] [vi]","おもいこむ","思い込む"  ],
  ["être déconnecté, être sorti, entre enlevé [一段] [vi]","はずれる","外れる"  ],
  ["être déterminé, être résolu","けっしんする","決心する"  ],
  ["être empilé, être entassé, se chevaucher [五段] [vi]","かさなる","重なる"  ],
  ["être en charge de, être responsable de","たんとうする","担当する"  ],
  ["être éparpiller, être en désordre [五段] [vi]","ちらかる","散らかる"  ],
  ["être épuisé (un article) [一段] [vi]","うりきれる","売り切れる"  ],
  ["être érigé, être fondé [五段] [vi]","たつ","建つ"  ],
  ["être fier, fanfaronner [五段] [vi]","いばる","威張る"  ],
  ["être fini, être complet, être fait [五段] [vi]","しあがる","仕上がる"  ],
  ["être fini, être terminé, être complètement saoul [五段] [vi]","できあがる","出来上がる"  ],
  ["être furieux, violent, agir violemment [一段] [vi]","あばれる","暴れる"  ],
  ["être habitué à voir quelque chose, être familier avec [一段] [vi]","みなれる","見慣れる"  ],
  ["être incapable de, trouver difficile de, faire plusieurs choses à la fois [一段] [vt]","かねる","兼ねる"  ],
  ["être injuste, être partial, prendre partie pour [五段] [vi]","かたよる","片寄る・偏る"  ],
  ["être inscrit (dans une école, une université)","ざいがくする","在学する"  ],
  ["être le suivant, venir après [五段] [vi]","つぐ","次ぐ"  ],
  ["être lié à, être en rapport avec, être influencé par, être affecté par [五段] [vi]","かかわる","係わる"  ],
  ["être luxuriant, pousser abondamment [五段] [vi]","しげる","茂る"  ],
  ["être mélangé avec, être combiné à, s'associer avec [五段] [vi]","まじる","交じる・混じる"  ],
  ["être mélangé avec, être combiné à, s'associer avec [五段] [vi]","まざる","混ざる・交ざる"  ],
  ["être mouillé, se mouiller [五段] [vi]","しめる","湿る"  ],
  ["être négligent envers, négliger, éviter [五段] [vt]","おこたる","怠る"  ],
  ["être obstrué, être bouché, être encombré, être occupé [五段] [vi]","ふさがる","塞がる"  ],
  ["être orageux, perdre son sang-froid [一段] [vi]","あれる","荒れる"  ],
  ["être photographié [五段] [vi]","うつる","写る"  ],
  ["être plein d'entrain, être plein d'énergie, être impatient [五段]","はりきる","張り切る"  ],
  ["être plein de (connotation négative), être couvert de [suffixe]","だらけ",""  ],
  ["être pris dans, se faire avoir [五段] [vi]","ひっかかる","引っ掛かる"  ],
  ["être profitable [五段] [vi]","もうかる","儲かる"  ],
  ["être rangé, être en ordre [五段] [vi]","ととのう","整う"  ],
  ["être rangé, être mis en ordre, être résolu, être terminé [五段] [vi]","かたづく","片付く"  ],
  ["être ressuscité, être restauré, être ramené, être rappelé [五段] [vi]","よみがえる","蘇る"  ],
  ["être satisfait","まんぞくする","満足する"  ],
  ["être sauvé, être secouru [五段] [vi]","たすかる","助かる"  ],
  ["être séparé [一段] [vt]","へだてる","隔てる"  ],
  ["être stupéfait, ébahi [一段] [vi]","あきれる","呆れる"  ],
  ["être suffisant, suffire, être assez [五段] [vi]","たる","足る"  ],
  ["être surchargé avec, porter sur son dos ou ses épaules [五段] [vt]","しょう","背負う"  ],
  ["être tous présents, devenir complet, être égal, rassembler [五段] [vi]","そろう","揃う"  ],
  ["être valide, être en cours, circuler","つうようする","通用する"  ],
  ["être, se trouver [五段] [vi]","ござる","御座る"  ],
  ["étudiant de … année [suffixe]","ねんせい","年生"  ],
  ["étudier","がくしゅうする","学習する"  ],
  ["Europe et Etats-Unis, l'Occident","おうべい","欧米"  ],
  ["évaporation, disparition inexpliquée","じょうはつ","蒸発"  ],
  ["évènement, festivité, rencontre sociale","もよおし","催し"  ],
  ["évènement, fonction","ぎょうじ","行事"  ],
  ["éventail","せんす","扇子"  ],
  ["éventer, battre [五段] [vt]","あおぐ","扇ぐ"  ],
  ["évident, banal, normal","あたりまえ","当たり前"  ],
  ["examiner (médical) [一段] [vt]","みる","診る"  ],
  ["exception","れいがい","例外"  ],
  ["exceptionnel","かくべつ","格別"  ],
  ["excès","かじょう","過剰"  ],
  ["excès, surplus","ちょうか","超過"  ],
  ["excursion d'une journée","ひがえり","日帰り"  ],
  ["excuse, prétexte","こうじつ","口実"  ],
  ["excusez-moi de partir avant vous","おさきに","お先に"  ],
  ["excusez-moi de vous déranger, expression utilisée en entrant dans la maison de quelqu'un d'autre","おじゃまします","お邪魔します"  ],
  ["exemple, cas, usage","れい・ためし","例"  ],
  ["exemple, illustration","じつれい","実例"  ],
  ["exemption de taxe, exonération de douane","めんぜい","免税"  ],
  ["existence","せいぞん","生存"  ],
  ["explication, commentaire","かいせつ","解説"  ],
  ["expression qui indique un effort, ho ! hisse !","よいしょ",""  ],
  ["exprime l'envie de quelqu'un d'autre [suffixe]","がる",""  ],
  ["extêmement, beaucoup","ごく","極"  ],
  ["extérieur (l')","がいぶ","外部"  ],
  ["extérieur, en plein air, dehors","おくがい","屋外"  ],
  ["externe, extérieur","がいぶ","外部"  ],
  ["extra, additionnel, de plus [suffixe]","まし","増し"  ],
  ["extraire, retirer, faire sortir [五段] [vt]","ひきだす","引き出す"  ],
  ["extrême, excessif, terrible, intense, sévère, grave","はなはだしい","甚だしい"  ],
  ["face, façade","しょうめん","正面"  ],
  ["facile, simple","あんい","安易"  ],
  ["façon, manière, apparence [suffixe]","ふり","振り"  ],
  ["faire attention","きをつける","気を付ける"  ],
  ["faire bouillir [一段] [vt]","ゆでる","茹でる"  ],
  ["faire bouillir, cuire, cuisiner [五段] [vt]","たく","炊く"  ],
  ["faire cuire à la vapeur [五段] [vt]","むす","蒸す"  ],
  ["faire du tourisme","かんこうする","観光する"  ],
  ["faire flotter, montrer (des sentiments), avoir l'air (triste, heureux) [一段] [vt]","うかべる","浮かべる"  ],
  ["faire griller, rôtir, faire frire [五段] [vt]","いる","煎る・炒る"  ],
  ["faire la grasse matinée, se lever tard","ねぼうする","寝坊する"  ],
  ["faire le change","りょうがえする","両替する"  ],
  ["faire ses condoléances, regretter, se lamenter sur, se repentir [五段] [vt]","くやむ","悔やむ"  ],
  ["faire ses études à l'étranger","りゅうがくする","留学する"  ],
  ["faire sonner, tinter, renifler bruyamment [五段] [vt]","ならす","鳴らす"  ],
  ["faire une copie propre","せいしょする","清書する"  ],
  ["faire, fabriquer [一段] [vt]","こしらえる","拵える"  ],
  ["famine","ききん","飢饉"  ],
  ["femme [woman (en)]","ウーマン",""  ],
  ["femme, personne de sexe féminin","おんなのひと","女の人"  ],
  ["ferme, énergique","つよき","強気"  ],
  ["ferme, ranch, prairie, pâturage","ぼくじょう","牧場"  ],
  ["fermement, complètement, entièrement","ぎっしり",""  ],
  ["fermeture (d'un magasin ou d'une entreprise)","きゅうぎょう","休業"  ],
  ["fermeture éclair [fastener (en)]","ファスナー",""  ],
  ["fermeture, dernier délai, fin, fermé","しめきり","締め切り"  ],
  ["fête bouddhique des morts, fête des lanternes","ぼん","盆"  ],
  ["feux d'artifices","はなび","花火"  ],
  ["fierté","とくい","得意"  ],
  ["figure","ずけい","図形"  ],
  ["fil de fer","はりがね","針金"  ],
  ["filet, toile","あみ","網"  ],
  ["fille ainée","ちょうじょ","長女"  ],
  ["fils (de quelqu'un d'autre)","ぼっちゃん","坊ちゃん"  ],
  ["fils aîné","ちょうなん","長男"  ],
  ["fin (d'une réunion, d'un évènement, d'une cérémonie)","へいかい","閉会"  ],
  ["fin de mois","げつまつ","月末"  ],
  ["fin, terminaison, pièce de théâtre Noh","しまい","仕舞"  ],
  ["finalement, au dernier moment","いよいよ","愈々"  ],
  ["fissure, fente","すきま","隙間"  ],
  ["fixé, déterminé","いってい","一定"  ],
  ["flânant, marchant sans but","うろうろ",""  ],
  ["flèche de direction","やじるし","矢印"  ],
  ["flotter [五段] [vi]","うく","浮く"  ],
  ["flotter, faire surface, venir à l'esprit [五段]","うかぶ","浮かぶ"  ],
  ["fonction, rôle","やくめ","役目"  ],
  ["fonctionnaire","やくにん","役人"  ],
  ["fondation, base","きばん","基盤"  ],
  ["fondation, base","きそ","基礎"  ],
  ["fondre, dissoudre, fusionner [一段] [vi]","とける","溶ける"  ],
  ["fontaine","ふんすい","噴水"  ],
  ["force, très autoritaire, agressif","ごういん","強引"  ],
  ["forêt","もり","森"  ],
  ["forêts et montagnes, forêt de montagne","さんりん","山林"  ],
  ["forêts, bois","しんりん","森林"  ],
  ["formation, apprentissage","けんしゅう","研修"  ],
  ["formation, création","せいりつ","成立"  ],
  ["forme","じょう","状"  ],
  ["forme, apparence, formalité, style, système, méthode, expression mathématique","けいしき","形式"  ],
  ["forme, temps (grammatical) [suffixe]","けい","形"  ],
  ["formule scientifique, formalité, officiel","こうしき","公式"  ],
  ["fort, puissant, vigoureux","ちからづよい","力強い"  ],
  ["forte émotion, impression, inspiration","かんげき","感激"  ],
  ["fourni avec, incluant, attaché à [suffixe]","つき","付き"  ],
  ["fourrure, peau","けがわ","毛皮"  ],
  ["fraction (mathématique)","ぶんすう","分数"  ],
  ["fragment, morceau, éclat","はへん","破片"  ],
  ["frais de port, affranchissement","そうりょう","送料"  ],
  ["franchise, candeur, sincérité","そっちょく","率直"  ],
  ["frapper fort, clouer, rentrer dans [一段] [vt]","ぶつける","打付ける"  ],
  ["frapper, taper [五段] [vt]","なぐる","殴る"  ],
  ["fréquence, nombre de fois","かいすう","回数"  ],
  ["fréquenter quelqu'un, accompagner quelqu'un, être d'accord avec quelqu'un [五段] [vi]","つきあう","付き合う"  ],
  ["friction, frottement","まさつ","摩擦"  ],
  ["friser (en parlant des cheveux) [一段] [vi]","ちぢれる","縮れる"  ],
  ["frontière, limite","きょうかい","境界"  ],
  ["frotter, chiffonner, froisser, masser [五段] [vt]","もむ","揉む"  ],
  ["frotter, gratter [五段] [vt]","こする","擦る"  ],
  ["fruit, noix, baie","かじつ","果実"  ],
  ["funérailles, obsèques","そうしき","葬式"  ],
  ["furigana (petits hiraganas au dessus des kanjis)","ふりがな","振り仮名"  ],
  ["future mariée, jeune mariée","はなよめ","花嫁"  ],
  ["gain et perte, avantage et désavantage","そんとく","損得"  ],
  ["gang, bande [gang (en)]","ギャング",""  ],
  ["garage","しゃこ","車庫"  ],
  ["garantie, assurance, sécurité","ほしょう","保障"  ],
  ["garçon","ぼうや","坊や"  ],
  ["gaz [gas (en)]","ガス",""  ],
  ["geler, être glacé [一段] [vi]","こごえる","凍える"  ],
  ["gêne, obstacle, empêchement","さしつかえ","差し支え"  ],
  ["geta (sandale japonais en bois)","げた","下駄"  ],
  ["glisser [一段] [vi]","ずれる","滑れる"  ],
  ["gomme [gom (nl)]","ゴム",""  ],
  ["gomme à effacer","けしゴム","消しゴム"  ],
  ["goûter [五段] [vt]","あじわう","味わう"  ],
  ["goûts, ce que l'on aime et ce que l'on déteste","すききらい","好き嫌い"  ],
  ["goutte d'eau","すいてき","水滴"  ],
  ["graine, grain","つぶ","粒"  ],
  ["graisse animale, lard","あぶら","脂"  ],
  ["grand [préfixe]","おお","大"  ],
  ["grandes lignes, remarques générales","がいろん","概論"  ],
  ["gratuit, libre [free (en)]","フリー",""  ],
  ["gravement malade, mal en point","じゅうたい","重体"  ],
  ["graver, sculpter, tailler [五段] [vt]","ほる","彫る"  ],
  ["graver, tailler, sculpter, découper, hacher [五段] [vt]","きざむ","刻む"  ],
  ["gravité","いんりょく","引力"  ],
  ["gravité, pensanteur","じゅうりょく","重力"  ],
  ["gravure, sculpture (l'activité et non l'objet)","ちょうこく","彫刻"  ],
  ["griffer, gratter, érafler, transpirer [五段] [vt]","かく","掻く"  ],
  ["gris, cendré","はいいろ","灰色"  ],
  ["grognement, plainte à voix basse","ぶつぶつ",""  ],
  ["grossier, indécent, vulgaire","げひん","下品"  ],
  ["grossièrement, approximativement, en règle générale","おおよそ","大凡"  ],
  ["grossir, enfler, gonfler [五段] [vt]","ふくらます","膨らます"  ],
  ["groupe (de musique) [band (en)]","バンド",""  ],
  ["groupe d'animaux (troupeau, essaim…), groupe, grappe (de fleurs), amas (d'étoiles)","むれ","群"  ],
  ["guerrier, samouraï","ぶし","武士"  ],
  ["guichet","まどぐち","窓口"  ],
  ["gymnastique","たいそう","体操"  ],
  ["habiller quelqu'un, vernir, revêtir, accuser quelqu'un, imputer à [一段]","きせる","着せる"  ],
  ["habitation, maison, résidence, adresse","すまい","住まい"  ],
  ["haie, clôture","かきね","垣根"  ],
  ["haïku, forme poétique japonaise","はいく","俳句"  ],
  ["haïr, détester [五段] [vt]","にくむ","憎む"  ],
  ["hall (d'hôtel, de bâtiment…) [lobby (en)]","ロビー",""  ],
  ["hasard, chance, fortuitement","ぐうぜん","偶然"  ],
  ["haut-parleur [speaker (en)]","スピーカー",""  ],
  ["haut, élevé, supérieur","こうそう","高層"  ],
  ["haut, grand [préfixe]","こう","高"  ],
  ["héberger [一段] [vt]","とめる","泊める"  ],
  ["hélicoptère [helicopter (en)]","ヘリコプター",""  ],
  ["hésiter [五段] [vi]","ためらう","躊躇う"  ],
  ["heure de pointe [rush hour (en)]","ラッシュアワー",""  ],
  ["heureux, joyeux, propice","めでたい","目出度い"  ],
  ["heurter, entrer en collision avec [五段]","つきあたる","突き当たる"  ],
  ["HLM, ensemble d'appartements","だんち","団地"  ],
  ["honteux, indécent","みっともない","見っともない"  ],
  ["hoquet","しゃっくり","吃逆"  ],
  ["horaire, programme [schedule (en)]","スケジュール",""  ],
  ["horizon, ligne horizontale","すいへいせん","水平線"  ],
  ["horizontal","すいへい","水平"  ],
  ["horticulture, jardinage","えんげい","園芸"  ],
  ["hôtel particulier, immeuble résidentiel de standing [mansion (en)]","マンション",""  ],
  ["hôtesse de l'air [stewardess (en)]","スチュワーデス",""  ],
  ["hourra !, félicitations ! Longue vie !","ばんざい","万歳"  ],
  ["huile, pétrole [oil (en)]","オイル",""  ],
  ["humidité","すいぶん","水分"  ],
  ["humidité","しっき","湿気"  ],
  ["humilité, modestie","けんきょ","謙虚"  ],
  ["humilité, modestie","けんそん","謙遜"  ],
  ["hydrogène","すいそ","水素"  ],
  ["hygiène, préservation de la santé","ほけん","保健"  ],
  ["hygiène, santé","えいせい","衛生"  ],
  ["hypothénuse, ligne oblique","しゃへん","斜辺"  ],
  ["hypothèse, supposition","かてい","仮定"  ],
  ["ici et là, petit à petit, éparpillé","てんてん","点々"  ],
  ["idée [idea (en)]","アイデア・アイディア",""  ],
  ["idée, notion, sens (du devoir par exemple), résignation, abandon","かんねん","観念"  ],
  ["idiot, stupide, bête","ばからしい","馬鹿らしい"  ],
  ["idiotisme, expression idiomatique","じゅくご","熟語"  ],
  ["ikebana, arrangement floral","いけばな","生花"  ],
  ["il y a longtemps, déjà","とっくに","疾っくに"  ],
  ["île de [suffixe]","とう","島"  ],
  ["illuminer, éclairer quelque chose [五段] [vt]","てらす","照らす"  ],
  ["image [image (en)]","イメージ",""  ],
  ["imiter, parodier, mimer [一段] [vt]","まねる","真似る"  ],
  ["immédiatement après, juste après","ちょくご","直後"  ],
  ["immédiatement, aussitôt","すぐ","直ぐ"  ],
  ["immédiatement, de suite, sans délai","さっそく","早速"  ],
  ["impatient, sérieux, qui risque sa vie","けんめい","懸命"  ],
  ["imperméable [raincoat (en)]","レーンコート・レインコート",""  ],
  ["impertinent, insolent, audacieux","なまいき","生意気"  ],
  ["imposition, taxation","かぜい","課税"  ],
  ["impressions, pensées","かんそう","感想"  ],
  ["imprimé, polycopié [print (en)]","プリント",""  ],
  ["imprimer [五段] [vt]","する","刷る"  ],
  ["imprudent, insouciant, optimiste, tranquille","のんき","呑気"  ],
  ["inattendu, imprévu, par hasard","おもいがけない","思い掛けない"  ],
  ["incertain, suspicieux, douteux, suspect","あやしい","怪しい"  ],
  ["inclinaison d'un axe, obliquité","ななめ","斜め"  ],
  ["inclure, enseigner quelque chose, faire comprendre [一段] [vt]","ふくめる","含める"  ],
  ["index (doigt)","ひとさしゆび","人差し指"  ],
  ["index, indice","さくいん","索引"  ],
  ["indication, notation, vérification","さいてん","採点"  ],
  ["indirect","かんせつ","間接"  ],
  ["industrie","さんぎょう","産業"  ],
  ["industrie de la pêche","ぎょぎょう","漁業"  ],
  ["inégal (relief du terrain, du sol), rugueux","でこぼこ","凸凹"  ],
  ["inévitable, inéluctable","やむをえない","やむを得ない"  ],
  ["inexcusable","もうしわけない","申し訳ない"  ],
  ["infini","むげん","無限"  ],
  ["influencer, contrôler","さゆうする","左右する"  ],
  ["ingrédient, composant","せいぶん","成分"  ],
  ["innombrable, en grande quantité, indénombrable","むすう","無数"  ],
  ["innovateur, innovant, mémorable","かっきてき","画期的"  ],
  ["inonder, déborder [一段] [vi]","あふれる","溢れる"  ],
  ["inscription, enregistrement (d'une personne), prise de note à l'écrit","かきとめ","書留"  ],
  ["insérer, emboîter, faire rentrer, mettre, faire l'amour [一段] [vt]","はめる","填める"  ],
  ["instrument de musique","がっき","楽器"  ],
  ["instrument, appareil [suffixe]","き","器"  ],
  ["instrument, outil","きぐ","器具"  ],
  ["intensifier, renforcer","きょうかする","強化する"  ],
  ["intérêt (dans quelque chose)","りがい","利害"  ],
  ["interposer, maintenir au milieu [五段] [vt]","はさむ","挟む"  ],
  ["interruption, blocage, suspension","ふつう","不通"  ],
  ["intervalle (de temps)","かんかく","間隔"  ],
  ["intervalle de temps, période de [suffixe]","かん","間"  ],
  ["interview, entretien [interview (en)]","インタビュー",""  ],
  ["introspection, méditation, contemplation, reconsidération","はんせい","反省"  ],
  ["invalide, sans effet","むこう","無効"  ],
  ["ironie, sarcasme","ひにく","皮肉"  ],
  ["irrégulié, désordonnée, instable","ふきそく","不規則"  ],
  ["issue d'une bataille, victoire ou défaite","しょうはい","勝敗"  ],
  ["itinéraire, route","みちじゅん","道順"  ],
  ["ivrogne, saoul","よっぱらい","酔っ払い"  ],
  ["j'ai compris ! Pas de souci !","しめた","占めた"  ],
  ["japonais-anglais (comme un dictionnaire par exemple)","わえい","和英"  ],
  ["jardin","えん・その","園"  ],
  ["je suis reconnaissant de vos efforts, merci pour vos efforts","ごくろうさま","ご苦労様"  ],
  ["je suis vraiment désolé, je m'en excuse profondément","きょうしゅくです","恐縮です"  ],
  ["jeter un coup d'œil, regarder furtivement [五段] [vt]","のぞく","覗く"  ],
  ["jeu du pierre-feuille-ciseaux","じゃんけん","じゃん拳"  ],
  ["jeune","わかわかしい","若々しい"  ],
  ["jeune personne, jeunesse","せいしょうねん","青少年"  ],
  ["jour de congé régulier","ていきゅうび","定休日"  ],
  ["jour de l'An","がんじつ・がんにち","元日"  ],
  ["jour du mois [suffixe]","か","日"  ],
  ["jour férié","しゅくじつ","祝日"  ],
  ["jour férié","さいじつ","祭日"  ],
  ["jour travaillé de la semaine","へいじつ","平日"  ],
  ["journaliste [journalist (en)]","ジャーナリスト",""  ],
  ["jours et nuits, tout le temps","にちや","日夜"  ],
  ["jurer, faire vœu de, prêter serment [五段] [vt]","ちかう","誓う"  ],
  ["jusqu'au bout, obstinément","あくまで","飽くまで"  ],
  ["juste avant","ちょくぜん","直前"  ],
  ["juste devant, juste en face de","まんまえ","真ん前"  ],
  ["juste, seulement","ほんの","本の"  ],
  ["justice, équitabilité, impartialité","こうせい","公正"  ],
  ["kana (syllabaires japonais)","かな","仮名"  ],
  ["Kansai (région Sud-Ouest du Japon vers Osaka et Kyoto)","かんさい","関西"  ],
  ["Kantô (région à l'Est du Japon vers Tôkyô)","かんとう","関東"  ],
  ["koto (harpe japonaise)","こと","琴"  ],
  ["l'actuel, ce [préfixe]","こん","今"  ],
  ["l'original (par opposition à la copie)","じつぶつ","実物"  ],
  ["l'un après l'autre, successivement","ぞくぞく","続々"  ],
  ["la ligne (téléphonique) est occupée, pendant une conversation","はなしちゅう","話中"  ],
  ["la semaine avant-dernière","せんせんしゅう","先々週"  ],
  ["la totalité, tout [suffixe]","ごと","共"  ],
  ["labourer, cultiver [五段] [vt]","たがやす","耕す"  ],
  ["lac de [suffixe]","こ","湖"  ],
  ["lâche, poltron, peureux","ひきょう","卑怯"  ],
  ["laine","ようもう","羊毛"  ],
  ["laine [wool (en)]","ウール",""  ],
  ["laine à tricoter","けいと","毛糸"  ],
  ["lampe à huile, kérosène","とうゆ","灯油"  ],
  ["lampe fluorescente","けいこうとう","蛍光灯"  ],
  ["lancement, petit-déjeuner [launch, lunch (en)]","ランチ",""  ],
  ["lancer un regard furieux à, regarder fixement [五段] [vt]","にらむ","睨む"  ],
  ["latitude","いど","緯度"  ],
  ["lave","ようがん","溶岩"  ],
  ["le corps tout entier","ぜんしん","全身"  ],
  ["le fait d'avoir une idée ou des connaissances sur quelque chose","こころあたり","心当たり"  ],
  ["le fait d'être de garde ou d'être en service","とうばん","当番"  ],
  ["le fait d'être sur le point de partir, de sortir","おでかけ","お出かけ"  ],
  ["le fait de dépasser son arrêt, sa gare, sa station…","のりこし","乗り越し"  ],
  ["le fait que quelque chose se fasse, suffixe -isation, -ication (international 国際, internationalisation 国際化) [suffixe]","か","化"  ],
  ["le jour convenu, le jour même","とうじつ","当日"  ],
  ["le même rang, égalité","どうかく","同格"  ],
  ["le même, ledit [préfixe]","どう","同"  ],
  ["le mois avant-dernier","せんせんげつ","先々月"  ],
  ["le premier, le numéro 1","だいいち","第一"  ],
  ["le prochain, le suivant (suivi d'une date) [préfixe]","みょう","明"  ],
  ["le public, grand public","こうしゅう","公衆"  ],
  ["le suivant [préfixe]","よく","翌"  ],
  ["lentille optique [lens (en)]","レンズ",""  ],
  ["les 10 premiers jours du mois","しょじゅん","初旬"  ],
  ["les alentours, les environs, le voisinage","ふきん","付近"  ],
  ["les deux [préfixe]","りょう","両"  ],
  ["les quatre saisons","しき","四季"  ],
  ["lever du soleil","ひので","日の出"  ],
  ["lèvres","くちびる","唇"  ],
  ["libération","かいほう","解放"  ],
  ["libérer, laisser s'échapper [五段] [vt]","にがす","逃がす"  ],
  ["librairie","しょてん","書店"  ],
  ["lieu célèbre, site réputé","めいしょ","名所"  ],
  ["lieu d'origine, habitat","げんさん","原産"  ],
  ["lieu de travail","しょくば","職場"  ],
  ["ligne droite","ちょくせん","直線"  ],
  ["ligne électrique, câble électrique, ligne téléphonique","でんせん","電線"  ],
  ["lignée familiale, système, ascendance","けいとう","系統"  ],
  ["limite","かぎり","限り"  ],
  ["limite, frontière","げんど","限度"  ],
  ["liquide, fluide","えきたい","液体"  ],
  ["lit, divan","しんだい","寝台"  ],
  ["litre [litre (fr)]","リットル",""  ],
  ["littérature, documents","ぶんけん","文献"  ],
  ["livraison rapide","そくたつ","速達"  ],
  ["livre d'images, encyclopédie illustrée (notamment pour les enfants)","ずかん","図鑑"  ],
  ["livre, publication","しょせき","書籍"  ],
  ["livret de banque, carnet","つうちょう","通帳"  ],
  ["locomotive","きかんしゃ","機関車"  ],
  ["loi, règle","ほうそく","法則"  ],
  ["loisir [leisure (en)]","レジャー",""  ],
  ["long (en temps)","ながい","永い"  ],
  ["longitude","けいど","経度"  ],
  ["longue écharpe, silencieux (pour une moto, une voiture…) [muffler (en)]","マフラー",""  ],
  ["lourd, important, massif, rigoureux","おもたい","重たい"  ],
  ["lycée","こうこう","高校"  ],
  ["machine [suffixe]","き","機"  ],
  ["machine à coudre [sewing machine (en)]","ミシン",""  ],
  ["magasin de produits de style occidental","ようひんてん","洋品店"  ],
  ["magasin, boutique","みせや","店屋"  ],
  ["maillot de bain","みずぎ","水着"  ],
  ["maintenance, réparation","ていれ","手入れ"  ],
  ["mais, cependant, à condition que","ただし","但し"  ],
  ["maison à louer","かしや","貸家"  ],
  ["maison, bâtiment","かおく","家屋"  ],
  ["maison, famille [suffixe]","け","家"  ],
  ["maison, hôtel, building, résidence, auberge [suffixe]","かん","館"  ],
  ["maître de conférence, professeur qui donne un cours magistral","こうし","講師"  ],
  ["majeur (le doigt)","なかゆび","中指"  ],
  ["majorité, plus grande partie","かはんすう","過半数"  ],
  ["malchance, infortune","ふうん","不運"  ],
  ["malicieux, désobligeant","いじわる","意地悪"  ],
  ["malin, futé, rusé","ずるい","狡い"  ],
  ["manière (de), méthode (de), style (de), courant de pensée [suffixe]","りゅう","流"  ],
  ["manque d'eau, pénurie d'eau","だんすい","断水"  ],
  ["manufacture, production","せいさく","製作"  ],
  ["manuscrit","げんこう","原稿"  ],
  ["marathon [marathon (en)]","マラソン",""  ],
  ["marque, signe, point de repère","めじるし","目印"  ],
  ["marron clair, brun","ちゃいろい","茶色い"  ],
  ["marteau de fer","かなづち","金槌"  ],
  ["masque [mask (en)]","マスク",""  ],
  ["match nul","ひきわけ","引き分け"  ],
  ["matières premières","げんりょう","原料"  ],
  ["maudire, avoir de la rancœur contre quelqu'un, en vouloir à [五段] [vt]","うらむ","恨む"  ],
  ["médecine générale, département de la médecine interne (dans un hôpital)","ないか","内科"  ],
  ["médicament","やくひん","薬品"  ],
  ["mélanger, remuer, brasser [一段] [vt]","まぜる","混ぜる・交ぜる"  ],
  ["membre d'un parti politique","せいとう","政党"  ],
  ["menacer, intimider, forcer, surprendre [五段] [vt]","おどかす","脅かす・威かす・嚇かす"  ],
  ["menu [menu (fr)]","メニュー",""  ],
  ["merci pour tout ce que vous faites pour moi","おせわになる","お世話になる"  ],
  ["mercredi","すいよう","水曜"  ],
  ["mérite, capacité, force","じつりょく","実力"  ],
  ["mes condéolances, quel dommage","おきのどくに","お気の毒に"  ],
  ["Messieurs [suffixe]","おんちゅう","御中"  ],
  ["mesure","そくてい","測定"  ],
  ["mesure, enquête (sondage)","そくりょう","測量"  ],
  ["mettre en ordre, arranger, rendre uniforme [一段] [vt]","そろえる","揃える"  ],
  ["mettre en ordre, rassembler, collecter, résumer [一段] [vt]","まとめる","纏める"  ],
  ["microscope","けんびきょう","顕微鏡"  ],
  ["miel, nectar","みつ","蜜"  ],
  ["milieu du mois, deuxième tiers d'un mois","ちゅうじゅん","中旬"  ],
  ["milieu, intermédiaire, à mi-chemin","ちゅうかん","中間"  ],
  ["millimètre [millimètre (fr)]","ミリメートル",""  ],
  ["mine de charbon","たんこう","炭鉱"  ],
  ["minéral","こうぶつ","鉱物"  ],
  ["misérable","みじめ","惨め"  ],
  ["mixture, mélange","こんごう","混合"  ],
  ["moche, laid, hideux","みにくい","醜い"  ],
  ["mochi (gâteau de riz glutineux)","もち","餅"  ],
  ["modèle [model (en)]","モデル",""  ],
  ["modéré, abordable, accessible","てごろ","手頃"  ],
  ["moderne [modern (en)]","モダン",""  ],
  ["modification, révision (d'une loi, d'un contrat…)","かいせい","改正"  ],
  ["modifier, renouveler [一段] [vt]","あらためる","改める"  ],
  ["moine bouddhiste","ぼうさん","坊さん"  ],
  ["moins (signe mathématique pour la soustraction) [minus (en)]","マイナス",""  ],
  ["moins de [suffixe]","みまん","未満"  ],
  ["moisissure","かび","黴"  ],
  ["monologue, le fait de parler tout seul","ひとりごと","独り言"  ],
  ["monorail [monorail (en)]","モノレール",""  ],
  ["Monseigneur, Monsieur [suffixe]","どの","殿"  ],
  ["montée soudaine, augmentation rapide","げきぞう","激増"  ],
  ["montée, pente, côte","さか","坂"  ],
  ["monter dans un véhicule (voiture, train…)","じょうしゃする","乗車する"  ],
  ["moral","いぎ","意義"  ],
  ["morceau de musique, air musical","きょく","曲"  ],
  ["moteur [motor (en)]","モーター",""  ],
  ["motif, patron (en couture) [pattern (en)]","パターン",""  ],
  ["mouchoir en papier, paper toilette","ちりがみ","塵紙"  ],
  ["mourir de faim, être affamé [一段] [vi]","うえる","飢える"  ],
  ["moustique","か","蚊"  ],
  ["Moyen Âge","ちゅうせい","中世"  ],
  ["moyenne, norme, standard","ひょうじゅん","標準"  ],
  ["moyens de transport","こうつうきかん","交通機関"  ],
  ["multiple, pluriel","ふくすう","複数"  ],
  ["multiplication","かけざん","掛け算"  ],
  ["mûrir, porter ses fruits [五段] [vi]","みのる","実る"  ],
  ["mutuel, réciproque","そうご","相互"  ],
  ["mythe, légende","しんわ","神話"  ],
  ["n'est ce pas ?, interjection pour demander la confirmation de l'interlocuteur","ね・ねえ",""  ],
  ["n'hésitez pas","ごえんりょなく","ご遠慮なく"  ],
  ["naïf, au cœur pur","じゅんじょう","純情"  ],
  ["national","こくりつ","国立"  ],
  ["national, appuyé par l'Etat, soutenu par l'Etat","こくてい","国定"  ],
  ["nationalité","こくせき","国籍"  ],
  ["nature (de quelqu'un), coutume, tradition, habitude","さが","性"  ],
  ["nature d'un terrain","ちしつ","地質"  ],
  ["nausée, envie de vomir","はきけ","吐き気"  ],
  ["ne faites pas attention à moi, ne vous inquiétez pas pour moi","おかまいなく","お構いなく"  ],
  ["ne pas écrire ou contacter quelqu'un depuis quelques temps","ごぶさたする","ご無沙汰する"  ],
  ["ne pas rester en contact avec quelqu'un, absence de nouvelles durant un long moment","ぶさた","無沙汰"  ],
  ["nécessités de la vie (des vêtements, de la nourriture et un abri)","いしょくじゅう","衣食住"  ],
  ["négligé, malpropre, relaché","だらしない",""  ],
  ["négligence, manque de préparation","ゆだん","油断"  ],
  ["négliger, ne pas s'occuper de (en parlant d'un travail) [一段] [vi]","なまける","怠ける"  ],
  ["négoce","ばいばい","売買"  ],
  ["net (poids)","しょうみ","正味"  ],
  ["nettoyage","せいそう","清掃"  ],
  ["nettoyage, entretien [cleaning (en)]","クリーニング",""  ],
  ["neutralité (électrique, chimique…), indifférence, androgyne, neutre (en grammaire)","ちゅうせい","中性"  ],
  ["neveu","おいさん","甥さん"  ],
  ["nièce","めい","姪"  ],
  ["nier, contredire, démentir [五段] [vt]","うちけす","打ち消す"  ],
  ["niveau [level (en)]","レベル",""  ],
  ["niveau avancé, niveau supérieur","じょうきゅう","上級"  ],
  ["niveau d'étude, classe (à l'école)","がっきゅう","学級"  ],
  ["niveau élémentaire, niveau débutant","しょきゅう","初級"  ],
  ["nom","めい","名"  ],
  ["nom d'un lieu","ちめい","地名"  ],
  ["nom de famille","せい","姓"  ],
  ["nom et prénom, identité","しめい","氏名"  ],
  ["nom, substantif","めいし","名詞"  ],
  ["nombre de choses plates (comme des feuilles)","まいすう","枚数"  ],
  ["nombre de jours","ひにち","日日"  ],
  ["nombre entier","せいすう","整数"  ],
  ["nombre impair","きすう","奇数"  ],
  ["nombre pair","ぐうすう","偶数"  ],
  ["nombril","へそ","臍"  ],
  ["nord-sud","なんぼく","南北"  ],
  ["nostalgique","なつかしい","懐かしい"  ],
  ["notre, la notre","わが","我・我が"  ],
  ["nourriture, nutriment","ようぶん","養分"  ],
  ["nouveau, nouvel [préfixe]","しん","新"  ],
  ["nouvelle lune, croissant de lune","みかづき","三日月"  ],
  ["numéro d'une maison","ばんち","番地"  ],
  ["numéro, nombre [number (en)]","ナンバー",""  ],
  ["numéro, nombre [suffixe]","ごう","号"  ],
  ["nylon [nylon (en)]","ナイロン",""  ],
  ["o-kazu (plat principal accompagnant le riz dans les repas japonais)","おかず",""  ],
  ["objet perdu","おとしもの","落し物"  ],
  ["objets nécessaires à la vie de tous les jours","にちようひん","日用品"  ],
  ["obscurité totale, noir complet","まっくら","真っ暗"  ],
  ["observation","かんそく","観測"  ],
  ["océan","かいよう","海洋"  ],
  ["œuvre courte (film, histoire…)","たんぺん","短編"  ],
  ["œuvres complètes","ぜんしゅう","全集"  ],
  ["ombre","ひかげ","日陰"  ],
  ["oncle","おじ","伯父・叔父"  ],
  ["onde électromagnétique, onde électrique","でんぱ","電波"  ],
  ["ongle, griffe, serre","つめ","爪"  ],
  ["onsen (bain thermal japonais), source chaude","おんせん","温泉"  ],
  ["opportuniste (pour l'argent)","げんきん","現金"  ],
  ["opportunité, occasion","ついで","序"  ],
  ["opposition, antagonisme","はん","反"  ],
  ["orchestre [orchestra (en)]","オーケストラ",""  ],
  ["ordre, discipline, règle, loi, règlement","きりつ","規律"  ],
  ["ordre, séquence, méthode","じゅんじょ","順序"  ],
  ["ordre, système, structure, organisation","たいせい","体制"  ],
  ["oreiller","まくら","枕"  ],
  ["organe [organ (en)]","オルガン",""  ],
  ["organiser (une réunion) [一段] [vt]","うちあわせる","打ち合わせる"  ],
  ["Orient","とうよう","東洋"  ],
  ["Orient et Occident, votre attention s'il vous plait","とうざい","東西"  ],
  ["ou, autrement","または","又は"  ],
  ["oubli, omission","しょうりゃく","省略"  ],
  ["oui ou non, accord ou refus","うむ","有無"  ],
  ["ouverture, le fait de devenir opérationnel ou en état de marche","かいつう","開通"  ],
  ["ouvrir en grand, ouvrir","かいほうする","開放する"  ],
  ["paix, harmonie, quiétude","わ","和"  ],
  ["pancarte, enseigne","ひょうしき","標識"  ],
  ["panneau coulissant","ふすま","襖"  ],
  ["panneau d'affichage, pancarte, enseigne","かんばん","看板"  ],
  ["pansement","ほうたい","包帯"  ],
  ["papeterie","ぶんぼうぐ","文房具"  ],
  ["papier à lettre, bloc de papier","びんせん","便箋"  ],
  ["paquet, morceau, tas, amoncellement","かたまり","塊"  ],
  ["par conséquent, alors","こうして","斯うして"  ],
  ["par inadvertance, par inattention","うっかり",""  ],
  ["parallèle, en même temps, simultané, dans la même direction","へいこう","平行"  ],
  ["parc d'attraction","ゆうえんち","遊園地"  ],
  ["parent, famille, proche","しんるい","親類"  ],
  ["parenthèses","かっこ","括弧"  ],
  ["parfaitement rond, parfaitement circulaire","まんまるい","真ん丸い"  ],
  ["parfum","こうすい","香水"  ],
  ["participation, apparition (sur scène)","しゅつじょう","出場"  ],
  ["participer à","さんかする","参加する"  ],
  ["partie écrite en kana après un kanji pour former un mot","おくりがな","送り仮名"  ],
  ["pas de problème, cela m'importe peu","かまいません","構いません"  ],
  ["pas encore [préfixe]","み","未"  ],
  ["passage, endroit, point, lieu","かしょ","箇所"  ],
  ["passer la nuit, loger (dans un hôtel par exemple) [五段] [vi]","とまる","泊る"  ],
  ["passer par hasard [五段] [vi]","とおりかかる","通り掛かる"  ],
  ["passer un examen","じゅけんする","受験する"  ],
  ["passif, peu enthousiaste, pessimiste","しょうきょくてき","消極的"  ],
  ["pâte, amidon, féculent","のり","糊"  ],
  ["paupière","まぶた","瞼"  ],
  ["payant","ゆうりょう","有料"  ],
  ["paye, salaire","きゅうよ","給与"  ],
  ["peau","ひふ","皮膚"  ],
  ["pêcheur","りょうし","漁師"  ],
  ["pêcheur","りょうし","漁師"  ],
  ["peigne","くし","櫛"  ],
  ["peinture (matière)","えのぐ","絵の具"  ],
  ["péninsule","はんとう","半島"  ],
  ["percer, piquer, transpercer, coudre [五段] [vt]","さす","刺す"  ],
  ["performance, capacité","せいのう","性能"  ],
  ["période, époque, durée [suffixe]","き","期"  ],
  ["perpendiculaire, vertical","すいちょく","垂直"  ],
  ["personne qui s'occupe d'un logement pendant que le propriétaire n'est pas là, concierge","るすばん","留守番"  ],
  ["pesanteur, poids, poids lourd (pour un sportif, une voiture…)","じゅうりょう","重量"  ],
  ["petit [préfixe]","こ","小"  ],
  ["peut-être","もしかしたら","若しかしたら"  ],
  ["peut-être","もしかすると","若しかすると"  ],
  ["phare","とうだい","灯台"  ],
  ["pharmacie","やっきょく","薬局"  ],
  ["photographier, prendre une photo","さつえいする","撮影する"  ],
  ["phrase en anglais, texte anglais","えいぶん","英文"  ],
  ["pièce (d'une maison)","しつ","室"  ],
  ["pièce avec des tatamis, salon","ざしき","座敷"  ],
  ["pièce de théâtre","えんげき","演劇"  ],
  ["pied (d'une montagne), base","ふもと","麓"  ],
  ["piété filiale","こうこう","孝行"  ],
  ["pile","でんち","電池"  ],
  ["pilier, poteau","はしら","柱"  ],
  ["pince, tenailles [pinch (en)]","ペンチ",""  ],
  ["pique-nique, ballade, randonnée","えんそく","遠足"  ],
  ["piquer, percer, poignarder, frapper [五段] [vt]","つく","突く"  ],
  ["pistolet, revolver [pistol (en)]","ピストル",""  ],
  ["placard, buffet, armoire","とだな","戸棚"  ],
  ["place (en ville)","ひろば","広場"  ],
  ["place pour les invités","きゃくせき","客席"  ],
  ["place, rang","い","位"  ],
  ["plaine, campagne","へいや","平野"  ],
  ["plainte, réclamation","くじょう","苦情"  ],
  ["plaisanter, blaguer, flirter [一段]","ふざける","巫山戯る"  ],
  ["plan, projet","けい","計"  ],
  ["plastique [plastic (en)]","プラスチック",""  ],
  ["plein d'entrain, animé, de façon très vivante","いきいき","生き生き"  ],
  ["plein, rempli","たっぷり",""  ],
  ["plier (des vêtements) [五段] [vt]","たたむ","畳む"  ],
  ["plonger (dans l'eau), s'enfoncer dans [五段] [vi]","もぐる","潜る"  ],
  ["plonger, se jeter dans, se précipiter dans [五段] [vi]","とびこむ","飛び込む"  ],
  ["plus de, plus que, de, par","より",""  ],
  ["plusieurs fois, à plusieurs fois, sincèrement","くれぐれも","呉れ呉れも"  ],
  ["plusieurs, quelques [préfixe]","いく","幾"  ],
  ["pneu [tyre (en)]","タイヤ",""  ],
  ["poêle à frire [fry pan (en)]","フライパン",""  ],
  ["poids de son corps","たいじゅう","体重"  ],
  ["poignée, guidon [handle (en)]","ハンドル",""  ],
  ["poignet","てくび","手首"  ],
  ["point de vue, manière de voir","みかた","見方"  ],
  ["point faible","じゃくてん","弱点"  ],
  ["point fort, avantage","ちょうしょ","長所"  ],
  ["point important, point majeur","じゅうてん","重点"  ],
  ["point principal, point essentiel","しょうてん","焦点"  ],
  ["pointe, bout, extrémité","せんたん","先端"  ],
  ["pointe, cap","みさき","岬"  ],
  ["points, score, note","てんすう","点数"  ],
  ["poisson rouge","きんぎょ","金魚"  ],
  ["poivre","こしょう","胡椒"  ],
  ["pôle Nord, Arctique","ほっきょく","北極"  ],
  ["pôle Sud, Antarctique","なんきょく","南極"  ],
  ["policier","じゅんさ","巡査"  ],
  ["pollution","こうがい","公害"  ],
  ["pont en fer, pont de voie ferrée","てっきょう","鉄橋"  ],
  ["port de [suffixe]","こう","港"  ],
  ["porte coulissante japonaise en papier","しょうじ","障子"  ],
  ["porte coulissante protégeant des orages","あまど","雨戸"  ],
  ["porte de derrière, porte de service","うらぐち","裏口"  ],
  ["porte principale","せいもん","正門"  ],
  ["porter ses fruits, fructifier [五段] [vi]","なる","生る"  ],
  ["porter sur ses épaules, tromper, duper [五段] [vt]","かつぐ","担ぐ"  ],
  ["poste de téléphone, ligne interne téléphonique","ないせん","内線"  ],
  ["poster (une lettre), expédier","ゆうそうする","郵送する"  ],
  ["poteau électrique, poteau téléphonique","でんちゅう","電柱"  ],
  ["pouce","おやゆび","親指"  ],
  ["pour cela, donc, pour cette raison","そのため","その為"  ],
  ["pour l'instant, pour le moment, provisoirement","いちおう","一応"  ],
  ["pour le moment","ひとまず","一まず"  ],
  ["pour le moment, temporairement","いったん","一旦"  ],
  ["pourboire [tip (en)]","チップ",""  ],
  ["poursuivre quelqu'un, courir après quelqu'un [一段] [vt]","おいかける","追いかける"  ],
  ["pousser (plante, poils, dents…), germer [一段] [vi]","はえる","生える"  ],
  ["poutre, colonne, digit, ordre de grandeur","けた","桁"  ],
  ["précis, judicieux, juste, convenable","てきかく","的確・適確"  ],
  ["prédicat (grammaire)","じゅつご","述語"  ],
  ["préfixe de négation (non-, an-, un-) [préfixe]","ひ","非"  ],
  ["préfixe ordinal (le …ième) [préfixe]","だい","第"  ],
  ["prélever, déduire, soustraire [五段]","さしひく","差し引く"  ],
  ["Premier Ministre","そうりだいじん","総理大臣"  ],
  ["première personne (grammaire)","いちにんしょう","一人称"  ],
  ["prendre avec soi, emporter","じさんする","持参する"  ],
  ["prendre des notes, écrire","ひっきする","筆記する"  ],
  ["prendre des nouvelles de quelqu'un malade, envoyer une lettre de rétablissement","みまいする","見舞いする"  ],
  ["prendre en charge [五段] [vt]","うけもつ","受け持つ"  ],
  ["prendre soin d'une maison pendant que le propriétaire n'est pas là","るすばんする","留守番する"  ],
  ["préparation, réserve","よび","予備"  ],
  ["présidence","しかい","司会"  ],
  ["présomption, supposition, conjecture","すいてい","推定"  ],
  ["presser, essorer, tordre [五段] [vt]","しぼる","絞る"  ],
  ["pression atmosphérique","きあつ","気圧"  ],
  ["pression sanguine","けつあつ","血圧"  ],
  ["prévention du crime","ぼうはん","防犯"  ],
  ["prévention, contrôle, empêchement","ぼうし","防止"  ],
  ["prévoir, prédire [五段] [vt]","うらなう","占う"  ],
  ["primitif","げんし","原始"  ],
  ["princesse","おうじょ","王女"  ],
  ["principal, important","おも","主"  ],
  ["principe, théorie, vérité fondamentale","げんり","原理"  ],
  ["prise de courant, consentement [concentric plug, consent (en)]","コンセント",""  ],
  ["privé (en parlant d'un établissement)","しりつ","私立"  ],
  ["privé, civil","みんかん","民間"  ],
  ["prix fixé","ていか","定価"  ],
  ["prix, charge, coût, taxe","りょうきん","料金"  ],
  ["prix, récompense (en espèces)","しょうきん","賞金"  ],
  ["prix, trophée, récompense","しょうひん","賞品"  ],
  ["probabilité","かくりつ","確率"  ],
  ["procédure, formalité","てつづき","手続き"  ],
  ["processus","かてい","過程"  ],
  ["prochain, suivant [préfixe]","あくる","明くる"  ],
  ["production d'électrique, génération éléctrique","はつでん","発電"  ],
  ["produit agricole","のうさんぶつ","農産物"  ],
  ["produit célèbre, spécialité d'une région","めいぶつ","名物"  ],
  ["produit chimique utilisé dans l'agriculture","のうやく","農薬"  ],
  ["produit d'une vente, recette (financière)","うりあげ","売上"  ],
  ["produits de la mer","すいさん","水産"  ],
  ["professeur assistant","じょきょうじゅ","助教授"  ],
  ["programme (d'un évènement, d'une réunion)","にってい","日程"  ],
  ["programme [programme (en)]","プログラム",""  ],
  ["programme, menu","こんだて","献立"  ],
  ["pronom","だいめいし","代名詞"  ],
  ["propagande, publicité","せんでん","宣伝"  ],
  ["propriétaire (d'un logement)","やぬし","家主"  ],
  ["publication, parution [suffixe]","かん","刊"  ],
  ["puéril, infantile","ようち","幼稚"  ],
  ["puiser (de l'eau), pomper (un liquide), boire (de l'alcool), sympathiser avec [五段] [vt]","くむ","汲む"  ],
  ["puissance électrique","でんりょく","電力"  ],
  ["puissance, autorité, influence","いりょく","威力"  ],
  ["puits","いど","井戸"  ],
  ["pupille","ひとみ","瞳"  ],
  ["pur, simple, sobre","じみ","地味"  ],
  ["pure, véritable, vrai","じゅんすい","純粋"  ],
  ["quai d'une gare [platform (en)]","プラットホーム",""  ],
  ["quantité, dose","ぶんりょう","分量"  ],
  ["quartier d'une ville, district","ちょうめ","丁目"  ],
  ["quartier général, administration centrale","ほんぶ","本部"  ],
  ["quel est le problème ?, qui a-t-il ?","なになに","何々"  ],
  ["quel… !, que ?","なんて","何て"  ],
  ["quelque part ailleurs, un autre endroit","よそ","余所"  ],
  ["question, compteur pour les questions [suffixe]","もん","問"  ],
  ["questions-réponses, dialogue","もんどう","問答"  ],
  ["queue (d'un animal)","しっぽ","尻尾"  ],
  ["qui démange","かゆい","痒い"  ],
  ["qui parle vite","はやくち","早口"  ],
  ["quotient, niveau, vente","しょう","商"  ],
  ["raccompagner (quelqu'un pour son départ) [五段] [vt]","みおくる","見送る"  ],
  ["raccourcir, réduire, contracter [一段] [vt]","ちぢめる","縮める"  ],
  ["raconter [五段] [vt]","ものがたる","物語る"  ],
  ["radical (d'un kanji)","ぶしゅ","部首"  ],
  ["raid, agression, invasion, pénétration","しんにゅう","侵入"  ],
  ["ramer, pagayer, pédaler, nager [五段] [vt]","こぐ","漕ぐ"  ],
  ["ramper [五段]","はう","這う"  ],
  ["rancœur, amertume","うらみ","恨み"  ],
  ["rang, ordre, classe","とう","等"  ],
  ["rangée d'arbres","なみき","並木"  ],
  ["rapidement","さっさと",""  ],
  ["rapidement","どんどん",""  ],
  ["rapporter à quelqu'un, demander de faire, ordonner [一段] [vt]","いいつける","言い付ける"  ],
  ["rare","まれ","稀"  ],
  ["rare","まれ","稀"  ],
  ["raser, couper [五段] [vt]","そる","剃る"  ],
  ["rasoir","かみそり","剃刀"  ],
  ["rassemblement, assemblée","しゅうごう","集合"  ],
  ["rationel, sensé","ごうり","合理"  ],
  ["rayon","はんけい","半径"  ],
  ["rayon lumineux, faisceau lumineux","こうせん","光線"  ],
  ["rayons de soleil, jour","ひざし","陽射・日差し"  ],
  ["rayure, raie","しま","縞"  ],
  ["réception (pour une occasion)","おうせつ","応接"  ],
  ["réception, accueil (de quelqu'un)","でむかえ","出迎え"  ],
  ["réceptionner, s'occuper de","おうたいする","応対する"  ],
  ["recevoir un enseignement [五段] [vt]","おそわる","教わる"  ],
  ["réchauffer [一段] [vt]","あたためる","温める・暖める"  ],
  ["réchauffer, sécher (auprès d'un feu) [五段] [vt]","あぶる","炙る"  ],
  ["récipient, conteneur","いれもの","入れ物"  ],
  ["récipient, vase","ようき","容器"  ],
  ["récolter, rassembler, mettre dans ,adopter [一段] [vt]","とりいれる","取り入れる"  ],
  ["réconciliation","なかなおり","仲直り"  ],
  ["réconforter, consoler [一段] [vt]","なぐさめる","慰める"  ],
  ["reconnaissant","ありがたい","有難い"  ],
  ["reconsidérer, se refaire une opinion [五段]","みなおす","見直す"  ],
  ["récréation [recreation (en)]","レクリエーション",""  ],
  ["rectangle","ちょうほうけい","長方形"  ],
  ["reçu, récépissé","うけとり","受け取り"  ],
  ["reçu, récépissé","りょうしゅう","領収"  ],
  ["redondant, verbeux, répétitif, tape-à-l'œil, bruyant","くどい","諄い"  ],
  ["réduction (de prix), escompte, rabais","わりびき","割引"  ],
  ["réfléchir (quelque chose), projeter (un film, une ombre) [五段] [vt]","うつす","映す"  ],
  ["réflexion (d'une image), reflet, influence","はんえい","反映"  ],
  ["refroidir, calmer, jeter un froid [五段] [vt]","さます","冷ます"  ],
  ["refroidir, réfrigérer [五段] [vt]","ひやす","冷やす"  ],
  ["refroidir, se refoidir, se calmer, baisser (fièvre, colère) [一段] [vi]","さめる","冷める"  ],
  ["regarder d'en haut [五段] [vt]","みおろす","見下ろす"  ],
  ["regarder fixement, fixer du regard [一段] [vt]","みつめる","見詰める"  ],
  ["regarder vers le haut, regarder en levant les yeux, admirer [一段] [vt]","みあげる","見上げる"  ],
  ["région froide, zone froide","かんたい","寒帯"  ],
  ["registre, livre","ちょう","帳"  ],
  ["réglage, contrôle","ちょうせつ","調節"  ],
  ["règle (pour mesurer)","じょうぎ","定規"  ],
  ["règle, double-décimètre","ものさし","物差し・物指"  ],
  ["regrettable, décevant, cher, de valeur","おしい","惜しい"  ],
  ["regretté, désiré, tant attendu","こいしい","恋しい"  ],
  ["régulation, ajustement, réglage","ちょうせい","調整"  ],
  ["régulièrement, progressivement","ちゃくちゃく","着々"  ],
  ["rejoindre (en parlant d'un cours d'eau), rencontrer","ごうりゅうする","合流する"  ],
  ["relativement, comparativement","わりと","割と"  ],
  ["remarquablement, sensiblement","めっきり",""  ],
  ["rembourser [五段] [vt]","はらいもどす","払い戻す"  ],
  ["remettre à plus tard, retarder [五段] [vt]","ずらす","滑らす"  ],
  ["remodelage, transformation, refonte","かいぞう","改造"  ],
  ["remporter une victoire","ゆうしょうする","優勝する"  ],
  ["rencontre universitaire, association scientifique","がっかい","学会"  ],
  ["rencontrer quelqu'un ayant un statut plus important que le nôtre (polie)","おめにかかる","お目に掛かる"  ],
  ["rendez-vous, réunion d'affaire","うちあわせ","打ち合わせ"  ],
  ["rendre visite à un malade [五段] [vt]","みまう","見舞う"  ],
  ["rendre visite, visiter","ほうもんする","訪問する"  ],
  ["renifler, flairer [五段] [vt]","かぐ","嗅ぐ"  ],
  ["renvoyer quelqu'un vers, faire retourner quelqu'un vers [五段] [vt]","かえす","帰す・還す"  ],
  ["répandre, déborder, s'échapper (des larmes, un sourire) [一段] [vi]","こぼれる","零れる"  ],
  ["réparation, rectification","しゅうぜん","修繕"  ],
  ["réponse","かいとう","回答・解答"  ],
  ["réponse","こたえ","答え"  ],
  ["réponse juste","せいかい","正解"  ],
  ["repos, pause","ひとやすみ","一休み"  ],
  ["repos, relaxation, détente","きゅうそく","休息"  ],
  ["requête, faveur, demande, confiance","たのみ","頼み"  ],
  ["résidence secondaire, villa","べっそう","別荘"  ],
  ["résister, supporter, endurer [一段] [vi]","たえる","耐える"  ],
  ["résonner, retentir [五段] [vi]","ひびく","響く"  ],
  ["respecter [五段] [vt]","うやまう","敬う"  ],
  ["respecter, admirer, considérer","そんけいする","尊敬する"  ],
  ["ressort","ばね","発条"  ],
  ["rester (à un endroit), demeurer, être limité à [五段] [vi]","とどまる・とまる","留まる"  ],
  ["résumé, points essentiels, fondamentaux","ようし","要旨"  ],
  ["résumé, synopsis","あらすじ","粗筋"  ],
  ["retenir (quelqu'un), contenir [一段] [vt]","ひきとめる","引き止める"  ],
  ["retourner, mettre à l'envers [五段] [vt]","うらがえす","裏返す"  ],
  ["retourner, renverser, faire chavirer [五段] [vt]","ひっくりかえす","引っ繰り返す"  ],
  ["réunion, assemblée","しゅうかい","集会"  ],
  ["réussite, performance, acte méritoire","こうせき","功績"  ],
  ["réveille-matin","めざまし","目覚まし"  ],
  ["revenir à son point de départ, revenir en arrière [五段] [vt]","ひきかえす","引き返す"  ],
  ["révérence pour saluer, salutation (en s'inclinant en avant)","おじぎ","御辞儀"  ],
  ["rêverie, vision, fantasme, imagination","くうそう","空想"  ],
  ["ride, pli","しわ","皺"  ],
  ["ridiculiser, se moquer de, taquiner [五段]","からかう","揶揄う"  ],
  ["rien (+ verbe au négatif), complètement (+ affirmatif), pas le moindre","なんとも","何とも"  ],
  ["robe [one-piece dress (en)]","ワンピース",""  ],
  ["robinet","じゃぐち","蛇口"  ],
  ["roi","こくおう","国王"  ],
  ["rôle principal","しゅやく","主役"  ],
  ["rômaji, caractères latins","ローマじ","ローマ字"  ],
  ["ronflement","いびき","鼾"  ],
  ["ronger, mordiller, mâcher, grignoter, avoir quelques notions en [五段] [vt]","かじる","齧る"  ],
  ["rose (couleur) [pink (en)]","ピンク",""  ],
  ["rotation","かいてん","回転"  ],
  ["roue de voiture","しゃりん","車輪"  ],
  ["roue dentée, pignon","はぐるま","歯車"  ],
  ["rouge à lèvres","くちべに","口紅"  ],
  ["rouille","さび","錆"  ],
  ["rouiller [一段] [vi]","さびる","錆びる"  ],
  ["rouler, faire rouler [五段] [vt]","ころがす","転がす"  ],
  ["rouler, tomber, chuter [五段] [vi]","ころがる","転がる"  ],
  ["route, chemin, voie","どう","道"  ],
  ["routine, travail quotidien","にっか","日課"  ],
  ["ruban [ribbon (en)]","リボン",""  ],
  ["rue principale, avenue","おおどおり","大通り"  ],
  ["rythme [rhythm (en)]","リズム",""  ],
  ["s'accroître, s'étendre","かくだいする","拡大する"  ],
  ["s'accroupir [五段] [vi]","しゃがむ",""  ],
  ["s'accumuler, s'entasser, s'amasser [五段] [vi]","たまる","溜まる"  ],
  ["s'aiguiser, devenir pointu [五段] [vi]","とがる","尖る"  ],
  ["s'améliorer, se perfectionner, progresser","じょうたつする","上達する"  ],
  ["s'apaiser, se calmer, se modérer [五段] [vi]","しずまる","静まる"  ],
  ["s'approche de quelque chose [五段] [vi]","ちかよる","近寄る"  ],
  ["s'approcher, se rapprocher","せっきんする","接近する"  ],
  ["s'approcher, se rapprocher, exiger [五段] [vi]","せまる","迫る"  ],
  ["s'appuyer contre, s'adosser à, peser sur l'estomac [一段] [vi]","もたれる","凭れる"  ],
  ["s'arrêter, ne pas bouger [五段]","たちどまる","立ち止まる"  ],
  ["s'asseoir [一段] [vi]","こしかける","腰掛ける"  ],
  ["s'assombrir, se couvrir (en parlant du temps), devenir nuageux [五段] [vi]","くもる","曇る"  ],
  ["s'écarter du chemin, faire place [五段] [vi]","どく","退く"  ],
  ["s'écarter du sujet, s'égarer, se perdre [一段] [vi]","それる","逸れる"  ],
  ["s'éclaircir (le temps), se dégager [五段] [vi]","すむ","澄む"  ],
  ["s'effondrer, s'écrouler, se dégrader [一段] [vi]","くずれる","崩れる"  ],
  ["s'éloigner de, quitter [一段] [vi]","はなれる","放れる"  ],
  ["s'engourdir [一段] [vi]","しびれる","痺れる"  ],
  ["s'épuiser, se fatiguer [一段] [vi]","くたびれる","草臥れる"  ],
  ["s'équilibrer, s'assortir, s'harmoniser [五段] [vi]","つりあう","釣り合う"  ],
  ["s'excuser, demander pardon [一段] [vi]","わびる","詫びる"  ],
  ["s'incliner, pencher, décliner, se coucher (pour le soleil), vaciller [五段]","かたむく","傾く"  ],
  ["s'occuper de, prendre en charge [五段] [vt]","あずかる","預かる"  ],
  ["s'ordonner, s'établir, s'organiser [五段] [vi]","まとまる","纏まる"  ],
  ["sa maison, son chez-soi","じたく","自宅"  ],
  ["sac à main [handbag (en)]","ハンドバッグ",""  ],
  ["saison (sportive) [season (en)]","シーズン",""  ],
  ["salaire mensuel","げっきゅう","月給"  ],
  ["salé","しおからい","塩辛い"  ],
  ["sale, impur, crasseux","ふけつ","不潔"  ],
  ["salir, rendre impur [五段] [vi]","にごる","濁る"  ],
  ["salir, tacher, polluer, déshonorer [五段] [vt]","よごす","汚す"  ],
  ["salle d'attente","まちあいしつ","待合室"  ],
  ["salle de réunion","かいかん","会館"  ],
  ["salon pour recevoir","きゃくま","客間"  ],
  ["sang","けつえき","血液"  ],
  ["sans raison spéciale, pour une raison ou une autre","なんとなく","何となく"  ],
  ["santé !","かんぱい","乾杯"  ],
  ["sashimi (tranches de poisson cru)","さしみ","刺身"  ],
  ["satisfaction","まんぞく","満足"  ],
  ["sauter, bondir, sauter [一段] [vi]","はねる","跳ねる"  ],
  ["saviez-vous que… ?","ごぞんじですか","ご存知ですか"  ],
  ["savoir [一段]","ぞんじる","存じる"  ],
  ["savoir, érudition","がくりょく","学力"  ],
  ["sceau (utilisé pour les signatures)","はんこ","判子"  ],
  ["scène, prestation scénique, représentation [scene (en)]","ステージ",""  ],
  ["scie","のこぎり","鋸"  ],
  ["science","りか","理科"  ],
  ["sciences","がくじゅつ","学術"  ],
  ["sciences humaines","じんぶんかがく","人文科学"  ],
  ["sciences naturelles","しぜんかがく","自然科学"  ],
  ["sciences sociales","しゃかいかがく","社会科学"  ],
  ["se briser, se fracasser [一段] [vi]","くだける","砕ける"  ],
  ["se calmer, se détendre [五段]","おちつく","落ち着く"  ],
  ["se comporter, se conduire, recevoir (des personnes) [五段] [vt]","ふるまう","振舞う"  ],
  ["se croiser sans se rencontrer, se manquer, être en désaccord [五段] [vi]","すれちがう","すれ違う"  ],
  ["se déchirer, se détruire, être battu [一段] [vi]","やぶれる","破れる"  ],
  ["se décider à, prendre une décision, se déterminer à","けつだんする","決断する"  ],
  ["se déplacer, migrer","いどうする","移動する"  ],
  ["se détacher, ressortir, se remarquer, être en avant [五段] [vi]","めだつ","目立つ"  ],
  ["se diffuser, se répandre, se propager","ふきゅうする","普及する"  ],
  ["se diriger vers, faire face à [五段] [vi]","むかう","向かう"  ],
  ["se disputer, s'affronter [五段] [vi]","あらそう","争う"  ],
  ["se faire tard, avancer [一段] [vi]","ふける","更ける"  ],
  ["se faner, se flétrir [一段] [vi]","かれる","枯れる"  ],
  ["se flétrir, se faner, s'estomper","しぼむ","萎む"  ],
  ["se fondre dans, s'adapter, entrer dans [五段] [vi]","とけこむ","溶け込む"  ],
  ["se gargariser, se rincer la bouche","うがいする","嗽する"  ],
  ["se gonfler, grossir, enfler [五段] [vi]","ふくらむ","膨らむ"  ],
  ["se laver le visage","せんめんする","洗面する"  ],
  ["se lever du lit, se réveiller","きしょうする","起床する"  ],
  ["se maquiller","けしょうする","化粧する"  ],
  ["se mettre à parler, briser la glace [五段] [vt]","いいだす","言い出す"  ],
  ["se perdre, s'égarer, être perplexe, être fasciné par, hésiter [五段] [vi]","まよう","迷う"  ],
  ["se prolonger, traîner en longueur [五段] [vi]","ながびく","長引く"  ],
  ["se promener le soir","やこうする","夜行する"  ],
  ["se propager, se diffuser","ふきゅうする","普及する"  ],
  ["se rafraîchir, aller dans un endroit frais [五段] [vi]","すずむ","涼む"  ],
  ["se rapprocher, devenir proche, se lier d'amitié avec quelqu'un [五段] [vi]","ちかづく","近づく"  ],
  ["se réchauffer [五段] [vi]","あたたまる","温まる・暖まる"  ],
  ["se renforcer, s'intensifier, augmenter [五段] [vi]","ふかまる","深まる"  ],
  ["se retirer, s'écarter, ne plus pouvoir sortir [五段] [vi]","ひっこむ","引っ込む"  ],
  ["se retourner, basculer par-dessus, tomber, être renversé [五段] [vi]","ひっくりかえる","引っ繰り返る"  ],
  ["se retourner, se tourner vers [五段]","ふりむく","振り向く"  ],
  ["se rétrécir, se contracter [五段] [vi]","ちぢむ","縮む"  ],
  ["se solidifier, durcir, devenir ferme [五段] [vi]","かたまる","固まる"  ],
  ["se transmettre, se propager, être introduit [五段] [vi]","つたわる","伝わる"  ],
  ["se tromper, faire une faute [五段]","まちがう","間違う"  ],
  ["seau [bucket (en)]","バケツ",""  ],
  ["sécher (des habits), dessécher [五段] [vt]","かわかす","乾かす"  ],
  ["sécher [五段] [vi]","かわく","乾く"  ],
  ["sécher, déshydrater, aérer [五段] [vt]","ほす","干す"  ],
  ["secrètement, furtivement","こっそり",""  ],
  ["segmentation, classification, division, voie de circulation","くぶん","区分"  ],
  ["séjourner","たいざいする","滞在する"  ],
  ["sel de table","しょくえん","食塩"  ],
  ["séminaire [Seminar (de)]","ゼミ",""  ],
  ["sensation, sentiment, émotion, impression","かん","感"  ],
  ["sentiments (sincères)","じっかん","実感"  ],
  ["sentir (bon ou mauvais), être parfumé, rougeoyer, luire [五段] [vi]","におう","匂う"  ],
  ["séparément","べつべつ","別々"  ],
  ["séries [series (en)]","シリーズ",""  ],
  ["serre","おんしつ","温室"  ],
  ["serveuse, hôtesse [waitress (en)]","ウエートレス",""  ],
  ["servir (de la nourriture), prescrire (un médicament) [五段] [vi]","もる","盛る"  ],
  ["servir de l'alcool [五段] [vt]","くむ","酌む"  ],
  ["shinkansen (train à grande vitesse japonais)","しんかんせん","新幹線"  ],
  ["shôgi (jeu d'échec japonais)","しょうぎ","将棋"  ],
  ["siège, banc","こしかけ","腰掛"  ],
  ["sieste","ひるね","昼寝"  ],
  ["signe de ponctuation","くとうてん","句読点"  ],
  ["signe, indication, tendance, cotation (boursière entre autres)","けはい","気配"  ],
  ["signe, marque, symbole","ふごう","符号"  ],
  ["signe, présage, prémonition, 10^12","ちょう","兆"  ],
  ["silencieusement, calmement","しいんと",""  ],
  ["singulier (grammaire)","たんすう","単数"  ],
  ["sirène [siren (en)]","サイレン",""  ],
  ["soba (nouilles de sarrasin)","そば","蕎麦"  ],
  ["société commerciale","しょうしゃ","商社"  ],
  ["soi-même, personnellement","みずから","自ら"  ],
  ["soigner un patient, veiller sur un patient","かんびょうする","看病する"  ],
  ["soins de beauté, beauté du visage","びよう","美容"  ],
  ["sol, surface de la terre","じめん","地面"  ],
  ["sol, terrain","じばん","地盤"  ],
  ["soldat, marin","へいたい","兵隊"  ],
  ["soleil couchant","ゆうひ","夕日"  ],
  ["sombre, mal éclairé","うすぐらい","薄暗い"  ],
  ["sortie éducative, visite","けんがく","見学"  ],
  ["sortir, produire, aller chercher, récupérer [五段] [vt]","とりだす","取り出す"  ],
  ["soudain, brusque, inattendu, improvisé","にわか","俄か"  ],
  ["soudaine averse le soir","ゆうだち","夕立"  ],
  ["soudainement","どっと",""  ],
  ["souligner, faire un trait sous quelque chose","かせんをひく","下線を引く"  ],
  ["soupe, jus, bouillon","しる","汁"  ],
  ["soupir","ためいき","溜息"  ],
  ["sourire","にこにこ",""  ],
  ["sous les pieds, allure, démarche","あしもと","足元・足下"  ],
  ["sous-vêtements, culotte, slip [underpants (en)]","パンツ",""  ],
  ["sous-vêtements, lingerie, chemise de nuit","はだぎ","肌着"  ],
  ["soustraction","ひきざん","引算"  ],
  ["spécial, extraordinaire, particulier","りんじ","臨時"  ],
  ["spécial, propice, joyeux, innocent, agréable","めでたい","目出度い"  ],
  ["spécial, unique","とくしゅ","特殊"  ],
  ["spécifique, particulier","とくてい","特定"  ],
  ["statistiques","とうけい","統計"  ],
  ["statut social, position sociale","みぶん","身分"  ],
  ["stop, arrêt [stop (en)]","ストップ",""  ],
  ["strict, rigoureux, sévère, ferme","げんじゅう","厳重"  ],
  ["structure, construction","こうぞう","構造"  ],
  ["stupéfiant, épouvantable, affreux, terrible","ものすごい","物凄い"  ],
  ["stupide, bon à rien, inutile, sans intérêt","くだらない","下らない"  ],
  ["style littéraire","ぶんたい","文体"  ],
  ["subalterne, junior","めした","目下"  ],
  ["sucer, mâcher, mordiller [五段] [vt]","しゃぶる",""  ],
  ["suffixe pour exprimer le fait qu'on retente une action [suffixe]","なおす","直す"  ],
  ["suffixe pour indiquer qu'une action a été accomplie totalement en usant d'un effort particulier pour la réussir [suffixe]","きる",""  ],
  ["suffixe pour la marque du pluriel [suffixe]","ら","等"  ],
  ["suffixe pour les nombres cardinaux [suffixe]","ばんめ","番目"  ],
  ["suffixe pour nominaliser des adjectifs, notamment ceux relatifs aux sens ou aux lieux (exemple : 甘い,doux donnera 甘み, douceur) [suffixe]","み",""  ],
  ["sujet d'étude","がっか","学科"  ],
  ["sujet grammatical","しゅご","主語"  ],
  ["superflu, inutile, excédant","よけい","余計"  ],
  ["supérieur, sénior","めうえ","目上"  ],
  ["superstition","めいしん","迷信"  ],
  ["supporter, endurer, braver [一段] [vt]","こらえる","堪える"  ],
  ["supprimer, effacer, enlever, éliminer","さくじょする","削除する"  ],
  ["surface de l'eau","すいめん","水面"  ],
  ["surprendre, effrayer [五段] [vt]","おどろかす","驚かす"  ],
  ["suspendre, faire osciller, balancer [一段] [vt]","ぶらさげる","ぶら下げる"  ],
  ["suspension, arrêt, interruption","ていし","停止"  ],
  ["symbole, code","きごう","記号"  ],
  ["système judiciaire, magistrature","はんじ","判事"  ],
  ["système, organisation","たいけい","体系"  ],
  ["tabi (chaussette japonaise dont le gros orteil est séparé)","たび","足袋"  ],
  ["table des matières","もくじ","目次"  ],
  ["tablier [apron (en)]","エプロン",""  ],
  ["tambour","たいこ","太鼓"  ],
  ["tard dans la nuit","しんや","深夜"  ],
  ["tasse à thé","ゆのみ","湯飲み"  ],
  ["taux d'humidité","しつど","湿度"  ],
  ["taxe, charge, prix [suffixe]","りょう","料"  ],
  ["téléscope","ぼうえんきょう","望遠鏡"  ],
  ["tempérament, caractère, nature","せいしつ","性質"  ],
  ["tempête de neige","ふぶき","吹雪"  ],
  ["temple","じいん","寺院"  ],
  ["tempo, rythme [tempo (it)]","テンポ",""  ],
  ["tenace, obstiné","しつこい",""  ],
  ["tenir quelque chose dans sa bouche (une cigarette, une pipe…) [一段] [vt]","くわえる","咥える"  ],
  ["terme de respect, langage de politesse","けいご","敬語"  ],
  ["terme, terminologie","ようご","用語"  ],
  ["terminus","しゅうてん","終点"  ],
  ["terrain, site, emplacement","しきち","敷地"  ],
  ["terre arable, terre cultivable","こうち","耕地"  ],
  ["territoire de [suffixe]","りょう","領"  ],
  ["thème, sujet [Thema (de)]","テーマ",""  ],
  ["tiède","ぬるい","温い"  ],
  ["tiens !, oh !, oh ?","おや",""  ],
  ["tir, lancement","はっしゃ","発射"  ],
  ["titre","だいめい","題名"  ],
  ["titre, en-tête, index, sous-titre","みだし","見出し"  ],
  ["toilettes","てあらい","手洗い"  ],
  ["toilettes, WC","べんじょ","便所"  ],
  ["tomber (des feuilles , des fleurs…), se disperser, s'éparpiller, se répandre [五段] [vi]","ちる","散る"  ],
  ["tordre, visser [五段] [vt]","ねじる","捩る"  ],
  ["tourmenter, faire souffrir, harceler [一段] [vt]","くるしめる","苦しめる"  ],
  ["tourner (un interrupteur), tordre, essayer de comprendre, se creuser la tête [五段] [vt]","ひねる","捻る"  ],
  ["tourner autour, entourer [五段] [vi]","めぐる","巡る"  ],
  ["tous les, chaque [préfixe]","まい","毎"  ],
  ["tout à l'heure, il y a peu","さきほど","先程"  ],
  ["tout noir, complètement noir","まっくろ","真っ黒"  ],
  ["tout, tous, la totalité","ぜん","全"  ],
  ["toute son énergie, toutes ses forces","ぜんりょく","全力"  ],
  ["traducation orale","つうやく","通訳"  ],
  ["traduire","やくする","訳する"  ],
  ["traduire [五段] [vt]","やくす","訳す"  ],
  ["transfert, déménagement","いてん","移転"  ],
  ["transfusion sanguine","ゆけつ","輸血"  ],
  ["transparent, clair","とうめい","透明"  ],
  ["transpirer, suer","あせをかく","汗を掻く"  ],
  ["transport","ゆそう","輸送"  ],
  ["transport maritime","ふなびん","船便"  ],
  ["travail accompli, travail achevé","できあがり","出来上がり"  ],
  ["travailler pour, être employé par [一段] [vt]","つとめる","勤める・務める"  ],
  ["travaux manuels","こうげい","工芸"  ],
  ["trébucher, se prendre les pieds dans [五段] [vi]","つまずく","躓く"  ],
  ["tremper, mouiller [五段] [vt]","ぬらす","濡らす"  ],
  ["triangle","さんかく","三角"  ],
  ["tricher, escroquer, tromper, duper [五段] [vt]","だます","騙す"  ],
  ["tricot","あみもの","編物"  ],
  ["trois jours auparavant","さきおととい","一昨昨日"  ],
  ["trop bien, plus que nécessaire, qui consomme beaucoup, gaspilleur","もったいない","勿体ない"  ],
  ["trouver un emploi","しゅうしょくする","就職する"  ],
  ["tube, tuyaux","くだ・かん","管"  ],
  ["tuer quelqu'un à l'aide d'une lame (d'un couteau, d'une épée…) [五段]","きる","斬る"  ],
  ["tuile","かわら","瓦"  ],
  ["udon (nouilles japonaises préparées avec de la farine de blé)","うどん","饂飩"  ],
  ["un autre jour, une autre fois","いずれ","孰"  ],
  ["un autre plat, un autre verre","おかわり","お代わり"  ],
  ["un instant s'il vous plaît","しょうしょうおまちください","少々お待ちください"  ],
  ["un par un, séparément","いちいち","一々"  ],
  ["un peu, une partie","いくぶん","幾分"  ],
  ["une section, une partie (d'un ensemble), un exemplaire (d'un document)","いちぶ","一部"  ],
  ["unie (pour une couleur)","むじ","無地"  ],
  ["urine","しょうべん","小便"  ],
  ["usage, emploi [suffixe]","もち","持ち"  ],
  ["usage, utilisation [suffixe]","づかい","遣い"  ],
  ["utilisation des kanas (syllabaires) pour écrire le japonais","かなづかい","仮名遣い"  ],
  ["utilisation, utilité","ようと","用途"  ],
  ["vaisselle","しょっき","食器"  ],
  ["vapeur","じょうき","蒸気"  ],
  ["vapeur d'eau","すいじょうき","水蒸気"  ],
  ["vapeur, buée","ゆげ","湯気"  ],
  ["vapeur, gaz","きたい","気体"  ],
  ["variations, fluctuation, augmentation et baisse","ぞうげん","増減"  ],
  ["vaste, étendu, large","ひろびろ","広々"  ],
  ["vendre en gros, râper (des légumes, des fruits…) [五段] [vt]","おろす","卸す"  ],
  ["vendre, mettre en vente","はつばいする","発売する"  ],
  ["vénérer, prier [五段] [vt]","おがむ","拝む"  ],
  ["venir à l'esprit [五段]","おもいつく","思い付く"  ],
  ["venir à l'esprit, trouver [五段]","おもいつく","思い付く"  ],
  ["vente promotionnelle, solde","とくばい","特売"  ],
  ["ventes","うれゆき","売れ行き"  ],
  ["ventilateur","せんぷうき","扇風機"  ],
  ["ventilation","かんき","換気"  ],
  ["vérité, réalité, sincérité, fidélité","じつ","実"  ],
  ["verser (une boisson), servir (des boissons) [五段] [vt]","さす","注す"  ],
  ["verser, déverser, répandre, ronchonner, se plaindre [五段] [vt]","こぼす","零す"  ],
  ["vertige, étourdissement","めまい","目眩"  ],
  ["vêtements japonais","わふく","和服"  ],
  ["vétéran [veteran (en)]","ベテラン",""  ],
  ["vexant, contrariant, regrettable, humiliant","くやしい","悔しい"  ],
  ["victoire ou défaite, match, compétition","しょうぶ","勝負"  ],
  ["vide, creux","しんくう","真空"  ],
  ["vie humaine","じんめい","人命"  ],
  ["vieux papiers, papiers à jeter","かみくず","紙屑"  ],
  ["village agricole, village rural","のうそん","農村"  ],
  ["ville basse","したまち","下町"  ],
  ["vinaigre","す","酢"  ],
  ["vinyle [vinyl (en)]","ビニール",""  ],
  ["violent, sans scrupule, brutal","らんぼう","乱暴"  ],
  ["violet","むらさき","紫"  ],
  ["vis, ressort (d'une montre, d'une horloge…)","ねじ","螺子"  ],
  ["viser [五段] [vt]","ねらう","狙う"  ],
  ["vitamine [vitamin (en)]","ビタミン",""  ],
  ["vitesse","そくりょく","速力"  ],
  ["vitesse (par heure)","じそく","時速"  ],
  ["voie ferrée","せんろ","線路"  ],
  ["vol, cambriolage","とうなん","盗難"  ],
  ["volcan","かざん","火山"  ],
  ["volet, store [shutter (en)]","シャッター",""  ],
  ["volume (pour un livre), bobine (pour un film) [suffixe]","かん","巻"  ],
  ["voter aux élections","とうひょうする","投票する"  ],
  ["voyage d'affaire","しゅっちょう","出張"  ],
  ["voyant, attirant à l'oeil","はで","派手"  ],
  ["voyons voir..., et bien…","ええと",""  ],
  ["vue, observation","ごらん","御覧"  ],
  ["yukata (kimono léger en coton)","ゆかた","浴衣"  ],
  ["zéro (pour une note)","れいてん","零点"  ],
  ["zone de production","さんち","産地"  ],
  ["zone tempérée","おんたい","温帯"  ],
  ["zôri (sandale de paille japonaise)","ぞうり","草履"  ]
];

module.exports = jlptfr2;