var jlptfr3 = [
  ["à l'intérieur de, dans [suffixe]","ない","内"  ],
  ["à l'occasion de, lors de","さい","際"  ],
  ["à notre époque, de nos jours, actuellement","げんざい","現在"  ],
  ["à nouveau, encore une fois","ふたたび","再び"  ],
  ["à partir de maintenant","こんご","今後"  ],
  ["à poings fermés (dormir), profondément (en parlant du sommeil)","ぐっすり",""  ],
  ["à tel point que","あんなに",""  ],
  ["abandonner, renoncer, laisser tomber [一段] [vt]","あきらめる","諦める"  ],
  ["abondamment","たっぷり",""  ],
  ["abondant, riche, plein","ほうふ","豊富"  ],
  ["abondant, riche, prospère","ゆたか","豊か"  ],
  ["aboyer, rugir, beugler, mugir [一段] [vi]","ほえる","吠える"  ],
  ["absence","けっせき","欠席"  ],
  ["absolu, inconstestable","ぜったい","絶対"  ],
  ["absolument, coûte que coûte","どうしても","如何しても"  ],
  ["absorbé, en plein rêve, dans un état second","むちゅう","夢中"  ],
  ["absorption, aspiration, attraction","きゅうしゅう","吸収"  ],
  ["accepter, recevoir, obtenir, prendre, comprendre [五段] [vt]","うけとる","受け取る"  ],
  ["accord, approbation","さんせい","賛成"  ],
  ["accord, approbation, consentement","しょうにん","承認"  ],
  ["accord, approbation, le fait d'accepter une situation","なっとく","納得"  ],
  ["accord, conclusion, règlement","きまり","決まり"  ],
  ["accorder de l'importance, considérer","じゅうしする","重視する"  ],
  ["accroissement, expansion","かくだい","拡大"  ],
  ["accueil, réception, bienvenue","かんげい","歓迎"  ],
  ["achèvement, accomplissement","かんせい","完成"  ],
  ["achèvement, fin, accomplissement","かんりょう","完了"  ],
  ["acquérir, obtenir, gagner, remporter [一段] [vt]","える・うる","得る"  ],
  ["acteur, actrice, artiste sur scène","はいゆう","俳優"  ],
  ["actif, dynamique, positif","せっきょくてき","積極的"  ],
  ["action boursière, titre boursier, souche d'un arbre","かぶ","株"  ],
  ["action, comportement, conduite","こうどう","行動"  ],
  ["activité, action","かつどう","活動"  ],
  ["actrice","じょゆう","女優"  ],
  ["additionner, ajouter, augmenter, rajouter [一段] [vt]","くわえる","加える"  ],
  ["adieux, raccompagnement de quelqu'un (à la gare, à l'aéroport...)","みおくり","見送り"  ],
  ["admiration","かんしん","感心"  ],
  ["admission (dans un lieu), accès, entrée","にゅうじょう","入場"  ],
  ["adopter, prendre, accepter, confisquer [一段] [vt]","とりあげる","取り上げる"  ],
  ["adorable, mignon","かわいらしい","可愛らしい"  ],
  ["adroit, habile","きよう","器用"  ],
  ["adversaire, opposant, compagnon","あいて","相手"  ],
  ["affaire criminelle, détective","けいじ","刑事"  ],
  ["affichage, annonce, pancarte, affiche","けいじ","掲示"  ],
  ["affirmation, déclaration, insistance","しゅちょう","主張"  ],
  ["âge","ねんれい","年齢"  ],
  ["agiter, secouer, remuer, distribuer (un rôle à un acteur) [五段] [vt]","ふる","振る"  ],
  ["agréable, admirable, génial","すてき","素敵"  ],
  ["agréable, confortable","かいていき","快適"  ],
  ["agriculture","のうぎょう","農業"  ],
  ["aide, assistance","えんじょ","援助"  ],
  ["aide, assistance, sauvetage","きゅうじょ","救助"  ],
  ["aide, assistant","じょしゅ","助手"  ],
  ["aider, sauver, secourir, épargner (la vie), soulager [一段] [vt]","たすける","助ける"  ],
  ["aiguille, hameçon","はり","針"  ],
  ["aiguisé, pointu","するどい","鋭い"  ],
  ["aile, plume","はね","羽"  ],
  ["ailes","つばさ","翼"  ],
  ["aimer, être amoureux","あいする","愛する"  ],
  ["aimer, préférer [五段] [vt]","このむ","好む"  ],
  ["air, ton, jointure, articulation","ふし","節"  ],
  ["album [album (en)]","アルバム",""  ],
  ["alentours, circonférence, environs","しゅうい","周囲"  ],
  ["aliments, produits alimentaires","しょくひん","食品"  ],
  ["aller à l'encontre de, s'opposer à, désobéir, résister [五段] [vi]","さからう","逆らう"  ],
  ["allié, ami","みかた","味方"  ],
  ["allonger, prolonger, reporter [五段] [vt]","のばす","延ばす・伸ばす"  ],
  ["alors, dans ce cas, sur ce, maintenant","そこで","其処で"  ],
  ["alpinisme","とざん","登山"  ],
  ["altérer, modifier, corriger, rectifier, retoucher","しゅうせいする","修正する"  ],
  ["ambassadeur","たいし","大使"  ],
  ["ambiance, atmosphère","ふんいき","雰囲気"  ],
  ["âme, esprit","せいしん","精神"  ],
  ["amélioration","かいぜん","改善"  ],
  ["amélioration, progrès, perfectionnement","じょうたつ","上達"  ],
  ["ami","ゆうじん","友人"  ],
  ["ami, camarade","とも","友"  ],
  ["amitié, camaraderie","ゆうじょう","友情"  ],
  ["amour","あい","愛"  ],
  ["amour, affection","あいじょう","愛情"  ],
  ["amour, passion amoureuse","こい","恋"  ],
  ["analyse","ぶんせき","分析"  ],
  ["ancien, ex- [préfixe]","きゅう","旧"  ],
  ["annonce, information","しらせ","知らせ"  ],
  ["antre, caverne, nid, toile d'araignée, ruche","す","巣"  ],
  ["apparaître, se dévoiler, s'exprimer (sentiment) [一段] [vi]","あらわれる","現れる・表れる・現われる"  ],
  ["apparence, forme, aspect","すがた","姿"  ],
  ["appât, nourriture pour animaux","えさ","餌"  ],
  ["appétit","しょくよく","食欲"  ],
  ["applaudir","はくしゅする","拍手する"  ],
  ["application, mise en pratique, utilisation","てきよう","適用"  ],
  ["apprentissage, érudition","がく","学"  ],
  ["après","のち","後"  ],
  ["après [suffixe]","ご","後"  ],
  ["après-demain","みょうごにち","明後日"  ],
  ["architecture, construction","けんちく","建築"  ],
  ["argent (métal)","ぎん","銀"  ],
  ["argent, espèces","きんせん","金銭"  ],
  ["arme","ぶき","武器"  ],
  ["armée, troupes","ぐん","軍"  ],
  ["armée, troupes, forces militaires","ぐんたい","軍隊"  ],
  ["arrangement, disposition, traitement","しょり","処理"  ],
  ["arrestation, capture","たいほ","逮捕"  ],
  ["arrêt de bus ou de tram","ていりゅうじょ","停留所"  ],
  ["arrêter, se concentrer sur, prêter attention à, se rappeler, garder à l'esprit, rester (dans un lieu, à un endroit) [一段] [vt]","とめる","留める・止める"  ],
  ["arrivée","とうちゃく","到着"  ],
  ["arriver à, mener à, conduire à [五段] [vi]","いたる","至る"  ],
  ["arriver en retard, être en retard","ちこくする","遅刻する"  ],
  ["arriver, avoir lieu, se produire [五段] [vi]","おこる","起こる"  ],
  ["art (en général)","げいじゅつ","芸術"  ],
  ["article de journal, compte-rendu","きじ","記事"  ],
  ["article, bien, produit","しな","品"  ],
  ["articles, marchandise, stock","しょうひん","商品"  ],
  ["artificiel","じんこう","人工"  ],
  ["assemblée, convention, rassemblement","たいかい","大会"  ],
  ["assistant, personne qui aide","てつだい","手伝い"  ],
  ["association d'idées, suggestion","れんそう","連想"  ],
  ["association, coopération, collaboration","きょうどう","共同"  ],
  ["association, relation, amitié, compagnie, connaissance","こうさい","交際"  ],
  ["assoupi, somnolant","いねむり","居眠り"  ],
  ["asssemblage, composition, organisation","こうせい","構成"  ],
  ["astucieux, malin, intelligent","りこう","利口"  ],
  ["atmosphère","たいき","大気"  ],
  ["attacher, lier, connecter, transférer (un appel téléphonique) [五段] [vt]","つなぐ","繋ぐ"  ],
  ["attacher, nouer, lier [五段]","むすぶ","結ぶ"  ],
  ["attaque, assaut, offensive","こうげき","攻撃"  ],
  ["attente, espoir, espérance","きたい","期待"  ],
  ["attention (le fait de faire attention à quelque chose), observation","ちゅうもく","注目"  ],
  ["attitude, manière","たいど","態度"  ],
  ["au fait, à propos","ところで",""  ],
  ["au maximum, au mieux, autant que possible","せいぜい","精々"  ],
  ["au même moment, simultanément","どうじ","同時"  ],
  ["au milieu de, en cours de, parmi","さいちゅう","最中"  ],
  ["aube, aurore","よあけ","夜明け"  ],
  ["auberge, logement","やど","宿"  ],
  ["audience, spectateurs","かんきゃく","観客"  ],
  ["augmentation, addition","ぞうか","増加"  ],
  ["augmenter, grandir, croître [五段]","ます","増す"  ],
  ["auparavant, autrefois","いぜん","以前"  ],
  ["auteur (d'un livre), écrivain","ちょしゃ","著者"  ],
  ["auteur, écrivain","さっか","作家"  ],
  ["autographe, signature","しょめい","署名"  ],
  ["autographe, signature [sign (en)]","サイン",""  ],
  ["automatique","じどう","自動"  ],
  ["autoriser, approuver, permettre","きょかする","許可する"  ],
  ["autre personne, étranger, inconnu","たにん","他人"  ],
  ["aux environs","あたり","辺り"  ],
  ["avancée, progrès","ぜんしん","前進"  ],
  ["avancer, promouvoir, faire progresser [一段] [vt]","すすめる","進める"  ],
  ["avant longtemps, bientôt","やがて","軈て"  ],
  ["avare, radin, mesquin","けち",""  ],
  ["avec exactitude, avec précision, avec soin","きちんと",""  ],
  ["avec le sourire","にっこり",""  ],
  ["avenir, fin, futur","すえ","末"  ],
  ["aventure, risque, danger","ぼうけん","冒険"  ],
  ["avertissement, mise en garde","けいこく","警告"  ],
  ["aviation","ひこう","飛行"  ],
  ["aviation","こうくう","航空"  ],
  ["avion à réaction","ジェットき","ジェット機"  ],
  ["baie, crique, golfe","わん","湾"  ],
  ["bain","ふろ","風呂"  ],
  ["balle, bol [ball, bowl (en)]","ボール",""  ],
  ["balle, spère, projectile","たま","玉・球・弾"  ],
  ["banc [bench (en)]","ベンチ",""  ],
  ["base, fondement, norme","きほん","基本"  ],
  ["base, origine, fondement, cause","もと","元・素・基"  ],
  ["bataille, combat","たたかい","戦い"  ],
  ["bateau [boat (en)]","ボート",""  ],
  ["bâton, baguette, barre","ぼう","棒"  ],
  ["beau, joli [handsome (en)]","ハンサム",""  ],
  ["beaucoup de monde, foule","ひとごみ","人混み・人込み"  ],
  ["beaucoup, très","おおいに","大いに"  ],
  ["belle femme","びじん","美人"  ],
  ["belle-fille, bru","よめ","嫁"  ],
  ["bien couper, être tranchant, se casser, rompre, être blessé, manquer de, battre (un temps par exemple), perdre son sang-froid, s'effondrer [一段] [vi]","きれる","切れる"  ],
  ["biens, fortune, richesse","ざいさん","財産"  ],
  ["bière [beer (en)]","ビール",""  ],
  ["bijou, pierre précieuse","ほうせき","宝石"  ],
  ["billet de banque, feuille [suffixe]","さつ","札"  ],
  ["blague","じょうだん","冗談"  ],
  ["blé","こむぎ","小麦"  ],
  ["blessure, coup, dommage","がい","害"  ],
  ["blessure, coupure, cicatrice, lésion, éclat","きず","傷"  ],
  ["boîte de conserve, cannette","かん","缶"  ],
  ["bon, de qualité, supérieur","じょうとう","上等"  ],
  ["bonheur, bénédiction, chance","しあわせ","幸せ"  ],
  ["bonheur, félicité","さいわい","幸い"  ],
  ["bonheur, prospérité","こうふく","幸福"  ],
  ["bord extérieur, rebord, coin","ふち","縁"  ],
  ["Bouddha, défunt, mort","ほとけ","仏"  ],
  ["boue","どろ","泥"  ],
  ["bouger, changer, déplacer, mettre en mouvement [五段] [vt]","うごかす","動かす"  ],
  ["bouquet, botte, paquet","たば","束"  ],
  ["bourgeon, bouton (d'une fleur)","め","芽"  ],
  ["bourse d'étude","しょうがくきん","奨学金"  ],
  ["bouteille, bocal, flacon","びん","瓶"  ],
  ["bref, en d'autres mots, au final","つまり","詰まり"  ],
  ["briller, scintiller [五段]","かがやく","輝く"  ],
  ["briquet, écrivain, motard [lighter, writer, rider (en)]","ライター",""  ],
  ["brouillard","きり","霧"  ],
  ["bruit","ものおと","物音"  ],
  ["bruit","そうおん","騒音"  ],
  ["bruit, tapage, agitation","さわぎ","騒ぎ"  ],
  ["brûler, se consumer [一段] [vi]","もえる","燃える"  ],
  ["brut, cru","なま","生"  ],
  ["budget, devis","よさん","予算"  ],
  ["bureau (de travail)","しょさい","書斎"  ],
  ["bureau (du travail) [office (en)]","オフィス",""  ],
  ["but [goal (en)]","ゴール",""  ],
  ["c'est-à-dire","すなわち","即ち"  ],
  ["cabane, hutte, abris, enclos (pour un animal)","こや","小屋"  ],
  ["cacher, dissimuler [五段] [vt]","かくす","隠す"  ],
  ["caisse, valise, cas [case (en)]","ケース",""  ],
  ["calcul","けいさん","計算"  ],
  ["calcul, compte, prise en compte","かんじょう","勘定"  ],
  ["calme, plat, assis en tailleur","たいら","平ら"  ],
  ["calme, serein","れいせい","冷静"  ],
  ["calme, tranquille, paisible","おだやか","穏やか"  ],
  ["camarades, copains, compagnons","なかま","仲間"  ],
  ["camion, piste (de course, d'un CD) [truck, track (en)]","トラック",""  ],
  ["camping, camp [camp (en)]","キャンプ",""  ],
  ["canapé, sofa, divant [sofa (en)]","ソファー",""  ],
  ["candidat, concurrent, candidature","こうほ","候補"  ],
  ["candide, naïf, simple","たんじゅん","単純"  ],
  ["capacité, compétence","のうりょく","能力"  ],
  ["capacités intellectuelles, intelligence","ちのう","知能"  ],
  ["capitaine [captain (en)]","キャプテン",""  ],
  ["capital, fond monétaire","しほん","資本"  ],
  ["capitale","しゅと","首都"  ],
  ["capitale, métropole","みやこ","都"  ],
  ["caractère, tempérament","せいかく","性格"  ],
  ["caractéristique, particularité","とくちょう","特徴"  ],
  ["carie, dent cariée","むしば","虫歯"  ],
  ["carte [card (en)]","カード",""  ],
  ["cartes à jouer [trump (en)]","トランプ",""  ],
  ["casserole, marmite","なべ","鍋"  ],
  ["ce dernier, cette dernière","こうしゃ","後者"  ],
  ["ceinture [belt (en)]","ベルト",""  ],
  ["ceinture de kimono","おび","帯"  ],
  ["célébrer, fêter [五段] [vt]","いわう","祝う"  ],
  ["célibat","どくしん","独身"  ],
  ["cendre","はい","灰"  ],
  ["centre [center (en)]","センター",""  ],
  ["centre, milieu, cœur, pivot","ちゅうしん","中心"  ],
  ["cependant","だけど",""  ],
  ["cependant, même si, néanmoins","それでも","其れでも"  ],
  ["cercle, anneau, boucle, compteur pour les roues et les fleurs","わ","輪"  ],
  ["cercle, rond, suffixe pour les noms de bateaux","まる","丸"  ],
  ["cerisier, fleur de cerisier","さくら","桜"  ],
  ["certitude, fiabilité","かくじつ","確実"  ],
  ["ces","これら","此れ等"  ],
  ["cesser, arrêter, abandonner [五段] [vt]","よす","止す"  ],
  ["cette fois-ci","こんかい","今回"  ],
  ["chaîne (de TV ou de radio)","きょく","局"  ],
  ["chaîne (en métal)","くさり","鎖"  ],
  ["chair, corps, individu, personne","み","身"  ],
  ["chaleur","おんだん","温暖"  ],
  ["champ","はたけ","畑"  ],
  ["champ, plaine, campagne","の","野"  ],
  ["chance, bonne fortune","こううん","幸運"  ],
  ["chance, occasion [chance (en)]","チャンス",""  ],
  ["change (monnaie)","りょうがえ","両替"  ],
  ["changement, modification","へんこう","変更"  ],
  ["changement, transformation","へんか","変化"  ],
  ["chanteur, chanteuse","かしゅ","歌手"  ],
  ["charbon, houille","せきたん","石炭"  ],
  ["charger (des bagages), embarquer, déposer quelqu'un en voiture, mentionner, publier (une annonce) [一段] [vt]","のせる","乗せる・載せる"  ],
  ["charme, conquête, victoire","こくふく","克服"  ],
  ["charme, séduction","みりょく","魅力"  ],
  ["château","しろ","城"  ],
  ["chemin, passe (dans un jeu de balle) [path, pass (en)]","パス",""  ],
  ["chemins de fer","てつどう","鉄道"  ],
  ["cheval","うま","馬"  ],
  ["cheveux","かみのけ","髪の毛"  ],
  ["chez soi, maison","たく","宅"  ],
  ["chiffre","すうじ","数字"  ],
  ["chiffre, nombre","かず","数"  ],
  ["chimie","かがく","化学"  ],
  ["chômage","しつぎょう","失業"  ],
  ["chose, affaire","ものごと","物事"  ],
  ["cime, point culminant","ちょうじょう","頂上"  ],
  ["circonstances, conditions, situation","じじょう","事情"  ],
  ["ciseaux","はさみ","剪刀・鋏"  ],
  ["citoyens, habitants, population","じゅうみん","住民"  ],
  ["civilisation, culture","ぶんめい","文明"  ],
  ["clair, qui clarifie, qui précise les choses","めいかく","明確"  ],
  ["clair, simple, facile","ようい","容易"  ],
  ["clarté, lumières","あかり","明かり"  ],
  ["classe (d'élèves), groupe (de personnes), équipe","くみ","組"  ],
  ["classique [classic (en)]","クラッシック",""  ],
  ["climat","きこう","気候"  ],
  ["coach, entraineur [coach (en)]","コーチ",""  ],
  ["code, corde [code, cord (en)]","コード",""  ],
  ["cœur (organe)","しんぞう","心臓"  ],
  ["coffre-fort, chambre forte","きんこ","金庫"  ],
  ["coïncident, accord, conformité, coopération","いっち","一致"  ],
  ["colis, paquet","こづつみ","小包"  ],
  ["collège","ちゅうがく","中学"  ],
  ["collègue, associé, collègue de travail","どうりょう","同僚"  ],
  ["colline","おか","丘"  ],
  ["collision","しょうとつ","衝突"  ],
  ["combattre, lutter [五段] [vi]","たたかう","戦う"  ],
  ["commande, ordre","ちゅうもん","注文"  ],
  ["commandement, direction, leadership","しどう","指導"  ],
  ["commémoration, souvenir","きねん","記念"  ],
  ["commencement, début","かいし","開始"  ],
  ["comment ?, combien ?","どんなに",""  ],
  ["commercant, marchant, vendeur","しょうにん","商人"  ],
  ["commerce, affaire, business","えいぎょう","営業"  ],
  ["commerce, business, transaction","しょうばい","商売"  ],
  ["compagnon (personne qui accompagne quelqu'un)","つれ","連れ"  ],
  ["comparaison","ひかく","比較"  ],
  ["compétent, capable, efficace","ゆうのう","有能"  ],
  ["complètement, entièrement","ぜんたい","全体"  ],
  ["complètement, entièrement, totalement, vraiment, effectivement","まったく","全く"  ],
  ["comportement, manières","ぎょうぎ","行儀"  ],
  ["composante, élément (d'un tableau par exemple)","ようそ","要素"  ],
  ["composer (de la musique)","さっきょくする","作曲する"  ],
  ["compréhension","りかい","理解"  ],
  ["comptabilité","かいけい","会計"  ],
  ["compte-rendu, rapport [report (en)]","レポート・リポート",""  ],
  ["compter [一段] [vt]","かぞえる","数える"  ],
  ["compter sur, avoir recours à, dépendre de [五段] [vi]","たよる","頼る"  ],
  ["compteur pour les chapitres [suffixe]","しょう","章"  ],
  ["compteur pour les chapîtres ou les leçons [suffixe]","か","課"  ],
  ["compteur pour les maisons ou les immeubles [suffixe]","けん","軒"  ],
  ["compteur pour les plats d'un repas [suffixe]","ひん","品"  ],
  ["concentration","しゅうちゅう","集中"  ],
  ["conclusion (d'un document, d'un rapport…)","けつろん","結論"  ],
  ["concret, tangible","ぐたい","具体"  ],
  ["condamner, blâmer, critiquer [一段] [vt]","せめる","責める"  ],
  ["condition, circonstance, situation","じょうきょう","状況"  ],
  ["condition, état de santé, degré, mesure, addition et soustraction","かげん","加減"  ],
  ["condition, terme d'un contrat","じょうけん","条件"  ],
  ["conférence, discours","こうえん","講演"  ],
  ["confiance","しんらい","信頼"  ],
  ["confier à la garde de, laisser quelqu'un à la charge de [一段] [vi]","あずける","預ける"  ],
  ["confier, laisser faire, charger quelqu'un de faire quelque chose, continuer quelque chose sans but particulier [一段] [vt]","まかせる","任せる"  ],
  ["confirmation, vérification","かくにん","確認"  ],
  ["conformément à, par conséquence","したがって","従って"  ],
  ["confortable, tranquille","らく","楽"  ],
  ["confusion, désordre","こんらん","混乱"  ],
  ["confusion, encombrement","こんざつ","混雑"  ],
  ["congé, vacances","きゅうか","休暇"  ],
  ["conjugaison, mise en pratique, application","かつよう","活用"  ],
  ["connaissance, savoir","ちしき","知識"  ],
  ["conscience","いしき","意識"  ],
  ["consécutif, successif, d'affilée","れんぞくで","連続で"  ],
  ["conservation, entretien","いじ","維持"  ],
  ["conservation, stockage, préservation","ほぞん","保存"  ],
  ["considérable, assez importante","かなり","可也"  ],
  ["consommation","しょうひ","消費"  ],
  ["Constitution","けんぽう","憲法"  ],
  ["construction, établissement","けんせつ","建設"  ],
  ["conte, histoire, légende","ものがたり","物語"  ],
  ["contenu, matière, substance, sujet","ないよう","内容"  ],
  ["continent","たいりく","大陸"  ],
  ["continuation, suite","つづき","続き"  ],
  ["contrat, accord, engagement","けいやく","契約"  ],
  ["contribution, donation","きふ","寄付"  ],
  ["contribution, service","こうけん","貢献"  ],
  ["contrôle, direction, supervision","かんとく","監督"  ],
  ["convenable, équitable, tolérable, propre","そうとう","相当"  ],
  ["convenir, être convenable, être approprié","てきする","適する"  ],
  ["coopération, collaboration","きょうりょく","協力"  ],
  ["copie d'examen","とうあん","答案"  ],
  ["copie, photocopie [copy (en)]","コピー",""  ],
  ["corde","なわ","縄"  ],
  ["corde, lacet, ficelle, proxénète","ひも","紐"  ],
  ["corne","つの","角"  ],
  ["corps (physique)","しんたい","身体"  ],
  ["correct, exact, juste, précis","せいかく","正確"  ],
  ["correctement","ちゃんと",""  ],
  ["correspondance, communication","つうしん","通信"  ],
  ["côté, flanc","わき","脇"  ],
  ["côte, rivage, rive","きし","岸"  ],
  ["coton","めん","綿"  ],
  ["coton","わた","綿"  ],
  ["coucher du soleil, crépuscule, fin de l'année","くれ","暮れ"  ],
  ["couper, séparer, casser, briser [五段] [vt]","わる","割る"  ],
  ["couple marié, mari et femme, époux","ふうふ","夫婦"  ],
  ["courage, bravoure","ゆうき","勇気"  ],
  ["courtoisie, politesse, manières","れいぎ","礼儀"  ],
  ["cousin","いとこ","従兄弟"  ],
  ["coût de la vie, les prix (en général)","ぶっか","物価"  ],
  ["coût, dépense","ひよう","費用"  ],
  ["coût, prix, valeur","かかく","価格"  ],
  ["coût, prix, valeur, mérite","ね","値"  ],
  ["couverture en laine","もうふ","毛布"  ],
  ["craindre, avoir peur de [一段] [vt]","おそれる","畏れる・恐れる"  ],
  ["cramoisi, pourpre","まっか","真っ赤"  ],
  ["crème [cream (en)]","クリーム",""  ],
  ["crème glacée [ice cream (en)]","アイスクリーム",""  ],
  ["crime, faute, péché","つみ","罪"  ],
  ["critique, commentaire","ひはん","批判"  ],
  ["critique, commentaire","ひひょう","批評"  ],
  ["croire [一段] [vt]","しんじる","信じる"  ],
  ["croire, avoir confiance en, se fier à","しんようする","信用する"  ],
  ["croiser (les bras par exemple), traverser [五段] [vt]","よこぎる","横切る"  ],
  ["croissance, développement","せいちょう","成長"  ],
  ["d'ailleurs, de plus, en plus","さらに","更に"  ],
  ["d'ailleurs, de plus, en plus","しかも","而も"  ],
  ["d'autre part, de plus, en outre","なお","尚"  ],
  ["d'ici peu","いまに","今に"  ],
  ["d'occasion, de seconde main","ちゅうこ","中古"  ],
  ["d'un coup, soudainement","とつぜん","突然"  ],
  ["d'un coup, soudainement, sans attendre","ばったり",""  ],
  ["d'une autre direction, d'un autre côté","いっぽう","一方"  ],
  ["dame, femme, Mme","ふじん","夫人"  ],
  ["dans tous le pays, national","ぜんこく","全国"  ],
  ["danse [dance (en)]","ダンス",""  ],
  ["date","ひづけ","日付"  ],
  ["davantage, encore plus","いっそう","一層"  ],
  ["de cette manière, de cette façon","こんなに",""  ],
  ["de forme, de style, similaire à, à la manière de [suffixe]","よう","様"  ],
  ["de l'autre côté de, en face de","むかい","向かい"  ],
  ["de nombreux, beaucoup de [préfixe]","すう","数"  ],
  ["de nos jours, à notre époque","きんだい","近代"  ],
  ["de nos jours, de notre époque","げんだい","現代"  ],
  ["de plus en plus","ますます","益々"  ],
  ["de tous les jours, ordinaire","にちじょう","日常"  ],
  ["de toute façon","とにかく","兎に角"  ],
  ["débat, discussion","ぎろん","議論"  ],
  ["débattre, discuter [一段] [vt]","ろんじる","論じる"  ],
  ["début, origine","はじまり","始まり"  ],
  ["décerner, offrir, donner [一段] [vt]","あたえる","与える"  ],
  ["déchirer, rompre, détruire, casser [五段] [vt]","やぶる","破る"  ],
  ["décision","けってい","決定"  ],
  ["décision, choix","せんたく","選択"  ],
  ["découverte","はっけん","発見"  ],
  ["décrire, dessiner, tracer [五段] [vt]","えがく","描く"  ],
  ["défaite","まけ","負け"  ],
  ["défaut, déficience, manque","けっかん","欠陥"  ],
  ["défaut, imperfection, point faible","けってん","欠点"  ],
  ["défavorable, inconvénient, désavantage","ふり","不利"  ],
  ["défendre, protéger, prévenir (un danger) [五段] [vt]","ふせぐ","防ぐ"  ],
  ["dehors, à l'extérieur [out (en)]","アウト",""  ],
  ["déjà, trop tard","すでに","既に"  ],
  ["délicat, subtile","びみょう","微妙"  ],
  ["délier, enlever [五段] [vt]","はずす","外す"  ],
  ["délinquant, criminel","はんにん","犯人"  ],
  ["délit","はんざい","犯罪"  ],
  ["demande, réclamation, requête","せいきゅう","請求"  ],
  ["demande, requête","いらい","依頼"  ],
  ["demande, requête","ようきゅう","要求"  ],
  ["demande, requête","じゅよう","需要"  ],
  ["démenti, refus, négation","ひてい","否定"  ],
  ["démissionner, quitter une entreprise [一段] [vt]","やめる","辞める"  ],
  ["démon, diable, mauvais esprit","あくま","悪魔"  ],
  ["démon, monstre","おに","鬼"  ],
  ["démonstration, manifestion politique [demonstration (en)]","デモ",""  ],
  ["dense, épais","みつ","密"  ],
  ["départ d'un véhicule","はっしゃ","発車"  ],
  ["dépasser, exceller, surpasser [一段] [vi]","すぐれる","優れる"  ],
  ["dépenses","ししゅつ","支出"  ],
  ["déplacement, aller simple","いき・ゆき","行き"  ],
  ["déplacement, mouvement, migration","いどう","移動"  ],
  ["déplacer, transporter, infecter [五段] [vt]","うつす","移す"  ],
  ["depuis","いらい","以来"  ],
  ["depuis [préfixe]","らい","来"  ],
  ["dernier, final","さいしゅう","最終"  ],
  ["dérober, voler [五段] [vt]","うばう","奪う"  ],
  ["désastre, décès, malheur","ふこう","不幸"  ],
  ["désert","さばく","砂漠"  ],
  ["désespérant, pénible, douloureux","つらい","辛い"  ],
  ["désespoir","しつぼう","失望"  ],
  ["désigner, montrer, identifier [五段] [vt]","さす","指す"  ],
  ["désirer, demander, souhaiter [五段] [vt]","ねがう","願う"  ],
  ["dessin, illustration, schéma, plan","ず","図"  ],
  ["destruction, extinction","ぜつめつ","絶滅"  ],
  ["détaillé, précis, exact","くわしい","詳しい"  ],
  ["détermination, résolution","けっしん","決心"  ],
  ["détester [五段] [vt]","きらう","嫌う"  ],
  ["dette, emprunt","しゃっきん","借金"  ],
  ["développement, croissance","はったつ","発達"  ],
  ["développement, croissance, essor, expansion","はってん","発展"  ],
  ["devenir énervé","いらいら","苛々"  ],
  ["devenir fou, se détraquer, aller de travers [五段] [vi]","くるう","狂う"  ],
  ["devoir, fonction, responsabilité","つとめ","務め"  ],
  ["devoir, obligation, responsabilité","ぎむ","義務"  ],
  ["Diète, Congrès, Parlement, assemblée","ぎかい","議会"  ],
  ["dieu, Dieu","かみ","神"  ],
  ["différence, divergence","ちがい","違い"  ],
  ["différence, variation, écart","さ","差"  ],
  ["difficulté, désarroi","こんなん","困難"  ],
  ["difficulté, trouble, problème, soin","めんどう","面倒"  ],
  ["dimanche","にちよう・にち","日曜・日"  ],
  ["diminuer, réduire, baisser [五段] [vi]","へる","減る"  ],
  ["diminuer, réduire, raccourcir [五段] [vt]","へらす","減らす"  ],
  ["diplomatie","がいこう","外交"  ],
  ["direct, immédiat","ちょくせつ","直接"  ],
  ["directement, sans intermédiaire","じかに","直に"  ],
  ["direction, côté, orientation","ほうこう","方向"  ],
  ["discours, allocution","えんぜつ","演説"  ],
  ["discours, allocution [speech (en)]","スピーチ",""  ],
  ["discrimination, différentiation, distinction","さべつ","差別"  ],
  ["disparaître, se cacher [一段] [vi]","かくれる","隠れる"  ],
  ["distinction, différentiation, classification","くべつ","区別"  ],
  ["divorce","りこん","離婚"  ],
  ["doctrine, principe, règle","しゅぎ","主義"  ],
  ["document","しょるい","書類"  ],
  ["document, dossier, score, record","きろく","記録"  ],
  ["domaine principale, spécialité","せんこう","専攻"  ],
  ["domaine, secteur, branche","ぶんや","分野"  ],
  ["domination, contrôle","しはい","支配"  ],
  ["dommage, dégât","そんがい","損害"  ],
  ["dommage, perte, dégât","そん","損"  ],
  ["dommages, dégâts","ひがい","被害"  ],
  ["donc, par conséquent","ですから",""  ],
  ["donner son avis, exprimer, affirmer [一段] [vt]","のべる","述べる"  ],
  ["donner, décerner, offrir [五段] [vt]","おくる","贈る"  ],
  ["doucement, furtivement","そっと",""  ],
  ["douleur","いたみ","痛み"  ],
  ["douleur, souffrance","くつう","苦痛"  ],
  ["douloureux, pénible","くるしい","苦しい"  ],
  ["doute, problème, question","ぎもん","疑問"  ],
  ["douter de, suspecter, soupçonner [五段] [vt]","うたがう","疑う"  ],
  ["douves, tranchée, fossé","ほり","濠"  ],
  ["drapeau","はた","旗"  ],
  ["droit, privilège","けんり","権利"  ],
  ["dur, solide, tendu, raide, formel, têtu, obstiné","かたい","固い・堅い・硬い"  ],
  ["durant la journée","にっちゅう","日中"  ],
  ["durant toute l'année, tout le temps","ねんじゅう","年中"  ],
  ["durée déterminée, période fixe","ていき","定期"  ],
  ["échange, substitution, remplacement","こうかん","交換"  ],
  ["échanger, remplacer, substituer [一段] [vt]","かえる","代える・替える・換える"  ],
  ["échelon, niveau, grade, rang","ていど","程度"  ],
  ["économies (réserve d'argent), épargne","ちょきん","貯金"  ],
  ["édition, publication","しゅっぱん","出版"  ],
  ["éducation physique","たいいく","体育"  ],
  ["effet, influence","えいきょう","影響"  ],
  ["efficacité, résultat, effet","こうか","効果"  ],
  ["effort, peine","どりょく","努力"  ],
  ["effort, travail, labeur","てま","手間"  ],
  ["égal, similaire, identique","ひとしい","等しい"  ],
  ["égalité, impartialité","びょうどう","平等"  ],
  ["égoïste","わがまま","我侭"  ],
  ["eh bien…","まあ",""  ],
  ["électron","でんし","電子"  ],
  ["éléphant","ぞう","象"  ],
  ["élever (des enfants), grandir [五段] [vi]","そだつ","育つ"  ],
  ["élever un animal [五段] [vt]","かう","飼う"  ],
  ["embaucher, employer, louer (un moyen de transport) [五段] [vt]","やとう","雇う"  ],
  ["embouteillage","じゅうたい","渋滞"  ],
  ["emmerdement, embêtement, ennui (vulg)","めいわく","迷惑"  ],
  ["émotion, sentiment","かんじょう","感情"  ],
  ["emplacement, lieu, endroit, espace","ば","場"  ],
  ["emploi, poste","しょく","職"  ],
  ["empoigner, saisir, attraper, modeler des sushis [五段] [vt]","にぎる","握る"  ],
  ["empreinte, marque","あと","跡"  ],
  ["en bref","ようするに","要するに"  ],
  ["en commun","きょうつう","共通"  ],
  ["en réalité","じつは","実は"  ],
  ["encre [ink (en)]","インク・インキ",""  ],
  ["énergie [energy (en)]","エネルギー",""  ],
  ["énergie, vivacité, enjouement","かっき","活気"  ],
  ["enfant perdu","まいご","迷子"  ],
  ["énigme, devinette, mystère","なぞ","謎"  ],
  ["enlever, exclure, éliminer [五段] [vt]","のぞく","除く"  ],
  ["ennemi, adversaire, concurrent","てき","敵"  ],
  ["ennuyeux, monotone","たいくつ","退屈"  ],
  ["énorme, considérable, important, significatif","たいした","大した"  ],
  ["énorme, vaste, immense","ばくだい","莫大"  ],
  ["enquête, investigation, recherche","ちょうさ","調査"  ],
  ["ensemble, avec","ともに","共に"  ],
  ["ensemble, manche (au tennis), série [set (en)]","セット",""  ],
  ["ensuite, de plus, et","そして","然して"  ],
  ["entièrement, complètement, comme si, pour ainsi dire","まるで","丸で"  ],
  ["entourer, encercler, clôturer [五段] [vt]","かこむ","囲む"  ],
  ["entrain, vigueur, force","いきおい","勢い"  ],
  ["entraînement, exercice","くんれん","訓練"  ],
  ["entreprendre, avoir du succès, être assigné, être équivalent à [五段] [vi]","あたる","当たる"  ],
  ["entreprise","きぎょう","企業"  ],
  ["entrer à l'université","しんがくする","進学する"  ],
  ["environ","やく","約"  ],
  ["environ, à peu près, approximativement","およそ","凡そ"  ],
  ["environnement, milieu, situation","かんきょう","環境"  ],
  ["éparge, économie","せつやく","節約"  ],
  ["épaule","かた","肩"  ],
  ["épingle [pin (en)]","ピン",""  ],
  ["épouvantable, effrayant","おそろしい","恐ろしい"  ],
  ["équilibre, balance, moyenne","へいきん","平均"  ],
  ["équilibre, stabilité","あんてい","安定"  ],
  ["équipe [team (en)]","チーム",""  ],
  ["équipement, installation, aménagement","せつび","設備"  ],
  ["équipement, installation, matériel","そうち","装置"  ],
  ["erreur","あやまり","誤り"  ],
  ["erreur, échec, mademoiselle, mythe [mistake, Miss, myth (en)]","ミス",""  ],
  ["erreur, faute","まちがい","間違い"  ],
  ["espèce, argent liquide","げんきん","現金"  ],
  ["espoir, souhait","きぼう","希望"  ],
  ["essai, test","ためし","試し"  ],
  ["essayer, tenter [五段] [vt]","ためす","試す"  ],
  ["essentiel, important","じゅうよう","重要"  ],
  ["estimation, approximation, supposition, direction","けんとう","見当"  ],
  ["estomac, ventre","い","胃"  ],
  ["et bien (pour faire la transition entre deux sujets différents)","さて","偖"  ],
  ["établir, décréter, introduire","じっしする","実施する"  ],
  ["état actuel, situation présente","げんじょう","現状"  ],
  ["état des choses, situation","じたい","事態"  ],
  ["état, aspect, apparence","ようす","様子"  ],
  ["état, pays, nation","こっか","国家"  ],
  ["état, province","しゅう","州"  ],
  ["état, situation, condition","じょうたい","状態"  ],
  ["étendue, envergure, portée","はんい","範囲"  ],
  ["éternel, perpétuel","えいえん","永遠"  ],
  ["éternité, perpétuité","えいきゅう","永久"  ],
  ["étoffe, morceau de tissu, tranche, morceau, compteur pour les tranches","きれ","切れ"  ],
  ["étoffe, tissu","ぬの","布"  ],
  ["étoffe, tissu, vraie nature de quelqu'un, poterie non vernie, pâte non préparée","きじ","生地"  ],
  ["étrange, anormal","いじょう","異常"  ],
  ["étrange, bizarre","きみょう","奇妙"  ],
  ["étrange, extraordinaire, mistérieux, miraculeux","ふしぎ","不思議"  ],
  ["étrange, inhabituel","みょう","妙"  ],
  ["étranger, extérieur","かいがい","海外"  ],
  ["être attrapé, être capturé, être pris [五段] [vi]","つかまる","捕まる"  ],
  ["être complètement absorbé dans, être à fond dans","ねっちゅうする","熱中する"  ],
  ["être concerné à, être lié à, être en lien avec","かんする","関する"  ],
  ["être content de, convenir, plaire","きにいる","気に入る"  ],
  ["être déçu, être découragé, être démoralisé","がっかりする",""  ],
  ["être dépourvu, être manquant, être absent, être déficitaire [一段] [vi]","かける","欠ける"  ],
  ["être différent de, varier, différer [五段] [vi]","ことなる","異なる"  ],
  ["être efficace, faire son travail, être possible d'utiliser [五段] [vi]","きく","効く"  ],
  ["être en charge de","たんとうする","担当する"  ],
  ["être enlevé, disparaitre, être attrapé, être récolté, être interprêté [一段]","とれる","取れる"  ],
  ["être étourdi, distrait, évanoui, flou","ぼんやりする",""  ],
  ["être humain, homme","にんげん","人間"  ],
  ["être inférieur à, être plus petit que [五段] [vi]","おとる","劣る"  ],
  ["être inquiet, être soucieux [五段]","なやむ","悩む"  ],
  ["être nommé, accéder à une position, prendre un siège ou une position, partir, apprendre (sous la direction d'un enseignantà [五段]","つく","就く"  ],
  ["être originaire de, venir de","しゅっしん","出身"  ],
  ["être paresseux, se relâcher [一段] [vt]","なまける","怠ける"  ],
  ["être plein, être rempli, monter (en parlant de la marée), mûrir, expirer [一段] [vi]","みちる","満ちる"  ],
  ["être résolu, se défaire, se dénouer [一段] [vi]","とける","解ける"  ],
  ["être séparé de, partir, quitter [一段] [vi]","はなれる","離れる"  ],
  ["être silencieux [五段] [vi]","だまる","黙る"  ],
  ["être triste, regretter, s'affliger [五段] [vt]","かなしむ","悲しむ"  ],
  ["être vendu [一段] [vi]","うれる","売れる"  ],
  ["être vivant, animal","いきもの","生き物"  ],
  ["être vivant, organisme","せいぶつ","生物"  ],
  ["étreindre, embrasser [五段] [vt]","だく・いだく","抱く"  ],
  ["étude des langues","ごがく","語学"  ],
  ["étude, apprentissage","がくもん","学問"  ],
  ["études","がくしゅう","学習"  ],
  ["études à l'étranger","りゅうがく","留学"  ],
  ["étudier (une situation), inspecter ,mesurer, peser [五段] [vt]","はかる","計る・量る・測る"  ],
  ["étudier, apprendre en profondeur [五段]","まなぶ","学ぶ"  ],
  ["étudier, discuter de, examiner, considérer","けんとうする","検討する"  ],
  ["Europe [Europa (pt)]","ヨーロッパ",""  ],
  ["évaluer, estimer (un prix)","ひょうかする","評価する"  ],
  ["évident, clair","あきらか","明らか"  ],
  ["éviter, fuir [一段] [vt]","さける・よける","避ける"  ],
  ["exactement, certainement, précisément","まさに","正に"  ],
  ["exactement, précisément, avec soin","ぴったり",""  ],
  ["excellent, supérieur","ゆうしゅう","優秀"  ],
  ["excuse","もうしわけ","申し訳"  ],
  ["exercer (une influence, un effet sur quelque chose, causer, occasionner (des dégâts) [五段] [vt]","およぼす","及ぼす"  ],
  ["existence","そんざい","存在"  ],
  ["expérience","じっけん","実験"  ],
  ["expert, maître, virtuose","めいじん","名人"  ],
  ["explosion, détonation","ばくはつ","爆発"  ],
  ["exprès, intentionellement","わざと","態と"  ],
  ["expression du visage","ひょうじょう","表情"  ],
  ["extraire, sortir, débrancher, omettre, dépasser [五段] [vt]","ぬく","抜く"  ],
  ["extrait, citation","いんよう","引用"  ],
  ["extraordinaire, étonnant, urgent","ひじょう","非常"  ],
  ["face, masque, surface","めん","面"  ],
  ["faible, pauvre, pas doué, pas très bon","にがて","苦手"  ],
  ["faillite, ruine, banqueroute","はさん","破産"  ],
  ["faire couler, verser (des larmes…), répandre, faire circuler [五段] [vt]","ながす","流す"  ],
  ["faire descendre (un passager d'un véhicule), descendre, abaisser, retirer de l'argent d'un compte [五段] [vt]","おろす","下ろす・降ろす"  ],
  ["faire face à, se tourner vers, correspondre à [五段]","むく","向く"  ],
  ["faire une demande de, souscrire, s'abonner, demander (une interview, un entretien) [五段] [vt]","もうしこむ","申し込む"  ],
  ["familié","したしい","親しい"  ],
  ["fardeau, ennui, souci, tracas","やっかい","厄介"  ],
  ["farine","こな・こ","粉"  ],
  ["fatigue, épuisement","つかれ","疲れ"  ],
  ["faute, cause, raison","せい","所為"  ],
  ["faveur, dette de gratitude, obligation morale","おん","恩"  ],
  ["femme au foyer","しゅふ","主婦"  ],
  ["femme, dame","ふじん","婦人"  ],
  ["femme, fille","じょし","女子"  ],
  ["fer (minerai)","てつ","鉄"  ],
  ["fer à repasser [iron (en)]","アイロン",""  ],
  ["fermement, fixement","じっと",""  ],
  ["fermer, clore [一段]","とじる","閉じる"  ],
  ["fermier","のうか","農家"  ],
  ["fermier, paysan","のうみん","農民"  ],
  ["fesses, derrière, postérieur","しり","尻"  ],
  ["feux de circulation","しんごう","信号"  ],
  ["fiançailles","こんやく","婚約"  ],
  ["fier","とくい","得意"  ],
  ["fierté","ほこり","誇り"  ],
  ["fierté, orgueil, vantardise","じまん","自慢"  ],
  ["fin (d'une rue par exemple), extrémité, bout, rebord, marge","はし","端"  ],
  ["finalement, à la fin","ついに","遂に"  ],
  ["finalement, en fin de compte","けっきょく","結局"  ],
  ["finance (en général), crédit, flux monétaire","きんゆう","金融"  ],
  ["finir [一段] [vt]","すませる","済ませる"  ],
  ["flamme","ほのお","炎"  ],
  ["flot, courant, écoulement","ながれ","流れ"  ],
  ["flûte, pipeau","ふえ","笛"  ],
  ["foi, croyance","しんこう","信仰"  ],
  ["foire, marché","いち","市"  ],
  ["fonction","きのう","機能"  ],
  ["fonction, rôle","やくわり","役割"  ],
  ["fond, partie basse","そこ","底"  ],
  ["fontaine, source","いずみ","泉"  ],
  ["forme, modèle, type","かた","型"  ],
  ["fort, déterminé, serré (en parlant d'un vêtement), intense, difficile","きつい",""  ],
  ["fortune, chance, destinée","うん","運"  ],
  ["fournir, équiper, installer [一段] [vt]","そなえる","備える"  ],
  ["fournir, obtenir, stocker, récolter [一段] [vt]","おさめる","収める・納める・治める"  ],
  ["fracture d'un os","こっせつ","骨折"  ],
  ["frais","しんせん","新鮮"  ],
  ["frapper à la porte [knock (en)]","ノック",""  ],
  ["frapper, battre, taper [五段] [vt]","たたく","叩く"  ],
  ["frapper, tapper, cogner [五段]","ぶつ","打つ"  ],
  ["frein [brake (en)]","ブレーキ",""  ],
  ["fréquemment, sans cesse","しきりに","頻りに"  ],
  ["fréquentation, relation","つきあい","付き合い"  ],
  ["fréquenter une école, se rendre à l'école","つうがくする","通学する"  ],
  ["fromage [cheese (en)]","チーズ",""  ],
  ["front","ひたい","額"  ],
  ["frontière, limite","さかい","境"  ],
  ["frontières d'un pays","こっきょう","国境"  ],
  ["fruit, noisette, noix, contenu","み","実"  ],
  ["fumée","けむり","煙"  ],
  ["fusée, médaillon [rocket, locket (en)]","ロケット",""  ],
  ["futile, absurbe, inutile","むだ","無駄"  ],
  ["futur (lointain)","みらい","未来"  ],
  ["gagner de l'argent, travailler [五段] [vi]","かせぐ","稼ぐ"  ],
  ["garantie, assurance, sécurité","ほしょう","保証"  ],
  ["garçon, serveur [boy (en)]","ボーイ",""  ],
  ["gauche et droite, contrôle, influence","さゆう","左右"  ],
  ["gel, givre","しも","霜"  ],
  ["généralement, d'habitude","いっぱんに","一般に"  ],
  ["genoux","ひざ","膝"  ],
  ["genre, sexe","せい","性"  ],
  ["gestion, administration","けいえい","経営"  ],
  ["gestion, administration, contrôle","かんり","管理"  ],
  ["gigantesque, énorme","きょだい","巨大"  ],
  ["glace","こおり","氷"  ],
  ["glacer, congeler, geler [五段] [vi]","こおる","凍る"  ],
  ["glande, sol [gland, ground (en)]","グランド",""  ],
  ["goût, choix, préférence, penchant","このみ","好み"  ],
  ["gouttière","のき","軒"  ],
  ["gouvernement","せいふ","政府"  ],
  ["gouverneur d'une région","ちじ","知事"  ],
  ["grade, rang, niveau","くらい","位"  ],
  ["graine, céréale","こくもつ","穀物"  ],
  ["graine, pépin","たね","種"  ],
  ["grande guerre, grande bataille","たいせん","大戦"  ],
  ["grande vitesse, vitesse rapide, autoroute","こうそく","高速"  ],
  ["grandiose","いだい","偉大"  ],
  ["gratuit","むりょう","無料"  ],
  ["grogner, rugir, gémir, hurler [五段] [vi]","うなる","唸る・呻る"  ],
  ["grossier (texture), rugueux (surface)","あらい","粗い"  ],
  ["grossier, rude, simple, humble","そまつ","粗末"  ],
  ["grossièrement, rapidement, approximativement","ざっと",""  ],
  ["groupe [group (en)]","グループ",""  ],
  ["groupe, masse","しゅうだん","集団"  ],
  ["guérison, récupération (suite à une maladie), rétablissement","かいふく","回復"  ],
  ["habituel, d'usage, précédent","れい","例"  ],
  ["habituel, ordinaire","ふだん","普段"  ],
  ["hanche, région lombaire","こし","腰"  ],
  ["haute mer, le large","おき","沖"  ],
  ["homme, personne de sexe masculin","おとこのひと","男の人"  ],
  ["honnête","しょうじき","正直"  ],
  ["horaire, instant, moment","じこく","時刻"  ],
  ["horizon","ちへいせん","地平線"  ],
  ["huile","あぶら","油"  ],
  ["humanité","じんるい","人類"  ],
  ["humeur","きげん","機嫌"  ],
  ["humour [humour (en)]","ユーモア",""  ],
  ["ici et là","あちこち・あちらこちら","彼方・此方"  ],
  ["ici et là, partout","ほうぼう","方々"  ],
  ["idéal","りそう","理想"  ],
  ["idée, pensée, réflexion","かんがえ","考え"  ],
  ["identique, du même genre, semblable","どうよう","同様"  ],
  ["identité, similarité, égalité","どういつ","同一"  ],
  ["idiot, bête","ばか","馬鹿"  ],
  ["il est sûr que, c'est certain que","ちがいない","違いない"  ],
  ["imagination","そうぞう","想像"  ],
  ["imitation, parodie","まね","真似"  ],
  ["immédiatement, directement, en personne","ただちに","直ちに"  ],
  ["implémentation, matérialisation, réalisation","じつげん","実現"  ],
  ["important, grave, sérieux","じゅうだい","重大"  ],
  ["impossible !, hors de question !, absolument pas !, n'importe quoi !","とんでもない",""  ],
  ["impression (de documents)","いんさつ","印刷"  ],
  ["impression (sensation)","いんしょう","印象"  ],
  ["impression, sentiment","かんじ","感じ"  ],
  ["inattendu, surprenant","いがい","意外"  ],
  ["incendie, embrasement","かさい","火災"  ],
  ["incident, affaire","じけん","事件"  ],
  ["incident, évènement, affaire","できごと","出来事"  ],
  ["inclure, renfermer, contenir, garder à l'esprit [五段] [vt]","ふくむ","含む"  ],
  ["indépendance","どくりつ","独立"  ],
  ["index, tableau, liste, répertoire [suffixe]","ひょう","表"  ],
  ["indiquer, signifier, marquer, montrer [五段] [vt]","しめす","示す"  ],
  ["individu, personne","もの","者"  ],
  ["individuel, personnel, privé","こじん","個人"  ],
  ["information, renseignement","じょうほう","情報"  ],
  ["informations, nouvelles","たより","便り"  ],
  ["ingénieur, technicien","ぎし","技師"  ],
  ["ingrédients, données, matériel","ざいりょう","材料"  ],
  ["injuste, inique, illégal, malhonnête","ふせい","不正"  ],
  ["insatisfaction, mécontentement, déplaisir","ふまん","不満"  ],
  ["insécurité, anxiété","ふあん","不安"  ],
  ["inspection (des douanes, d'une usine…)","けんさ","検査"  ],
  ["insuffisant, défectueux, manque","ふそく","不足"  ],
  ["intelligent, sage, brillant","かしこい","賢い"  ],
  ["intention, but","いし","意思"  ],
  ["interdiction de fumer, défense de fumer","きんえん","禁煙"  ],
  ["interdiction, prohibition","きんし","禁止"  ],
  ["intérêt pour quelque chose","かんしん","関心"  ],
  ["intérieur, partie interne","おく","奥"  ],
  ["interprétation","かいしゃく","解釈"  ],
  ["interprétation, représentation musicale","えんそう","演奏"  ],
  ["interrupteur [switch (en)]","スイッチ",""  ],
  ["interruption, arrêt, suspension","ちゅうし","中止"  ],
  ["intervalle de temps, période","ま","間"  ],
  ["intolérable, insupportable","たまらない","堪らない"  ],
  ["intuition, sixième sens","かん","勘"  ],
  ["invention","はつめい","発明"  ],
  ["inversé, opposé","ぎゃく","逆"  ],
  ["inviter, causer, provoquer [五段] [vt]","まねく","招く"  ],
  ["inviter, tenter, attirer [五段] [vt]","さそう","誘う"  ],
  ["involontairement, fortuitement, instinctivement","おもわず","思わず"  ],
  ["Japon","にほん・にっぽん","日本"  ],
  ["jeans [jeans (en)]","ジーンズ",""  ],
  ["jeu [game (en)]","ゲーム",""  ],
  ["jeu d'un acteur, interprétation, performance d'un acteur","えんぎ","演技"  ],
  ["jeudi","もくよう・もく","木曜・木"  ],
  ["jeune fille, fille","しょうじょ","少女"  ],
  ["jeune homme","だんし","男子"  ],
  ["jeune, adolescent","しょうねん","少年"  ],
  ["jeunes hommes, jeunes","せいねん","青年"  ],
  ["joie, plaisir, satisfaction","よろこび","喜び"  ],
  ["joue","ほお","頬"  ],
  ["jour de la semaine","ようび","曜日"  ],
  ["journaliste","きしゃ","記者"  ],
  ["joyeux, heureux, plaisant","ゆかい","愉快"  ],
  ["jugement, décision, verdict, conclusion","はんだん","判断"  ],
  ["jugement, procès, arbitrage","しんばん","審判"  ],
  ["jumeau","ふたご","双子"  ],
  ["jus [juice (en)]","ジュース",""  ],
  ["juste au moment","とたん","途端"  ],
  ["juste une minute, juste un peu","しょうしょう","少々"  ],
  ["justice, équitabilité, impartialité","こうへい","公平"  ],
  ["katana (sabre japonais)","かたな","刀"  ],
  ["l'autre jour, il y a quelques jours","せんじつ","先日"  ],
  ["l'un après l'autre, chacun","ひとりひとり","一人一人"  ],
  ["la personne elle-même, elle-même, lui-même","ほんにん","本人"  ],
  ["laisser de côté, léguer, sauvegarder, garder en réserve [五段] [vt]","のこす","残す"  ],
  ["laisser passer, faire passer [五段] [vt]","とおす","通す"  ],
  ["lait [milk (en)]","ミルク",""  ],
  ["lamentable, malheureux, regrettable","きのどく","気の毒"  ],
  ["langage","げんご","言語"  ],
  ["langue (organe)","した","舌"  ],
  ["langue japonaise, langue nationale du Japon","こくご","国語"  ],
  ["langue, mot [suffixe]","ご","語"  ],
  ["lapin","うさぎ","兎"  ],
  ["largeur","はば","幅"  ],
  ["larme","なみだ","涙"  ],
  ["le dernier, le pire, le plus bas, dégoûtant, répugnant","さいてい","最低"  ],
  ["le fait de recevoir, s'il vous plait","ちょうだい","頂戴"  ],
  ["le fait de trouver un emploi, inauguration","しゅうしょく","就職"  ],
  ["le maximum, le plus","さいこう","最高"  ],
  ["le plus, extrêmement","もっとも","最も"  ],
  ["le premier (des deux)","ぜんしゃ","前者"  ],
  ["lecture","よみ","読み"  ],
  ["lecture","どくしょ","読書"  ],
  ["lecture japonaise des kanjis","くん","訓"  ],
  ["légal, officiel","せいしき","正式"  ],
  ["lentement, petit à petit, peu à peu","じょじょに","徐々に"  ],
  ["lettre de l'alphabet, caractères d'écriture","もじ・もんじ","文字"  ],
  ["libérer, éloigner, séparer [五段] [vt]","はなす","放す"  ],
  ["lieu actuel, scène du crime","げんば","現場"  ],
  ["lieu de naissance, village natal","こきょう","故郷"  ],
  ["limitation, restriction","せいげん","制限"  ],
  ["limite, frontière, bordure","げんかい","限界"  ],
  ["limiter, restreindre [五段] [vi]","かぎる","限る"  ],
  ["livraison, distribution","はいたつ","配達"  ],
  ["livre","としょ","図書"  ],
  ["livres","しょもつ","書物"  ],
  ["loi","ほう","法"  ],
  ["longue période","ちょうき","長期"  ],
  ["longueur, hauteur","たて","縦"  ],
  ["loyer","やちん","家賃"  ],
  ["lumière du soleil","にっこう","日光"  ],
  ["lundi","げつよう・げつ","月曜・月"  ],
  ["luxueux, extravagant","ぜいたく","贅沢"  ],
  ["machine à écrire [typewriter (en)]","タイプライター",""  ],
  ["machine, mécanisme, instrument","きかい","機械・器械"  ],
  ["mais, cependant","だが",""  ],
  ["mais, parce que, aussi","だって",""  ],
  ["maison, famille, lignée, style","いっか","一家"  ],
  ["maison, quai d'une gare [home, platform (en)]","ホーム",""  ],
  ["maîtriser, apprendre, maître [master (en)]","マスター",""  ],
  ["majorité, adulte","せいじん","成人"  ],
  ["majorité, grande partie, la plupart","だいぶぶん","大部分"  ],
  ["majorité, principalement, généralement","たいはん","大半"  ],
  ["malentendu, contresens","ごかい","誤解"  ],
  ["malheureusement","あいにく","生憎"  ],
  ["maman [mama (en)]","ママ",""  ],
  ["manche de vêtement","そで","袖"  ],
  ["manger (vulgaire), vivre, piquer (comme un insecte), taquiner, consommer (du temps ou des ressources) [五段] [vt]","くう","食う"  ],
  ["manière (dans le comportement)","さほう","作法"  ],
  ["manifestation, incarnation, expression","あらわれ","現れ"  ],
  ["manque de hauteur, infériorité, dernier tome d'un ensemble de 2 ou 3","げ","下"  ],
  ["manuel scolaire, livre scolaire","きょうかしょ","教科書"  ],
  ["manufacture, production","せいぞう","製造"  ],
  ["maquillage","けしょう","化粧"  ],
  ["marché (aux légumes, aux poissons, d'un produit…)","いちば","市場"  ],
  ["marché [market (en)]","マーケット",""  ],
  ["marche, colonne, échelon, rang","だん","段"  ],
  ["mardi","かよう・か","火曜・火"  ],
  ["marge, surplus, flexibilité, temps","よゆう","余裕"  ],
  ["marque, symbole","しるし","印"  ],
  ["match, compétition","きょうぎ","競技"  ],
  ["matière (à l'école), cours","かもく","科目"  ],
  ["matière, substance","ぶっしつ","物質"  ],
  ["mauvais, faux, injustifiable, déconseillé","ふか","不可"  ],
  ["mauvaise blague, sale tour","いたずら","悪戯"  ],
  ["mauvaise habitude, défaut","くせ","癖"  ],
  ["mécanisme, équipement, moteur, institution, organisation","きかん","機関"  ],
  ["médecin","いし","医師"  ],
  ["médisance, calomnie","わるぐち","悪口"  ],
  ["meilleur ami","しんゆう","親友"  ],
  ["membre [member (en)]","メンバー",""  ],
  ["membre d'un comité","いいん","委員"  ],
  ["membre d'une association","かいいん","会員"  ],
  ["membre de la Diète, du Congrès ou du Parlement","ぎいん","議員"  ],
  ["même si, bien que, quoi que, exemple","たとえ","例え"  ],
  ["même si, cependant","ところが","所が"  ],
  ["mémoire, souvenir, remémoration","きおく","記憶"  ],
  ["mémorisation, par coeur","あんき","暗記"  ],
  ["mener à, conduire à, comprendre [一段] [vi]","つうじる","通じる"  ],
  ["mère","ははおや","母親"  ],
  ["métal","きんぞく","金属"  ],
  ["météo, temps","てんこう","天候"  ],
  ["méthode, manière","ほうほう","方法"  ],
  ["mettre l'accent sur, insister sur","きょうちょうする","強調する"  ],
  ["meubles, mobilier","かぐ","家具"  ],
  ["micro [mike (en)]","マイク",""  ],
  ["midi","しょうご","正午"  ],
  ["migraine","ずつう","頭痛"  ],
  ["milieu, centre","ちゅうおう","中央"  ],
  ["ministre","だいじん","大臣"  ],
  ["minuit, en pleine nuit","よなか","夜中"  ],
  ["minutie, exhaustivité, complétude","てってい","徹底"  ],
  ["mode, tendance, vogue","りゅうこう","流行"  ],
  ["modéré, mesuré","てきど","適度"  ],
  ["mois et années","ねんげつ・としつき","年月"  ],
  ["moisson, récolte, collecte","しゅうかく","収穫"  ],
  ["moitié, mi-chemin, demi","なかば","半ば"  ],
  ["monde","よのなか","世の中"  ],
  ["montant (d'argent) [suffixe]","がく","額"  ],
  ["montant d'argent","きんがく","金額"  ],
  ["monter à Tôkyô, aller à Tôkyô","じょうきょうする","上京する"  ],
  ["montrer, afficher, révéler [五段] [vt]","あらわす","表す・現す・著す"  ],
  ["morale","どうとく","道徳"  ],
  ["mort certaine, résultat inéluctable, désespéré","ひっし","必死"  ],
  ["mort, mortalité","しぼう","死亡"  ],
  ["mot de vocabulaire","たんご","単語"  ],
  ["moteur [engine (en)]","エンジン",""  ],
  ["motif, design","がら","柄"  ],
  ["motif, figure","もよう","模様"  ],
  ["mousse, bulle","あわ","泡"  ],
  ["moyen, mesure","しゅだん","手段"  ],
  ["mur, clôture","へい","塀"  ],
  ["muscle, tendon","きんにく","筋肉"  ],
  ["muscle, tendon, ligament, ligne, action (d'un roman)","すじ","筋"  ],
  ["musée","はくぶつかん","博物館"  ],
  ["mutuel, réciproque","たがい","互い"  ],
  ["n'importe comment, chaque chose, tout","なんでも","何でも"  ],
  ["n'importe quand","いまにも","今にも"  ],
  ["n'importe quand, jamais (+ négatif)","いつでも","何時でも"  ],
  ["naissance","たんじょう","誕生"  ],
  ["naissance, lieu de naissance","うまれ","生まれ"  ],
  ["natation, nage","およぎ","泳ぎ"  ],
  ["nation, peuple, citoyen","こくみん","国民"  ],
  ["nature","しぜん","自然"  ],
  ["naturel, spontané","てんねん","天然"  ],
  ["naturel, vraisemblable, plausible","もっとも","尤も"  ],
  ["ne doit pas faire, sans espoir, pas bon","いけない","行けない"  ],
  ["ne pas tenir compte de, fermer les yeux sur, ignorer","むしする","無視する"  ],
  ["nerf, sensibilité","しんけい","神経"  ],
  ["niveau d'eau, niveau, standard","すいじゅん","水準"  ],
  ["Noël [Christmas (en)]","クリスマス",""  ],
  ["nom de famille, lignée, Mr.","し","氏"  ],
  ["nom, réputation","な","名"  ],
  ["nombre de fois [suffixe]","たび","度"  ],
  ["non [no (en)]","ノー",""  ],
  ["normal, satisfaisant, bien","じゅんちょう","順調"  ],
  ["note explicative, commentaire, NB","ちゅう","注"  ],
  ["note, memo [memo (en)]","メモ",""  ],
  ["nourriture","しょくもつ","食物"  ],
  ["nourriture, vivres","しょくりょう","食料"  ],
  ["nous, notre, nos","われわれ","我々"  ],
  ["nouvellement, fraîchement","あらた","新た"  ],
  ["nu, dénudé","はだか","裸"  ],
  ["nutrition, alimentation","えいよう","栄養"  ],
  ["obéir, se conformer à, accompagner [五段] [vi]","したがう","従う"  ],
  ["objectif, but","もくてき","目的"  ],
  ["objectif, but, cible","もくひょう","目標"  ],
  ["objet (d'une étude par exemple), but","たいしょう","対象"  ],
  ["observation, surveillance","かんさつ","観察"  ],
  ["obstacle, entrave, empêchement","しょうがい","障害"  ],
  ["occuper, remplir, contenir [一段] [vt]","しめる","占める"  ],
  ["officiel, responsable","かかり","係り・係"  ],
  ["ombre, ombrage","かげ","影・陰"  ],
  ["omettre, oublier, restreindre, réduire [五段] [vt]","はぶく","省く"  ],
  ["opération chirurgicale","しゅじゅつ","手術"  ],
  ["opération, traitement, manipulation","そうさ","操作"  ],
  ["opinion, point de vue","けんかい","見解"  ],
  ["opposition, résistance, défiance, hostilité","はんこう","反抗"  ],
  ["or (métal)","きん","金"  ],
  ["ordinaire, commun, gratuit, seulement","ただ","唯・只"  ],
  ["ordinateur [computer (en)]","コンピューター",""  ],
  ["ordonner, commander, nommer (quelqu'un à un poste) [一段] [vt]","めいじる","命じる"  ],
  ["ordre, commandement, directive","めいれい","命令"  ],
  ["ordre, succession, circonstances, dès que","しだい","次第"  ],
  ["ordre, tour","じゅん","順"  ],
  ["ordre, tour","じゅんばん","順番"  ],
  ["organisation, association","だんたい","団体"  ],
  ["organisation, système, construction","そしき","組織"  ],
  ["os","ほね","骨"  ],
  ["où ?, qui ?, quoi ?","いずれ","孰"  ],
  ["ou bien","あるいは","或いは"  ],
  ["ou, ou alors","それとも","其れ共"  ],
  ["ouvrage, œuvre, production","さくひん","作品"  ],
  ["oxygène","さんそ","酸素"  ],
  ["paiement","しはらい","支払"  ],
  ["paiement, allocation, pension","しきゅう","支給"  ],
  ["paix","へいわ","平和"  ],
  ["panier, cage","かご","籠"  ],
  ["papotage, bavardage","おしゃべり","お喋り"  ],
  ["paquet, colis","つつみ","包み"  ],
  ["par hasard, accidentellement","ぐうぜん","偶然"  ],
  ["par hasard, par chance","たまたま","偶々"  ],
  ["par hasard, soudainement","ふと","不図"  ],
  ["parce que","なぜなら","何故なら"  ],
  ["parcelle de terre","とち","土地"  ],
  ["pardonner, excuser, permettre, autoriser [五段] [vt]","ゆるす","許す"  ],
  ["parent, proche","しんせき","親戚"  ],
  ["parfum, odeur, fragrance","かおり","香り・薫り"  ],
  ["parking","ちゅうしゃ","駐車"  ],
  ["parlement, assemblée, congrès","こっかい","国会"  ],
  ["parler ensemble [五段] [vt]","はなしあう","話し合う"  ],
  ["parler, discuter","しゃべる","喋る"  ],
  ["parti politique","とう","党"  ],
  ["participation, engagement","さんか","参加"  ],
  ["particularité, caractéristique","どくとく","独特"  ],
  ["partie supérieure, amont d'une rivière","かみ","上"  ],
  ["partir, quitter [五段] [vi]","さる","去る"  ],
  ["parvenir à, atteindre, arriver à","たっする","達する"  ],
  ["parvenir, arriver, être attentif [五段] [vi]","とどく","届く"  ],
  ["pas du tout (+ verbe négatif)","すこしも","少しも"  ],
  ["pas forcément, pas toujours","かならずしも","必ずしも"  ],
  ["pas possible !, pas moyen !, en aucun cas !","まさか",""  ],
  ["pas possible, en général, vraiment","いったい","一体"  ],
  ["passable, acceptable [suffixe]","か","可"  ],
  ["passage, trafic, circulation","つうこう","通行"  ],
  ["passage, traversée","つうか","通過"  ],
  ["passager","じょうきゃく","乗客"  ],
  ["passé, temps anciens","かこ","過去"  ],
  ["passeport [passport (en)]","パスポート",""  ],
  ["passer (du temps), boire (de l'alcool) [五段] [vt]","すごす","過ごす"  ],
  ["passer une nuit blanche, faire une nuit blanche","てつやする","徹夜する"  ],
  ["passer, s'écouler (en parlant du temps) [五段] [vi]","たつ","経つ"  ],
  ["passer, traverser [一段] [vi]","とおりすぎる","通り過ぎる"  ],
  ["pathétique, qui fait pitié","かわいそう","可哀想"  ],
  ["patience, persévérance, maitrise de soi","がまん","我慢"  ],
  ["patient (hôpital)","かんじゃ","患者"  ],
  ["patinage [skate (en)]","スケート",""  ],
  ["pause, repos","きゅうけい","休憩"  ],
  ["pauvre","まずしい","貧しい"  ],
  ["paye, salaire","きゅうりょう","給料"  ],
  ["payer [五段] [vt]","しはらう","支払う"  ],
  ["paysage","ふうけい","風景"  ],
  ["peau","はだ","肌"  ],
  ["peau, cuir, épiderme","かわ","皮・革"  ],
  ["pêche (aux poissons), monnaie (après un achat)","つり","釣り"  ],
  ["peintre, dessinateur","がか","画家"  ],
  ["peinture","かいが","絵画"  ],
  ["peinture [pek (nl)]","ペンキ",""  ],
  ["pelouse, gazon","しばふ","芝生"  ],
  ["pensée, idée","しそう","思想"  ],
  ["perdre, égarer [五段] [vt]","うしなう","失う"  ],
  ["père","ちちおや","父親"  ],
  ["performances, résultats","せいせき","成績"  ],
  ["période en années [suffixe]","ねんかん","年間"  ],
  ["période, époque, ère","ねんだい","年代"  ],
  ["période, intervalle","きかん","期間"  ],
  ["période, saison","じき","時期"  ],
  ["permis, licence, certificat, autorisation","めんきょ","免許"  ],
  ["personnalité, personnage, personne d'envergure","じんぶつ","人物"  ],
  ["personne âgée","ろうじん","老人"  ],
  ["personnellement, soi-même","じしん","自身"  ],
  ["personnes âgées","としより","年寄り"  ],
  ["personnes âgées, vieux","おい","老い"  ],
  ["pertinent, approprié, adéquat","てきせつ","適切"  ],
  ["petit ami, petite amie, amoureux","こいびと","恋人"  ],
  ["petits-enfants","まご","孫"  ],
  ["pétrole","せきゆ","石油"  ],
  ["peu pratique, incommode, handicapant","ふじゆう","不自由"  ],
  ["peur, terreur, effroi","きょうふ","恐怖"  ],
  ["peut-être","かもしれない","かも知れない"  ],
  ["peut-être, probablement","おそらく","恐らく"  ],
  ["phénomène","げんしょう","現象"  ],
  ["philosophie","てつがく","哲学"  ],
  ["phrase, paragraphe, section, passage, vers","く","句"  ],
  ["phrase, proposition grammaticale, écrit","ぶん","文"  ],
  ["physique (science)","ぶつり","物理"  ],
  ["pièce de monnaie","こうか","硬貨"  ],
  ["pièce de monnaire en cuivre","どうか","銅貨"  ],
  ["pièce de théâtre","げき","劇"  ],
  ["pièce de théâtre","しばい","芝居"  ],
  ["pilote [pilot (en)]","パイロット",""  ],
  ["pin","まつ","松"  ],
  ["pinceau (pour écrire)","ふで","筆"  ],
  ["pique-nique [picnic (en)]","ピクニック",""  ],
  ["pistolet, fusil, arme à feu","じゅう","銃"  ],
  ["pitié, compassion","あわれ","哀れ"  ],
  ["place, position","いち","位置"  ],
  ["plainte, mécontentement","ふへい","不平"  ],
  ["plan, idée, projet","あん","案"  ],
  ["plan, projet","せっけい","設計"  ],
  ["plan, projet [plan (en)]","プラン",""  ],
  ["planche, plaque","いた","板"  ],
  ["plancher, sol","ゆか","床"  ],
  ["plant de riz","いね","稲"  ],
  ["plante","しょくぶつ","植物"  ],
  ["plat, repas, nourriture, riz cuit","めし","飯"  ],
  ["plus [plus (en)]","プラス",""  ],
  ["plus ou moins, quelque peu","たしょう","多少"  ],
  ["plutôt que, au lieu de","むしろ","寧ろ"  ],
  ["poème","し","詩"  ],
  ["poète","しじん","詩人"  ],
  ["poignée de mains","あくしゅ","握手"  ],
  ["point de vue, position, situation","たちば","立場"  ],
  ["point essentiel","ようてん","要点"  ],
  ["pois, haricots, graine de soja","まめ","豆"  ],
  ["poison, venin","どく","毒"  ],
  ["poitrine","むね","胸"  ],
  ["polémique, controverse","ろんそう","論争"  ],
  ["pollution, contamination","おせん","汚染"  ],
  ["pompiers","しょうぼう","消防"  ],
  ["populaire, à la mode","にんき","人気"  ],
  ["popularité, réputation, célébrité, notoriété","ひょうばん","評判"  ],
  ["portion, section, partie","ぶぶん","部分"  ],
  ["possible, réalisable","かのう","可能"  ],
  ["potin, rumeur","うわさ","噂"  ],
  ["pour ainsi dire, si je puis dire","いわば","言わば"  ],
  ["pour cent [percent (en)]","パーセント",""  ],
  ["pour toujours, éternellement","いつまでも","何時までも"  ],
  ["pourquoi ?, pour quelle raison ?, comment ?","なんで","何で"  ],
  ["pourrir, devenir mauvais, rouiller [五段]","くさる","腐る"  ],
  ["poursuivre, pourchasser, courir après [五段] [vt]","おう","追う"  ],
  ["poussière","ほこり","埃"  ],
  ["pratique, exécution, réalisation","じっこう","実行"  ],
  ["précaution, prévention","よぼう","予防"  ],
  ["précaution, soin, vigilance","ようじん","用心"  ],
  ["précieux, de valeur","きちょう","貴重"  ],
  ["prédiction, estimation","よそく","予測"  ],
  ["préfécture","けん","県"  ],
  ["préfixe de négation (non-, an-, un-) [préfixe]","ふ","不"  ],
  ["préfixe de négation ou de privatif [préfixe]","む","無"  ],
  ["Premier Ministre","しゅしょう","首相"  ],
  ["premier, en tête [top (en)]","トップ",""  ],
  ["prendre en compte, considérer","こうりょする","考慮する"  ],
  ["prendre, saisir, agripper, empoigner [五段] [vt]","つかむ","掴む"  ],
  ["préparation, décision, résolution, résignation","かくご","覚悟"  ],
  ["présentation, soumission (d'un rapport, d'un document…)","ていしゅつ","提出"  ],
  ["président d'une assemblée","ぎちょう","議長"  ],
  ["Président, chef de l'Exécutif","だいとうりょう","大統領"  ],
  ["prétendu, soi-disant [préfixe]","いわゆる","所謂"  ],
  ["preuve, justification","しょうめい","証明"  ],
  ["prévision","よほう","予報"  ],
  ["prévision, attentes","よき","予期"  ],
  ["prince","おうじ","王子"  ],
  ["principal, majeur","しゅよう","主要"  ],
  ["principalement, essentiellement","おもに","主に"  ],
  ["prix [suffixe]","しょう","賞"  ],
  ["prix élevé","こうか","高価"  ],
  ["prix, coût, charge","だいきん","代金"  ],
  ["prix, frais, taxe","りょうきん","料金"  ],
  ["problèmes, ennuis, difficultés, soucis, tracas","くろう","苦労"  ],
  ["procès, jugement","さいばん","裁判"  ],
  ["production, récolte","さくもつ","作物"  ],
  ["produire, provoquer [一段] [vt]","しょうじる","生じる"  ],
  ["produit manufacturé","せいひん","製品"  ],
  ["professeur, docteur (titre universitaire)","はかせ","博士"  ],
  ["professeur, enseignant","きょうし","教師"  ],
  ["professeur, enseignement","きょうじゅ","教授"  ],
  ["profession","しょくぎょう","職業"  ],
  ["professionnel [professional (en)]","プロ",""  ],
  ["profit, gain, bénéfice, intérêt","りえき","利益"  ],
  ["profitable, avantageux, lucratif","ゆうり","有利"  ],
  ["profonde émotion, excitation, le fait d'être profondément touché par quelque chose","かんどう","感動"  ],
  ["programme TV de fiction, drame [drama (en)]","ドラマ",""  ],
  ["progrès, avancée","しんぽ","進歩"  ],
  ["promenade, randonnée [hiking (en)]","ハイキング",""  ],
  ["proposition, offre, suggestion","ていあん","提案"  ],
  ["propre","せいけつ","清潔"  ],
  ["propriétaire","おおや","大家"  ],
  ["protéger, respecter (un règlement, une promesse…) [五段] [vt]","まもる","守る"  ],
  ["proverbe","ことわざ","諺"  ],
  ["province, région, aire, district","じかた・ちほう","地方"  ],
  ["provisions, vivres, rations","しょくりょう","食糧"  ],
  ["prudence, attention, précaution","しんちょう","慎重"  ],
  ["prune, prunier","うめ","梅"  ],
  ["psychologie","しんり","心理"  ],
  ["puant, malodorant, suspect, douteux","くさい","臭い"  ],
  ["publication, annonce","はっぴょう","発表"  ],
  ["publication, édition","はっこう","発行"  ],
  ["publicité","こうこく","広告"  ],
  ["puéril, immature","おさない","幼い"  ],
  ["puissant, fort","きょうりょく","強力"  ],
  ["punir, châtier, sanctionner","ばっする","罰する"  ],
  ["qualité","しつ","質"  ],
  ["quantité","りょう","量"  ],
  ["quelque chose","なにか","何か"  ],
  ["quelque part","どこか","何所か"  ],
  ["question","とい","問い"  ],
  ["queue, file d'attente, ligne, file","れつ","列"  ],
  ["quoi qu'il en soit, d'une façon ou d'une autre","なんとか","何とか"  ],
  ["race","じんしゅ","人種"  ],
  ["racine, source, origine, cause","ね","根"  ],
  ["raconter, dire, narrer [五段] [vt]","かたる","語る"  ],
  ["rang, grade, classe","きゅう","級"  ],
  ["rangement, mise en ordre","せいり","整理"  ],
  ["rapide (en parlant d'un développement)","きゅうそく","急速"  ],
  ["rapidement, brusquement, immédiatement","きゅうに","急に"  ],
  ["rapport, compte-rendu","ほうこく","報告"  ],
  ["rapport, relation, lien","かんれん","関連"  ],
  ["raquette [racket (en)]","ラケット",""  ],
  ["rarement (+négatif)","めったに","滅多に"  ],
  ["rattraper [五段] [vi]","おいつく","追い付く"  ],
  ["réalité","げんじつ","現実"  ],
  ["récemment, ces derniers temps","ちかごろ","近頃"  ],
  ["rechercher, demander, vouloir, souhaiter [一段] [vt]","もとめる","求める"  ],
  ["recommandation","すいせん","推薦"  ],
  ["recommander, conseiller, encourager, proposer (du vin) [一段] [vt]","すすめる","勧める"  ],
  ["reconnaître, apprécier, observer, remarquer, admettre, approuver [一段] [vt]","みとめる","認める"  ],
  ["recouvrir, cacher, dissimuler [五段] [vt]","おおう","覆う"  ],
  ["référence, consultation","さんこう","参考"  ],
  ["refuser, rejeter, décliner, informer, dire au préalable [五段] [vt]","ことわる","断る"  ],
  ["regarder, contempler, fixer quelque chose du regard [一段] [vt]","ながめる","眺める"  ],
  ["région, zone géographique","ちいき","地域"  ],
  ["régulier, vrai","せい","正"  ],
  ["reine","じょおう","女王"  ],
  ["relation personnelle","なか","仲"  ],
  ["religion","しゅうきょう","宗教"  ],
  ["remerciement, gratitude, reconnaissance","かんしゃ","感謝"  ],
  ["remettre à plus tard, ajourner","えんきする","延期する"  ],
  ["remplaçant, suppléant, substitut","だいり","代理"  ],
  ["remplir un formulaire","きにゅうする","記入する"  ],
  ["remplir, tasser, boucher, bloquer [一段] [vt]","つめる","詰める"  ],
  ["rencontre, accueil, le fait d'aller à la rencontre de quelqu'un","むかえ","迎え"  ],
  ["rencontre, rendez-vous","であい","出会い・出合い"  ],
  ["rencontrer par hasard, avoir un rendez-vous [五段] [vi]","であう","出会う・出合う"  ],
  ["rendez-vous [date (en)]","デート",""  ],
  ["renverser quelqu'un avec un véhicule [五段] [vt]","ひく","轢く"  ],
  ["réparation, dépannage","しゅうり","修理"  ],
  ["repas de midi","ちゅうしょく","昼食"  ],
  ["répéter, refaire [五段] [vt]","くりかえす","繰り返す"  ],
  ["répondre, satisfaire, accepter [一段] [vi]","おうじる","応じる"  ],
  ["représentation, délégation, exemple, modèle","だいひょう","代表"  ],
  ["représentation, expression","ひょうげん","表現"  ],
  ["réserve, provision","きょうきゅう","供給"  ],
  ["résidence, habitation","じゅうたく","住宅"  ],
  ["résidu, reste","のこり","残り"  ],
  ["résistance, opposition","ていこう","抵抗"  ],
  ["résoudre, dénouer [五段] [vt]","とく","解く"  ],
  ["respect, considération, admiration","そんけい","尊敬"  ],
  ["respect, estime","そんちょう","尊重"  ],
  ["respect, honneur, déférence","けいい","敬意"  ],
  ["respectivement, chacun respectivement, tour à tour","おのおの・それぞれ","各々"  ],
  ["respiration, souffle","こきゅう","呼吸"  ],
  ["responsabilité","せきにん","責任"  ],
  ["ressemblant, semblable","そっくり",""  ],
  ["ressembler, correspondre, convenir, aller bien ensemble [五段] [vi]","にあう","似合う"  ],
  ["ressentir, éprouver [一段]","かんじる","感じる"  ],
  ["ressources","しげん","資源"  ],
  ["restaurer, retourner, rendre, restituer [五段] [vt]","もどす","戻す"  ],
  ["résultat, conséquence, issue","けっか","結果"  ],
  ["retourner chez soi","きたくする","帰宅する"  ],
  ["retraite, isolement","いんたい","引退"  ],
  ["réunion, rassemblement","かいごう","会合"  ],
  ["réunion, rassemblement","あつまり","集まり"  ],
  ["réunir, assembler, unir, produire (une émission, une série…) [五段]","くむ","組む"  ],
  ["réussite (d'un examen par exemple), succès","ごうかく","合格"  ],
  ["revenu, recette","しゅうにゅう","収入"  ],
  ["rideau de scène, acte (au théâtre)","まく","幕"  ],
  ["rien (+ verbe au négatif), aucun, et tout le reste (+ nom avec も)","なにも","何も"  ],
  ["rire, sourire","わらい","笑い"  ],
  ["rizière","た","田"  ],
  ["robe [dress (en)]","ドレス",""  ],
  ["roc, rocher","いわ","岩"  ],
  ["roi","おうさま","王様"  ],
  ["roi, monarque, empereur","おう","王"  ],
  ["rôle, situation, fonction, service","やく","役"  ],
  ["route, chemin","どうろ","道路"  ],
  ["rythme, tonalité, humeur, état d'esprit, état de santé, tendance","ちょうし","調子"  ],
  ["s'ajouter, rejoindre, augmenter [五段] [vi]","くわわる","加わる"  ],
  ["s'écouler, couler, ruisseler [一段] [vi]","ながれる","流れる"  ],
  ["s'écrier, crier [五段] [vi]","さけぶ","叫ぶ"  ],
  ["s'empiler, s'entasser, s'accumuler [五段]","つもる","積もる"  ],
  ["s'enfoncer, couler, se sentir déprimé [五段] [vi]","しずむ","沈む"  ],
  ["s'ennuyer, se lasser [一段] [vi]","あきる","飽きる"  ],
  ["s'envoler, être projeté, omettre, ignorer, répandre (une rumeur) [五段] [vt]","とばす","飛ばす"  ],
  ["s'étendre, s'allonger, pousser (les cheveux, la barbe…), être reporté, être prolongé [一段] [vi]","のびる","伸びる・延びる"  ],
  ["s'étendre, se répandre, s'étirer, atteindre [五段] [vi]","ひろがる","広がる"  ],
  ["s'occuper de, gérer, traiter [五段] [vt]","あつかう","扱う"  ],
  ["sac","ふくろ","袋"  ],
  ["sac [bag (en)]","バッグ",""  ],
  ["sagesse, intelligence, raison, bon sens","ちえ","知恵"  ],
  ["sain et sauf, sûr, sans risque","ぶじ","無事"  ],
  ["saison des pluies","ばいう・つゆ","梅雨"  ],
  ["saison, temps, gaieté","ようき","陽気"  ],
  ["salon","いま","居間"  ],
  ["samedi","どよう・ど","土曜・土"  ],
  ["sans [suffixe]","なし","無し"  ],
  ["sans souci, à loisir","のんびり",""  ],
  ["santé","けんこう","健康"  ],
  ["satellite","えいせい","衛星"  ],
  ["satisfait","まんぞく","満足"  ],
  ["savant, érudit","がくしゃ","学者"  ],
  ["scène (de théâtre), cadre (d'un film, d'un roman…)","ぶたい","舞台"  ],
  ["scène, situation","ばめん","場面"  ],
  ["scrutin, vote","とうひょう","投票"  ],
  ["se confronter à, affronter, s'opposer à, faire face à","たいする","対する"  ],
  ["se connecter, se mélanger [一段] [vt]","あわせる","合わせる"  ],
  ["se diriger vers [一段] [vt]","むける","向ける"  ],
  ["se fonder sur, se baser sur [五段] [vi]","もとづく","基づく"  ],
  ["se gargariser, se rincer la bouche","うがいする","含嗽する"  ],
  ["se lever (le soleil), s'éclaircir [一段] [vi]","あける","明ける"  ],
  ["se lever, se mettre debout [五段] [vi]","たちあがる","立ち上がる"  ],
  ["se noyer, se livrer à [一段] [vi]","おぼれる","溺れる"  ],
  ["se rendre compte de, réaliser [五段]","きづく","気付く"  ],
  ["se réveiller [一段] [vi]","さめる","覚める"  ],
  ["se réveiller, se lever [五段] [vt]","さます","覚ます"  ],
  ["se saouler [五段] [vi]","よう","酔う"  ],
  ["se sentir à l'aise, se sentir libéré","さっぱりする",""  ],
  ["seconde","びょう","秒"  ],
  ["secourir, aider, venir en aide [五段] [vt]","すくう","救う"  ],
  ["secret, mystère","ひみつ","秘密"  ],
  ["secteur, zone, quartier","ちく","地区"  ],
  ["séjour","たいざい","滞在"  ],
  ["séjour, nuit d'hôtel","しゅくはく","宿泊"  ],
  ["semaine","しゅう","週"  ],
  ["semestre, trimestre, période scolaire","がっき","学期"  ],
  ["sens commun","じょうしき","常識"  ],
  ["sens, sensation","かんかく","感覚"  ],
  ["sensation","きみ","気味"  ],
  ["séparation, départ, section, partie","わかれ","別れ"  ],
  ["séparer, diviser, différencier, partager [一段] [vt]","わける","分ける"  ],
  ["séparer, diviser, partager [五段] [vt]","はなす","離す"  ],
  ["sérieux, consciencieux","しんけん","真剣"  ],
  ["sérieux, grave","しんこく","深刻"  ],
  ["service postal, courrier","ゆうびん","郵便"  ],
  ["service, devoir, responsabilité, travail","つとめ","勤め"  ],
  ["service, support [service (en)]","サービス",""  ],
  ["serviette de toilette [towel (en)]","タオル",""  ],
  ["seul, célibataire","ひとり","独り"  ],
  ["seul, unique","ゆいいつ","唯一"  ],
  ["seulement (+nombre), uniquement","たった",""  ],
  ["seulement, tout juste, une petite quantité de","わずか","僅か"  ],
  ["si","もしも","若しも"  ],
  ["si jamais, si par hasard","まんいち","万一"  ],
  ["siècle","せいき","世紀"  ],
  ["siège, place assise","ざせき","座席"  ],
  ["signal, signe","あいず","合図"  ],
  ["simple, seulement, pur","たんなる","単なる"  ],
  ["simplement, seulement","たんに","単に"  ],
  ["sincèrement, véritablement","じつに","実に"  ],
  ["singe","さる","猿"  ],
  ["situation (commerciale ou des affaires), activité (du marché)","けいき","景気"  ],
  ["ski [ski (en)]","スキー",""  ],
  ["société, monde","せけん","世間"  ],
  ["sœurs","しまい","姉妹"  ],
  ["soir, soirée","ゆうべ","夕べ"  ],
  ["sol, terre","つち","土"  ],
  ["Soleil","たいよう","太陽"  ],
  ["solliciter, faire appel à, poursuivre une personne en justice, se plaindre auprès de [一段] [vt]","うったえる","訴える"  ],
  ["solution","かいけつ","解決"  ],
  ["sombre (couleur), fort (goût, odeur), épais","こい","濃い"  ],
  ["somme totale, montant total","ごうけい","合計"  ],
  ["sommeil","すいみん","睡眠"  ],
  ["sommet, apogée","さかり","盛り"  ],
  ["sortir","がいしゅつする","外出する"  ],
  ["sortir brusquement, surgir, apparaitre soudainement [五段] [vi]","とびだす","飛び出す"  ],
  ["sortir, être manquant, être omis, tomber [一段] [vi]","ぬける","抜ける"  ],
  ["soudain, brusque","きゅうげき","急激"  ],
  ["souffle, respiration","いき","息"  ],
  ["souffler, respirer, dire (des mensonges) [五段] [vt]","つく","吐く"  ],
  ["souffrir de, être atteint de [五段]","かかる","罹る"  ],
  ["souffrir, gémir, être inquiet [五段] [vi]","くるしむ","苦しむ"  ],
  ["souhait, demande, requête, désir","ねがい","願い"  ],
  ["souhait, espoir, désir","のぞみ","望み"  ],
  ["souhaiter, espérer, désirer [五段] [vt]","のぞむ","望む"  ],
  ["soulever, lever, augmenter, flatter [一段] [vt]","もちあげる","持ち上げる"  ],
  ["soupe, bouillon [soup (en)]","スープ",""  ],
  ["sourire [五段] [vi]","ほほえむ","微笑む"  ],
  ["sourire, visage souriant","えがお","笑顔"  ],
  ["souris, rat","ねずみ","鼠"  ],
  ["sous-sol, souterrain","ちか","地下"  ],
  ["soutenir, supporter [一段] [vt]","ささえる","支える"  ],
  ["souvenir","おもいで","思い出・想い出"  ],
  ["souvent, à plusieurs reprises","たびたび","度々"  ],
  ["souvent, fréquemment","しばしば","屡"  ],
  ["sphère, balle","きゅう","球"  ],
  ["splendide, magnifique, merveilleux, beau","みごと","見事"  ],
  ["splendide, magnifique, somptueux","ごうか","豪華"  ],
  ["sportif, joueur d'une équipe","せんしゅ","選手"  ],
  ["stand, tribunes [stand (en)]","スタンド",""  ],
  ["star, vedette [star (en)]","スター",""  ],
  ["statut, position sociale","ちい","地位"  ],
  ["stimulation, excitation","しげき","刺激"  ],
  ["stress, tension, nervosité","きんちょう","緊張"  ],
  ["style [style (en)]","スタイル",""  ],
  ["subsistance, vie","くらし","暮らし"  ],
  ["succès","せいこう","成功"  ],
  ["succession, héritage","そうぞく","相続"  ],
  ["succursale (d'une société), filiale","してん","支店"  ],
  ["sueur","あせ","汗"  ],
  ["suicide","じさつ","自殺"  ],
  ["sujet (d'une conversation, d'un livre…), thème","わだい","話題"  ],
  ["supplémentaire, en excès, en plus","よぶん","余分"  ],
  ["surface, apparence, extérieur","ひょうめん","表面"  ],
  ["symptôme","しょうじょう","症状"  ],
  ["syndicat, association","くみあい","組合"  ],
  ["système, organisation, régime","せいど","制度"  ],
  ["table à manger","しょくたく","食卓"  ],
  ["tableau noir","こくばん","黒板"  ],
  ["taille (d'une personne)","しんちょう","身長"  ],
  ["tailler, tondre, couper (des cheveux) [五段] [vt]","かる","刈る"  ],
  ["talent, don","さいのう","才能"  ],
  ["talent, don, théâtre Nô","のう","能"  ],
  ["taux, ratio, proportion","りつ","率"  ],
  ["taxe","ぜい","税"  ],
  ["taxe, impôt","ぜいきん","税金"  ],
  ["tel quel, sans changement","そのまま","其の儘"  ],
  ["température","おんど","温度"  ],
  ["température atmosphérique","きおん","気温"  ],
  ["température corporelle","たいおん","体温"  ],
  ["tempête","あらし","嵐"  ],
  ["tendance, mode, penchant","けいこう","傾向"  ],
  ["tenir dans les bras, avoir (des problèmes, des dettes…), recruter, embaucher [一段] [vt]","かかえる","抱える"  ],
  ["tente [tent (en)]","テント",""  ],
  ["terminer, finir, achever [一段] [vt]","おえる","終える"  ],
  ["Terre, globe terrestre","ちきゅう","地球"  ],
  ["terre, sol, terrain","ち","地"  ],
  ["terre, terrain","りく","陸"  ],
  ["théâtre","げきじょう","劇場"  ],
  ["théorie, opinion","せつ","説"  ],
  ["thèse, dissertation, étude (sur)","ろんぶん","論文"  ],
  ["ticket, coupon, certificat","けん","券"  ],
  ["tige, queue (d'un champignon, d'une fleur)","え","柄"  ],
  ["tigre","とら","虎"  ],
  ["tirer, retirer, étirer, traîner [五段] [vt]","ひっぱる","引っ張る"  ],
  ["titre, sujet, thème","だい","題"  ],
  ["toît","やね","屋根"  ],
  ["tombe","はか","墓"  ],
  ["tomber, s'effondrer [五段] [vi]","ころぶ","転ぶ"  ],
  ["tonne [ton (en)]","トン",""  ],
  ["tonnerre","かみなり","雷"  ],
  ["tôt ou tard, éventuellement","そのうち","その内"  ],
  ["totalité, complétude, perfection","かんぜん","完全"  ],
  ["toucher, appliquer, mettre, poser [一段] [vt]","あてる","当てる"  ],
  ["toucher, ressentir, percevoir, violer (des lois) [一段] [vi]","ふれる","触れる"  ],
  ["toujours, constamment","つねに","常に"  ],
  ["tour de passe-passe, tour de magie, jonglage","てじな","手品"  ],
  ["tour, pagode","とう","塔"  ],
  ["tourisme","かんこう","観光"  ],
  ["tourner, faire circuler, entourer [五段] [vt]","まわす","回す"  ],
  ["tournure de phrase, plainte","もんく","文句"  ],
  ["tous les membres","ぜんいん","全員"  ],
  ["tous, toutes","あらゆる","有らゆる"  ],
  ["tout d'un coup, tout à la fois","いちどに","一度に"  ],
  ["tout, en entier","すべて","全て"  ],
  ["toutes les personnes, tous les gens","かたがた","方々"  ],
  ["toux","せき","咳"  ],
  ["tradition","でんとう","伝統"  ],
  ["traduction, version (traduction d'une langue étrangère vers la langue maternelle du traducteur)","やく","訳"  ],
  ["tragédie","ひげき","悲劇"  ],
  ["trahir [五段] [vt]","うらぎる","裏切る"  ],
  ["train (ordinaire)","れっしゃ","列車"  ],
  ["train qui s'éloigne de Tôkyô","くだり","下り"  ],
  ["traitement médical, soins","いりょう","医療"  ],
  ["transmettre, assigner, céder (quelque chose à quelqu'un) [五段] [vt]","ゆずる","譲る"  ],
  ["travail de bureau","じむ","事務"  ],
  ["travail manuel, labeur, travail","ろうどう","労働"  ],
  ["travail, opération, activité","はたらき","働き"  ],
  ["travail, opération, fabrication, corvée","さぎょう","作業"  ],
  ["travaux ménagers, tâches ménagères","かじ","家事"  ],
  ["traversée, franchissement","おうだん","横断"  ],
  ["traverser, franchir, passer de l'autre côté [一段] [vi]","こえる","超える・越える"  ],
  ["traverser, surpasser, dépasser, excéder, déménager [五段]","こす","越す・超す"  ],
  ["trembler, vibrer, secouer [一段] [vi]","ふるえる","震える"  ],
  ["trésor","たから","宝"  ],
  ["tropiques","ねったい","熱帯"  ],
  ["trottoir, chemin","ほどう","歩道"  ],
  ["trou, orifice","あな","穴"  ],
  ["tu, ton, toi (vulgaire)","おまえ","お前"  ],
  ["tube, tuyau","かん・くだ","管"  ],
  ["tube, tuyau [pipe (en)]","パイプ",""  ],
  ["tuer [五段] [vt]","ころす","殺す"  ],
  ["tunnel [tunnel (en)]","トンネル",""  ],
  ["type, archétype, modèle","てんけい","典型"  ],
  ["un certain","ある","或る"  ],
  ["un instant, un moment","いっしゅん","一瞬"  ],
  ["un instant, un moment, une seconde","しゅんかん","瞬間"  ],
  ["un jour, à l'occasion","いつか","何時か"  ],
  ["un moment, une heure, peu de temps","いちじ","一時"  ],
  ["un mot","ひとこと","一言"  ],
  ["un par un, l'un après l'autre, successivement","つぎつぎに","次々に"  ],
  ["un peu, en partie, un petit moment, quelque peu","やや","稍"  ],
  ["une sorte de, un genre de, un type de [préfixe]","いっしゅ","一種"  ],
  ["unité, crédit (à l'école)","たんい","単位"  ],
  ["Univers","うちゅう","宇宙"  ],
  ["utilisation, application, emploi","しよう","使用"  ],
  ["utiliser [一段] [vt]","もちいる","用いる"  ],
  ["vache","うし","牛"  ],
  ["vague","なみ","波"  ],
  ["vaincre, défaire [五段] [vt]","たおす","倒す"  ],
  ["valeur, mérite","かち","価値"  ],
  ["valide, disponible, efficace","ゆうこう","有効"  ],
  ["vallée","たに","谷"  ],
  ["van [van (en)]","バン",""  ],
  ["varié","さまざま","様々"  ],
  ["variété, sorte, genre, catégorie, type","しゅるい","種類"  ],
  ["vendredi","きんよう・きん","金曜・金"  ],
  ["vente","はんばい","販売"  ],
  ["ventre, abdomen, estomac","はら","腹"  ],
  ["verbe","どうし","動詞"  ],
  ["vérifier, s'assurer de, confirmer [一段] [vt]","たしかめる","確かめる"  ],
  ["vérité, fait","じじつ","事実"  ],
  ["vérité, réalité","じっさい","実際"  ],
  ["verre, herbe [glass, grass (en)]","グラス",""  ],
  ["verser, répandre [五段]","そそぐ","注ぐ"  ],
  ["vertu, bien","ぜん","善"  ],
  ["vêtements","いふく","衣服"  ],
  ["vêtements, tenue, habits","ふくそう","服装"  ],
  ["via","けいゆ","経由"  ],
  ["victoire","ゆうしょう","優勝"  ],
  ["victoire","かち","勝ち"  ],
  ["vide","から","空"  ],
  ["vide, place, espace","あき","明き・空き"  ],
  ["vidéo [video (en)]","ビデオ",""  ],
  ["vie","いのち","命"  ],
  ["vie (en tant que concept opposé à la mort)","じんせい","人生"  ],
  ["vie entière, existence","いっしょう","一生"  ],
  ["ville","とかい","都会"  ],
  ["ville","とし","都市"  ],
  ["vin [wine (en)]","ワイン",""  ],
  ["violation, transgression","いはん","違反"  ],
  ["violent, furieux, intense, tempétueux","はげしい","激しい"  ],
  ["violon [violin (en)]","バイオリン",""  ],
  ["visite","ほうもん","訪問"  ],
  ["visite médicale","しんさつ","診察"  ],
  ["vitesse, vélocité","そくど","速度"  ],
  ["vivre, passer du temps [五段] [vt]","くらす","暮らす"  ],
  ["voiture [car (en)]","カー",""  ],
  ["vol n° [suffixe]","びん","便"  ],
  ["voleur, cambrioleur, vol, cambriolage","ごうとう","強盗"  ],
  ["volonté","いし","意志"  ],
  ["voyage en voiture [drive (en)]","ドライブ",""  ],
  ["voyage, excursion","たび","旅"  ],
  ["vrai, véritable, original (contraire d'une copie)","ほんもの","本物"  ],
  ["vue, paysage","ながめ","眺め"  ],
  ["vue, scène, spectacle","こうけい","光景"  ],
  ["whisky [whisky (en)]","ウイスキー",""  ],
  ["yacht [yacht (en)]","ヨット",""  ],
  ["zut ! Merde !","しまった",""  ]
];

module.exports = jlptfr3;