var jlptfr5 = [
  ["à plus tard","また",""  ],
  ["à travers, partout dans, partout en [suffixe]","じゅう","中"  ],
  ["accrocher, porter (des lunettes...), appeler (au téléphone), prendre, dépenser (de l'argent, du temps) [一段] [vt]","かける","掛ける"  ],
  ["achats, courses","かいもの","買い物"  ],
  ["acheter [五段] [vt]","かう","買う"  ],
  ["adorable, adoré","だいすき","大好き"  ],
  ["adorable, mignon","かわいい","可愛い"  ],
  ["adulte, grande personne","おとな","大人"  ],
  ["ah !, oh !, hey!","ああ","嗚呼"  ],
  ["alcool, sake","さけ","酒"  ],
  ["aligner [一段] [vt]","ならべる","並べる"  ],
  ["aller [vi]","いく・ゆく","行く"  ],
  ["allumer (la lumière, une cigarette…) [一段] [vt]","つける","点ける"  ],
  ["allumer la lumière","でんきをつける","電気を点ける"  ],
  ["ambassade","たいしかん","大使館"  ],
  ["ami, compagnon","ともだち","友達"  ],
  ["animal","どうぶつ","動物"  ],
  ["animé (en parlant d'une ville, d'une rue…)","にぎやか","賑やか"  ],
  ["année dernière","きょねん","去年"  ],
  ["année prochaine","らいねん","来年"  ],
  ["années, compteur pour les années [suffixe]","ねん","年"  ],
  ["anniversaire","たんじょうび","誕生日"  ],
  ["ans (pour l'âge) [suffixe]","さい","歳"  ],
  ["appareil photo [camera (en)]","カメラ",""  ],
  ["appartement [apartment (en)]","アパート",""  ],
  ["appeler [五段] [vt]","よぶ","呼ぶ"  ],
  ["après","あと","後"  ],
  ["après-demain","あさって","明後日"  ],
  ["après-midi","ごご","午後"  ],
  ["après-midi","ひる","昼"  ],
  ["arbre, bois (la matière)","き","木"  ],
  ["argent, monnaie","おかね","お金"  ],
  ["argent, monnaie","かね","金"  ],
  ["arriver, atteindre [五段]","つく","着く"  ],
  ["arriver, venir","くる","来る"  ],
  ["ascenseur [elevator (en)]","エレベーター",""  ],
  ["assiette","さら","皿"  ],
  ["attacher [一段] [vt]","しめる","締める"  ],
  ["attendre [五段] [vt]","まつ","待つ"  ],
  ["au revoir","さよなら",""  ],
  ["au revoir, adieu","さようなら","左様なら"  ],
  ["aujourd'hui","きょう・こんにち","今日"  ],
  ["automne","あき","秋"  ],
  ["avant-hier","おととい・いっさくじつ","一昨日"  ],
  ["avant, auparavant [suffixe]","まえ","前"  ],
  ["avion","ひこうき","飛行機"  ],
  ["avoir besoin, nécessiter [五段] [vi]","いる","要る"  ],
  ["avoir, posséder [五段] [vi]","ある","有る"  ],
  ["bagage, paquet","にもつ","荷物"  ],
  ["baguette","はし","箸"  ],
  ["bande magnétique, cassette audio [tape (en)]","テープ",""  ],
  ["banque","ぎんこう","銀行"  ],
  ["bas, faible (température, rang, degré…)","ひくい","低い"  ],
  ["bâtiment","たてもの","建物"  ],
  ["beau temps, temps clair","はれ","晴れ"  ],
  ["beau, propre, joli, clair","きれい","奇麗・綺麗"  ],
  ["beaucoup","たくさん","沢山"  ],
  ["beaucoup aimé, adoré","すき","好き"  ],
  ["beaucoup, extrêmement","とても","迚も"  ],
  ["bentô, panier-repas japonais","おべんとう","お弁当"  ],
  ["beurre [butter (en)]","バター",""  ],
  ["bibliothèque (bâtiment)","としょかん","図書館"  ],
  ["bibliothèque (rangement)","ほんだな","本棚"  ],
  ["bien sûr, évidemment","もちろん","勿論"  ],
  ["bien, adroitement","よく","好く"  ],
  ["bien, donc...","あの",""  ],
  ["bien, merveilleux","けっこう","結構"  ],
  ["bienvenue (dans notre magasin, notre restaurant)","いらっしゃいませ",""  ],
  ["blanc","しろい","白い"  ],
  ["bleu (le), vert (le)","あお","青"  ],
  ["bleu, vert, inexpérimenté","あおい","青い・青い"  ],
  ["boire [五段] [vt]","のむ","飲む"  ],
  ["boisson","のみもの","飲み物"  ],
  ["boite","はこ","箱"  ],
  ["bol à riz, tasse à thé","ちゃわん","茶碗"  ],
  ["bon, délicieux","おいしい","美味しい"  ],
  ["bonbon, sucrerie","あめ","飴"  ],
  ["bonjour (l'après-midi)","こんにちは","今日は"  ],
  ["bonjour (le matin)","おはようございます","お早う御座います"  ],
  ["bonne nuit","おやすみなさい","お休みなさい"  ],
  ["bonne santé, forme","じょうぶ","丈夫"  ],
  ["bonsoir","こんばんは","今晩は"  ],
  ["bouche, ouverture","くち","口"  ],
  ["boutique de, magasin de [suffixe]","てん","店"  ],
  ["bouton [botan (pt)]","ボタン",""  ],
  ["bureau (meuble)","つくえ","机"  ],
  ["bureau de poste","ゆうびんきょく","郵便局"  ],
  ["bus [bus (en)]","バス",""  ],
  ["c'est OK, raisonnable, ça me convient","けっこうです","結構です"  ],
  ["café [coffee (en)]","コーヒー",""  ],
  ["calendrier [calendar (en)]","カレンダー",""  ],
  ["calepin, cahier, note [note (en)]","ノート",""  ],
  ["calme","しずか","静か"  ],
  ["caractères chinois, kanji","かんじ","漢字"  ],
  ["carte postale","はがき","葉書"  ],
  ["carte, plan","ちず","地図"  ],
  ["ce (loin du locuteur et de l'interlocuteur)","あの","彼の"  ],
  ["ce (proche de l'interlocuteur)","その","其の"  ],
  ["ce (proche du locuteur)","この","此の"  ],
  ["ce côté-ci (proche du locuteur)","こちら","此方"  ],
  ["ce côté-là (loin du locuteur et de l'interlocuteur)","あちら","彼方"  ],
  ["ce côté-là (loin du locuteur et de l'interlocuteur)","あっち","彼方"  ],
  ["ce matin","けさ","今朝"  ],
  ["ce mois-ci","こんげつ","今月"  ],
  ["ce soir","こんばん","今晩"  ],
  ["ceci (loin du locuteur et de l'interlocuteur)","あれ","彼"  ],
  ["ceci (proche de l'interlocuteur)","それ","其れ"  ],
  ["ceci (proche du locuteur)","これ","惟"  ],
  ["célèbre","ゆうめい","有名"  ],
  ["cendrier","はいざら","灰皿"  ],
  ["cent","ひゃく","百"  ],
  ["centre commercial [department (en)]","デパート",""  ],
  ["cette année","ことし","今年"  ],
  ["cette semaine","こんしゅう","今週"  ],
  ["cette sorte de","こんな",""  ],
  ["chaise","いす","椅子"  ],
  ["chambre","へや","部屋"  ],
  ["chanson, chant","うた","歌"  ],
  ["chanter (oiseau), aboyer, miauler, grogner (pangolin)... [五段]","なく","鳴く"  ],
  ["chanter [五段] [vt]","うたう","歌う"  ],
  ["chapeau","ぼうし","帽子"  ],
  ["chaque [suffixe]","ずつ",""  ],
  ["chaud (temps météo.)","あつい","暑い"  ],
  ["chauffage [stove (en)]","ストーブ",""  ],
  ["chaussettes","くつした","靴下"  ],
  ["chaussures","くつ","靴"  ],
  ["chemin","みち","道"  ],
  ["chemise [white shirt (en)]","ワイシャツ",""  ],
  ["chemise, chemisier [shirt (en)]","シャツ",""  ],
  ["chez soi","うちで","内で"  ],
  ["chien","いぬ","犬"  ],
  ["chose, objet","もの","物"  ],
  ["ciel","そら","空"  ],
  ["cigarette, tabac","たばこ","煙草"  ],
  ["cinéma (bâtiment)","えいがかん","映画館"  ],
  ["cinq","ご","五"  ],
  ["cinq","いつつ","五つ"  ],
  ["cinquième jour du mois, 5 jours","いつか","五日"  ],
  ["clair","あかるい","明るい"  ],
  ["clair de lune","つきあかり","月明かり"  ],
  ["classe [class (en)]","クラス",""  ],
  ["clé","かぎ","鍵"  ],
  ["coin (d'une rue, d'un trottoir…), rebord, bord","かど","角"  ],
  ["coller, fixer [五段]","はる","張る"  ],
  ["combien ? (prix)","いくら","幾ら"  ],
  ["combien ? (quantité)","いくつ","幾つ"  ],
  ["combien (+ compteur) ? [préfixe]","なん","何"  ],
  ["comment ?, de quelle manière ?","どう","如何"  ],
  ["composition, essai (écrit), rédaction","さくぶん","作文"  ],
  ["comprendre, être au courant, connaitre (une langue) [五段] [vi]","わかる","分かる"  ],
  ["compteur des numéros d'ordre (suffixe en -ième comme dans deuxième) [suffixe]","め","目"  ],
  ["compteur pour le nombre de fois [suffixe]","かい","回"  ],
  ["compteur pour le nombre de mois [suffixe]","かげつ","ヶ月・箇月"  ],
  ["compteur pour le nombre de voitures [suffixe]","だい","台"  ],
  ["compteur pour les étages [suffixe]","かい","階"  ],
  ["compteur pour les livres [suffixe]","さつ","冊"  ],
  ["compteur pour les objets plats comme des feuilles [suffixe]","まい","枚"  ],
  ["compteur pour les objets ronds et longs [suffixe]","ほん","本"  ],
  ["compteur pour les occurrences, le nombre de fois [suffixe]","ど","度"  ],
  ["compteur pour les personnes [suffixe]","にん","人"  ],
  ["compteur pour les petits animaux [suffixe]","ひき","匹"  ],
  ["connaître, savoir [五段] [vt]","しる","知る"  ],
  ["costume d'affaire","せびろ","背広"  ],
  ["côté (d'un boîte, d'un batîment...)","よこ","横"  ],
  ["côté (d'un triangle par ex.), les alentours","へん","辺"  ],
  ["couleur","いろ","色"  ],
  ["couper [五段] [vt]","きる","切る"  ],
  ["courir [五段] [vi]","はしる","走る"  ],
  ["cours, classe","じゅぎょう","授業"  ],
  ["court","みじかい","短い"  ],
  ["couteau [knife (en)]","ナイフ",""  ],
  ["cravate [necktie (en)]","ネクタイ",""  ],
  ["crayon","えんぴつ","鉛筆"  ],
  ["cuillère [spoon (en)]","スプーン",""  ],
  ["cuisine","だいどころ","台所"  ],
  ["d'habitude, en général","たいてい","大抵"  ],
  ["dangereux","あぶない","危ない"  ],
  ["dans ce cas, alors, donc","それでわ","其れでは"  ],
  ["dans deux ans","さらいねん","再来年"  ],
  ["de l'autre côté","むこう","向こう"  ],
  ["de même","こちらこそ",""  ],
  ["de temps en temps, parfois","ときどき","時々"  ],
  ["début","はじめ","初め"  ],
  ["début, départ, origine","はじめ","始め"  ],
  ["degré (angle, température...)","ど","度"  ],
  ["dehors, extérieur, à l'air libre","そと","外"  ],
  ["demain","あした","明日"  ],
  ["demander [五段]","たのむ","頼む"  ],
  ["dent","は","歯"  ],
  ["derrière","うしろ","後ろ"  ],
  ["désagréable, déplaisant","いや","嫌・否"  ],
  ["descendre (d'une montagne, un bus...) [一段] [vi]","おりる","降りる"  ],
  ["désiré, voulu","ほしい","欲しい"  ],
  ["désolé, excusez moi","ごめんなさい","ご免なさい"  ],
  ["désolé, excusez moi","すみません","済みません"  ],
  ["dessous","した","下"  ],
  ["dessus","うえ","上"  ],
  ["détesté","きらい","嫌い"  ],
  ["deux","に","二"  ],
  ["deux","ふたつ","二つ"  ],
  ["deux personnes","ふたり","二人"  ],
  ["devant, avant","まえ","前"  ],
  ["devenir, se changer en, être composé de, être constitué de [五段] [vi]","なる","成る"  ],
  ["devoir à la maison","しゅくだい","宿題"  ],
  ["dictionnaire","じびき","字引"  ],
  ["dictionnaire","じしょ","辞書"  ],
  ["difficile","むずかしい","難しい"  ],
  ["dimanche","にちようび","日曜日"  ],
  ["dîner, repas du soir","ばんごはん","晩ご飯"  ],
  ["dire [五段]","いう","言う"  ],
  ["discours, conversation","はなし","話"  ],
  ["disparaître, s'éteindre, s'effacer [一段] [vi]","きえる","消える"  ],
  ["disque (de musique), record [record (en)]","レコード",""  ],
  ["divers","そのほか","その他"  ],
  ["divers, autre","ほか","他"  ],
  ["divers, variés","いろいろ","色々"  ],
  ["dix","じゅう・とお","十"  ],
  ["dix-mille","まん","万"  ],
  ["dixième jour du mois, 10 jours","とおか","十日"  ],
  ["docteur, médecin","いしゃ","医者"  ],
  ["donc, alors, et bien","では",""  ],
  ["donner [一段] [vt]","あげる","上げる"  ],
  ["douche [shower (en)]","シャワー",""  ],
  ["doué, bon","じょうず","上手"  ],
  ["douloureux","いたい","痛い"  ],
  ["doux, délicieux, sucré","あまい","甘い"  ],
  ["droit devant, en face","まっすぐ","真っ直ぐ"  ],
  ["droite","みぎ","右"  ],
  ["eau","みず","水"  ],
  ["école","がっこう","学校"  ],
  ["écouter, entendre, demander [五段] [vt]","きく","聞く"  ],
  ["écrire [五段] [vt]","かく","書く"  ],
  ["électricité, lumière électrique","でんき","電気"  ],
  ["élève","せいと","生徒"  ],
  ["emprunter, louer [一段] [vt]","かりる","借りる"  ],
  ["enchanté, je compte sur vous","どうぞよろしく","どうぞ宜しく"  ],
  ["encore","また","復"  ],
  ["encore, plus, déjà","もう",""  ],
  ["endroit, lieu","ところ","所"  ],
  ["énergique, en bonne santé","げんき","元気"  ],
  ["enfant","こども","子供"  ],
  ["enfiler un vêtement sur les épaules, s'habiller [一段]","きる","着る"  ],
  ["enlever (des habits), se déshabiller [五段] [vt]","ぬぐ","脱ぐ"  ],
  ["ennuyeux, peu intéressant","つまらない","詰まらない"  ],
  ["enseigner, instruire [一段] [vt]","おしえる","教える"  ],
  ["ensemble","いっしょ","一緒"  ],
  ["ensuite, après, depuis lors","それから","其れから"  ],
  ["entrée","いりぐち","入り口"  ],
  ["entreprise","かいしゃ","会社"  ],
  ["entrer, pénétrer [五段]","はいる","入る"  ],
  ["enveloppe","ふうとう","封筒"  ],
  ["environ [suffixe]","くらい・ぐらい",""  ],
  ["envoyer, expédier, accompagner une personne [五段] [vt]","おくる","送る"  ],
  ["épais, lourd","あつい","厚い"  ],
  ["épicé","からい","辛い"  ],
  ["épouse (d'un autre)","おくさん","奥さん"  ],
  ["épouse (la nôtre)","かない","家内"  ],
  ["escalader, grimper, gravir, se lever (le soleil) [五段] [vi]","のぼる","登る・上る・昇る"  ],
  ["escaliers","かいだん","階段"  ],
  ["est","ひがし","東"  ],
  ["et demie [suffixe]","はん","半"  ],
  ["et ensuite, et après","そうして","然うして"  ],
  ["étang","いけ","池"  ],
  ["etc, et cetera [suffixe]","など","等"  ],
  ["été","なつ","夏"  ],
  ["éteindre (un appareil, un feu), effacer, supprimer [五段] [vt]","けす","消す"  ],
  ["étranger","がいこくじん","外国人"  ],
  ["être capable de faire, être fait [一段] [vi]","できる","出来る"  ],
  ["être commencé [五段] [vi]","はじまる","始まる"  ],
  ["être différent [五段] [vi]","ちがう","違う"  ],
  ["être fatigué [一段] [vi]","つかれる","疲れる"  ],
  ["être gêné, être embarrassé [五段] [vi]","こまる","困る"  ],
  ["être humain, une personne","ひと","人"  ],
  ["être, arriver (poli) [五段]","おいでになる","お出でになる"  ],
  ["être, se trouver, exister [五段] [vi]","ある","在る"  ],
  ["étroit, exigu, petit","せまい","狭い"  ],
  ["études, travail","べんきょう","勉強"  ],
  ["étudiant","がくせい","学生"  ],
  ["étudiant venant de l'étranger","りゅうがくせい","留学生"  ],
  ["étudier","べんきょうする","勉強する"  ],
  ["étudier, apprendre (de quelqu'un) [五段] [vt]","ならう","習う"  ],
  ["excès, trop plein, surplus","あんまり・あまり","余り"  ],
  ["excusez-moi","しつれいします","失礼します"  ],
  ["excusez-moi, je suis désolé","しつれいしました","失礼しました"  ],
  ["exercice","れんしゅう","練習"  ],
  ["facile, simple","やさしい","易しい"  ],
  ["facile, simple, gentil","やさしい","優しい"  ],
  ["faire","する","為る"  ],
  ["faire [五段] [vt]","やる","遣る"  ],
  ["faire des efforts, s'appliquer, travailler [一段] [vt]","つとめる","努める"  ],
  ["faire des exercices, s'entraîner","れんしゅうする","練習する"  ],
  ["faire la lessive","せんたくする","洗濯する"  ],
  ["faire le ménage","そうじする","掃除する"  ],
  ["faire, créer, réaliser, construire, fabriquer [五段] [vt]","つくる","作る・創る・造る"  ],
  ["famille","かぞく","家族"  ],
  ["famille (sa), maison (sa)","かてい","家庭"  ],
  ["femme","おんな","女"  ],
  ["fenêtre","まど","窓"  ],
  ["fermer [一段] [vt]","しめる","閉める"  ],
  ["fête [party (en)]","パーティー",""  ],
  ["fille","おんなのこ","女の子"  ],
  ["film","えいが","映画"  ],
  ["film [film (en)]","フィルム",""  ],
  ["fin, ténu","ほそい","細い"  ],
  ["finir [五段] [vi]","おわる","終わる"  ],
  ["fleur","はな","花"  ],
  ["fleurir, éclore [五段] [vi]","さく","咲く"  ],
  ["fort, puissant","つよい","強い"  ],
  ["foule","おおぜい","大勢"  ],
  ["fourchette [fork (en)]","フォーク",""  ],
  ["frais","すずしい","涼しい"  ],
  ["frères et soeurs (d'une même famille), frères","きょうだい","兄弟"  ],
  ["froid (temps météo.)","さむい","寒い"  ],
  ["fruit","くだもの","果物"  ],
  ["fumer, respirer, inhaler [五段] [vt]","すう","吸う"  ],
  ["garçon","おとこのこ","男の子"  ],
  ["gare","えき","駅"  ],
  ["gâteau, confiserie","おかし","お菓子"  ],
  ["gauche","ひだり","左"  ],
  ["glacé (au toucher), froid","つめたい","冷たい"  ],
  ["gramme [gram (en)]","グラム",""  ],
  ["grand-frère","あに","兄"  ],
  ["grand-frère (polie)","おにいさん","お兄さん"  ],
  ["grand-mère (polie)","おばあさん","お婆さん"  ],
  ["grand-père (polie)","おじいさん","お爺さん"  ],
  ["grand, large","おおきい","大きい"  ],
  ["grande-soeur","あね","姉"  ],
  ["grande-soeur (polie)","おねえさん","お姉さん"  ],
  ["gros, épais","ふとい","太い"  ],
  ["guitare [guitar (en)]","ギター",""  ],
  ["habiter [五段] [vi]","すむ","住む"  ],
  ["hall d'entrée, vestibule","げんかん","玄関"  ],
  ["hallo (au téléphone)","もしもし",""  ],
  ["haut, cher","たかい","高い"  ],
  ["heure (comme dans : 6h du matin, 18h…) [suffixe]","じ","時"  ],
  ["heure, temps","じかん","時間"  ],
  ["heure, temps, moment [suffixe]","とき","時"  ],
  ["heureux de faire votre connaissance","はじめまして","始めまして"  ],
  ["hier","きのう","昨日"  ],
  ["hiragana (un des syllabaires japonais)","ひらがな","平仮名"  ],
  ["hiver","ふゆ","冬"  ],
  ["homme","おとこ","男"  ],
  ["hôpital","びょういん","病院"  ],
  ["hôtel [hotel (en)]","ホテル",""  ],
  ["huit","はち","八"  ],
  ["huit","やっつ","八つ"  ],
  ["huitième jour du mois, 8 jours","ようか","八日"  ],
  ["ici (proche du locuteur)","ここ","此所"  ],
  ["identique, égal","おなじ","同じ"  ],
  ["il n'y a pas de quoi, de rien","どういたしまして","どう致しまして"  ],
  ["image, dessin","え","絵"  ],
  ["immédiatement","すぐに","直ぐに"  ],
  ["important","たいせつ","大切"  ],
  ["informations [news (en)]","ニュース",""  ],
  ["intéressant","おもしろい","面白い"  ],
  ["introduire, mettre dedans, insérer, préparer (du thé, du café) [一段] [vt]","いれる","入れる"  ],
  ["jambe","あし","足"  ],
  ["jardin","にわ","庭"  ],
  ["jaune","きいろ","黄色"  ],
  ["jaune","きいろい","黄色い"  ],
  ["je, mon, moi (formel)","わたくし","私"  ],
  ["je, mon, moi (neutre)","わたし","私"  ],
  ["jeu","あそび","遊び"  ],
  ["jeudi","もくようび","木曜日"  ],
  ["jeune","わかい","若い"  ],
  ["jouer [五段] [vi]","あそぶ","遊ぶ"  ],
  ["jouer d'un instrument à corde, dessiner (ligne) [五段]","ひく","引く"  ],
  ["jour du mois, compteur pour les jours du mois [suffixe]","にち","日"  ],
  ["journal (papier)","しんぶん","新聞"  ],
  ["jupe [skirt (en)]","スカート",""  ],
  ["juste une minute, un petit peu, un instant, un moment","ちょっと","一寸"  ],
  ["juste, exact","ちょうど","丁度"  ],
  ["juste, seulement [suffixe]","だけ","丈"  ],
  ["katakana (un des syllabaires japonais)","かたかな","片仮名"  ],
  ["kilogramme [kilogramme (fr)]","キログラム",""  ],
  ["kilomètre [kilomètre (fr)]","キロメートル",""  ],
  ["l'année avant l'année dernière, il y a 2 ans","おととし・いっさくねん","一昨年"  ],
  ["là (proche de l'interlocuteur)","そこ","其処"  ],
  ["là-bas (loin du locuteur et de l'interlocuteur)","あそこ","彼処"  ],
  ["lait de vache","ぎゅうにゅう","牛乳"  ],
  ["langue anglaise","えいご","英語"  ],
  ["langue japonaise","にほんご","日本語"  ],
  ["large, vaste","ひろい","広い"  ],
  ["laver [五段] [vt]","あらう","洗う"  ],
  ["léger, mineur, peu sérieux","かるい","軽い"  ],
  ["légume","やさい","野菜"  ],
  ["lent","おそい","遅い"  ],
  ["lentement, tranquillement","ゆっくり",""  ],
  ["lequel ?","どれ","何れ"  ],
  ["lessive","せんたく","洗濯"  ],
  ["lettre","てがみ","手紙"  ],
  ["lire [五段] [vt]","よむ","読む"  ],
  ["lit [bed (en)]","ベッド",""  ],
  ["livre","ほん","本"  ],
  ["long","ながい","長い"  ],
  ["long, distant","とおい","遠い"  ],
  ["lourd, massif","おもい","重い"  ],
  ["lundi","げつようび","月曜日"  ],
  ["lunette","めがね","眼鏡"  ],
  ["magasin","みせ","店"  ],
  ["magnétophone [tape recorder (en)]","テープレコーダー",""  ],
  ["magnifique, splendide, impressionnant","りっぱ","立派"  ],
  ["main","て","手"  ],
  ["maintenant","いま","今"  ],
  ["mais, cependant","でも",""  ],
  ["mais, cependant, pourtant, toutefois","しかし","併し"  ],
  ["maison","いえ","家"  ],
  ["maison (sa), chez soi","うち","家・内"  ],
  ["malade","びょうき","病気"  ],
  ["manger [一段] [vt]","たべる","食べる"  ],
  ["manteau, veste","うわぎ","上着"  ],
  ["manteau, veste, court (de tennis, de basket…) [coat, court (en)]","コート",""  ],
  ["maraîcher, marchand de fruits et légumes","やおや","八百屋"  ],
  ["marcher [五段] [vi]","あるく","歩く"  ],
  ["mardi","かようび","火曜日"  ],
  ["mari (de quelqu'un) (polie)","ごしゅじん","ご主人"  ],
  ["mariage","けっこん","結婚"  ],
  ["marque du pluriel, suffixe pour le pluriel [suffixe]","たち","達"  ],
  ["marron","ちゃいろ","茶色"  ],
  ["marron clair","ちゃいろ","茶色"  ],
  ["match, allumette [match (en)]","マッチ",""  ],
  ["matin","ごぜん","午前"  ],
  ["matin","あさ","朝"  ],
  ["mauvais, méprisable","わるい","悪い"  ],
  ["médicament","くすり","薬"  ],
  ["meillleur, le premier, le numéro 1","いちばん","一番"  ],
  ["mer","うみ","海"  ],
  ["merci","どうも",""  ],
  ["merci beaucoup","どうもありがとうございます","どうも有難う御座います"  ],
  ["merci pour ce repas (après avoir mangé)","ごちそうさまでした","ご馳走様でした"  ],
  ["merci pour ce repas (expression de gratitude avant de commencer à manger)","いただきます","戴きます"  ],
  ["mercredi","すいようび","水曜日"  ],
  ["mère","はは","母"  ],
  ["mère (polie)","おかあさん","お母さん"  ],
  ["météo, temps","てんき","天気"  ],
  ["mètre [meter (en)]","メートル",""  ],
  ["métro","ちかてつ","地下鉄"  ],
  ["mille","せん","千"  ],
  ["mince, pâle (pour une couleur)","うすい","薄い"  ],
  ["minute","ふん","分"  ],
  ["mois de l'année [suffixe]","がつ","月"  ],
  ["mois dernier","せんげつ","先月"  ],
  ["mois prochain","らいげつ","来月"  ],
  ["moitié","はんぶん","半分"  ],
  ["montagne, mont","やま","山"  ],
  ["monter (dans un véhicule), prendre (un train), embarquer (dans un avion, un bateau) [五段] [vi]","のる","乗る"  ],
  ["montre, horloge, réveil","とけい","時計"  ],
  ["montrer, afficher, laisser montrer [一段] [vt]","みせる","見せる"  ],
  ["mot, langage, phrase, parole","ことば","言葉"  ],
  ["mouchoir [handkerchief (en)]","ハンカチ",""  ],
  ["mourir [五段] [vi]","しぬ","死ぬ"  ],
  ["musique, mouvement (musique)","おんがく","音楽"  ],
  ["nager [五段] [vi]","およぐ","泳ぐ"  ],
  ["naître [一段] [vi]","うまれる","生まれる"  ],
  ["neige","ゆき","雪"  ],
  ["neuf","きゅう・く","九"  ],
  ["neuf","ここのつ","九つ"  ],
  ["neuvième jour du mois, 9 jours","ここのか","九日"  ],
  ["nez","はな","鼻"  ],
  ["noir","くろい","黒い"  ],
  ["noir (le)","くろ","黒"  ],
  ["nom","なまえ","名前"  ],
  ["non","いいえ, いえ","否"  ],
  ["nord","きた","北"  ],
  ["nourriture","たべもの","食べ物"  ],
  ["nouveau","あたらしい","新しい"  ],
  ["nuageux","くもり","曇り"  ],
  ["nuit","よる・よ","夜"  ],
  ["numéro","ばんごう","番号"  ],
  ["occupé","いそがしい","忙しい"  ],
  ["oeil","め","目"  ],
  ["oeuf","たまご","卵"  ],
  ["oiseau","とり","鳥"  ],
  ["oncle (polie)","おじさん","伯父さん・叔父さん"  ],
  ["oreille","みみ","耳"  ],
  ["où ?","どこ","何所"  ],
  ["oublier [一段] [vt]","わすれる","忘れる"  ],
  ["ouest","にし","西"  ],
  ["oui","はい",""  ],
  ["oui, en effet, c'est cela","ええ",""  ],
  ["ouvrir (un parapluie) [五段] [vi]","さす","差す"  ],
  ["ouvrir [一段] [vt]","あける","開ける・明ける"  ],
  ["page [page (en)]","ページ",""  ],
  ["pain [pan (en)]","パン",""  ],
  ["pantalon [jupon (fr)]","ズボン",""  ],
  ["pantoufle [slipper (en)]","スリッパ",""  ],
  ["papier","かみ","紙"  ],
  ["parapluie","かさ","傘"  ],
  ["parc public, jardin public","こうえん","公園"  ],
  ["parents (père et mère)","りょうしん","両親"  ],
  ["parler [五段] [vt]","はなす","話す"  ],
  ["partir (en train, en avion…) [五段] [vi]","たつ","発つ"  ],
  ["pas doué, mauvais","へた","下手"  ],
  ["pas encore (+négatif), encore (+positif)","まだ・いまだ","未だ"  ],
  ["pas tellement (+négatif)","あまり","余り"  ],
  ["pays étranger","がいこく","外国"  ],
  ["pays, région, province","くに","国"  ],
  ["pendant","ちゅう","中"  ],
  ["père","ちち","父"  ],
  ["père (polie)","おとうさん","お父さん"  ],
  ["personne (poli)","かた","方"  ],
  ["petit","ちいさい","小さい"  ],
  ["petit poste de police","こうばん","交番"  ],
  ["petit-déjeuner","あさごはん","朝ご飯"  ],
  ["petit-frère","おとうと","弟"  ],
  ["petite-soeur","いもうと","妹"  ],
  ["peu appétisant, sans goût","まずい","不味い"  ],
  ["peu cher, bon marché, calme, paisible","やすい","安い"  ],
  ["peut-être","たぶん","多分"  ],
  ["photographie","しゃしん","写真"  ],
  ["phrase, style d'écriture, texte","ぶんしょう","文章"  ],
  ["pied","あし","足"  ],
  ["pierre, roc","いし","石"  ],
  ["piscine [pool (en)]","プール",""  ],
  ["plaisant, agréable, bien","いい・よい","良い"  ],
  ["plaisant, amusant","たのしい","楽しい"  ],
  ["plat, cuisine","りょうり","料理"  ],
  ["pluie","あめ","雨"  ],
  ["plus","もっと",""  ],
  ["poche [pocket (en)]","ポケット",""  ],
  ["poisson","さかな・うお","魚"  ],
  ["policier (désigné de manière amicale)","おまわりさん","お巡りさん"  ],
  ["polir, nettoyer, faire briller [五段] [vt]","みがく","磨く"  ],
  ["pont","はし","橋"  ],
  ["porc","ぶたにく","豚肉"  ],
  ["porte","もん","門"  ],
  ["porte (style occidental) [door (en)]","ドア",""  ],
  ["porte coulissante","と","戸"  ],
  ["porter des vêtements en dessous de la taille [五段] [vt]","はく","穿く・履く"  ],
  ["porter quelque chose sur la tête, être recouvert (d'eau, de poussière…), supporter (un défaut, un manque…) [五段] [vt]","かぶる","被る"  ],
  ["portez-vous bien, prends soin de toi","おげんきで","お元気で"  ],
  ["poser [五段]","おく","置く"  ],
  ["poser une question","しつもんする","質問する"  ],
  ["poulet","とりにく","鶏肉"  ],
  ["pour la première fois","はじめて","初めて"  ],
  ["pourquoi ?","どうして","如何して"  ],
  ["pousser, presser [五段] [vt]","おす","押す"  ],
  ["pratique, utile","べんり","便利"  ],
  ["précédent, antérieur","さき","先"  ],
  ["préfixe honorifique [préfixe]","ご・お","御"  ],
  ["premier jour du mois, 1 jour","ついたち","一日"  ],
  ["prendre (du temps, de l'argent), être accroché, être suspendu, être couvert (par une assurance, un contrat…) [五段] [vi]","かかる","掛かる"  ],
  ["prendre (une photographie) [五段] [vt]","とる","撮る"  ],
  ["prendre une douche, prendre un bain, se dorer au soleil [一段] [vt]","あびる","浴びる"  ],
  ["prendre une photo","しゃしんをとる","写真を撮る"  ],
  ["prendre, emporter [五段] [vt]","とる","取る"  ],
  ["prêter [五段] [vt]","かす","貸す"  ],
  ["printemps","はる","春"  ],
  ["problème, sujet à traiter, question","もんだい","問題"  ],
  ["proche (en distance), près","ちかい","近い"  ],
  ["proche de, à côté de","そば","側"  ],
  ["proche, voisin","となり","隣"  ],
  ["professeur, enseignant","せんせい","先生"  ],
  ["progressivement, petit à petit","だんだん","段々"  ],
  ["promenade, balade","さんぽ","散歩"  ],
  ["puis-je rentrer ? (dans la maison de quelqu'un d'autre)","ごめんください","ご免下さい"  ],
  ["pull [sweater (en)]","セーター",""  ],
  ["quand ?","いつ","何時"  ],
  ["quatre","し","四"  ],
  ["quatre","よっつ","四つ"  ],
  ["quatrième jour du mois, 4 jours","よっか","四日"  ],
  ["que, quoi ?","なん・なに","何"  ],
  ["quel ?","どの","何の"  ],
  ["quel côté ?","どちら","何方"  ],
  ["quel genre ?","どんな",""  ],
  ["quelqu'un","だれか","誰か"  ],
  ["question, demande de renseignement","しつもん","質問"  ],
  ["qui ? (poli)","どなた","何方"  ],
  ["qui ?, quelqu'un","だれ","誰"  ],
  ["qui a du temps libre","ひま","暇"  ],
  ["qui n'existe pas, qui n'est pas là, qui n'est pas possédé","ない","無い"  ],
  ["qui va bien, sans problème","だいじょうぶ","大丈夫"  ],
  ["quitter, sortir [一段] [vt]","でる","出る"  ],
  ["radio [radio (en)]","ラジオ",""  ],
  ["rapide (temps), diligent","はやい","早い"  ],
  ["rapide (vitesse), véloce","はやい","速い"  ],
  ["réfrigérateur","れいぞうこ","冷蔵庫"  ],
  ["remettre, livrer, transmettre [五段] [vt]","わたす","渡す"  ],
  ["rencontrer, voir (une personne) [五段] [vi]","あう","会う・遭う"  ],
  ["repas de midi","ひるごはん","昼ご飯"  ],
  ["répondre [一段] [vi]","こたえる","答える"  ],
  ["restaurant [restaurant (fr)]","レストラン",""  ],
  ["rester (au même endroit), stopper, s'arrêter, demeurer, être limité à, s'établir [五段] [vi]","とまる・とどまる","止まる・留まる"  ],
  ["retourner, renvoyer quelque chose [五段] [vt]","かえす","返す"  ],
  ["revue, magazine","ざっし","雑誌"  ],
  ["rhume","かぜ","風邪"  ],
  ["rivière, cours d'eau","かわ","川・河"  ],
  ["riz cuit, repas","ごはん","ご飯"  ],
  ["rond, circulaire","まるい","丸い"  ],
  ["rond, circulaire","まるい","円い"  ],
  ["rouge","あかい","赤い"  ],
  ["rouge (le)","あか","赤"  ],
  ["rouleau de tissu","ひき","匹"  ],
  ["s'asseoir [五段] [vi]","すわる","座る"  ],
  ["s'éclaircir, s'ensoleiller [一段] [vi]","はれる","晴れる"  ],
  ["s'il vous plaît","おねがいします","お願いします"  ],
  ["s'il vous plaît","どうぞ",""  ],
  ["s'ouvrir [五段] [vi]","あく","開く"  ],
  ["sac, cartable","かばん","鞄"  ],
  ["sale","きたない","汚い"  ],
  ["salle à manger","しょくどう","食堂"  ],
  ["salle de classe","きょうしつ","教室"  ],
  ["salon de thé","きっさ","喫茶"  ],
  ["salon de thé, café (lieux)","きっさてん","喫茶店"  ],
  ["saluer","あいさつする","挨拶する"  ],
  ["samedi","どようび","土曜日"  ],
  ["sauce soja","しょうゆ","醤油"  ],
  ["savon","せっけん","石鹸"  ],
  ["se coucher, aller dormir [一段] [vi]","ねる","寝る"  ],
  ["se fermer [五段] [vi]","しまる","閉まる"  ],
  ["se lever, être érigé, être levé, tenir debout [五段] [vi]","たつ","立つ"  ],
  ["se marier","けっこんする","結婚する"  ],
  ["se mettre en rangs, faire la queue, rivaliser, égaler [五段] [vi]","ならぶ","並ぶ"  ],
  ["se promener","さんぽする","散歩する"  ],
  ["se reposer, être absent, prendre un congé [五段] [vi]","やすむ","休む"  ],
  ["se réveiller, se lever [一段] [vi]","おきる","起きる"  ],
  ["se souvenir [一段] [vt]","おぼえる","覚える"  ],
  ["second jour du mois, 2 jours","ふつか","二日"  ],
  ["sel","しお","塩"  ],
  ["semaine","しゅうかん","週間"  ],
  ["semaine dernière","せんしゅう","先週"  ],
  ["semaine prochaine","らいしゅう","来週"  ],
  ["sept","なな","七"  ],
  ["sept","ななつ","七つ"  ],
  ["septième jour du mois, 7 jours","なのか","七日"  ],
  ["sérieux, grave, important, immense, énorme","たいへん","大変"  ],
  ["si, quand, et, avec","と",""  ],
  ["signification, sens","いみ","意味"  ],
  ["six","ろく","六"  ],
  ["six","むっつ","六つ"  ],
  ["sixième jour du mois, 6 jours","むいか","六日"  ],
  ["soi-même, elle-même, lui-même","じぶん","自分"  ],
  ["soir, soirée","ゆうがた","夕方"  ],
  ["soir, soirée","ばん","晩"  ],
  ["sombre","くらい","暗い"  ],
  ["sortie","でぐち","出口"  ],
  ["sortir, partir [一段] [vi]","でかける","出かける"  ],
  ["sortir, partir [五段] [vt]","だす","出す"  ],
  ["souffler (vent) [五段]","ふく","吹く"  ],
  ["souvent","よく","克く"  ],
  ["sport [sport (en)]","スポーツ",""  ],
  ["stylo [pen (en)]","ペン",""  ],
  ["stylo-bille [ball-pen (en)]","ボールペン",""  ],
  ["stylo-plume","まんねんひつ","万年筆"  ],
  ["sucre","さとう","砂糖"  ],
  ["sud","みなみ","南"  ],
  ["suffixe pour les noms (Mme, Mr) [suffixe]","さん",""  ],
  ["suivant","つぎ","次"  ],
  ["support, socle, table","だい","台"  ],
  ["table [table (en)]","テーブル",""  ],
  ["taille (hauteur d'une personne)","せい","背"  ],
  ["tante","おば","伯母・叔母"  ],
  ["tante (polie)","おばさん","伯母さん・叔母さん"  ],
  ["taxi [taxi (en)]","タクシー",""  ],
  ["téléphone","でんわ","電話"  ],
  ["télévision [television (en)]","テレビ",""  ],
  ["tenir, porter, posséder [五段]","もつ","持つ"  ],
  ["test, essai [test (en)]","テスト",""  ],
  ["tête","あたま","頭"  ],
  ["thé","おちゃ","お茶"  ],
  ["thé noir","こうちゃ","紅茶"  ],
  ["ticket, billet","きっぷ","切符"  ],
  ["tiède, chaud","あたたかい","温かい・暖かい"  ],
  ["timbre","きって","切手"  ],
  ["tirer [五段]","ひく","引く"  ],
  ["toilettes","おてあらい","お手洗い"  ],
  ["toilettes [toilet (en)]","トイレ",""  ],
  ["tomber (neige, pluie, grêle...) [五段] [vi]","ふる","降る"  ],
  ["totalement, en entier","ぜんぶ","全部"  ],
  ["toujours, à chaque fois, jamais (+négatif)","いつも","何時も"  ],
  ["tourner, se courber, se plier [五段] [vi]","まがる","曲がる"  ],
  ["tous les ans","まいとし・まいねん","毎年・毎年"  ],
  ["tous les jours","まいにち","毎日"  ],
  ["tous les matins","まいあさ","毎朝"  ],
  ["tous les mois","まいつき","毎月"  ],
  ["tous les soirs","まいばん","毎晩"  ],
  ["tout le monde","みなさん","皆さん"  ],
  ["toutes les semaines","まいしゅう","毎週"  ],
  ["train","でんしゃ","電車"  ],
  ["travail, emploi","しごと","仕事"  ],
  ["travailler [五段] [vi]","はたらく","働く"  ],
  ["traverser [五段] [vi]","わたる","渡る"  ],
  ["trois","さん","三"  ],
  ["trois","みっつ","三つ"  ],
  ["troisième jour du mois, 3 jours","みっか","三日"  ],
  ["tu, toi, ton (neutre)","あなた","貴方"  ],
  ["un","いち","一"  ],
  ["un","ひとつ","一つ"  ],
  ["un jour","いちにち","一日"  ],
  ["un mois","ひとつき","一月"  ],
  ["un peu","すこし","少し"  ],
  ["une personne","ひとり","一人"  ],
  ["une semaine","いっしゅうかん","一週間"  ],
  ["université","だいがく","大学"  ],
  ["utiliser, employer, dépenser (de l'argent, du temps), parler (une langue) [五段] [vt]","つかう","使う"  ],
  ["vacances d'été","なつやすみ","夏休み"  ],
  ["vacances, congé, repos","やすみ","休み"  ],
  ["vase","かびん","花瓶"  ],
  ["véhicule","じどうしゃ","自動車"  ],
  ["vélo","じてんしゃ","自転車"  ],
  ["vendre [五段] [vt]","うる","売る"  ],
  ["vendredi","きんようび","金曜日"  ],
  ["vent","かぜ","風"  ],
  ["ventre, estomac","おなか","お腹"  ],
  ["verre (contenu) [cup (en)]","コップ",""  ],
  ["vers (pour l'heure) [suffixe]","ころ・ごろ",""  ],
  ["vêtements","ふく","服"  ],
  ["vêtements occidentaux","ようふく","洋服"  ],
  ["viande","にく","肉"  ],
  ["viande de boeuf","ぎゅうにく","牛肉"  ],
  ["vieux, âgé","ふるい","古い"  ],
  ["ville, quartier","まち","町・街"  ],
  ["vingt ans (être agé de)","はたち","二十歳"  ],
  ["vingtième jour du mois, 20 jours","はつか","二十日"  ],
  ["visage","かお","顔"  ],
  ["voir [一段] [vt]","みる","見る・観る・視る"  ],
  ["voisinage, environ","ちかく","近く"  ],
  ["voiture, automobile","くるま","車"  ],
  ["voix","こえ","声"  ],
  ["voler, s'envoler, bondir [五段] [vi]","とぶ","飛ぶ・跳ぶ"  ],
  ["voyage","りょこう","旅行"  ],
  ["voyager","りょこうする","旅行する"  ],
  ["vrai, véritable","ほんとう","本当"  ],
  ["vraiment, réellement","ほんとうに","本当に"  ],
  ["yen","えん","円"  ],
  ["zéro","れい","零"  ],
  ["zéro [zero (en)]","ゼロ",""  ]
];

module.exports = jlptfr5;