var jlptfr4 = [
  ["à peu près","ばかり","許り"  ],
  ["à peu près, dans l'ensemble","だいたい","大体"  ],
  ["à propos de","について",""  ],
  ["à tout à l'heure (se dit en partant lorsqu'on reviendra plus tard)","いってらっしゃい","行ってらっしゃい"  ],
  ["à tout à l'heure (se dit en partant lorsqu'on reviendra plus tard) (poli)","いってまいります","行って参ります"  ],
  ["absence (de chez soi)","るす","留守"  ],
  ["absolument pas","けっして","決して"  ],
  ["accessoire [accessory (en)]","アクセサリー",""  ],
  ["accident, incident","じこ","事故"  ],
  ["accueillir, recevoir, accepter quelqu'un, aller à l'encontre de, aller chercher quelqu'un [一段] [vt]","むかえる","迎える"  ],
  ["admirable, merveilleux","すばらしい","素晴らしい"  ],
  ["admission dans une école ou une université","にゅうがく","入学"  ],
  ["adresse","じゅうしょ","住所"  ],
  ["aéroport","くうこう","空港"  ],
  ["affaire (business), utilisation, tâche","よう","用"  ],
  ["Afrique [Africa (en)]","アフリカ",""  ],
  ["aider, assister [五段] [vt]","てつだう","手伝う"  ],
  ["ainsi","そう",""  ],
  ["air, atmosphère","くうき","空気"  ],
  ["ajouter (des nombres) [五段] [vt]","たす","足す"  ],
  ["alcool [alcohol (en)]","アルコール",""  ],
  ["alentours, circonférence, contour","まわり","回り・周り"  ],
  ["aller à (l'école...), passer [五段] [vi]","とおる","通る"  ],
  ["amer","にがい","苦い"  ],
  ["Amérique [America (en)]","アメリカ",""  ],
  ["année","とし","年"  ],
  ["approprié, convenable","てきとう","適当"  ],
  ["approvisionnement d'eau, conduite d'eau, distribution d'eau","すいどう","水道"  ],
  ["après celà","これから","此れから"  ],
  ["arrêter, stopper [一段] [vt]","とめる","止める"  ],
  ["arrêter, stopper [一段] [vt]","やめる","止める"  ],
  ["Asie, asiatique [Asia (en)]","アジア",""  ],
  ["assez, suffisant","じゅうぶん","十分"  ],
  ["assistance","せわ","世話"  ],
  ["attraper, capturer [一段] [vt]","つかまえる","捕まえる"  ],
  ["auberge japonaise, hôtel","りょかん","旅館"  ],
  ["auditorium","こうどう","講堂"  ],
  ["augmenter [一段] [vt]","あげる","上げる"  ],
  ["augmenter, s'accroître [一段] [vi]","ふえる","増える"  ],
  ["auparavant, autrefois","むかし","昔"  ],
  ["autant que possible","なるべく","成る可く"  ],
  ["autre, différent, séparé, distinct","べつ","別"  ],
  ["avancer, progresser, aller de l'avant, s'améliorer [五段] [vi]","すすむ","進む"  ],
  ["avant de, moins de [suffixe]","いない","以内"  ],
  ["avoir faim [五段] [vi]","すく","空く"  ],
  ["avoir soif [五段] [vi]","かわく","渇く"  ],
  ["avoir sommeil","ねむい","眠い"  ],
  ["bande dessinée, manga","まんが","漫画"  ],
  ["banlieue","こうがい","郊外"  ],
  ["barbe","ひげ","髭"  ],
  ["bateau, navire","ふね","船"  ],
  ["beaucoup, nombreux","おおい","多い"  ],
  ["bébé","あかちゃん","赤ちゃん"  ],
  ["bébé","あかんぼう","赤ん坊"  ],
  ["belle (envers une femme)","うつくしい","美しい"  ],
  ["bien entendu, bien sûr","かしこまりました","畏まりました"  ],
  ["bien, très bien, parfait","よろしい","宜しい"  ],
  ["bienvenue à la maison (la notre)","おかえりなさい","お帰りなさい"  ],
  ["bizarre, étrange","へん","変"  ],
  ["bon rétablissement (à une personne malade)","おだいじに","お大事に"  ],
  ["bouger [五段] [vi]","うごく","動く"  ],
  ["bouillir, chauffer [五段] [vt]","わかす","沸かす"  ],
  ["branche","えだ","枝"  ],
  ["bras","うで","腕"  ],
  ["bruyant, gênant","うるさい","煩い"  ],
  ["bureau (pièce)","じむしょ","事務所"  ],
  ["c'est ennuyeux","それはいけませんね","其れはいけませんね"  ],
  ["cadeau","おくりもの","贈り物"  ],
  ["cadeau [present (en)]","プレゼント",""  ],
  ["cadeau, souvenir","おみやげ","お土産"  ],
  ["campagne","いなか","田舎"  ],
  ["caractère (imprimerie)","じ","字"  ],
  ["cause, motif","りゆう","理由"  ],
  ["cause, origine, raison","げんいん","原因"  ],
  ["ce côté-ci (proche du locuteur)","こっち","此方"  ],
  ["ce côté-là (proche de l'interlocuteur)","そちら","其方"  ],
  ["ce côté-là (proche de l'interlocuteur)","そっち","其方"  ],
  ["ce genre de","あんな",""  ],
  ["ce soir","こんや","今夜"  ],
  ["cela faisait longtemps","ひさしぶり","久し振り"  ],
  ["célébration","おいわい","お祝い"  ],
  ["cent millions","おく","億"  ],
  ["certainement, assurément, si je ne me trompe pas","たしか","確"  ],
  ["certainement, sans faute","ぜひ","是非"  ],
  ["certainement, surement, sans aucun doute","かならず","必ず"  ],
  ["ces temps-ci","このごろ","此の頃"  ],
  ["cesser, s'arrêter (en parlant de la pluie, la neige...), être terminé [五段] [vi]","やむ","止む"  ],
  ["cette fois, la prochaine fois","こんど","今度"  ],
  ["chaîne stéréo [stereo (en)]","ステレオ",""  ],
  ["chance, opportunité","きかい","機会"  ],
  ["changer, se transformer [五段] [vi]","かわる","変わる"  ],
  ["changer, varier [一段] [vt]","かえる","変える"  ],
  ["chauffage","だんぼう","暖房"  ],
  ["chercher [五段] [vt]","さがす","探す・捜す"  ],
  ["cheveux, poil, laine","け","毛"  ],
  ["choisir [五段] [vt]","えらぶ","選ぶ"  ],
  ["chose (abstraite)","こと","事"  ],
  ["circonstance, condition","つごう","都合"  ],
  ["citoyen","しみん","市民"  ],
  ["civilisation, culture","ぶんか","文化"  ],
  ["clairement, distinctement","はっきり",""  ],
  ["client, invité","きゃく","客"  ],
  ["cloche [bell (en)]","ベル",""  ],
  ["coeur, âme","こころ","心"  ],
  ["coiffeur, salon de coiffure","とこや","床屋"  ],
  ["coin intérieur","すみ","隅"  ],
  ["collège","ちゅうがっこう","中学校"  ],
  ["coller, attacher, fixer, enfiler un vêtement, accompagner quelqu'un, allumer [一段] [vt]","つける","付ける・着ける"  ],
  ["comme ça","あんな",""  ],
  ["comme je le pensais","やっぱり・やはり",""  ],
  ["comme, tellement","そんなに",""  ],
  ["commencer, débuter [一段] [vt]","はじめる","始める"  ],
  ["comment ?","いかが","如何"  ],
  ["commerce (étranger)","ぼうえき","貿易"  ],
  ["comparer [一段] [vt]","くらべる","比べる"  ],
  ["compétence, technique","ぎじゅつ","技術"  ],
  ["compétition, concours","きょうそう","競争"  ],
  ["compliqué","ふくざつ","複雑"  ],
  ["concert [concert (en)]","コンサート",""  ],
  ["condition, état","ぐあい","具合"  ],
  ["conducteur","うんてんしゅ","運転手"  ],
  ["conduire","うんてんする","運転する"  ],
  ["conduite (d'un véhicule)","うんてん","運転"  ],
  ["conférence, réunion, meeting","かいぎ","会議"  ],
  ["confiture [jam (en)]","ジャム",""  ],
  ["connaissance (personne)","ごぞんじ","ご存知"  ],
  ["consentement","しょうち","承知"  ],
  ["considérablement, beaucoup","だいぶ","大分"  ],
  ["construire [一段] [vt]","たてる","建てる"  ],
  ["consultation, discussion","そうだん","相談"  ],
  ["contact, communication","れんらく","連絡"  ],
  ["contacter","れんらくする","連絡する"  ],
  ["content","うれしい","嬉しい"  ],
  ["continuer [一段] [vt]","つづける","続ける"  ],
  ["contraire, opposé, objection","はんたい","反対"  ],
  ["convenir [五段] [vi]","あう","合う"  ],
  ["conversation, dialogue, discussion","かいわ","会話"  ],
  ["copier, reproduire, filmer, photographier [五段] [vt]","うつす","写す"  ],
  ["corps","からだ","体"  ],
  ["côté opposé, derrière, partie cachée du regard","うら","裏"  ],
  ["coton","もめん","木綿"  ],
  ["cou","くび","首"  ],
  ["cours magistral, conférence","こうぎ","講義"  ],
  ["court de tennis [tennis court (en)]","テニスコート",""  ],
  ["courtoisie, politesse","おれい","お礼"  ],
  ["cruel","ひどい","酷い・非道い"  ],
  ["d'abord, en premier","まず","先ず"  ],
  ["dangereux, risqué","きけん","危険"  ],
  ["dans deux mois","さらいげつ","再来月"  ],
  ["dans deux semaines","さらいしゅう","再来週"  ],
  ["dans le but de, à cause de, du fait de","ため","為"  ],
  ["danse","おどり","踊り"  ],
  ["danser [五段] [vi]","おどる","踊る"  ],
  ["de ce fait","それで","其れで"  ],
  ["de cette manière, comme cela","こう","斯う"  ],
  ["de loin, à distance","とおく","遠く"  ],
  ["de plus, d'ailleurs","それに","其れに"  ],
  ["de toute ses forces, très fort","いっしょうけんめい","一生懸命"  ],
  ["décider, déterminer, fixer [一段] [vt]","きめる","決める"  ],
  ["décorer, orner [五段] [vt]","かざる","飾る"  ],
  ["découvrir, trouver [一段] [vt]","みつける","見付ける"  ],
  ["demain","あす","明日"  ],
  ["demander conseil, consulter","そうだんする","相談する"  ],
  ["demander, se renseigner [一段] [vt]","たずねる","尋ねる"  ],
  ["demander, visiter (hum) [五段] [vt]","うかがう","伺う"  ],
  ["déménager [五段] [vi]","ひっこす","引っ越す"  ],
  ["déménager, transférer [五段] [vi]","うつる","移る"  ],
  ["dentiste","はいしゃ","歯医者"  ],
  ["départ","しゅうぱつ","出発"  ],
  ["département universitaire","がくぶ","学部"  ],
  ["dépasser, excéder [一段] [vi]","すぎる","過ぎる"  ],
  ["descendre (d'une montage, d'un bus...) [一段] [vi]","おりる","下りる"  ],
  ["descendre, accorder (à quelqu'un) [五段] [vi]","さげる","下げる"  ],
  ["désolé pour l'attente","おまたせしました","お待たせしました"  ],
  ["détritus, déchets, ordures","ごみ","芥"  ],
  ["détruire, casser, briser [五段] [vt]","こわす","壊す"  ],
  ["deux côtés, les 2 parties","りょうほう","両方"  ],
  ["dictionnaire","じてん","辞典"  ],
  ["diffusion, émission","ほうそう","放送"  ],
  ["dîner, repas du soir","ゆうはん","夕飯"  ],
  ["dire (hum) [五段] [vt]","もうす","申す"  ],
  ["dire, parler (poli) [五段] [vt]","おっしゃる","仰る"  ],
  ["dire, raconter (poli) [一段] [vt]","もうしあげる","申し上げる"  ],
  ["dispute, querelle","けんか","喧嘩"  ],
  ["doigt","ゆび","指"  ],
  ["donc","だから",""  ],
  ["donner [一段] [vt]","くれる","呉れる"  ],
  ["donner à quelqu'un d'inférieur en rang [五段] [vt]","やる","遣る"  ],
  ["donner, confier [五段]","くださる","下さる"  ],
  ["donner, offrir, élever [一段] [vt]","さしあげる","差し上げる"  ],
  ["dormir [五段] [vi]","ねむる","眠る"  ],
  ["dos","せなか","背中"  ],
  ["double, deux fois","ばい","倍"  ],
  ["doucement, petit à petit","そろそろ",""  ],
  ["doué, bon","うまい","上手い"  ],
  ["doux, tendre, mou","やわらかい","柔らかい・軟らかい"  ],
  ["durant la journée","ひるま","昼間"  ],
  ["eau chaude","おゆ","お湯"  ],
  ["échanger, remplacer [一段] [vt]","とりかえる","取り替える"  ],
  ["échec","しっぱい","失敗"  ],
  ["école primaire","しょうがっこう","小学校"  ],
  ["économie (en général)","けいざい","経済"  ],
  ["éducation, entrainement","きょういく","教育"  ],
  ["effrayant, inquiétant","こわい","怖い・恐い"  ],
  ["église","きょうかい","教会"  ],
  ["élever, ériger [一段] [vt]","そだてる","育てる"  ],
  ["élever, ériger, dresser, établir [一段] [vt]","たてる","立てる"  ],
  ["elle, sa (neutre)","かのじょ","彼女"  ],
  ["embêter [一段] [vt]","いじめる","苛める"  ],
  ["emmener [一段]","つれる","連れる"  ],
  ["employé d'un magasin, vendeur","てんいん","店員"  ],
  ["en effet, c'est cela","なるほど","成る程"  ],
  ["en route, en chemin, à mi-chemin","とちゅう","途中"  ],
  ["endroit, lieu, espace","ばしょ","場所"  ],
  ["enfant de quelqu'un d'autre","おこさん","お子さん"  ],
  ["enfant, petit (d'un animal)","こ","子"  ],
  ["ensuite","すると",""  ],
  ["enthousiasme, impatience","ねっしん","熱心"  ],
  ["entre, parmi","うち","中"  ],
  ["entre, parmi","あいだ","間"  ],
  ["envelopper, emballer [五段] [vt]","つつむ","包む"  ],
  ["envelopper, emballer, empaqueter [五段] [vt]","くるむ","包む"  ],
  ["époque, période","じだい","時代"  ],
  ["épouse, femme","つま","妻"  ],
  ["épreuve sportive, match","しあい","試合"  ],
  ["escalateur [escalator (en)]","エスカレーター",""  ],
  ["esprit, humeur","き","気"  ],
  ["essence [gasoline (en)]","ガソリン",""  ],
  ["étagère","たな","棚"  ],
  ["étinceler, briller, scintiller [五段] [vi]","ひかる","光る"  ],
  ["étoile","ほし","星"  ],
  ["étrange, drôle","おかしい","可笑しい"  ],
  ["être (pour quelque chose d'animé), exister [五段] [vi]","おる","居る"  ],
  ["être à l'heure, arriver à temps [五段]","まにあう","間に合う"  ],
  ["être absent de chez soi","るすする","留守する"  ],
  ["être allumé (lumière, lampe...), prendre feu [五段] [vi]","つく","点く"  ],
  ["être apprivoisé, s'habituer à [一段] [vi]","なれる","馴れる"  ],
  ["être audible [一段] [vi]","きこえる","聞こえる"  ],
  ["être bouilli, chauffé [五段] [vi]","わく","沸く・湧く"  ],
  ["être brûlé [一段] [vi]","やける","焼ける"  ],
  ["être décidé, être déterminé [五段] [vi]","きまる","決まる"  ],
  ["être en retard, être différé [一段] [vi]","おくれる","後れる・遅れる"  ],
  ["être plié, se rompre, se briser [一段] [vi]","おれる","折れる"  ],
  ["être réjoui, être joyeux, se réjouir [五段] [vi]","よろこぶ","喜ぶ"  ],
  ["être rempli, être bondé [五段] [vi]","こむ","込む・混む"  ],
  ["être réparé, être guéri, se remettre (santé) [五段] [vi]","なおる","直る・治る"  ],
  ["être réservé, hésiter","えんりょする","遠慮する"  ],
  ["être secoué, être remué, trembler [一段] [vi]","ゆれる","揺れる"  ],
  ["être séparé, divisé, se séparer [一段] [vi]","わかれる","別れる・分かれる"  ],
  ["être suffisant, être assez [一段] [vi]","たりる","足りる"  ],
  ["être surpris","びっくりする","吃驚する"  ],
  ["être surpris, être étonné [五段] [vi]","おどろく","驚く"  ],
  ["être tranquille","あんしんする","安心する"  ],
  ["être trempé, être mouillé [一段] [vi]","ぬれる","濡れる"  ],
  ["être trouvé, être découvert [五段] [vi]","みつかる","見付かる"  ],
  ["être utile [五段]","やくにたつ","役に立つ"  ],
  ["être utile [五段]","やくだつ","役立つ"  ],
  ["être vide [五段] [vi]","すく","空く"  ],
  ["être visible, apparaître, sembler [一段] [vi]","みえる","見える"  ],
  ["étude, recherche","けんきゅう","研究"  ],
  ["étudiant à l'université","だいがくせい","大学生"  ],
  ["examen","しけん","試験"  ],
  ["examiner, vérifier [一段] [vt]","しらべる","調べる"  ],
  ["excepté","いがい","以外"  ],
  ["expérience","けいけん","経験"  ],
  ["explication","せつめい","説明"  ],
  ["exportations","ゆしゅつ","輸出"  ],
  ["exposition","てんらんかい","展覧会"  ],
  ["extrêmement","ずいぶん","随分"  ],
  ["extrêmement","ひじょうに","非常に"  ],
  ["face, partie visible (contraire de 裏)","おもて","表"  ],
  ["facile à [suffixe]","やすい","易い"  ],
  ["facile, simple","かんたん","簡単"  ],
  ["facilement, considérablement, très, difficilement","なかなか","中々"  ],
  ["faible, fragile","よわい","弱い"  ],
  ["faire (hum) [五段] [vt]","いたす","致す"  ],
  ["faire (poli) [五段] [vt]","なさる","為さる"  ],
  ["faire de l'exercice","うんどうする","運動する"  ],
  ["faire de son mieux, persévérer [五段] [vi]","がんばる","頑張る"  ],
  ["faire des aller-et-retours, faire la navette, fréquenter, aller à (une école, une église...)","かよう","通う"  ],
  ["faire du bruit [五段] [vi]","さわぐ","騒ぐ"  ],
  ["faire le tour, circuler, aller partout autour [五段] [vi]","まわる","回る"  ],
  ["faire un numéro, exécuter, faire, avoir lieu [五段]","おこなう","行う"  ],
  ["faire une erreur, se tromper, confondre [一段] [vt]","まちがえる","間違える"  ],
  ["fait en, fait de [suffixe]","せい","製"  ],
  ["félicitations","おめでとうございます","お目出度うご座います"  ],
  ["femme","じょせい","女性"  ],
  ["fermement","しっかり","確り"  ],
  ["festin, banquet","ごちそう","ご馳走"  ],
  ["festival","まつり","祭"  ],
  ["feu","ひ","火"  ],
  ["feuille","は","葉"  ],
  ["fièvre, température","ねつ","熱"  ],
  ["fil","いと","糸"  ],
  ["fille, femme non mariée","むすめ","娘"  ],
  ["fils","むすこ","息子"  ],
  ["fin","おわり","終わり"  ],
  ["finalement, etc","とうとう","等々"  ],
  ["finir [五段] [vi]","すむ","済む"  ],
  ["finir, fermer, clôturer, mettre fin à [五段] [vt]","しまう","仕舞う"  ],
  ["fonctionnaire","こうむいん","公務員"  ],
  ["force, énergie, puissance","ちから","力"  ],
  ["forme, apparence","かっこう","格好"  ],
  ["forme, aspect, apparence","かたち","形"  ],
  ["formule, équation, cérémonie","しき","式"  ],
  ["frapper (une personne), battre [五段] [vt]","うつ","打つ・撃つ"  ],
  ["futon","ふとん","布団"  ],
  ["futur (proche)","しょうらい","将来"  ],
  ["gagner [五段] [vi]","かつ","勝つ"  ],
  ["galerie d'art","びじゅつかん","美術館"  ],
  ["gants","てぶくろ","手袋"  ],
  ["gâteau [cake (en)]","ケーキ",""  ],
  ["gentil","しんせつ","親切"  ],
  ["gentillesse","しんせつ","親切"  ],
  ["géographie","ちり","地理"  ],
  ["glisser [五段] [vi]","すべる","滑る"  ],
  ["gorge","のど","喉"  ],
  ["goût","あじ","味"  ],
  ["grammaire","ぶんぽう","文法"  ],
  ["grand-mère","そぼ","祖母"  ],
  ["grand-père","そふ","祖父"  ],
  ["grand, large","おおきな","大きな"  ],
  ["griller, rôtir [五段] [vt]","やく","焼く"  ],
  ["gronder (quelqu'un) [五段] [vt]","しかる","叱る"  ],
  ["grossir [五段] [vi]","ふとる","太る"  ],
  ["guerre","せんそう","戦争"  ],
  ["guider, faire visiter","あんないする","案内する"  ],
  ["habitude, manière","しゅうかん","習慣"  ],
  ["habituel, ordinaire","ふつう","普通"  ],
  ["hanami, contemplation de la floraison des cerisiers","はなみ","花見"  ],
  ["herbe","くさ","草"  ],
  ["hier soir","ゆうべ","昨夜"  ],
  ["histoire","れきし","歴史"  ],
  ["hospitalisation, entrée à l'hôpital","にゅういん","入院"  ],
  ["il y a longtemps","さっき",""  ],
  ["il, son (neutre)","かれ","彼"  ],
  ["île","しま","島"  ],
  ["ils, leurs (neutre)","かれら","彼ら・彼等"  ],
  ["immeuble [building (en)]","ビル",""  ],
  ["impolitesse","しつれい","失礼"  ],
  ["important","だいじ","大事"  ],
  ["importation, introduction","ゆにゅう","輸入"  ],
  ["impossible, inutile, déraisonnable","むり","無理"  ],
  ["impossible, non, pas moyen","だめ","駄目"  ],
  ["incendie","かじ","火事"  ],
  ["incommode, peu pratique","ふべん","不便"  ],
  ["incroyable, admirable","すごい","凄い"  ],
  ["indispensable, nécessaire","ひつよう","必要"  ],
  ["industrie","こうぎょう","工業"  ],
  ["infirmière","かんごふ","看護婦"  ],
  ["information, renseignement","あんない","案内"  ],
  ["informer, annoncer, prévenir [一段] [vt]","しらせる","知らせる"  ],
  ["inhabituel, rare, insolite","めずらしい","珍しい"  ],
  ["inquiétudes, angoisses","しんぱい","心配"  ],
  ["insecte","むし","虫"  ],
  ["intention","つもり","積もり"  ],
  ["intérêt dans quelque chose","きょうみ","興味"  ],
  ["international","こくさい","国際"  ],
  ["invitation","しょうたい","招待"  ],
  ["je suis rentré (en rentrant chez soi)","ただいま","ただ今"  ],
  ["je, moi, mon (familier)","ぼく","僕"  ],
  ["jeune femme (poli)","おじょうさん","お嬢さん"  ],
  ["jouet","おもちゃ・がんぐ","玩具"  ],
  ["jour du Nouvel-An","しょうがつ","正月"  ],
  ["jour, soleil","ひ","日"  ],
  ["jour, soleil","ひ","日・陽"  ],
  ["journal (entreprise)","しんぶんしゃ","新聞社"  ],
  ["journal intime","にっき","日記"  ],
  ["judo","じゅうどう","柔道"  ],
  ["juste, correct","ただしい","正しい"  ],
  ["kimono (vêtement traditionnel japonais)","きもの","着物"  ],
  ["laboratoire, pièce de séminaire","けんきゅうしつ","研究室"  ],
  ["lac","みずうみ","湖"  ],
  ["laisser tomber, faire tomber [五段] [vt]","おとす","落とす"  ],
  ["lancer, jeter [一段] [vt]","なげる","投げる"  ],
  ["lancer, jeter [一段] [vt]","すてる","捨てる"  ],
  ["le dernier","さいご","最後"  ],
  ["le faire de prendre des nouvelles de quelqu'un malade","おみまい","お見舞い"  ],
  ["le plus récent, ces temps-ci, récemment","さいきん","最近"  ],
  ["le premier","さいしょ","最初"  ],
  ["lève-tard","あさねぼう","朝寝坊"  ],
  ["liberté","じゆう","自由"  ],
  ["libre","じゆう","自由"  ],
  ["lieu de réunion","かいじょう","会場"  ],
  ["lieu de vente, surface de vente","うりば","売り場"  ],
  ["ligne (de train, de téléphone...)","せん","線"  ],
  ["limite, borne, dimension","ほど","程"  ],
  ["littérature","ぶんがく","文学"  ],
  ["livrer, distribuer [一段] [vt]","とどける","届ける"  ],
  ["loi","ほうりつ","法律"  ],
  ["louer, admirer [一段] [vt]","ほめる","褒める"  ],
  ["lumière","ひかり","光"  ],
  ["lumière électrique","でんとう","電灯"  ],
  ["Lune","つき","月"  ],
  ["lycée","こうとうがっこう","高等学校"  ],
  ["lycéen","こうこうせい","高校生"  ],
  ["mais","けれど",""  ],
  ["mais","けれども",""  ],
  ["mâle","だんせい","男性"  ],
  ["malpoli","しつれい","失礼"  ],
  ["manger (poli) [五段] [vt]","めしあがる","召し上がる"  ],
  ["manière de, méthode de [suffixe]","かた","方"  ],
  ["marchandises","しなもの","品物"  ],
  ["marcher sur, piétiner, évaluer, estimer [五段] [vt]","ふむ","践む・踏む"  ],
  ["mari, époux","おっと","夫"  ],
  ["mathématique","すうがく","数学"  ],
  ["médecine","いがく","医学"  ],
  ["mensonge","うそ","嘘"  ],
  ["merci à vous","おかげさまで","お陰様で"  ],
  ["méthode, manière","しかた","仕方"  ],
  ["mettre en rangs, énumérer [一段] [vt]","ならべる","並べる"  ],
  ["milieu, centre","まんなか","真ん中"  ],
  ["miroir","かがみ","鏡"  ],
  ["miso (plat traditionnel japonais consistant en une pâte fermentée et salée)","みそ","味噌"  ],
  ["moins de, au dessous-de, sous","いか","以下"  ],
  ["mois","つき","月"  ],
  ["monde","せかい","世界"  ],
  ["mordre, machouiller, ronger [五段] [vt]","かむ","噛む"  ],
  ["moto [auto-bike (en)]","オートバイ",""  ],
  ["mourir, perdre la vie [五段] [vi]","なくなる","亡くなる"  ],
  ["mouvement, exercice","うんどう","運動"  ],
  ["mur, cloison","かべ","壁"  ],
  ["natation","すいえい","水泳"  ],
  ["nécessaire","ひつよう","必用"  ],
  ["nettoyer, ranger [一段] [vt]","かたづける","片づける"  ],
  ["normalement","ふつうは","普通は"  ],
  ["nourriture","しょくりょうひん","食料品"  ],
  ["nuage","くも","雲"  ],
  ["objet perdu","わすれもの","忘れ物"  ],
  ["obstacle","じゃま","邪魔"  ],
  ["obtention d'un diplôme","そつぎょう","卒業"  ],
  ["occasionnellement","たまに","偶に"  ],
  ["Occident, pays occidentaux","せいよう","西洋"  ],
  ["odeur, senteur","におい","匂い"  ],
  ["opinion, avis","いけん","意見"  ],
  ["opposé","はんたい","反対"  ],
  ["orange (fruit ou couleur) [orange (en)]","オレンジ",""  ],
  ["ou, autrement","まだは",""  ],
  ["ouais, ok, yeah (marque l'accord)","うん",""  ],
  ["outil, instrument","どうぐ","道具"  ],
  ["ouvrir (un compte en banque, un festival...) [五段] [vt]","ひらく","開く"  ],
  ["panne, dérèglement","こしょう","故障"  ],
  ["par exemple","たとえば","例えば"  ],
  ["pardessus [overcoat (en)]","オーバー",""  ],
  ["parents","おや","親"  ],
  ["particulièrement","とくに","特に"  ],
  ["pas du tout (+négatif)","ちっとも","些とも"  ],
  ["pas du tout (+négatif)","ぜんぜん","全然"  ],
  ["pas particulièrement","べつに","別に"  ],
  ["passe-temps, hobby","しゅみ","趣味"  ],
  ["passer voir quelqu'un, rendre visite à [五段] [vi]","よる","寄る"  ],
  ["pause déjeuner","ひるやすみ","昼休み"  ],
  ["payer [五段] [vt]","はらう","払う"  ],
  ["paysage","けしき","景色"  ],
  ["PDG","しゃちょう","社長"  ],
  ["pêcher [五段] [vt]","つる","釣る"  ],
  ["peindre, enduire, laquer, vernir [五段] [vt]","ぬる","塗る"  ],
  ["penser [五段] [vt]","おもう","思う"  ],
  ["pension, logement","げしゅく","下宿"  ],
  ["perdre (quelque chose ou quelqu'un) [五段] [vt]","なくす","無くす・亡くす"  ],
  ["perdre du poids [一段] [vi]","やせる","痩せる"  ],
  ["perdre, être vaincu [一段] [vi]","まける","負ける"  ],
  ["personne riche","かねもち","金持ち"  ],
  ["petit","ちいさな","小さな"  ],
  ["petit oiseau","ことり","小鳥"  ],
  ["petit, détaillé","こまかい","細かい"  ],
  ["peu","すくない","少ない"  ],
  ["peu profond","あさい","浅い"  ],
  ["piano [piano (en)]","ピアノ",""  ],
  ["pickpocket","すり","掏摸"  ],
  ["piqûre, injection","ちゅうしゃ","注射"  ],
  ["placard","おしいれ","押入れ"  ],
  ["place de parking","ちゅうしゃじょう","駐車場"  ],
  ["plaisir, amusement","たのしみ","楽しみ"  ],
  ["plan, emploi du temps, programme","よてい","予定"  ],
  ["planter, faire pousser (fleur, arbre...) [一段] [vt]","うえる","植える"  ],
  ["pleurer [五段]","なく","泣く"  ],
  ["plier, rompre, casser [五段] [vt]","おる","折る"  ],
  ["plus de, au dessus-de, davantage","いじょう","以上"  ],
  ["point, marque, score","てん","点"  ],
  ["poli, courtois","ていねい","丁寧"  ],
  ["police","けいさつ","警察"  ],
  ["policier","けいかん","警官"  ],
  ["politique (en général)","せいじ","政治"  ],
  ["population","じんこう","人口"  ],
  ["port","みなと","港"  ],
  ["portefeuille","さいふ","財布"  ],
  ["poupée, marionnette","にんぎょう","人形"  ],
  ["pourquoi ?","なぜ","何故"  ],
  ["prendre un repas","しょくじする","食事する"  ],
  ["préparation","したく","支度"  ],
  ["préparation","ようい","用意"  ],
  ["préparation pour un cours","よしゅう","予習"  ],
  ["préparation, préparatif","じゅんび","準備"  ],
  ["présence","しゅっせき","出席"  ],
  ["présentateur (TV, radio) [announcer (en)]","アナウンサー",""  ],
  ["présentation, introduction (d'une personne)","しょうかい","紹介"  ],
  ["presque, à peine, peu","ほとんど","殆ど"  ],
  ["prévisions météorologiques","てんきよほう","天気予報"  ],
  ["prier pour [五段] [vi]","いのる","祈る"  ],
  ["principal (école)","こうちょう","校長"  ],
  ["prix, coût","ねだん","値段"  ],
  ["production, quelque chose qui est manufacturé","せいさん","生産"  ],
  ["profond","ふかい","深い"  ],
  ["programme (tv, radio)","ばんぐみ","番組"  ],
  ["projet, plan","けいかく","計画"  ],
  ["promesse, engagement","やくそく","約束"  ],
  ["prononciation","はつおん","発音"  ],
  ["proportion, ratio, %","わりあい","割合"  ],
  ["prudence, attention","ちゅうい","注意"  ],
  ["quel côté ?","どっち","何方"  ],
  ["raisin","ぶどう","葡萄"  ],
  ["raison, conclusion après un raisonnement","わけ","訳"  ],
  ["ramasser, recueillir [五段] [vt]","ひろう","拾う"  ],
  ["rassemblement, club, association [suffixe]","かい","会"  ],
  ["récemment, l'autre jour","このあいだ","この間"  ],
  ["réception, bureau de renseignement","うけつけ","受付"  ],
  ["recevoir (hum), manger ou boire [五段] [vt]","いただく","戴く・頂く"  ],
  ["recevoir [五段] [vt]","もらう","貰う"  ],
  ["recevoir, accepter, passer (un examen par exemple) [一段] [vt]","うける","受ける"  ],
  ["réfléchir, considérer [一段] [vt]","かんがえる","考える"  ],
  ["refroidir, rafraîchir [一段] [vi]","ひえる","冷える"  ],
  ["regard, vue (poli)","はいけん","拝見"  ],
  ["règlement, règlementation","きそく","規則"  ],
  ["regrettable","ざんねん","残念"  ],
  ["relation, rapport, lien","かんけい","関係"  ],
  ["rempli, plein, ivre","いっぱい","一杯"  ],
  ["réparer, guérir [五段] [vt]","なおす","直す・治す"  ],
  ["repas","しょくじ","食事"  ],
  ["répondre","へんじする","返事する"  ],
  ["réponse","こたえ","応え"  ],
  ["réponse","へんじ","返事"  ],
  ["réservation, contrat","よやく","予約"  ],
  ["réserve, distance, défiance","えんりょ","遠慮"  ],
  ["rester, être restant [五段] [vi]","のこる","残る"  ],
  ["retour","かえり","帰り"  ],
  ["retourner (vers), revenir (à) [五段] [vi]","もどる","戻る"  ],
  ["réunir, rassembler [一段] [vt]","あつめる","集める"  ],
  ["rêve","ゆめ","夢"  ],
  ["réveiller, lever [五段] [vt]","おこす","起こす"  ],
  ["revenir, retourner (à notre point de départ) [五段] [vi]","かえる","帰る・返る"  ],
  ["révision","ふくしゅう","復習"  ],
  ["riche, prospère","さかん","盛ん"  ],
  ["rideau [curtain (en)]","カーテン",""  ],
  ["rire, sourire [五段] [vi]","わらう","笑う"  ],
  ["rivage, côte (mer)","かいがん","海岸"  ],
  ["riz non préparé, riz cru","こめ","米"  ],
  ["roman","しょうせつ","小説"  ],
  ["rue, avenue","とおり","通り"  ],
  ["s'assombrir, se coucher (pour le soleil), se terminer [一段] [vi]","くれる","暮れる"  ],
  ["s'échapper, s'enfuir [一段] [vi]","にげる","逃げる"  ],
  ["s'effondrer [一段] [vi]","たおれる","倒れる"  ],
  ["s'élever, grimper, augmenter [五段] [vi]","あがる","上がる"  ],
  ["s'excuser [五段] [vi]","あやまる","謝る"  ],
  ["s'habituer à [一段] [vi]","なれる","慣れる"  ],
  ["s'inquiéter, s'occuper de [五段]","かまう","構う"  ],
  ["sable","すな","砂"  ],
  ["saison","きせつ","季節"  ],
  ["salade [salade (pt)]","サラダ",""  ],
  ["salle de réception, salon","おうせつま","応接間"  ],
  ["salutation","あいさつ","挨拶"  ],
  ["sanctuaire shinto","じんじゃ","神社"  ],
  ["sandale [sandal (en)]","サンダル",""  ],
  ["sandwich [sandwich (en)]","サンドイッチ",""  ],
  ["sang","ち","血"  ],
  ["science","かがく","科学"  ],
  ["se blesser","けがする","怪我する"  ],
  ["se calmer (pluie, douleur...), se retirer [五段] [vi]","さがる","下がる"  ],
  ["se casser, se briser [一段] [vi]","こわれる","壊れる"  ],
  ["se continuer, se prolonger [五段] [vi]","つづく","続く"  ],
  ["se dépêcher [五段] [vi]","いそぐ","急ぐ"  ],
  ["se disputer, se quereller","けんかする","喧嘩する"  ],
  ["se fâcher, se mettre en colère [五段] [vi]","おこる","怒る"  ],
  ["se faire du souci","しんぱいする","心配する"  ],
  ["se faire plaisir, se divertir [五段]","たのしむ","楽しむ"  ],
  ["se fendre, se briser, se casser [一段] [vi]","われる","割れる"  ],
  ["se perdre, disparaître [五段] [vi]","なくなる","無くなる"  ],
  ["se rappeler, se souvenir [五段] [vt]","おもいだす","思い出す"  ],
  ["se ressembler, être similaire [一段] [vi]","にる","似る"  ],
  ["se réunir [五段] [vi]","あつまる","集まる"  ],
  ["se salir [一段] [vi]","よごれる","汚れる"  ],
  ["se vider, être vide, être disponible [五段] [vi]","あく","空く"  ],
  ["selon","によると","に依ると"  ],
  ["sensation, humeur","きぶん","気分"  ],
  ["sensation, sentiment","きもち","気持ち"  ],
  ["sérieux, sincère, honnête","まじめ","真面目"  ],
  ["seul, solitaire","さびしい","寂しい"  ],
  ["si possible, autant que possible","できるだけ","出来るだけ"  ],
  ["si, au cas où","もし","若し"  ],
  ["siège","せき","席"  ],
  ["situation, cas","ばあい","場合"  ],
  ["société","しゃかい","社会"  ],
  ["soie","きぬ","絹"  ],
  ["son (bruit)","おと・ね","音"  ],
  ["sonner, résonner [五段] [vi]","なる","鳴る"  ],
  ["sortie de l'hôpital","たいいん","退院"  ],
  ["sous-vêtements","したぎ","下着"  ],
  ["soutien, support","おかげ","お陰"  ],
  ["spécial","とくべつ","特別"  ],
  ["spécialité","せんもん","専門"  ],
  ["station-essence [gazoline stand (en)]","ガソリンスタンド",""  ],
  ["strict, sévère","きびしい","厳しい"  ],
  ["suffixe pour indiquer qu'une chose est presque sûre, qu'elle doit être ainsi [suffixe]","はず","筈"  ],
  ["suffixe pour indiquer une propriété, une relation ou une occupation d'une personne (ferme 農, fermier 農家) [suffixe]","か","家"  ],
  ["suffixe pour les noms (Mr, Mme), apparence, manière [suffixe]","さま","様"  ],
  ["supérieur (au travail, à l'école...)","せんぱい","先輩"  ],
  ["supermarché [supermarket (en)]","スーパー",""  ],
  ["sûr","あんぜん","安全"  ],
  ["sûr, certain","たしか","確か"  ],
  ["sûrement, certainement, sans aucun doute","きっと","急度"  ],
  ["surpris, étonné","びっくり","吃驚"  ],
  ["tâche, affaire, chose à faire","ようじ","用事"  ],
  ["tatami, couverture de sol japonais en paille","たたみ","畳"  ],
  ["tel quel, comme, parce que","まま",""  ],
  ["télégramme","でんぽう","電報"  ],
  ["tellement","それほど","其れ程"  ],
  ["temple bouddhiste","てら","寺"  ],
  ["tennis [tennis (en)]","テニス",""  ],
  ["terrain d'aviation","ひこうじょう","飛行場"  ],
  ["texte [texte (en)]","テキスト",""  ],
  ["timide, embarrassé","はずかしい","恥ずかしい"  ],
  ["tiroir","ひきだし","引き出し"  ],
  ["toît","おくじょう","屋上"  ],
  ["tomber, chuter [一段] [vi]","おちる","落ちる"  ],
  ["toucher [五段] [vi]","さわる","触る"  ],
  ["tourisme","けんぶつ","見物"  ],
  ["tous, complètement","すっかり",""  ],
  ["tout le monde, tout","みな・みんな","皆"  ],
  ["traduction","ほんやく","翻訳"  ],
  ["traduire","ほんやくする","翻訳する"  ],
  ["trafic, transports","こうつう","交通"  ],
  ["train à vapeur","きしゃ","汽車"  ],
  ["train express","きゅうこう","急行"  ],
  ["train express","とっきゅう","特急"  ],
  ["transférer, changer (de bus, de train…) [一段] [vt]","のりかえる","乗り換える"  ],
  ["transmettre, communiquer, propager [一段] [vt]","つたえる","伝える"  ],
  ["transporter [五段]","はこぶ","運ぶ"  ],
  ["travail à temps partiel [arbeit (de)]","アルバイト",""  ],
  ["tremblement de terre","じしん","地震"  ],
  ["tremper, mariner [一段] [vt]","つける","漬ける・浸ける"  ],
  ["très prochainement","もうすぐ","もう直ぐ"  ],
  ["très, complètement, pendant longtemps","ずっと",""  ],
  ["triste, mélancolique","かなしい","悲しい"  ],
  ["tu, ton, toi (familier)","きみ","君"  ],
  ["type, style [type (en)]","タイプ",""  ],
  ["typhon","たいふう","台風"  ],
  ["un instant, un moment","しばらく","暫く"  ],
  ["une fois","いちど","一度"  ],
  ["une telle (chose), une pareille (chose) [préfixe]","そんな",""  ],
  ["urbain","と","都"  ],
  ["urgent, soudain","きゅう","急"  ],
  ["usine, atelier","こうば・こうじょう","工場"  ],
  ["utilisation, application","りよう","利用"  ],
  ["valise [suitcase (en)]","スーツケース",""  ],
  ["véhicule","のりもの","乗り物"  ],
  ["venir, aller (hum) [五段]","まいる","参る"  ],
  ["venir, arriver (hum) [五段] [vi]","いらっしゃる",""  ],
  ["verre (matière) [glass (en)]","ガラス",""  ],
  ["vert","みどり","緑"  ],
  ["vie quotidienne","せいかつ","生活"  ],
  ["vie, existence","せいめい","生命"  ],
  ["village","むら","村"  ],
  ["ville","し","市"  ],
  ["visiter","けんぶつする","見物する"  ],
  ["visiter [一段] [vt]","たずねる","訪ねる"  ],
  ["vivre, exister [一段] [vt]","いきる","生きる"  ],
  ["voir, regarder (hon) [五段]","ごらんになる","ご覧に成る"  ],
  ["voisinage, environs","きんじょ","近所"  ],
  ["voler, dérober [五段] [vt]","ぬすむ","盗む"  ],
  ["voleur, cambrioleur","どろぼう","泥棒"  ],
  ["votre maison, votre foyer (hum)","おたく","お宅"  ],
  ["vous voilà donc, vous voilà !","よくいらっしゃいました",""  ],
  ["zoo","どうぶつえん","動物園"  ]
];

module.exports = jlptfr4;